src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Structure__c</fullName>
        <label>Business Structure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Foreign Corporation</fullName>
                </value>
                <value>
                    <fullName>Joint Stock Associations</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Method__c</fullName>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated license record.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profession_Code__c</fullName>
        <label>Profession Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Code__c</fullName>
        <defaultValue>&quot;AFR-MG-MS-SubSrc-GLRV&quot;</defaultValue>
        <label>Revenue Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Contracts__c</fullName>
        <label># Initial Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Reinstatement_Eligible__c</fullName>
        <description>Formula to check Reinstatement Eligibility</description>
        <formula>IF(AND(OR((TODAY() &gt; Late_Renewal_Eligible_End_Date__c &amp;&amp; ( ISPICKVAL(MUSW__Status__c, &apos;Canceled&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;))), 
(AND ( OR (ISPICKVAL(Credential_Type__c, &apos;Temporary Certified General&apos;), ISPICKVAL(Credential_Type__c, &apos;Temporary State Licensed&apos;), ISPICKVAL(Credential_Type__c, &apos;Temporary Certified Residential&apos;)), OR( ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;), ISPICKVAL(MUSW__Status__c, &apos;Active&apos;), ISPICKVAL(MUSW__Status__c, &apos;Canceled&apos;)) ))), 
(NOT(OR(ISPICKVAL(Credential_Type__c, &apos;Funeral Establishment&apos;), ISPICKVAL(Credential_Type__c, &apos;Crematory&apos;), ISPICKVAL(Credential_Type__c, &apos;Certificate of Removal Registration&apos;), ISPICKVAL(Credential_Type__c, &apos;Funeral Establishment Branch&apos;), ISPICKVAL(Credential_Type__c, &apos;Cremated Remains Disposition Permit&apos;))))) 
, TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Reinstatement Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Renewal_Eligible__c</fullName>
        <description>Formula to determine renewal eligibility</description>
        <formula>IF(TODAY() &gt;= Renewal_Eligible_Start_Date__c  &amp;&amp; Is_Reinstatement_Eligible__c==False , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of Units</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profession_Code__c</fullName>
        <description>Five digit code identifying the profession</description>
        <label>Profession Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Fee_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Fee outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Method__c</fullName>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>License Type list</description>
        <label>License Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>License_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession_Code__c</fullName>
        <label>Profession Code</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Code__c</fullName>
        <label>Revenue Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Master Fee List</label>
    <nameField>
        <label>Master Fee List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Fee List</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Fees</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MUSW__Master_Fee_List__c.object
    <fields>
        <fullName>Business_Structure__c</fullName>
        <label>Business Structure</label>
        <length>100</length>
        <type>Text</type>
    </fields>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Renewal Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of Units</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Renewal_Application__c.object
    <fields>
        <fullName>Initial_Contracts__c</fullName>
        <label># Initial Contracts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/License_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Acupuncturist (ACU)</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Cosmetologist</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Esthetician</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Hair Designer</fullName>
    </customValue>
    <customValue>
        <fullName>Advanced Manicurist</fullName>
    </customValue>
    <customValue>
        <fullName>Anesthesiologist Assistant (AA)</fullName>
    </customValue>
    <customValue>
        <fullName>Approved Training Agency (ATA)</fullName>
    </customValue>
    <customValue>
        <fullName>Architect - Firm (ARC)</fullName>
    </customValue>
    <customValue>
        <fullName>Architect - Individual (ARC)</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Athletic Trainer (AT)</fullName>
    </customValue>
    <customValue>
        <fullName>Audiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Audiologist - Temporary</fullName>
    </customValue>
    <customValue>
        <fullName>Barber</fullName>
    </customValue>
    <customValue>
        <fullName>Barbershop</fullName>
    </customValue>
    <customValue>
        <fullName>Barber Student</fullName>
    </customValue>
    <customValue>
        <fullName>Barber Teacher</fullName>
    </customValue>
    <customValue>
        <fullName>Boutique Service Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Boutique Service Salon</fullName>
    </customValue>
    <customValue>
        <fullName>Building Department Certification</fullName>
    </customValue>
    <customValue>
        <fullName>Business Facility Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Conceded Eminence</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Embalmer Apprenticeship</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Funeral Director Apprenticeship</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Pharmacy Technician</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Public Accountant</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Public Accountant REG</fullName>
    </customValue>
    <customValue>
        <fullName>Chair Rental</fullName>
    </customValue>
    <customValue>
        <fullName>Chemical Dependency Counselor Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Chemical Dependency Counselor Assistant Preliminary</fullName>
    </customValue>
    <masterLabel>License Type</masterLabel>
</GlobalValueSet>

src/classes/LnP_generateFeeRecords_Class.cls
/*
Name: LnP_generateFeeRecords_Class
Description: LnP_generateFeeRecords_Class is used to generate the fee records for License.
Created By:Chiranrh Aradhya 
Created Date: 08/20/2019
*/
public with sharing class LnP_generateFeeRecords_Class {
 @AuraEnabled
    public static String generateFeeRecords(Id licenseId) {
        try{
            
            MUSW__License2__c license_Rec = new MUSW__License2__c();
            license_Rec = [Select Id,MUSW__Status__c,Manual_Fee_Generation__c,MUSW__Primary_Licensee__r.business_structure__c,Credential_Type__c,Initial_Contracts__c,Application_Type__c,Application_Method__c,Is_Reinstatement_Eligible__c,Application__c,Number_of_Units__c,Is_Renewal_Eligible__c FROM MUSW__License2__c  where Id =:licenseId ];
                    
            String FeeGenartionCheckStatus = Label.Fee_Generation_Check_Status;
            String FeeGenartionCompletedStatus = Label.Fee_Generation_Completed_Status;
            String FeeGenarationStatusError =Label.Fee_Generation_Status_Error;
            
            if(license_Rec.MUSW__Status__c != FeeGenartionCheckStatus){
                return FeeGenarationStatusError;
            }else{
                license_Rec.Manual_Fee_Generation__c = True;
                update license_Rec;
                return 'true';
            }          
            /*
            
                    List<MUSW__Master_Fee_List__c> MasterFeelist = new List <MUSW__Master_Fee_List__c>();
                    List<MUSW__Fee__c> feeList = new List<MUSW__Fee__c>();
                    List<MUSW__Fee__c> InsertedfeeList = new List<MUSW__Fee__c>();
                    MUSW__License2__c license_Rec = new MUSW__License2__c();
                   
                    String FeeGenartionCheckStatus = Label.Fee_Generation_Check_Status;
                    String FeeGenartionCompletedStatus = Label.Fee_Generation_Completed_Status;
                    String FeeGenarationStatusError =Label.Fee_Generation_Status_Error;
                    
                    license_Rec = [Select Id,MUSW__Status__c,MUSW__Primary_Licensee__r.business_structure__c,Credential_Type__c,Initial_Contracts__c,Application_Type__c,Application_Method__c,Is_Reinstatement_Eligible__c,Application__c,Number_of_Units__c,Is_Renewal_Eligible__c FROM MUSW__License2__c  where Id =:licenseId ];
                    
                    String licenseApplicationMethod = license_Rec.Application_Method__c;
                    String licenseCredentialType = license_Rec.Credential_Type__c;
                    String licenseApplicationType = license_Rec.Application_Type__c;
                    
                    if(license_Rec.MUSW__Status__c != FeeGenartionCheckStatus){
                        return FeeGenarationStatusError;
                    }else{
                    
                            String Query ='Select Name,Id,Active__c,Agency__c,License_Type__c,Credential_Type__c,Profession_Code__c,Revenue_Code__c,Fee_Calculation_Type__c,Fee_Type__c,Base__c,Business_Structure__c,Fee_Formula_Amount__c,Is_Endorsement__c,Application_Type__c,Portal_Name__c,Agency_Number__c,Credential__c,Application_Method__c from MUSW__Master_Fee_List__c where Active__c = True AND Base__c != null AND Is_Endorsement__c = False AND Application_Method__c =: licenseApplicationMethod AND Credential_Type__c =: licenseCredentialType AND Application_Type__c =: licenseApplicationType';
                        
                            MasterFeelist= Database.Query(Query);
                        
                            for(MUSW__Master_Fee_List__c msFeeRec:MasterFeelist){
                                
                                 if(msFeeRec.Application_Method__c == license_Rec.Application_Method__c && license_Rec.Credential_Type__c == msFeeRec.Credential_Type__c && msFeeRec.Application_Type__c == license_Rec.Application_Type__c && license_Rec.MUSW__Primary_Licensee__r.business_structure__c != null && license_Rec.MUSW__Primary_Licensee__r.business_structure__c == msFeeRec.Business_Structure__c ){
                                                                                
                                            MUSW__Fee__c Fee_record = new MUSW__Fee__c();
                                            Fee_record.MUSW__Type__c = msFeeRec.Fee_Type__c;
                                            //Fee_record.MUSW__Amount__c = Amt;
                                            Fee_record.MUSW__Amount__c = msFeeRec.Base__c;
                                            Fee_record.Agency__c =msFeeRec.Agency__c;
                                            Fee_record.Revenue_Code__c =msFeeRec.Revenue_Code__c;
                                            Fee_record.Application_Type__c =msFeeRec.Application_Type__c;
                                            Fee_record.portal_name__c =msFeeRec.Portal_Name__c;
                                            Fee_record.Agency_Number__c =msFeeRec.Agency_Number__c;
                                            Fee_record.Profession_Code__c =msFeeRec.Profession_Code__c;
                                            Fee_record.Application_Method__c =msFeeRec.Application_Method__c;
                                            Fee_record.License_Type__c =msFeeRec.License_Type__c;
                                            Fee_record.Fee_Name__c= msFeeRec.Name;
                                            Fee_record.MUSW__License2__c = license_Rec.Id;
                                            feeList.add(Fee_record);
                                            
                                        }else if(msFeeRec.Application_Method__c == license_Rec.Application_Method__c && license_Rec.Credential_Type__c == msFeeRec.Credential_Type__c && msFeeRec.Application_Type__c == license_Rec.Application_Type__c && license_Rec.MUSW__Primary_Licensee__r.business_structure__c == null){
                                            
                                            MUSW__Fee__c Fee_record = new MUSW__Fee__c();
                                            Fee_record.MUSW__Type__c = msFeeRec.Fee_Type__c;
                                            //Fee_record.MUSW__Amount__c = Amt;
                                            Fee_record.MUSW__Amount__c = msFeeRec.Base__c;
                                            Fee_record.Agency__c =msFeeRec.Agency__c;
                                            Fee_record.Revenue_Code__c =msFeeRec.Revenue_Code__c;
                                            Fee_record.Application_Type__c =msFeeRec.Application_Type__c;
                                            Fee_record.portal_name__c =msFeeRec.Portal_Name__c;
                                            Fee_record.Agency_Number__c =msFeeRec.Agency_Number__c;
                                            Fee_record.Profession_Code__c =msFeeRec.Profession_Code__c;
                                            Fee_record.Application_Method__c =msFeeRec.Application_Method__c;
                                            Fee_record.License_Type__c =msFeeRec.License_Type__c;
                                            Fee_record.Fee_Name__c= msFeeRec.Name;
                                            Fee_record.MUSW__License2__c = license_Rec.Id;
                                            feeList.add(Fee_record);
                                        }
                                        
                            }
                        
                            if(!feeList.isEmpty()){
                                InsertedfeeList = Utilityclass_withsharing.insertList(feeList);
                                if(!InsertedfeeList.isEmpty()){
                                    license_Rec.MUSW__Status__c =FeeGenartionCompletedStatus;
                                    update license_Rec;
                                    return 'True';
                                }
                            }
                        
                            
                            license_Rec.MUSW__Status__c =FeeGenartionCompletedStatus;
                            update license_Rec;
                        
                        }
                    
                    return 'False';
             
            */
             
        }catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e,'LnP_generateFeeRecords_Class','generateFeeRecords');return 'False';}
        
    }
    
    @AuraEnabled
    public static String generateFeeRecords_Renewals(Id renewalId) {
        try{
                   

            String FeeGenartionCheckStatus = Label.Fee_Generation_Check_Status;
            String FeeGenartionCompletedStatus = Label.Fee_Generation_Completed_Status_Renewal;
            String FeeGenarationStatusError =Label.Fee_Generation_Status_Error;
            
            Renewal_Application__c renewal_Rec = new Renewal_Application__c();
            
            renewal_Rec =[Select Id,Renewal_Status__c,Manual_Fee_Generation__c,Renewal_Reinstatement_Type__c,Credential_Type__c,Application_Type__c,Applicant__c,License_Account__c,License__c,License__r.Is_Late_Renewal_Eligible__c, License__r.Deployed__c from Renewal_Application__c where Id =:renewalId];
            
            if(renewal_Rec.Renewal_Status__c != FeeGenartionCheckStatus){
                return FeeGenarationStatusError;
            }else{
                renewal_Rec.Manual_Fee_Generation__c=True;
                update renewal_Rec;
                return 'True';
            }

            /*
                       
            List<MUSW__Master_Fee_List__c> MasterFeelist = new List <MUSW__Master_Fee_List__c>();
            List<MUSW__Fee__c> feeList = new List<MUSW__Fee__c>();
            List<MUSW__Fee__c> InsertedfeeList = new List<MUSW__Fee__c>();
            
            String FeeGenartionCheckStatus = Label.Fee_Generation_Check_Status;
            String FeeGenartionCompletedStatus = Label.Fee_Generation_Completed_Status_Renewal;
            String FeeGenarationStatusError =Label.Fee_Generation_Status_Error;
            
            Renewal_Application__c renewal_Rec = new Renewal_Application__c();
            
            renewal_Rec =[Select Id,Renewal_Status__c,Manual_Fee_Generation__c,Renewal_Reinstatement_Type__c,Credential_Type__c,Application_Type__c,Applicant__c,License_Account__c,License__c,License__r.Is_Late_Renewal_Eligible__c, License__r.Deployed__c from Renewal_Application__c where License__c != null AND License__r.Deployed__c = False AND License_Account__c = null AND Application_Type__c != null AND Id =:renewalId];
            
            
            String renewalApplicationMethod = renewal_Rec.Renewal_Reinstatement_Type__c;
            String renewalCredentialType = renewal_Rec.Credential_Type__c;
            String renewalApplicationType = renewal_Rec.Application_Type__c;
           
            if(renewal_Rec.Renewal_Status__c != FeeGenartionCheckStatus){
                return FeeGenarationStatusError;
            
            }else{
              String Query;
              if(renewal_Rec.License__r.Is_Late_Renewal_Eligible__c == False ){
            
                Query ='Select Name,Id,Active__c,Agency__c,is_Late_Renewal__c,License_Type__c,Credential_Type__c,Profession_Code__c,Revenue_Code__c,Fee_Calculation_Type__c,Fee_Type__c,Base__c,Business_Structure__c,Fee_Formula_Amount__c,Is_Endorsement__c,Application_Type__c,Portal_Name__c,Agency_Number__c,Credential__c,Application_Method__c from MUSW__Master_Fee_List__c where Active__c = True AND Base__c != null AND Is_Endorsement__c = False AND is_Late_Renewal__c = False AND Application_Method__c =: renewalApplicationMethod AND Credential_Type__c =: renewalCredentialType AND Application_Type__c =: renewalApplicationType';
                
                }else if(renewal_Rec.License__r.Is_Late_Renewal_Eligible__c == True ){
                    Query ='Select Name,Id,Active__c,Agency__c,is_Late_Renewal__c,License_Type__c,Credential_Type__c,Profession_Code__c,Revenue_Code__c,Fee_Calculation_Type__c,Fee_Type__c,Base__c,Business_Structure__c,Fee_Formula_Amount__c,Is_Endorsement__c,Application_Type__c,Portal_Name__c,Agency_Number__c,Credential__c,Application_Method__c from MUSW__Master_Fee_List__c where Active__c = True AND Base__c != null AND Is_Endorsement__c = False AND Application_Method__c =: renewalApplicationMethod AND Credential_Type__c =: renewalCredentialType AND Application_Type__c =: renewalApplicationType';
                }
                
            
                MasterFeelist= Database.Query(Query);
                
                for(MUSW__Master_Fee_List__c msFeeRec:MasterFeelist){
                    
                     if(msFeeRec.Application_Method__c == renewal_Rec.Renewal_Reinstatement_Type__c && renewal_Rec.Credential_Type__c == msFeeRec.Credential_Type__c && msFeeRec.Application_Type__c == renewal_Rec.Application_Type__c ){
                            
                               
                                MUSW__Fee__c Fee_record = new MUSW__Fee__c();
                                Fee_record.MUSW__Type__c = msFeeRec.Fee_Type__c;
                                //Fee_record.MUSW__Amount__c =Decimal.valueOf(msFeeRec.Fee_Formula_Amount__c);
                                Fee_record.MUSW__Amount__c = msFeeRec.Base__c;
                                Fee_record.Agency__c =msFeeRec.Agency__c;
                                Fee_record.Revenue_Code__c =msFeeRec.Revenue_Code__c;
                                Fee_record.Application_Type__c =msFeeRec.Application_Type__c;
                                Fee_record.portal_name__c =msFeeRec.Portal_Name__c;
                                Fee_record.Agency_Number__c =msFeeRec.Agency_Number__c;
                                Fee_record.Profession_Code__c =msFeeRec.Profession_Code__c;
                                Fee_record.Application_Method__c =msFeeRec.Application_Method__c;
                                Fee_record.License_Type__c =msFeeRec.License_Type__c;
                                Fee_record.Fee_Name__c= msFeeRec.Name;
                                Fee_record.Renewal_Application__c = renewal_Rec.Id;
                                feeList.add(Fee_record);
                                
                            }
                }
                
                if(!feeList.isEmpty()){
                    InsertedfeeList = Utilityclass_withsharing.insertList(feeList);
                    if(!InsertedfeeList.isEmpty()){
                        renewal_Rec.Renewal_Status__c =FeeGenartionCompletedStatus;
                        update renewal_Rec;
                        return 'True';
                    }
                }
            }
            return 'False';
            */
            
        }catch(Exception e){DOL_CreateErrorLog_Exception.logApplicationError(e,'LnP_generateFeeRecords_Class','generateFeeRecords_Renewals');return 'False';}
        
    }
}