src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <label>UBI #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Unique_ID_To_Provide__c</fullName>
        <label>Select Personal ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SSN</fullName>
                    <label>Social Security Number (SSN)</label>
                </value>
                <value>
                    <fullName>ITIN</fullName>
                    <label>Individual Taxpayer Identification Number (ITIN)</label>
                </value>
                <value>
                    <fullName>No_SSN_or_ITIN</fullName>
                    <label>I don&apos;t have an SSN or ITIN</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <formula>Ultimate_Parent_Account__r.UBI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBI Number</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Physical address</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for License Parcel Record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMUSEMENT</fullName>
                </value>
                <value>
                    <fullName>CHECK</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER REQUEST</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE</fullName>
                </value>
                <value>
                    <fullName>HOME</fullName>
                </value>
                <value>
                    <fullName>INSPECTION</fullName>
                </value>
                <value>
                    <fullName>INSPECTIONS</fullName>
                </value>
                <value>
                    <fullName>INVOICE</fullName>
                </value>
                <value>
                    <fullName>LOCATION OF HOME</fullName>
                </value>
                <value>
                    <fullName>LPOCONTRACT</fullName>
                </value>
                <value>
                    <fullName>MAILING ADDRESS</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MINE SAFETY</fullName>
                </value>
                <value>
                    <fullName>OWNER</fullName>
                </value>
                <value>
                    <fullName>UNDELIVERABLE</fullName>
                </value>
                <value>
                    <fullName>WORK</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PHYSICAL ADDRESS</fullName>
                </value>
                <value>
                    <fullName>SITE</fullName>
                    <isActive>false</isActive>
                    <label>SITE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parent_Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The associated parcel that is the containing parcel for addresses, units or sub-lots.</description>
        <label>Parent Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Related Parcels</relationshipLabel>
        <relationshipName>Parcel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of parcel record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Physical_and_Mailing_Address_Same__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Physical and Mailing Address Same</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Polaris_LicenseParcelTriggerHandler_Test.cls
@isTest
public class Polaris_LicenseParcelTriggerHandler_Test {
    
    @testSetup
    private static void setupTestData()
    {   
        Account account = new Account(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Account',UBI_Number__c ='79068467');
        insert account;
        Contact c = new Contact(LastName= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Contact44',FirstName= DOL_AppConstants.NULL_EMPTY_STRING + 'BasicGov', Email= DOL_AppConstants.NULL_EMPTY_STRING + 'test@basicgov.com',Account=account
                               ,Unique_ID_To_Provide__c='No_SSN_or_ITIN');
        insert c;

        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicenseIndividual(LicRecTypeId1, c.Id, 'Appraisers - Real Estate', 'Certified General Appraiser', 'General Application');
        MUSW__Parcel__c par = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique1', Address_Type__c='PHYSICAL ADDRESS',MUSW__Primary_Contact__c= c.Id);
        insert par;
        MUSW__Parcel__c par4 = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique4', Address_Type__c='PHYSICAL ADDRESS',MUSW__Primary_Contact__c= c.Id);
        insert par4;
        MUSW__Parcel__c par2 = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique2', Address_Type__c='MAILING ADDRESS',MUSW__Primary_Contact__c=c.id);
        insert par2;
        MUSW__Parcel__c par3 = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique3',Address_Type__c='MAILING ADDRESS', is_Physical_and_Mailing_Address_Same__c=true,MUSW__Primary_Contact__c =c.id);
        insert par3;
        List<MUSW__Parcel__c > lstparcel = [Select Id,Address_Type__c,is_Physical_and_Mailing_Address_Same__c FROM MUSW__Parcel__c where MUSW__Primary_Contact__r.name ='BasicGov Test Contact44'];        
         List<MUSW__License_Parcel__c> licenseParcelList = new List<MUSW__License_Parcel__c>();
        for(MUSW__Parcel__c parcelInstance : lstparcel) {
            MUSW__License_Parcel__c licenseParcelRecord = new MUSW__License_Parcel__c();
            licenseParcelRecord.MUSW__Parcel__c = parcelInstance.Id;
            licenseParcelRecord.MUSW__License2__c    = lic1.id;
            licenseParcelRecord.Status__c = 'Active';
            if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && !parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
            }else if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
                licenseParcelRecord.Physical__c = true;
            }else{
                licenseParcelRecord.Physical__c = true;
            }
            licenseParcelList.add(licenseParcelRecord); 
        }
        insert licenseParcelList;
       
    }
    
    @isTest
    public static void testTriggerInsert(){
        List<MUSW__Parcel__c > lstparcel = [Select Id,Address_Type__c,is_Physical_and_Mailing_Address_Same__c FROM MUSW__Parcel__c where MUSW__Primary_Contact__r.name ='BasicGov Test Contact44'];
        List<MUSW__License2__c> lstlicense =[select id from MUSW__License2__c where Application_Type__c = 'Appraisers - Real Estate'];
        List<MUSW__License_Parcel__c> licenseParcelList = new List<MUSW__License_Parcel__c>();
        for(MUSW__Parcel__c parcelInstance : lstparcel) {
            MUSW__License_Parcel__c licenseParcelRecord = new MUSW__License_Parcel__c();
            licenseParcelRecord.MUSW__Parcel__c = parcelInstance.Id;
            licenseParcelRecord.MUSW__License2__c    = lstlicense[0].id;
            licenseParcelRecord.Status__c = 'Active';
            if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && !parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
            }else if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
                licenseParcelRecord.Physical__c = true;
            }else{
                licenseParcelRecord.Physical__c = true;
            }
            licenseParcelList.add(licenseParcelRecord); 
        }
        insert licenseParcelList;
         system.assertEquals(4, licenseParcelList.size());
        
    }
      @isTest
    public static void testTriggerUpdate(){
        List<MUSW__License_Parcel__c> licenseParcelList =[select id,MUSW__Parcel__r.name,MUSW__Parcel__r.Address_Type__c,MUSW__Parcel__r.is_Physical_and_Mailing_Address_Same__c from MUSW__License_Parcel__c  where MUSW__Parcel__r.name in ('xyz123Unique1','xyz123Unique2','xyz123Unique3','xyz123Unique4')];
        for(MUSW__License_Parcel__c lstparcel2 : licenseParcelList) {
            if(lstparcel2.MUSW__Parcel__r.Address_Type__c == 'PHYSICAL ADDRESS' && lstparcel2.MUSW__Parcel__r.name  =='xyz123Unique1') {                
               lstparcel2.Mailing__c = true;
            }
        }
        update licenseParcelList;
        system.assertEquals(4, licenseParcelList.size());
        
    }
    @isTest
    public static void testTriggerDelete(){
        List<MUSW__License_Parcel__c> licenseParcelList =[select id,MUSW__Parcel__r.Address_Type__c,MUSW__Parcel__r.is_Physical_and_Mailing_Address_Same__c from MUSW__License_Parcel__c  where MUSW__Parcel__r.name in ('xyz123Unique1','xyz123Unique2','xyz123Unique3')];
        delete licenseParcelList;
        undelete licenseParcelList;
    }
}