src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Social_Security_Number_Encrypted__c</fullName>
        <description>Encrypted SSN field</description>
        <label>Social Security Number Encrypted</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Birth_City__c</fullName>
        <label>Birth City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birth_Country__c</fullName>
        <label>Birth Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_of_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Birth_State_Province__c</fullName>
        <label>Birth State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Provinces</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duplicate_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this field if you want to override the Duplicate check.</description>
        <label>Duplicate Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Ethnicity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Social_Security_Number_Encrypted__c</fullName>
        <label>Social Security Number Encrypted</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Ethnicity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>American Indian or Alaska Native</fullName>
    </customValue>
    <customValue>
        <fullName>Asian Indian</fullName>
    </customValue>
    <customValue>
        <fullName>Black or African American</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <customValue>
        <fullName>Filipino</fullName>
    </customValue>
    <customValue>
        <fullName>Guamanian or Chamorro</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic - Cuban</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic - Latino, or Spanish Origin</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic - Mexican, Chicano</fullName>
    </customValue>
    <customValue>
        <fullName>Hispanic - Puerto Rican</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Native Hawaiian</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Other Asian</fullName>
    </customValue>
    <customValue>
        <fullName>Other Pacific Islander</fullName>
    </customValue>
    <customValue>
        <fullName>Samoan</fullName>
    </customValue>
    <customValue>
        <fullName>Vietnamese</fullName>
    </customValue>
    <customValue>
        <fullName>White</fullName>
    </customValue>
    <description>Ethnicity values</description>
    <masterLabel>Ethnicity</masterLabel>
</GlobalValueSet>

src/globalValueSets/List_of_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina</fullName>
    </customValue>
    <customValue>
        <fullName>Burma</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <description>List of countries for selection on Applications</description>
    <masterLabel>List of Countries</masterLabel>
</GlobalValueSet>

src/globalValueSets/State_Provinces.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Guam</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <description>List of US States and Provinces</description>
    <masterLabel>State Provinces</masterLabel>
</GlobalValueSet>

src/classes/ApexUserSharingModelTest.cls
/**
* Name: ApexUserSharingModelTest
* Type: Class
* Description: Apex Test Class for ApexUserSharingModel.
* Date:        Developer/Company                 	Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 09/24/2018   Srikanth Kottam/Deloitte           Initial Creation
**/
@isTest
public class ApexUserSharingModelTest {
    @testSetup
    public static void createTestData(){
        //Create Business Account
        Account busAcc = CreateTestDataUtility.createBusinessAccount();
        
        //Create Account
        Account acc = CreateTestDataUtility.createAccount();
        
        List<Account> accList = new List<Account>{busAcc, acc};
            insert accList;
        
        //Create Contact
        Contact firstCon = new Contact(LastName = 'firstConLastName', firstName =  'firstConFirstName', Email='firstcon@mailinator.com', 
                                       Birthdate = null, AccountId = acc.Id, Social_Security_Number_Encrypted__c = '111222333', 
                                       Duplicate_Override__c = true, Birth_Country__c ='United States', Birth_State_Province__c='Illinois', Birth_City__c='Chicago', 
                                       Gender__c='Male', Ethnicity__c='Asian Indian');
        //Create 2nd Contact
        Contact secondCon = new Contact(LastName = 'secondConLastName', firstName =  'secondConFirstName', Email='secondcon@mailinator.com', 
                                        Birthdate = null, AccountId = acc.Id, Social_Security_Number_Encrypted__c = '999888777', 
                                        Duplicate_Override__c = true, Birth_Country__c ='United States', Birth_State_Province__c='Illinois', Birth_City__c='Chicago', 
                                        Gender__c='Male', Ethnicity__c='Asian Indian');
        
        List<Contact> conList = new List<Contact>{firstCon, secondCon};
            insert conList;
        
        //Create Community User
        User portalUser = CreateTestDataUtility.createCommunityTestUser(firstCon.Id);
        portalUser.Alias = 'puser';
        portalUser.Email = 'portaluserone@mailinator.com';
        portalUser.LastName = 'firstConLastName';
        portalUser.UserName = 'portaluserone@mailinator.com';
        
        //Create Community Plus User
        User plusUser = CreateTestDataUtility.createCommunityPlusUser(secondCon.Id);
        plusUser.Alias = 'ppuser';
        plusUser.Email='portalplususerone@mailinator.com';
        plusUser.LastName='secondConLastName';
        plusUser.UserName='portalplususerone@mailinator.com';
        
        List<User> lstUser = new List<User>{portalUser, plusUser};
        insert lstUser;
    }
    @isTest
    Static void testSharing(){
        Test.startTest();
        Account busAcc = [Select Id FROM Account WHERE Name = 'TestBusinessAccount'];
        Account acc = [Select Id FROM Account WHERE Name = 'utilityAccountFirstName'];
        system.debug('busAcc>>>'+busAcc);
        Contact c = [Select Id FROM Contact WHERE LastName = 'secondConLastName'];
        Contact c2 = [Select Id FROM Contact WHERE LastName = 'firstConLastName'];
        User u = [SELECT Id, isActive FROM User WHERE ContactId =: c.Id]; 
        User u2 = [SELECT Id, isActive FROM User WHERE ContactId =: c2.Id];
        //Create Account Contact
        MUSW__Account_Contact__c testAccCon = CreateTestDataUtility.createAccountContact(busAcc.Id,c.Id);
        Database.insert(testAccCon);
        Map<Id, MUSW__Account_Contact__c> insertAccountContact = new Map<Id, MUSW__Account_Contact__c>();
        insertAccountContact.put(testAccCon.Id, testAccCon);
        System.runAs(u){
            //Create Credential
            Musw__License2__c pendingCredential = CreateTestDataUtility.createLicense(acc.Id, c.Id);
            insert pendingCredential; 
            
        }
        List<Musw__License2__c> lstCredential = [Select Id, MUSW__Primary_Licensee__c from Musw__License2__c where MUSW__Primary_Licensee__c =: acc.Id];
        system.debug('lstCredential>>>'+lstCredential);
        system.assertEquals(lstCredential.size(), 1);
        
        List<Musw__License2__share> credShare = [Select id, ParentId, UserOrGroupId, AccessLevel from MUSW__License2__share 
                                                 where ParentId =: lstCredential[0].id or UserOrGroupId =: u.Id];
        system.debug('credShare>>>'+credShare);
        system.assertEquals(credShare.size(), 2);
        System.runAs(u2){
            //Create Credential
            Musw__License2__c activeCredential = CreateTestDataUtility.createLicense(acc.Id, c2.Id);
            insert activeCredential; 
        }
        MUSW__Account_Contact__c updateAccCon = [Select id, MUSW__Account__c, MUSW__Contact__c from MUSW__Account_Contact__c
                                                 where MUSW__Account__c =: busAcc.Id and MUSW__Contact__c =: c.Id];
        updateAccCon.MUSW__Contact__c = c2.Id;
        update testAccCon;
        
        Map<Id, MUSW__Account_Contact__c> updateAccountContact = new Map<Id, MUSW__Account_Contact__c>();
        updateAccountContact.put(updateAccCon.Id, updateAccCon);
        ApexUserSharingModel apexSharing = new ApexUserSharingModel();
        apexSharing.getAccountIds(false, true, insertAccountContact, updateAccountContact);
        Test.stopTest();
    }
}