src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>User_Account</fullName>
        <active>true</active>
        <description>User Account</description>
        <label>User Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parcel for which the application is being submitted.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>General_Service_Request</fullName>
        <active>true</active>
        <label>General Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Universal_Default_License_Record_Type</fullName>
        <active>true</active>
        <description>This is the record type if the application type doesn&apos;t appear on any other record types.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMUSEMENT</fullName>
                </value>
                <value>
                    <fullName>CHECK</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER REQUEST</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE</fullName>
                </value>
                <value>
                    <fullName>HOME</fullName>
                </value>
                <value>
                    <fullName>INSPECTION</fullName>
                </value>
                <value>
                    <fullName>INSPECTIONS</fullName>
                </value>
                <value>
                    <fullName>INVOICE</fullName>
                </value>
                <value>
                    <fullName>LOCATION OF HOME</fullName>
                </value>
                <value>
                    <fullName>LPOCONTRACT</fullName>
                </value>
                <value>
                    <fullName>MAILING ADDRESS</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MINE SAFETY</fullName>
                </value>
                <value>
                    <fullName>OWNER</fullName>
                </value>
                <value>
                    <fullName>UNDELIVERABLE</fullName>
                </value>
                <value>
                    <fullName>WORK</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PHYSICAL ADDRESS</fullName>
                </value>
                <value>
                    <fullName>SITE</fullName>
                    <isActive>false</isActive>
                    <label>SITE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_BG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>Field to Store county</description>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MUSW__State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Physical_and_Mailing_Address_Same__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Physical and Mailing Address Same</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Profession__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SOD_Address_Auth__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>AuthID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>AuthID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthToken__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>AuthToken</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SOD_Address_Auth</label>
</CustomObject>

src/globalValueSets/County.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Asotin</fullName>
    </customValue>
    <customValue>
        <fullName>Benton</fullName>
    </customValue>
    <customValue>
        <fullName>Chelan</fullName>
    </customValue>
    <customValue>
        <fullName>Clallam</fullName>
    </customValue>
    <customValue>
        <fullName>Clark</fullName>
    </customValue>
    <customValue>
        <fullName>Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Cowlitz</fullName>
    </customValue>
    <customValue>
        <fullName>Douglas</fullName>
    </customValue>
    <customValue>
        <fullName>Ferry</fullName>
    </customValue>
    <customValue>
        <fullName>Franklin</fullName>
    </customValue>
    <customValue>
        <fullName>Garfield</fullName>
    </customValue>
    <customValue>
        <fullName>Grant</fullName>
    </customValue>
    <customValue>
        <fullName>Grays Harbor</fullName>
    </customValue>
    <customValue>
        <fullName>Island</fullName>
    </customValue>
    <customValue>
        <fullName>Jefferson</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>Kitsap</fullName>
    </customValue>
    <customValue>
        <fullName>Kittitas</fullName>
    </customValue>
    <customValue>
        <fullName>Klickitat</fullName>
    </customValue>
    <customValue>
        <fullName>Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Mason</fullName>
    </customValue>
    <customValue>
        <fullName>Okanogan</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Pend Oreille</fullName>
    </customValue>
    <customValue>
        <fullName>Pierce</fullName>
    </customValue>
    <customValue>
        <fullName>San Juan</fullName>
    </customValue>
    <customValue>
        <fullName>Skagit</fullName>
    </customValue>
    <customValue>
        <fullName>Skamania</fullName>
    </customValue>
    <description>County Picklist</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Cemetery</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/LnP_LicenseAddressApexControllerTest.cls
@isTest
public class LnP_LicenseAddressApexControllerTest {
    
    @testSetup static void setup() {
        // Create common test accounts
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('User_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecordTypeId);
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecordTypeId,acc.Id);
        Id parcelRecordTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByDeveloperName().get('Address').getRecordTypeId();
        MUSW__Parcel__c testparcel1 = DOL_TestDataFactory.createParcel(parcelRecordTypeId);
        testparcel1.MUSW__Primary_Contact__c = con.Id;
        testparcel1.Address_Type__c = 'MAILING ADDRESS';
        testparcel1.is_Physical_and_Mailing_Address_Same__c = true;
        update testparcel1;
        Id LocationRT = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByName().get('Affiliated Location').getRecordTypeId(); 
        Id licRecordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        Id licRecordTypeIdIndivi = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByDeveloperName().get('Universal_Default_License_Record_Type').getRecordTypeId();        
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicenseIndividual(licRecordTypeIdIndivi, con.Id, 'Notary Public', 'Notary Public', 'General Application');
        MUSW__License2__c lic2 = DOL_TestDataFactory.createLicense(licRecordTypeId, acc.Id, 'Cemeteries', 'Cemetery', 'General Application');
        MUSW__License_Parcel__c testLicenseParcel = DOL_TestDataFactory.createLicenseParcel(lic1.id,testparcel1.id);
        Request__c testRequest1 = DOL_TestDataFactory.createRequest(lic1.Id,'Cemeteries', 'Cemetery');
        MUSW__Parcel__c testparcel2 = DOL_TestDataFactory.createParcel(parcelRecordTypeId);
        testparcel2.MUSW__Primary_Contact__c = con.Id;
        testparcel2.Primary_Account__c = acc.Id;
        testparcel2.Request_Parcel__c = testRequest1.Id;
        testparcel2.Request__c = testRequest1.Id;
        testparcel2.recordtypeid = LocationRT;
        testparcel2.Address_Type__c = 'PHYSICAL ADDRESS';
        testparcel2.is_Physical_and_Mailing_Address_Same__c = false;
        update testparcel2;
        
    }
    
    
    public static testMethod void LnP_LicenseAddressApexControllerMethod1(){
        Contact con = [Select Id from contact where LastName= 'Test Contact' ];        
        Account acc = [Select Id from Account where Name= 'Test Account' ];        
        Id applicationRecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByDeveloperName().get('General_Service_Request').getRecordTypeId();
        MUSW__Application2__c testApp = DOL_TestDataFactory.createApplication(applicationRecordTypeId);
        MUSW__Parcel__c parcel = [Select Id,Application_BG__c from MUSW__Parcel__c where MUSW__Primary_Contact__c=: con.Id limit 1];
        MUSW__Parcel__c parcelPhysical = [Select Id,Application_BG__c from MUSW__Parcel__c where Primary_Account__c=: acc.Id limit 1];
        parcel.Application_BG__c = testApp.Id;
        update parcel;
        MUSW__License2__c lic1 = [Select id from MUSW__License2__c where Credential_Type__c='Notary Public' limit 1];
        MUSW__License2__c lic2 = [Select id from MUSW__License2__c where Credential_Type__c='Cemetery' limit 1];
        Request__c testRequest1 = [Select id From Request__c where License_Type__c='Cemetery' limit 1];
        
        String addressStringone = 'Businessfirst, Olympia, WA, 9887, United States';
        String addressStringtwo = 'Businessfirst,Businesstwo, Olympia, WA, 9887, United States';
        test.startTest();
        LnP_LicenseAddressApexController.getAllAddress(con.Id,testApp.Id);
        LnP_LicenseAddressApexController.getPhysicalAddress(lic1.Id);
        LnP_LicenseAddressApexController.getAddressDetailsType();
        LnP_LicenseAddressApexController.getPhysicalAddressForRequest(testRequest1.Id);
        LnP_LicenseAddressApexController.getCountyValue('WA','Olympia');
        LnP_LicenseAddressApexController.getCountyValue('AL','Test');
        LnP_LicenseAddressApexController.sameAddUpdate(parcel.Id,'MUSW__Parcel__c',con.Id,true,testApp.Id);
        LnP_LicenseAddressApexController.sameAddUpdate(parcelPhysical.Id,'MUSW__Parcel__c',con.Id,true,testApp.Id);
        LnP_LicenseAddressApexController.deleteTableRecord(parcel.Id,'MAILING ADDRESS','MUSW__Parcel__c',testApp.Id);
        LnP_LicenseAddressApexController.getStates(parcel,'County__c');
        LnP_LicenseAddressApexController.validateAddress('add1','add2','city','state','1222');        
        
        test.stopTest();
    }
    public static testMethod void LnP_LicenseAddressApexControllerMethod2(){
        Contact con = [Select Id from contact where LastName= 'Test Contact' ];        
        Account acc = [Select Id from Account where Name= 'Test Account' ];        
        Id applicationRecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByDeveloperName().get('General_Service_Request').getRecordTypeId();
        MUSW__Application2__c testApp = DOL_TestDataFactory.createApplication(applicationRecordTypeId);
        MUSW__Application2__c testApp2 = DOL_TestDataFactory.createApplication(applicationRecordTypeId);
        MUSW__Parcel__c parcel = [Select Id,Application_BG__c from MUSW__Parcel__c where MUSW__Primary_Contact__c=: con.Id limit 1];
        MUSW__Parcel__c parcelPhysical = [Select Id,Application_BG__c from MUSW__Parcel__c where Primary_Account__c=: acc.Id limit 1];
        parcel.Application_BG__c = testApp.Id;        
        update parcel;
        
        List<Id> lstparelId = new List<Id>();
        lstparelId.add(parcel.Id);
        MUSW__License2__c lic1 = [Select id from MUSW__License2__c where Credential_Type__c='Notary Public' limit 1];
        MUSW__License2__c lic2 = [Select id from MUSW__License2__c where Credential_Type__c='Cemetery' limit 1];
        Request__c testRequest1 = [Select id From Request__c where License_Type__c='Cemetery' limit 1];
        String addressStringone = 'Businessfirst, Olympia, WA, 9887, United States';
        String addressStringtwo = 'Businessfirst,Businesstwo, Olympia, WA, 9887, United States';
        test.startTest();
        LnP_LicenseAddressApexController.integrationsaveAddress(addressStringone,false,testApp.Id,false,'MAILING ADDRESS','Adams',con.Id,'Contact',false,false);
        LnP_LicenseAddressApexController.integrationsaveAddress(addressStringone,true,testApp2.Id,true,'PHYSICAL ADDRESS','Adams',acc.Id,'Account',true,true);
        LnP_LicenseAddressApexController.AffiliatedLocation(JSON.serialize(parcel),true,true);
        LnP_LicenseAddressApexController.AffiliatedLocation(JSON.serialize(parcel),true,false);
        LnP_LicenseAddressApexController.AffiliatedLocation(JSON.serialize(parcel),false,true);
        LnP_LicenseAddressApexController.AffiliatedLocation(JSON.serialize(parcel),false,false);
        LnP_LicenseAddressApexController.removeLocation(parcel.Id,true);
        LnP_LicenseAddressApexController.removeLocation(parcel.Id,false);
        LnP_LicenseAddressApexController.setRequestLocationTable(testRequest1.Id);
        //LnP_LicenseAddressApexController.removeAffiliationRequest(lstparelId,testRequest1.Id);
        LnP_LicenseAddressApexController.undoAffiliateRequest(parcel.Id,'Pending Add','test');
        LnP_LicenseAddressApexController.undoAffiliateRequest(parcel.Id,'Pending Remove','test');
        LnP_LicenseAddressApexController.undoAffiliateRequest(parcel.Id,'Pending Remove',null);
        LnP_LicenseAddressApexController.setLocationTable(testApp.Id, testRequest1.Id, true,true);
        LnP_LicenseAddressApexController.setLocationTable(testApp.Id, testRequest1.Id, false,true);
        LnP_LicenseAddressApexController.setLocationTable(testApp.Id, testRequest1.Id, false,false);
        test.stopTest();
    }
     public static testMethod void LnP_LicenseAddressApexControllerMethod3(){
         Contact con = [Select Id from contact where LastName= 'Test Contact' ]; 
         Account acc = [Select Id from Account where Name= 'Test Account' ]; 
         Id applicationRecordTypeId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByDeveloperName().get('General_Service_Request').getRecordTypeId();
         MUSW__Application2__c testApp = DOL_TestDataFactory.createApplication(applicationRecordTypeId);
         MUSW__Parcel__c parcel = [Select Id,Application_BG__c from MUSW__Parcel__c where MUSW__Primary_Contact__c=: con.Id limit 1];
        MUSW__Parcel__c parcelPhysical = [Select Id,Application_BG__c from MUSW__Parcel__c where Primary_Account__c=: acc.Id limit 1];
        parcel.Application_BG__c = testApp.Id;
        parcelPhysical.Application_BG__c = testApp.Id;
        update parcel;
        update parcelPhysical;
        SOD_Address_Auth__c objCS = new SOD_Address_Auth__c(Name = 'Auto_Complete_Address');
         objCS.url__c ='https://us-autocomplete.api.smartystreets.com/suggest?';
             objCS.AuthID__c = '414e1969-26ef-f656-68bc-668f24ce0b8d';
             objCS.AuthToken__c = 'VgUZjHEiR0cQd7LrsfEq';
         objCS.Key__c = '33656206653415784';
         insert objCS;
         test.startTest();
         LnP_LicenseAddressApexController.AddrWrapper wrapper = new LnP_LicenseAddressApexController.AddrWrapper();
         wrapper.country = 'country';
         wrapper.street ='Street';
         wrapper.street2 ='street2';
         wrapper.city ='city';
         wrapper.state ='state';
         wrapper.zip ='zip';
         
         LnP_LicenseAddressApexController.addContactparcel(con.Id,parcel.Id);
         LnP_LicenseAddressApexController.getloggedInContactData();
         LnP_LicenseAddressApexController.getAutoComplete('test');
         StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
         test.stopTest();
         
     }
}