src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Alias__c</fullName>
        <description>The account alias will be used to identify specific businesses if you manage multiple businesses with the same name.</description>
        <label>Business Alias</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Doing_Business_As_1__c</fullName>
        <description>Indicates the name they are doing business as (1)</description>
        <label>Doing Business As</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Primary_Contact__c</fullName>
        <description>Primary Contact Email</description>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Extension__c</fullName>
        <label>Extension</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEIN_Number_Encrypted__c</fullName>
        <description>Encrypted field for FEIN Number</description>
        <inlineHelpText>FEIN Number Encrypted</inlineHelpText>
        <label>FEIN Number Encrypted</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>First_Name_Primary_Contact__c</fullName>
        <description>Primary Contact First Name</description>
        <label>Primary Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_Primary_Contact__c</fullName>
        <description>Primary Contact Last Name</description>
        <label>Primary Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Primary_Contact__c</fullName>
        <description>Primary Contact Phone</description>
        <label>Primary Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Security Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Social_Security_Number_Encrypted__c</fullName>
        <description>Encrypted SSN field</description>
        <label>Social Security Number Encrypted</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Type_of_Ownership__c</fullName>
        <description>DO NOT USE. This is same as &quot;Business Structure&quot; field. Account&apos;s ownership types list</description>
        <label>Type of Ownership</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Limited Partnership</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Professional Association</fullName>
                </value>
                <value>
                    <fullName>Public School</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>Associate_Status__c</fullName>
        <description>Associate Status between Account and Contact</description>
        <label>Associate Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>MUSW__Successor__c</fullName>
        <description>The succeeding User will inherit all records currently associated with the User being deactivated</description>
        <inlineHelpText>The succeeding User will inherit all records currently associated with the User being deactivated</inlineHelpText>
        <label>Successor</label>
        <relationshipName>InactiveUsers</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Add_BusinessController.cls
public class Add_BusinessController {
	
    //get BusinessAccount RecordType Id 
    @AuraEnabled 
    public static id getRecordTypeIdAccount(){
       return Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId() ;
    }
    
     @AuraEnabled
    public static List<Account> getAllAccounts(){
        Set<Id> accntIdSet = new Set<Id>();
        User currentUser = [SELECT Id, Name,firstName ,lastName, ContactId , IsActive, IsPortalEnabled, MUSW__Successor__c, ProfileId , email from User Where ID = :UserInfo.getUserId() LIMIT 1];
        List<MUSW__Account_Contact__c> accntConList = [SELECT Id,MUSW__Contact__c,MUSW__Account__c,MUSW__Account__r.Name,MUSW__Account__r.Type_of_Ownership__c,MUSW__Account__r.Security_Code__c,MUSW__Account__r.First_Name_Primary_Contact__c,MUSW__Account__r.Last_Name_Primary_Contact__c,MUSW__Account__r.Business_Alias__c ,MUSW__Account__r.Doing_Business_As_1__c ,MUSW__Account__r.Website,MUSW__Account__r.Phone_Primary_Contact__c,MUSW__Account__r.Fax,MUSW__Account__r.Email__c,MUSW__Account__r.Email_Primary_Contact__c,MUSW__Account__r.FEIN_Number_Encrypted__c,MUSW__Account__r.Social_Security_Number_Encrypted__c,MUSW__Account__r.UBI_Number__c,MUSW__Account__r.Extension__c,MUSW__Account__r.Business_Phone__c,Name FROM MUSW__Account_Contact__c WHERE MUSW__Contact__c =: currentUser.ContactId  AND MUSW__Account__c != null and Associate_Status__c = 'Active'] ; 
        for(MUSW__Account_Contact__c accCon : accntConList ){
            accntIdSet.add(accCon.MUSW__Account__c);
        }
        return [select Id,Name,Type_of_Ownership__c,Doing_Business_As_1__c,First_Name_Primary_Contact__c,Last_Name_Primary_Contact__c,Phone_Primary_Contact__c,UBI_Number__c,Email__c,Business_Phone__c,Extension__c,Website from Account where id in:accntIdSet ];
    }
    
    @AuraEnabled
    public static void createAccountContactObject(String aId){
        System.debug('inside createAccount::');
        MUSW__Account_Contact__c retRes ;
         User currentUser = [SELECT Id,ContactId , email from User Where ID = :UserInfo.getUserId() LIMIT 1];
        list<MUSW__Account_Contact__c> businessList = new list<MUSW__Account_Contact__c>([SELECT Id, MUSW__Contact__c, MUSW__Account__r.Name, MUSW__Account__r.BillingStreet, MUSW__Account__r.BillingCity, MUSW__Account__r.BillingState, MUSW__Account__r.BillingPostalCode, MUSW__Account__r.BillingCountry FROM MUSW__Account_Contact__c WHERE MUSW__Contact__c =: currentUser.ContactId AND MUSW__Account__c =: aId ]);
        if(businessList.size()==0){
            MUSW__Account_Contact__c ac = new MUSW__Account_Contact__c();
            ac.MUSW__Account__c = aId;
            ac.MUSW__Contact__c = currentUser.ContactId;
            ac.Associate_Status__c = 'Active' ;
            insert ac;
        }
        
    }
    
    @AuraEnabled
    public static void updateAccount(List<Account> acc ){
        update acc;
    }
    
}