src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <label>UBI #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
    <fields>
        <fullName>Unique_ID_To_Provide__c</fullName>
        <label>Select Personal ID</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SSN</fullName>
                    <label>Social Security Number (SSN)</label>
                </value>
                <value>
                    <fullName>ITIN</fullName>
                    <label>Individual Taxpayer Identification Number (ITIN)</label>
                </value>
                <value>
                    <fullName>No_SSN_or_ITIN</fullName>
                    <label>I don&apos;t have an SSN or ITIN</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/License_Type__mdt.object
<CustomObject>
    <description>This is the configuration that helps create application.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the type of application.</description>
        <label>Application Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <label>Credential Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>License Type</label>
    <pluralLabel>License Types</pluralLabel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Combined Licenses</relationshipLabel>
        <relationshipName>Combined_Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <formula>Ultimate_Parent_Account__r.UBI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBI Number</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for License Parcel Record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address_Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMUSEMENT</fullName>
                </value>
                <value>
                    <fullName>CHECK</fullName>
                </value>
                <value>
                    <fullName>CONTACT</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER REQUEST</fullName>
                </value>
                <value>
                    <fullName>DO NOT USE</fullName>
                </value>
                <value>
                    <fullName>HOME</fullName>
                </value>
                <value>
                    <fullName>INSPECTION</fullName>
                </value>
                <value>
                    <fullName>INSPECTIONS</fullName>
                </value>
                <value>
                    <fullName>INVOICE</fullName>
                </value>
                <value>
                    <fullName>LOCATION OF HOME</fullName>
                </value>
                <value>
                    <fullName>LPOCONTRACT</fullName>
                </value>
                <value>
                    <fullName>MAILING ADDRESS</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MINE SAFETY</fullName>
                </value>
                <value>
                    <fullName>OWNER</fullName>
                </value>
                <value>
                    <fullName>UNDELIVERABLE</fullName>
                </value>
                <value>
                    <fullName>WORK</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PHYSICAL ADDRESS</fullName>
                </value>
                <value>
                    <fullName>SITE</fullName>
                    <isActive>false</isActive>
                    <label>SITE</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of parcel record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status = Accepted when the document satisfies the submission requirement. Status = Additional Info. Required when the document does not satisfy the submission requirement and should be sent back to the Applicant.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Additional Info. Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>Public_Disciplinary_Action__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box to make the disciplinary action public</description>
        <inlineHelpText>Check this box to make the disciplinary action public</inlineHelpText>
        <label>Public Disciplinary Action</label>
        <type>Checkbox</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/Polaris_DynamicSQL_Test.cls
@isTest
public class Polaris_DynamicSQL_Test {
  
    @testSetup
    private static void setupTestData()
    {   
        Account account = new Account(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Account',UBI_Number__c ='79068467');
        insert account;
        Contact c = new Contact(LastName= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Contact44',FirstName= DOL_AppConstants.NULL_EMPTY_STRING + 'BasicGov', Email= DOL_AppConstants.NULL_EMPTY_STRING + 'test@basicgov.com',Account=account
                                ,Unique_ID_To_Provide__c='No_SSN_or_ITIN');
        insert c;
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicenseIndividual(LicRecTypeId1, c.Id, 'Appraisers - Real Estate', 'Certified General Appraiser', 'General Application');
        MUSW__License2__c lic2 = new MUSW__License2__c(MUSW__Status__c='Active',Name='System Number',Related_License__c= lic1.Id,Application_Type__c='Appraisers - Real Estate'
                                                      ,Credential_Type__c = 'Certified General Appraiser',Application_Method__c = 'General Application');
        insert lic2;
        MUSW__Submission__c sub  = New MUSW__Submission__c(Public_Distribution_URL__c='abc',MUSW__License2__c=lic1.id,Public_Disciplinary_Action__c=true);
        insert sub;
        MUSW__Parcel__c par = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique1', Address_Type__c='PHYSICAL ADDRESS',MUSW__Primary_Contact__c= c.Id);
        insert par;

        List<MUSW__Parcel__c > lstparcel = [Select Id,Address_Type__c,is_Physical_and_Mailing_Address_Same__c FROM MUSW__Parcel__c where MUSW__Primary_Contact__r.name ='BasicGov Test Contact44'];        
        List<MUSW__License_Parcel__c> licenseParcelList = new List<MUSW__License_Parcel__c>();
        for(MUSW__Parcel__c parcelInstance : lstparcel) {
            MUSW__License_Parcel__c licenseParcelRecord = new MUSW__License_Parcel__c();
            licenseParcelRecord.MUSW__Parcel__c = parcelInstance.Id;
            licenseParcelRecord.MUSW__License2__c    = lic1.id;
            licenseParcelRecord.Status__c = 'Active';
            if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && !parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
            }else if(parcelInstance.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && parcelInstance.is_Physical_and_Mailing_Address_Same__c){
                licenseParcelRecord.Mailing__c = true;
                licenseParcelRecord.Physical__c = true;
            }else{
                licenseParcelRecord.Physical__c = true;
            }
            licenseParcelList.add(licenseParcelRecord); 
        }
        insert licenseParcelList;
        MUSW__Parcel__c par4 = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'xyz123Unique4', Address_Type__c='PHYSICAL ADDRESS',MUSW__Primary_Contact__c= c.Id);
        insert par4;
        MUSW__License_Parcel__c licenseParcelRecord = new MUSW__License_Parcel__c();
        licenseParcelRecord.MUSW__Parcel__c = par4.Id;
        licenseParcelRecord.MUSW__License2__c    = lic2.id;
        licenseParcelRecord.Status__c = 'Active';
        if(par4.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && !par4.is_Physical_and_Mailing_Address_Same__c){
            licenseParcelRecord.Mailing__c = true;
        }else if(par4.Address_Type__c == DOL_AppConstants.CAP_MAILING_ADDRESS && par4.is_Physical_and_Mailing_Address_Same__c){
            licenseParcelRecord.Mailing__c = true;
            licenseParcelRecord.Physical__c = true;
        }else{
            licenseParcelRecord.Physical__c = true;
        }
        insert licenseParcelRecord;        
        Profile p = [SELECT Id FROM Profile WHERE Name='CPQ Integration User'];
        User u2 = new User(Alias = 'newUser', Email='newuser5676@testorg.com',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p.Id,
                           TimeZoneSidKey='America/Los_Angeles', UserName='newuser5676@testorg.com');
        insert u2;
        
    }
    @isTest  
    private static void setDataForClass() {
        String objectName ='MUSW__License_Parcel__c';
        string field = 'MUSW__License2__r.License_Printable_Name__c,MUSW__License2__r.Name,MUSW__License2__r.Credential_Type__c,MUSW__License2__r.MUSW__Status__c,MUSW__License2__r.Sub_Status__c,MUSW__Parcel__r.MUSW__City__c,MUSW__License2__r.Related_License__c,MUSW__License2__r.RecordType.Name';
        String objectname2 ='License_Type__mdt';
        string field2 ='Credential_Type__c,IndividualBusinessType__c';
        List<String> lstFieldsName = field.split(',');
        List<String> lstFieldsName2 = field2.split(',');
        Map<String,String> mapCriteria = new Map<String,String>();
        mapCriteria.put('MUSW__License2__r.Credential_Type__c','Certified General Appraiser');
        Map<String,String> mapCriteriaOr = new Map<String,String>();
        mapCriteriaOr.put('MUSW__License2__r.RecordType.Name','Individual');
        Map<String,String> mapCriteriaOrCorrect = new Map<String,String>();
        mapCriteriaOrCorrect.put('1','MUSW__License2__r.RecordType.Name=Individual');
        Map<String,String> mapCriteria2 = new Map<String,String>();
        mapCriteria2.put('IndividualBusinessType__c','Individual');
        boolean bIsStatusIncluded =false;
        boolean showDeciplinary= true;
        Map<String,String> mapCriteriaLicesne = new Map<String,String>();
        mapCriteriaLicesne.put('Application_Type__c','Appraisers - Real Estate');
        string objectApi =  'MUSW__License2__c';
        string fieldsList = 'Name,Id';
        List<String> lstFieldsName3 = fieldsList.split(',');
        Map<String,String> mapCriteriaOror = new Map<String,String>();
        mapCriteriaOror.put('Delivery_Method__c','Individual');
        mapCriteriaOror.put('Credential_Type__c','Appraisers - Real Estate');
        Polaris_DynamicSQL pds = new Polaris_DynamicSQL();
        Polaris_DynamicSQL.generateQuery(objectname2, lstFieldsName2, mapCriteria2);
        Polaris_DynamicSQL.generateQueryLimit(objectApi, lstFieldsName3, mapCriteriaOror,50);
        Polaris_DynamicSQL.generateQueryWithGenericOR(objectName,lstFieldsName,mapCriteria,mapCriteriaOrCorrect,bIsStatusIncluded,showDeciplinary); 
       // Polaris_DynamicSQL.generateQueryWithGenericOR(objectApi,lstFieldsName,mapCriteriaLicesne,mapCriteriaOrCorrect,bIsStatusIncluded,showDeciplinary); 
        Polaris_DynamicSQL.generateQueryWithGenericOR(objectName,lstFieldsName,mapCriteria,mapCriteriaOrCorrect,true,showDeciplinary); 
        Polaris_DynamicSQL.generateQueryWithOR(objectName,lstFieldsName,mapCriteria,true,showDeciplinary); 
         Polaris_DynamicSQL.generateQueryWithOR(objectName,lstFieldsName,mapCriteria,false,showDeciplinary);
        //Polaris_DynamicSQL.generateQueryWithORDetails(objectname2, lstFieldsName2, mapCriteria2,false,showDeciplinary);    
        try{
           Polaris_DynamicSQL.generateQueryLimit(objectName,lstFieldsName,mapCriteria,50);  
        }   catch(Exception ex) {
            
        }
        try{
         Polaris_DynamicSQL.generateQuery(objectName, lstFieldsName, mapCriteria);   
        }   catch(Exception ex) {
            
        }
        try{
          Polaris_DynamicSQL.generateQueryWithGenericOR(objectName,lstFieldsName,mapCriteria,mapCriteriaOr,bIsStatusIncluded,showDeciplinary);  
        }   catch(Exception ex) {
            
        }    
        try{
            Polaris_DynamicSQL.generateQueryWithOR(objectName,lstFieldsName2,mapCriteria,false,showDeciplinary); 
        }   catch(Exception ex) {
            
        } 
        
        
    }
    @isTest
    public static void testgenerateQueryWithORparent(){
       List<MUSW__License2__c> lstlicense =[select id from MUSW__License2__c where Application_Type__c = 'Appraisers - Real Estate' and Related_License__c != null];
        String value = String.valueof(lstlicense[0].id);
        String objectName ='MUSW__License_Parcel__c';
        String fields = 'MUSW__License2__c,MUSW__License2__r.Related_License__r.MUSW__Applicant__r.Full_Name__c,MUSW__License2__r.Related_License__r.Name, MUSW__License2__r.Related_License__r.Credential_Type__c,MUSW__License2__r.Related_License__r.MUSW__Status__c';
        List<String> lstFieldsName = fields.split(',');
        Map<String,String> mapCriteria = new Map<String,String>();
        mapCriteria.put('MUSW__License2__c',value);
        Polaris_DynamicSQL.generateQueryWithORparent(objectName,lstFieldsName,mapCriteria,false);
        Polaris_DynamicSQL.generateQueryWithORparent(objectName,lstFieldsName,mapCriteria,true);
       ///Polaris_DynamicSQL.generateQueryWithORDetails(objectName,lstFieldsName,mapCriteria,true,true);
    }
        @isTest
    public static void testgenerateQueryWithORparentNegative(){
       List<MUSW__License2__c> lstlicense =[select id from MUSW__License2__c where Application_Type__c = 'Appraisers - Real Estate' and Related_License__c = null];
        String value = String.valueof(lstlicense[0].id);
        String objectName ='MUSW__License_Parcel__c';
        String fields = 'MUSW__License2__c,MUSW__License2__r.Related_License__r.MUSW__Applicant__r.Full_Name__c,MUSW__License2__r.Related_License__r.Name, MUSW__License2__r.Related_License__r.Credential_Type__c,MUSW__License2__r.Related_License__r.MUSW__Status__c';
        List<String> lstFieldsName = fields.split(',');
        Map<String,String> mapCriteria = new Map<String,String>();
        mapCriteria.put('MUSW__License2__c',value);
        try{
             Polaris_DynamicSQL.generateQueryWithORparent(objectName,lstFieldsName,mapCriteria,false);
        }
        catch(Exception ex) {
            
        }
    }
    
        @isTest
    public static void testfetchMetaDataValues(){
        Map<String,List<String>> testRes = Polaris_DynamicSQL.fetchMetaDataValues();
        MUSW__License2__c obj = new MUSW__License2__c(); 
        Account obj2 = new Account();
        Polaris_DynamicSQL.MapgetPicklistFieldValues('MUSW__License2__c','Application_Type__c');
        Polaris_DynamicSQL.getPicklistFieldValues('MUSW__License2__c','Application_Type__c');
        Polaris_DynamicSQL.getPicklistOptions(obj,'Application_Type__c','Credential_Type__c');  
        try {
          Polaris_DynamicSQL.getPicklistFieldValues('MUSW__License2__c','cvb');  
        } catch(Exception ex) {
            
        }
        try {
            Polaris_DynamicSQL.MapgetPicklistFieldValues('MUSW__License2__c','');  
        } catch(Exception ex) {
            
        }
        try {
            Polaris_DynamicSQL.getPicklistOptions(obj2,'Application_Type__c','');  
        } catch(Exception ex) {
            
        }
        try {
            Polaris_DynamicSQL ibj = new Polaris_DynamicSQL();
            ibj.operator = '=0';
            List<Polaris_DynamicSQL> lstobj= new List<Polaris_DynamicSQL>();
            lstobj.add(ibj);
            Polaris_DynamicSQL.generateWhereQuery(lstobj);  
        } catch(Exception ex) {
            
        }
    }
    
     @isTest
    public static void testaddComplaint(){
       User u3 = [SELECT Id FROM User WHERE UserName='newuser5676@testorg.com'];
       String ida= Polaris_DynamicSQL.addComplaint();
        String abc = '{"selectedProfession":"Appraisers - Real Estate","professionalData":{"firstName":"Robert","lastName":"Smith","licenseNumber":"","email":"","phone":"","address":"","city":"","state":"Washington","county":""},"businessData":{"businessName":"test","doingBusinessAs":"","licenseNumber":"","email":"robinsmith5555@mailinator.com","phone":"","address":"Goudiya Matam Street","city":"Kovvur","state":"Washington","county":""},"information":{"firstName":"Robert","lastName":"Smith","businessName":"","email":"robinsmith5555@mailinator.com","phone":"","address":"Goudiya Matam Street","city":"Kovvur","state":"Washington","zipcode":"53435"},"complaintSummary":"test description","agreeCheck":true,"anonymous":true}';
        Polaris_DynamicSQL.saveComplaint(abc,ida);
        try {
             Polaris_DynamicSQL.saveComplaint(abc,'ggg');
        } catch(Exception ex) {
            
        }
    }
         @isTest
    public static void testwrapperClass(){
        Polaris_DynamicSQL.professionalDataClass test = new Polaris_DynamicSQL.professionalDataClass();
        test.address='abc';
        test.city='abc';
        test.county='cde';
        test.email='cde';
        test.firstName ='ede';
        test.lastName='etet';
        test.licenseNumber='ahd';
        test.licenseStatus='ff';
        test.phone='56546';
        
        Polaris_DynamicSQL.informationClass infotest = new Polaris_DynamicSQL.informationClass();
        infotest.address='abc';
        infotest.city='abc';
        infotest.state='cde';
        infotest.firstName ='ede';
        infotest.lastName='etet';
        infotest.email='etet';
        infotest.zipcode='ff';
        infotest.phone='56546';
        infotest.middleName='56546';
        
        Polaris_DynamicSQL.businessDataClass busintest = new Polaris_DynamicSQL.businessDataClass();
        busintest.address='abc';
        busintest.businessName='abc';
        busintest.county='cde';
        busintest.doingBusinessAs ='ede';
        busintest.email='etet';
        busintest.licenseStatus='ff';
        busintest.phone='56546';

    }
}