src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Primary_Contact__c</fullName>
        <description>Primary Contact Email</description>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone_Primary_Contact__c</fullName>
        <description>Primary Contact Phone</description>
        <label>Primary Contact Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>Business Account</description>
        <label>Business Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Field__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is this related to a permit renewal?</description>
        <label>Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountValidatorTest.cls
@isTest
public class AccountValidatorTest {
    @isTest
    static void validationMethod(){
        Application_Field__c appField1 = DOL_TestDataFactory.createApplicationField('Email__c', 'Camping Resorts', 'Camping Resort Company', 'Account');
        appField1.License__c = true;
        update appField1;
        Application_Field__c appField2 = DOL_TestDataFactory.createApplicationField('Email_Primary_Contact__c', 'Camping Resorts', 'Camping Resort Company', 'Account');
        appField2.License__c = true;
        update appField2;
        Application_Field__c appField3 = DOL_TestDataFactory.createApplicationField('Phone_Primary_Contact__c', 'Camping Resorts', 'Camping Resort Company', 'Account');
        appField3.License__c = true;
        appField3.Permit_Renewal__c = true;
        update appField3;
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecordTypeId);
        
        Test.startTest();
        ValidationError ve = new ValidationError();
        
        AccountValidator.validate(ve, acc.Id, 'Camping Resort Company', 'Camping Resort Company', 'License__c');
        AccountValidator.validate(ve, acc.Id, 'Manufactured Homes Communities', 'Mechanical', 'Permit_Renewal__c');
        Test.stopTest();
    }
}