src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>User_Account</fullName>
        <active>true</active>
        <description>User Account</description>
        <label>User Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Subsection__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit?</description>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Subsection</label>
    <nameField>
        <label>Subsection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Subsections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Physical address</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Public address</description>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for License Parcel Record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of parcel record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Universal_Default_Permit_Record_Type</fullName>
        <active>true</active>
        <description>This is the record type for any plan review/permits.</description>
        <label>Universal Default Permit Record Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a Permit</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits as Property</relationshipLabel>
        <relationshipName>Parcel_Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Permit2_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to check if address is physical address.</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Public address</description>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Permit Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddressValidatorTest.cls
@isTest
public class AddressValidatorTest {
    @testSetup
    static void createData(){
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('User_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecordTypeId);
        
        Id licRecordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(licRecordTypeId, acc.Id, 'Camping Resorts', 'Camping Resort Company', 'General Application');
        
        Id parRecordTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByDeveloperName().get('Address').getRecordTypeId();
        MUSW__Parcel__c parcel = DOL_TestDataFactory.createParcel(parRecordTypeId);
        
        MUSW__License_Parcel__c licParcel = DOL_TestDataFactory.createLicenseParcel(lic.Id, parcel.Id);
        MUSW__License_Parcel__c licParcel2 = DOL_TestDataFactory.createLicenseParcel(lic.Id, parcel.Id);
        
        Application_Subsection__c appSubSec = DOL_TestDataFactory.createApplicationSubSection('Camping Resorts', 'Camping Resort Company');
        
        Id permitRecordType = Schema.SObjectType.MUSW__Permit2__c.getRecordTypeInfosByDeveloperName().get('Universal_Default_Permit_Record_Type').getRecordTypeId();
        MUSW__Permit2__c permit = DOL_TestDataFactory.createPermit(permitRecordType);
        
        MUSW__Permit_Parcel__c permPar = DOL_TestDataFactory.createPermitParcel(permit.Id, parcel.Id);
        MUSW__Permit_Parcel__c permPar2 = DOL_TestDataFactory.createPermitParcel(permit.Id, parcel.Id);
        
    }
    
    @isTest
    static void validateAddressTest(){
        MUSW__License2__c lic = [SELECT Id FROM MUSW__License2__c LIMIT 1];
        String licId = String.valueOf(lic.Id);
        
        MUSW__Parcel__c parcel = [SELECT Id, Name, Status__c FROM MUSW__Parcel__c LIMIT 1];
        
        List<MUSW__License_Parcel__c> licParcel = [SELECT Id, Mailing__c, Physical__c, Public__c FROM MUSW__License_Parcel__c];
        
        Application_Subsection__c appSubSec = [SELECT Id, Name, License__c FROM Application_Subsection__c LIMIT 1];
        appSubSec.Name = 'Mailing Camping Resort Company';
        appSubSec.License__c = true;
        update appSubSec;
        
        ValidationError ve = new ValidationError();
        AddressValidator.validate(ve, 'Camping Resort Company', 'Camping Resort Company', 'License__c', licId);
        
        appSubSec.Name = 'Public Camping Resort Company';
        update appSubSec;
        AddressValidator.validate(ve, 'Camping Resort Company', 'Camping Resort Company', 'License__c', licId);
        
        appSubSec.Name = 'Physical Camping Resort Company';
        update appSubSec;
        AddressValidator.validate(ve, 'Camping Resort Company', 'Camping Resort Company', 'License__c', licId);
        
        licParcel[0].Mailing__c = true;
        licParcel[0].Physical__c = true;
        licParcel[0].Public__c = true;
        update licParcel[0];
        AddressValidator.validate(ve, 'Camping Resort Company', 'Camping Resort Company', 'License__c', licId);
        
        MUSW__Permit2__c permit = [SELECT Id FROM MUSW__Permit2__c LIMIT 1];
        
        List<MUSW__Permit_Parcel__c> permParcel = [SELECT Id, Mailing__c, Physical__c, Public__c FROM MUSW__Permit_Parcel__c];
        permParcel[1].Mailing__c = false;
        permParcel[1].Public__c = false;
        permParcel[1].Physical__c = false;
        update permParcel[1];
        
        AddressValidator.validate(ve, 'POWTS', 'Electrical', 'Permit__c', String.valueOf(permit.Id));
        
    }
}