src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change Name</fullName>
                </value>
                <value>
                    <fullName>Withdraw Application</fullName>
                </value>
                <value>
                    <fullName>Submit Additional Documentation</fullName>
                </value>
                <value>
                    <fullName>Change in Status</fullName>
                </value>
                <value>
                    <fullName>Exam Re-Application</fullName>
                </value>
                <value>
                    <fullName>Relinquish Delegated Agent Status</fullName>
                </value>
                <value>
                    <fullName>Manage Affiliations</fullName>
                </value>
                <value>
                    <fullName>Public Health Emergency Plan Review</fullName>
                </value>
                <value>
                    <fullName>Priority Plan Review</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Title Modification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated application record.</description>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BG_File_Location_Type__c</fullName>
        <label>BG File Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Bluebeam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Background_Question_Field_API_Name__c</fullName>
        <description>Field to store field API name for background question</description>
        <label>Background Question Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates submission list entries that are always required and will be defaulted to the Portal.</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object associated with submission list record</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Name</fullName>
                </value>
                <value>
                    <fullName>Withdraw Application</fullName>
                </value>
                <value>
                    <fullName>Submit Additional Documentation</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Title Modification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Submission list record show for</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_Portal_User__c</fullName>
        <description>Is this a portal user?</description>
        <formula>OR(ISPICKVAL(UserType, &apos;CspLitePortal&apos;), ISPICKVAL(UserType, &apos;PowerCustomerSuccess&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Portal User</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Object.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MUSW__License2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal_Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>MUSW__Application2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Musw__Permit2__c</fullName>
    </customValue>
    <description>List of objects</description>
    <masterLabel>Object</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/classes/ServiceRequestTriggerhandler.cls
/*************************************************************************************************************
** User Story: N/A
**************************************************************************************************************
** Class Name    : ServiceRequestTriggerhandler
** Description   : Consolidated Trigger Handler for ServiceRequest Object.
** Version       : 1.0
** Built By      : 
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
**  **********************************************************************************************************/

public class ServiceRequestTriggerhandler implements BGCM.ITriggerHandler {
    public static user u;

    public ServiceRequestTriggerhandler(){
        u = [Select Id, UserType, Is_Portal_User__c From User where Id = :UserInfo.getUserId()];
    }
    
    public void onBeforeDelete(){}
    public void onBeforeInsert(){
    	processPortalValidations();
    }
    public void onBeforeUndelete(){}
    public void onBeforeUpdate(){
        processPortalValidations();
        beforeMethod();
    }
    public void onAfterDelete(){}
    public void onAfterInsert(){
    	afterMethod();
    }
    public void onAfterUndelete(){}
    public void onAfterUpdate(){
    	afterMethod();
    }
    
    private void processPortalValidations(){
    	if (u.Is_Portal_User__c == true) {
            //This method is for base validation on service request details provided by the Applicant
            BaseValidator v = new BaseValidator();
            for( SObject sObj : Trigger.new ) {
                v.validateServiceRequest(BaseValidator.ApplicationObjectType.ServiceRequest,  sObj);
            }
        }
    }
    
    private void afterMethod(){
    	Map<Id, MUSW__Application2__c> srsInPendingStatusMap = new Map<Id, MUSW__Application2__c>();
        Set<String> srInPendingStatusSet = new Set<String>();
        String permitTypesList = '';
        
        //This Method is called when already an AccountContact Record exists on an Account and serviceRequest records get Created. This Record will be shared with the community Plus User
        ServiceRequestUsersharing controller = new ServiceRequestUsersharing();
        controller.ServiceRequest_RecordInsert(Trigger.New);
        
        //Share the Service Request records when the Delegated Admin is the applicant on the License  
        ServiceRequestCreatedByDelegate delegateController = new ServiceRequestCreatedByDelegate();
        delegateController.shareServiceRequestRecords(Trigger.New);
        
        System.debug('trigger size'+trigger.New.size());
        for(Integer i = 0; i < trigger.New.size(); i++) {
            System.debug('in for loop');
            MUSW__Application2__c srNew = (MUSW__Application2__c) trigger.New[i];
            //get the license id to update submission list             
            System.debug('license status '+ srNew.MUSW__Status__c);
            if(srNew.MUSW__Status__c == '' || srNew.MUSW__Status__c == 'Pending') {
                System.debug('license status is pending or blank');
                
				 //If the license is in pending status- add it to the map
				 
                srsInPendingStatusMap.put(srNew.Id, srNew);
                
                 /* If the license is in pending status- add the license type to the set to avoid 
				  * duplciation/repetition of the same license type */
                 
                //licenseTypesInPendingStatusSet.add(srNew.Credential_Type__c);
                
                if(srNew.Credential__c != null && srNew.Credential__c != ''){
                    srInPendingStatusSet.add(srNew.Credential__c);
                }else if(srNew.Permit_Type__c != null && srNew.Permit_Type__c != ''){
                    permitTypesList = permitTypesList + ',\'' + srNew.Permit_Type__c + '\'';
                }
            }
            
        }
        
        if(srsInPendingStatusMap.size() > 0) {
            System.debug('in if size > 0 ');
            //Creating a map of license type and corresponding submission list.
        
        permitTypesList = permitTypesList.removeStart(',');
        if(permitTypesList == '') permitTypesList = '\'dummy_value\'';
        Map<String, List<MUSW__Master_Submission_List__c>> srTypesSubmissionListMap = new Map<String, List<MUSW__Master_Submission_List__c>>();
        String query = 'SELECT Id, External_id__c, Name, Background_Question_Field_API_Name__c,' +
                                                  ' Description_Long__c, Application_Type__c, Credential_Type__c, Credential__c, Default__c, Show_For__c,' +
                                                  ' Submission_Type__c, Document_API_Name__c, Service_Request_Type__c, BG_File_Location_Type__c, Permit_Type__c' +
                                                  ' FROM MUSW__Master_Submission_List__c ' +
                                                  ' WHERE Active__c = TRUE ' +
                                                  ' AND Object__c = \'' + label.API_Service_Request + '\'' +
                                                  ' AND Show_For__c includes (\'Service Request\') ' +
                                                  ' AND (Credential__c IN :srInPendingStatusSet OR Permit_Type__c includes (' + permitTypesList + '))' +
                                                  ' LIMIT 5000';
            
        for(MUSW__Master_Submission_List__c masterSubmission: Database.query(query)) {
			System.debug('in second for loop ');     			                                                
            
            if(masterSubmission.Credential__c != null && masterSubmission.Credential__c != ''){
                List<MUSW__Master_Submission_List__c> tempSubmissionList = new List<MUSW__Master_Submission_List__c> ();
                /* if license type already exists in the map, then fetch the list of submission list
				* records associated with that license type*/
                if(srTypesSubmissionListMap.containsKey(masterSubmission.Credential__c)) {
                    tempSubmissionList = srTypesSubmissionListMap.get(masterSubmission.Credential__c);
                }
                /*1. adding submission list for the license type in a list                                                      
                * 2. If the above 'if condition' was executed, then the new submission list record would be added to the
                * existing list */
                tempSubmissionList.add(masterSubmission);
                //adding license type and corresponding list in a map
                srTypesSubmissionListMap.put(masterSubmission.Credential__c, tempSubmissionList);
            }else if(masterSubmission.Permit_Type__c != null && masterSubmission.Permit_Type__c != ''){
                List<MUSW__Master_Submission_List__c> tempSubmissionList = new List<MUSW__Master_Submission_List__c> ();
                /* if license type already exists in the map, then fetch the list of submission list
				* records associated with that license type*/
                if(srTypesSubmissionListMap.containsKey(masterSubmission.Permit_Type__c)) {
                    tempSubmissionList = srTypesSubmissionListMap.get(masterSubmission.Permit_Type__c);
                }
                /*1. adding submission list for the license type in a list                                                      
                * 2. If the above 'if condition' was executed, then the new submission list record would be added to the
                * existing list */
                tempSubmissionList.add(masterSubmission);
                //adding license type and corresponding list in a map
                srTypesSubmissionListMap.put(masterSubmission.Permit_Type__c, tempSubmissionList);
            }
        }

        Set<String> srFieldSet = Schema.SObjectType.MUSW__Application2__c.fields.getMap().keyset();

        List<MUSW__Submission__c> submissionUpsertList = new List<MUSW__Submission__c>();
        List<MUSW__Submission__c> submissionDeleteList = new List<MUSW__Submission__c>();
        // Querying existing submissions under license records and iterating over it to create new submissions
         
        for(MUSW__Application2__c serviceRequest:[Select id, MUSW__Type__c, (Select Id, Name, LicenseQuestionKey__c FROM MUSW__Submissions__r) FROM MUSW__Application2__c WHERE Id = :srsInPendingStatusMap.keyset()]){

            // Getting new license instance from Trigger.newMap
            
            MUSW__Application2__c newSR = srsInPendingStatusMap.get(serviceRequest.Id);

            //Creating a map of existing submission records
            
            Map<String,MUSW__Submission__c> keyToSubmissionMap = new Map<String, MUSW__Submission__c>();
            for(MUSW__Submission__c submission: serviceRequest.MUSW__Submissions__r) {
                if(submission.LicenseQuestionKey__c != null){
                    keyToSubmissionMap.put(submission.LicenseQuestionKey__c, submission);
                }
            }
            
            // Creating submissions based on License Type
            List<MUSW__Master_Submission_List__c> masterSubmissionList = null;
            if(newSR.Credential__c != null && newSR.Credential__c != ''){
            	masterSubmissionList = srTypesSubmissionListMap.get(newSR.Credential__c);
            }else if(newSR.Permit_Type__c != null && newSR.Permit_Type__c != ''){
                masterSubmissionList = srTypesSubmissionListMap.get(newSR.Permit_Type__c);
            }
            if(masterSubmissionList != null && masterSubmissionList.size() > 0) {
                for(MUSW__Master_Submission_List__c masterSubmission : masterSubmissionList) {
                	if(serviceRequest.MUSW__Type__c == masterSubmission.Service_Request_Type__c){
	                    String srSubmissionComboKey = String.valueOf(newSR.Id) + String.valueOf(masterSubmission.External_Id__c);
	                    // If question is background question type, submission is created based on answer
	                     
	                    if(masterSubmission.Background_Question_Field_API_Name__c != null && srFieldSet.contains(masterSubmission.Background_Question_Field_API_Name__c.toLowerCase())) {
	                        String questionAnswer;
	                        questionAnswer= (String)newSR.get(masterSubmission.Background_Question_Field_API_Name__c);
	                        
	                       // If answer is 'Yes' new submission is created
	                        
	                        if(questionAnswer!= null && questionAnswer.equalsIgnoreCase('Yes')) { 
	                            if(!keyToSubmissionMap.containsKey(srSubmissionComboKey)) {
	                                MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name = masterSubmission.Name, Description_Long__c = masterSubmission.Description_Long__c,
	                                                                                            LicenseQuestionKey__c = srSubmissionComboKey, MUSW__Application2__c = newSR.Id, Application_Type__c = masterSubmission.Application_Type__c,
	                                                                                            Type__c = (masterSubmission.Submission_Type__c == 'Hardcopy: To be Mailed' ? 'Hardcopy' : 'Softcopy'),
	                                                                                            Extid_from_Submission_List__c = masterSubmission.External_Id__c, Document_API_Name__c = masterSubmission.Document_API_Name__c,
	                                                                                            MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
	                                
	                                if(newSubmission.MUSW__BG_File_Location_Type__c == null || newSubmission.MUSW__BG_File_Location_Type__c == '') newSubmission.MUSW__BG_File_Location_Type__c = 'Salesforce';
	                                submissionUpsertList.add(newSubmission);
	                            }
	                        }else if((questionAnswer == null || questionAnswer.equalsIgnoreCase('No')) && keyToSubmissionMap.containsKey(srSubmissionComboKey)) {
	                           //If answer is 'No' and there is an existing submission, it is deleted
	                             
	                            MUSW__Submission__c oldSubmission = keyToSubmissionMap.get(srSubmissionComboKey);
	                            submissionDeleteList.add(oldSubmission);
	                        }
	                    }
	                    else if(masterSubmission.Default__c) {
	                        // If submisison list is not of question type, corresponding submission is created
	                        
	                        if(!keyToSubmissionMap.containsKey(srSubmissionComboKey)) {
	                            if(masterSubmission.Show_For__c != null && masterSubmission.Show_For__c.containsIgnoreCase('Service Request')) {
	                                MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name = masterSubmission.Name, Description_Long__c = masterSubmission.Description_Long__c,
	                                                                                        LicenseQuestionKey__c = srSubmissionComboKey, MUSW__Application2__c = newSR.Id, Application_Type__c = masterSubmission.Application_Type__c,
	                                                                                        Type__c = (masterSubmission.Submission_Type__c =='Hardcopy: To be Mailed' ? 'Hardcopy: To be Mailed' : 'Softcopy: To be Uploaded'),
	                                                                                        MUSW__Required__c = masterSubmission.Default__c, Extid_from_Submission_List__c = masterSubmission.External_Id__c,
	                                                                                        Document_API_Name__c = masterSubmission.Document_API_Name__c, MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
	                                
	                                if(newSubmission.MUSW__BG_File_Location_Type__c == null || newSubmission.MUSW__BG_File_Location_Type__c == '') newSubmission.MUSW__BG_File_Location_Type__c = 'Salesforce';
	                                submissionUpsertList.add(newSubmission);
	                            }
	                            
	                        }
	                    }
	                }
                }
            }
        }
            
            upsert submissionUpsertList LicenseQuestionKey__c;
            if(Schema.sObjectType.MUSW__Submission__c.isDeletable()) {
                delete submissionDeleteList;
            }
            
        }
    }
    
    public void beforeMethod(){
        
        // If Request for deletion is checked capture the Date which is used for reporting
        list<MUSW__Application2__c> triggerNew = trigger.new;
        for(MUSW__Application2__c SR : triggerNew){
            MUSW__Application2__c srOld = null;
            if(trigger.Old != null){
                srOld = (MUSW__Application2__c)trigger.OldMap.get(SR.Id);
            }
            
            if (srOld != null && srOld.MUSW__Status__c != SR.MUSW__Status__c && SR.MUSW__Status__c == label.ST_Generate_Fee) {
                SR.Attestation_Date__c   = system.today();
            }
        }
        Map<Id, Decimal> MapSRTotalFee = new Map<Id, Decimal>();
        if (trigger.isUpdate) {
            for (AggregateResult ar : [Select MUSW__Application2__c, SUM(MUSW__Amount__c) amt, SUM(MUSW__Amount_Waived__c) wamt From MUSW__Fee__c where MUSW__Application2__c IN :trigger.New group by MUSW__Application2__c]) {
                Decimal feeAmt = (Decimal) ar.get('amt');
                Decimal feeWaivedAmt = (Decimal) ar.get('wamt');
                if (feeAmt == null) feeAmt = 0;
                if (feeWaivedAmt == null) feeWaivedAmt = 0;
                MapSRTotalFee.put((Id) ar.get('MUSW__Application2__c'), feeAmt - feeWaivedAmt);
            }
            for(sObject sObj : trigger.New){
                MUSW__Application2__c sRequest = (MUSW__Application2__c) sObj;
                MUSW__Application2__c sRequestOld = null;
                if(trigger.Old != null){
                    sRequestOld = (MUSW__Application2__c)trigger.OldMap.get(sRequest.Id);
                }
                if(sRequest.MUSW__Total_Fees__c > 0 && sRequest.MUSW__Total_Balance__c == 0 && (sRequestOld == null || sRequestOld.MUSW__Total_Balance__c > 0)){
                    sRequest.MUSW__Status__c = 'Submitted';
                }
                
                Decimal feeAmt = MapSRTotalFee.get(sRequest.Id);
                if (sRequest.Id != null && feeAmt != null && sRequest.MUSW__Total_Fees__c != feeAmt) {
                    sRequest.MUSW__Total_Fees__c = feeAmt;
                    
                }
            } 
        }
    }
}