src/objects/Account.object
<CustomObject>
	<fields>
        <fullName>ThirdPary_Billing_Code__c</fullName>
        <label>ThirdPary Billing Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AMR_Link__mdt.object
<CustomObject>
    <fields>
        <fullName>AMR_Type__c</fullName>
        <label>AMR Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self Service</fullName>
                    <default>true</default>
                    <label>Self Service</label>
                </value>
                <value>
                    <fullName>AMR</fullName>
                    <label>AMR Review</label>
                </value>
                <value>
                    <fullName>AMR Auto Approve</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Method__c</fullName>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Application</fullName>
                    <default>true</default>
                    <label>General Application</label>
                </value>
                <value>
                    <fullName>Comity</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notary Public</fullName>
                    <default>true</default>
                    <label>Notary Public</label>
                </value>
                <value>
                    <fullName>Geologist</fullName>
                </value>
                <value>
                    <fullName>Timeshares</fullName>
                </value>
                <value>
                    <fullName>Architects</fullName>
                </value>
                <value>
                    <fullName>Appraisers - Real Estate</fullName>
                </value>
                <value>
                    <fullName>Camping Resorts</fullName>
                </value>
                <value>
                    <fullName>Funerals</fullName>
                </value>
                <value>
                    <fullName>Engineers</fullName>
                </value>
                <value>
                    <fullName>Appraisal Management Companies</fullName>
                </value>
                <value>
                    <fullName>On-site Wastewater</fullName>
                </value>
                <value>
                    <fullName>Landscape Architects</fullName>
                </value>
                <value>
                    <fullName>Cemeteries</fullName>
                </value>
                <value>
                    <fullName>Land Surveyors</fullName>
                </value>
                <value>
                    <fullName>Delegated Municipality</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes</fullName>
                </value>
                <value>
                    <fullName>Program Unknown</fullName>
                </value>
                <value>
                    <fullName>Misc Payments</fullName>
                </value>
                <value>
                    <fullName>Appraiser Course</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Generate_Fee__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Generate Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notary Public</fullName>
                    <default>true</default>
                    <label>Notary Public</label>
                </value>
                <value>
                    <fullName>Geologist</fullName>
                </value>
                <value>
                    <fullName>Geologist In Training</fullName>
                </value>
                <value>
                    <fullName>Camping Resort Salesperson</fullName>
                </value>
                <value>
                    <fullName>Registered Appraiser Trainee</fullName>
                </value>
                <value>
                    <fullName>Appraiser Trainee</fullName>
                </value>
                <value>
                    <fullName>Timeshare Salesperson</fullName>
                </value>
                <value>
                    <fullName>Timeshare Company</fullName>
                </value>
                <value>
                    <fullName>Architect</fullName>
                </value>
                <value>
                    <fullName>Camping Resort Company</fullName>
                </value>
                <value>
                    <fullName>Appraiser Course</fullName>
                </value>
                <value>
                    <fullName>Certified General Appraiser</fullName>
                </value>
                <value>
                    <fullName>Certificate of Removal Registration</fullName>
                </value>
                <value>
                    <fullName>Academic Intern</fullName>
                </value>
                <value>
                    <fullName>Temporary Certified General</fullName>
                </value>
                <value>
                    <fullName>Engineer in Training</fullName>
                </value>
                <value>
                    <fullName>Professional Engineer</fullName>
                </value>
                <value>
                    <fullName>State Licensed Appraiser</fullName>
                </value>
                <value>
                    <fullName>Appraisal Management Company</fullName>
                </value>
                <value>
                    <fullName>Appraisal Controlling Person</fullName>
                </value>
                <value>
                    <fullName>On-site Wastewater Designer</fullName>
                </value>
                <value>
                    <fullName>On-site Wastewater Inspector</fullName>
                </value>
                <value>
                    <fullName>Certified Residential Appraiser</fullName>
                </value>
                <value>
                    <fullName>Landscape Architect</fullName>
                </value>
                <value>
                    <fullName>Funeral Director Intern</fullName>
                </value>
                <value>
                    <fullName>Funeral Establishment</fullName>
                </value>
                <value>
                    <fullName>Embalmer Intern</fullName>
                </value>
                <value>
                    <fullName>Crematory</fullName>
                </value>
                <value>
                    <fullName>Cremated Remains Disposition Permit</fullName>
                </value>
                <value>
                    <fullName>Prearrangement Funeral Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sections__c</fullName>
        <label>Sections</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AMR Link</label>
    <pluralLabel>AMR Links</pluralLabel>
</CustomObject>

src/objects/Branch_License__mdt.object
<CustomObject>
    <fields>
        <fullName>Branch_License__c</fullName>
        <label>Branch License</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Main_License__c</fullName>
        <label>Main License</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Branch License</label>
    <pluralLabel>Branch Licenses</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>License Website</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who is making the request.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Profession__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/classes/Polaris_AMRLinkCntrl.cls
public class Polaris_AMRLinkCntrl {
    
    @AuraEnabled
    Public static List<AMR_Link__mdt> fetchServiceLinksServer(String board, String licenseType, String applicationMethod)
    {       
        return [SELECT id,MasterLabel,AMR_Type__c,Order_Number__c,Board__c,Service_Request_Type__c,License_Type__c,Application_Method__c FROM AMR_Link__mdt where Board__c =:board AND License_Type__c =:licenseType AND Application_Method__c=:applicationMethod ORDER BY Order_Number__c ASC  ];
    }
    @AuraEnabled
    public static String fetchAppId(String licId)
    {
        String appId = '';
        system.debug('licId : '+licId);
        if(licId!=null){
            MUSW__License2__c lic = [SELECT id,Application__c FROM MUSW__License2__c where id=:licId ];
            appId = lic.Application__c;
        }
        return appId;
    }
    
    //getMetada values in manage request
    @AuraEnabled
    public static AMR_Link__mdt getMetadata(String board,String ServiceRequestType,String licenseType){
      
      List<AMR_Link__mdt> listMdt = [ SELECT Sections__c,Generate_Fee__c FROM AMR_Link__mdt WHERE Board__c =:board AND License_Type__c =:licenseType AND Service_Request_Type__c =:ServiceRequestType];
      
      if(!listMdt.isEmpty()){
          return   listMdt[0];
      }else{
          return null;
      }
      
    }
    
    
    @AuraEnabled
    public static String fetchWebsiteInfo(String licId)
    {
        String websiteInfo = '';
        system.debug('licId : '+licId);
        if(licId!=null){
            MUSW__License2__c lic = [SELECT id,Website__c FROM MUSW__License2__c where id=:licId ];
            websiteInfo = lic.Website__c;
        }
        return websiteInfo;
    }
	
	@AuraEnabled
    public static Account fetchAccountInfo(String licId)
    {
        Account acct = null;
        list<Account> acctlist = [select id,name,ThirdPary_Billing_Code__c from account where id=:licId];
        system.debug('acctlist==='+acctlist);
        if(!acctlist.isEmpty())
        {
            acct = acctlist[0];
        }
        return acct;
    }
	
    @AuraEnabled
    public static void updateWebsiteInfo(String licId,String websiteInfo)
    {   
        system.debug('websiteInfo==='+ websiteInfo+'==licId=='+licId);
        if(String.isNotBlank(websiteInfo) && websiteInfo == 'createCode' && String.isNotBlank(licId)){
        String value = 'success';
        /*List<User> userInfoData = new  List<User>();
        String queryCondition = ' Id=\''+UserInfo.getUserId()+'\'';
        System.debug('User Id ' + queryCondition);
        String queryStr = 'SELECT Username, ContactId, Contact.Name, Contact.AccountId, Contact.Account.Name FROM User WHERE  '+queryCondition + 'Limit 1';
        system.debug('queryStr '+queryStr);
        userInfoData = Utilityclass_withsharing.queryRecords(queryStr);
        //system.debug('userInfoData==='+userInfoData);
        string AccountId= userInfoData[0].Contact.AccountId;
        //string AccountId= userInfoData[0].AccountId;*/
        list<account> acctlist = [select id,name,ThirdPary_Billing_Code__c from account where id=:licId];
        system.debug('acctlist==='+acctlist);
        if(!acctlist.isEmpty())
        {
            string randomcharacter= Polaris_AMRLinkCntrl.generateRandomString(6);  
            system.debug('randomcharacter==='+randomcharacter);
            Account  accts= new Account();
            accts.id=acctlist[0].id;
            //accts.id=AccountId;
            accts.ThirdPary_Billing_Code__c=randomcharacter;
            system.debug('accts==='+accts);
            upsert  accts;
            }
        //return value;===============================
        }else{
            system.debug('dferfer'+ websiteInfo);
            MUSW__License2__c lic = [SELECT id,Website__c FROM MUSW__License2__c where id=:licId ];
            lic.Website__c =  websiteInfo;
            update lic;
        }
    }
    @AuraEnabled
    public static String insertRequest(String licId,String licenseType, String board,String ServiceRequestType)
    {
        List<User> userInfoData = new  List<User>();
        String queryCondition = ' Id=\''+UserInfo.getUserId()+'\'';
        System.debug('User Id ' + queryCondition);
        String queryStr = 'SELECT Username, ContactId, Contact.Name, Contact.AccountId, Contact.Account.Name FROM User WHERE  '+queryCondition + 'Limit 1';
        system.debug('queryStr '+queryStr);
        
        userInfoData = Utilityclass_withsharing.queryRecords(queryStr);
        Id getContactId = '003r000000EOhBB';
        if(userInfoData[0].ContactId != null){
            getContactId = userInfoData[0].ContactId;
        }
        system.debug('licenseType'+licenseType+'board');
        Request__c application = new Request__c();
        application.Profession__c = board; 
        application.License_Type__c = licenseType;        
        application.Stage__c = 0;
        application.Service_Request_Type__c = ServiceRequestType;
        application.Contact__c = getContactId;
        if(licId != null && licId != ''){
            application.License__c = licId;  
        }  
        try
        {          
            insert application;
        }
        catch(Exception e){
            HandleException.LogException(e,'Polaris_AMRLinkCntrl','insertRequest');            
        }
        string appId = '';
        return appId = application.Id;
        
    }
    
    @AuraEnabled 
    public static List<selectListWrapper> getPickListData(String mainLicense){
    List<String> str = new List<String>();
    List<selectListWrapper> listWrapper = new List<selectListWrapper>();
    List<Branch_License__mdt> brachList = [select id,MasterLabel,Branch_License__c,Main_License__c from Branch_License__mdt where Main_License__c =:mainLicense];
        if(!brachList.isEmpty()){
            str = brachList[0].Branch_License__c.split(',');
        }
      for(String s : str){
           selectListWrapper slw = new selectListWrapper();
           slw.label = s;
           slw.value = s;
           slw.selected = true;
           listWrapper.add(slw);
      }
      return listWrapper;
    }
	@AuraEnabled 
    public static String createCodeValue(String test)
    {            
       system.debug('createcode===');
        String value = 'success';
        List<User> userInfoData = new  List<User>();
        String queryCondition = ' Id=\''+UserInfo.getUserId()+'\'';
        System.debug('User Id ' + queryCondition);
        String queryStr = 'SELECT Username, ContactId, Contact.Name, Contact.AccountId, Contact.Account.Name FROM User WHERE  '+queryCondition + 'Limit 1';
        system.debug('queryStr '+queryStr);
        
        userInfoData = Utilityclass_withsharing.queryRecords(queryStr);
        system.debug('userInfoData==='+userInfoData);
        string AccountId= userInfoData[0].Contact.AccountId;
        list<account> acctlist = [select id,name,ThirdPary_Billing_Code__c from account where id=:AccountId];
        system.debug('acctlist==='+acctlist);
        if(!acctlist.isEmpty())
        {
            string randomcharacter= Polaris_AMRLinkCntrl.generateRandomString(5);  
            Account  accts= new Account();
            accts.id=acctlist[0].id;
            accts.ThirdPary_Billing_Code__c=randomcharacter;
            system.debug('accts==='+accts);
            upsert  accts;
            }
        return value;
    }

    
    public static String generateRandomString(Integer len) {
    final String chars = '0123456789';
    String randStr = '';
    while (randStr.length() < len) {
       Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
       randStr += chars.substring(idx, idx+1);
    }
    return randStr; 
}

    
    //method to create application.
    @AuraEnabled
    public static Id createApplication(String board, String licenseType, String applicationType,String account,String LicenseUpgradeRecordID){
    
    Id applicationId = LnP_WizardApexController.startAnApplication(board,licenseType,applicationType,account,LicenseUpgradeRecordID);
    
    return applicationId;
    }
    
    public class selectListWrapper{
        @AuraEnabled public string label;
        @AuraEnabled public string value;
        @AuraEnabled public boolean selected;
    }
    
    
    
}