src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BGBK__Cart__c.object
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Cart</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BGBK__Payment_Batch__c.object
<CustomObject>
    <description>A payment batch groups associated payments. For example, payments entered by an operator on a particular date.</description>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Register</label>
        <referenceTo>Cash_Register__c</referenceTo>
        <relationshipLabel>Payment Batches</relationshipLabel>
        <relationshipName>Payment_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Batch</label>
    <nameField>
        <label>Payment Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cash_Register__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <label>Cash Register</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Back-Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cash Register</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cash Register Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether to disable triggers for a profile/user- specially useful during data loads</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Agency_Code__c</fullName>
        <label>Agency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated license record.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <description>Deprecated. Used for the simple implementation of historical data.</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee_Payment__c.object
<CustomObject>
    <description>Allocated Receipt amounts paying Fees</description>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cart used to make this fee payment</description>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Fee Payments</relationshipLabel>
        <relationshipName>Fee_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated fee record. The System populates this during payment processing.</description>
        <label>Fee</label>
        <referenceTo>MUSW__Fee__c</referenceTo>
        <relationshipLabel>Applied Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Amount__c</fullName>
        <description>The payment amount applied to the fee. The System populates this during payment processing.</description>
        <label>Payment Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Receipt__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated receipt record. The System populates this during payment processing.</description>
        <label>Receipt</label>
        <referenceTo>MUSW__Receipt__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee Payment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MUSW__Fee_Payment__c.object
    <fields>
        <fullName>Agency_Code__c</fullName>
        <formula>TEXT(MUSW__Receipt__r.Agency_Code__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Code</label>
        <type>Text</type>
    </fields>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Licensee Email</description>
        <formula>MUSW__Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Licensee Email</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>Agency_Code__c</fullName>
        <description>1966</description>
        <label>Agency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DHP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US-1656</description>
        <label>DHP?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intake_Method__c</fullName>
        <label>Intake Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                </value>
                <value>
                    <fullName>Validation Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Card_Type__c</fullName>
        <description>Deprecated.</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Agency_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>3000</fullName>
    </customValue>
    <customValue>
        <fullName>5400</fullName>
    </customValue>
    <description>1966 : Global value set for agency code</description>
    <masterLabel>Agency Code</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/ReceiptTriggerHandlerTest.cls
@isTest
public class ReceiptTriggerHandlerTest {
     @testsetup
    static void setup(){
     BGBK__Payment_Batch__c objPaymentBatch = new BGBK__Payment_Batch__c();
        objPaymentBatch.Name ='test';
        insert objPaymentBatch;
        BGBK__Cart__c objCart= DOL_TestDataFactory.createCartRecord(objPaymentBatch.Id);
         MUSW__Receipt__c receiptRecord = new MUSW__Receipt__c(MUSW__Payment_Method__c = 'Credit Card'  ,MUSW__Amount_Tendered__c =1000.00,Intake_Method__c='counter');
       
            //DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord.MUSW__Payment_Method__c = 'CC';
        receiptRecord.MUSW__Card_Type__c = 'MC';
        receiptRecord.BGBK__Cart__c =objCart.Id;
        insert receiptRecord;
        
         Id businessAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc= DOL_TestDataFactory.createAccount(businessAccount);
        acc.Email__c = 'test@mailinator.com';
        update acc;
        
        Id businessLicenseType = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(businessLicenseType, acc.Id, 'Architects', 'Architect', 'General Application');
        
        MUSW__Fee__c objFee = DOL_TestDataFactory.createFeeWithLicense('General',100.00,lic.id);
           
        
        MUSW__Fee_Payment__c objFeePayment = new MUSW__Fee_Payment__c(  MUSW__Payment_Amount__c =100.00);
        objFeePayment.MUSW__Receipt__c=receiptRecord.Id;    
        objFeePayment.MUSW__Fee__c=objFee.id;
        insert objFeePayment;
        

    }
    public static testmethod void testRecieptMethod(){
        Test.startTest();
         Id cashRegRecTypeId = Schema.SObjectType.Cash_Register__c.getRecordTypeInfosByName().get('Cash Register').getRecordTypeId();
        // Insert cashRegister
        Cash_Register__c cashRegisterRecord = DOL_TestDataFactory.createValidationRoomCashRegister(cashRegRecTypeId,100.0,200.0,300.0,400.0);
        
        BGBK__Payment_Batch__c pb = DOL_TestDataFactory.createPaymentBatch(cashRegisterRecord.Id);
        
        BGBK__Cart__c cartRecord = DOL_TestDataFactory.createCartRecord(pb.Id);
        
        MUSW__Receipt__c receiptRecord = DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord.BGBK__Cart__c= cartRecord.id;
        update receiptRecord;
        System.assertEquals(receiptRecord.BGBK__Cart__c!=null, true);
        
        ReceiptTriggerHandler rec = new ReceiptTriggerHandler();
        rec.onBeforeDelete();
        rec.onBeforeUndelete();
        Test.stopTest();
        
    }
    
    public static testmethod void handleDeleteScenario(){
        Test.startTest();
        
        Id businessAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc= DOL_TestDataFactory.createAccount(businessAccount);
        acc.Email__c = 'test@mailinator.com';
        update acc;
        
        Id businessLicenseType = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        //MUSW__License2__c lic = DOL_TestDataFactory.createLicense(businessLicenseType, acc.Id, 'Architects', 'Architect', 'General Application');
        
        BGBK__Payment_Batch__c objPaymentBatch = new BGBK__Payment_Batch__c();
        objPaymentBatch.Name ='test';
        insert objPaymentBatch;
        BGBK__Cart__c objCart= DOL_TestDataFactory.createCartRecord(objPaymentBatch.Id);
        
        
        MUSW__Receipt__c receiptRecord = new MUSW__Receipt__c(MUSW__Payment_Method__c = 'Credit Card'  ,MUSW__Amount_Tendered__c =1000.00,Intake_Method__c='counter');
       
            //DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord.MUSW__Payment_Method__c = 'CC';
        receiptRecord.MUSW__Card_Type__c = 'MC';
        receiptRecord.BGBK__Cart__c =objCart.Id;
        //insert receiptRecord;
        MUSW__Receipt__c receiptRecordtoUpdate  =[select id,MUSW__Payment_Method__c,MUSW__Card_Type__c,BGBK__Cart__c,MUSW__Amount_Tendered__c,Intake_Method__c from MUSW__Receipt__c limit 1]; 
        receiptRecordtoUpdate.BGBK__Cart__c =objCart.Id;
        receiptRecordtoUpdate.DHP__c = true;
        receiptRecordtoUpdate.Agency_Code__c ='3000';
            update receiptRecordtoUpdate;
        //delete receiptRecord;
        
        
        MUSW__Receipt__c receiptRecord1 = DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord1.MUSW__Payment_Method__c = 'CC';
        receiptRecord1.MUSW__Card_Type__c ='VISA';
        receiptRecord.BGBK__Cart__c =objCart.Id;
        receiptRecord1.DHP__c = true;
        insert receiptRecord;
        update receiptRecord1;
        delete receiptRecord;
        undelete receiptRecord;
        
        MUSW__Receipt__c receiptRecord2 = DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord2.MUSW__Payment_Method__c = 'CC';
        receiptRecord2.MUSW__Card_Type__c ='AMEX';
        receiptRecord2.DHP__c = true;
        receiptRecord2.Agency_Code__c ='3000';
        update receiptRecord2;
        
       // MUSW__Fee__c objFee = DOL_TestDataFactory.createFeeWithLicense('General',100.00,lic.id);
        
       // MUSW__Fee_Payment__c feePayment = new MUSW__Fee_Payment__c(MUSW__Payment_Amount__c=100.0,DHP_Amount__c=100.0,MUSW__Receipt__c=receiptRecord2.id,MUSW__Fee__c=objFee.id);
        //insert  feePayment;  
        //ReceiptTriggerHandler rd = new ReceiptTriggerHandler();
        //RunTriggerDispatcher.Run(rd);
        Test.stopTest();
    }
    
    public static testmethod void insertCustomSetting(){
        Global_Settings__c setting = new Global_Settings__c(SetupOwnerId=UserInfo.getUserId(),Disable_Triggers__c=true);
        upsert setting;
        

    }
    public static testmethod  void testmethod3(){
        MUSW__Receipt__c receiptRecordtoUpdate  =[select id,MUSW__Payment_Method__c,MUSW__Card_Type__c,BGBK__Cart__c,MUSW__Amount_Tendered__c,Intake_Method__c from MUSW__Receipt__c limit 1]; 
        //receiptRecordtoUpdate.BGBK__Cart__c =objCart.Id;
        receiptRecordtoUpdate.DHP__c = true;
        receiptRecordtoUpdate.Agency_Code__c ='3000';
        receiptRecordtoUpdate.MUSW__Payment_Method__c ='Check/Cashier\'s Check';
            update receiptRecordtoUpdate;
    }
    public static testmethod  void testmethod4(){
        MUSW__Receipt__c receiptRecordtoUpdate  =[select id,MUSW__Payment_Method__c,MUSW__Card_Type__c,BGBK__Cart__c,MUSW__Amount_Tendered__c,Intake_Method__c from MUSW__Receipt__c limit 1]; 
        //receiptRecordtoUpdate.BGBK__Cart__c =objCart.Id;
        receiptRecordtoUpdate.DHP__c = true;
        receiptRecordtoUpdate.Agency_Code__c ='3000';
        receiptRecordtoUpdate.MUSW__Payment_Method__c ='Cash';
            update receiptRecordtoUpdate;
    }
     public static testmethod  void testmethod6(){
         MUSW__Receipt__c receiptRecord = new MUSW__Receipt__c(MUSW__Payment_Method__c = 'Credit Card'  ,MUSW__Amount_Tendered__c =1000.00,Intake_Method__c='counter');
       
            //DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord.MUSW__Payment_Method__c = 'CC';
        receiptRecord.MUSW__Card_Type__c = 'AMEX';
        //receiptRecord.BGBK__Cart__c =objCart.Id;
        insert receiptRecord;
    }
    public static testmethod  void testmethod5(){
         MUSW__Receipt__c receiptRecord = new MUSW__Receipt__c(MUSW__Payment_Method__c = 'Credit Card'  ,MUSW__Amount_Tendered__c =1000.00,Intake_Method__c='counter');
       
            //DOL_TestDataFactory.createReceipt('Credit Card',1000,'Counter');
        receiptRecord.MUSW__Payment_Method__c = 'CC';
        receiptRecord.MUSW__Card_Type__c = 'VISA';
        //receiptRecord.BGBK__Cart__c =objCart.Id;
        insert receiptRecord;
    }
        
}