src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether to disable triggers for a profile/user- specially useful during data loads</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_License__c</fullName>
        <description>Business License</description>
        <formula>OR(ISPICKVAL( Credential__c , &apos;Dwelling Contractor&apos;), 
ISPICKVAL( Credential__c , &apos;Dwelling Contractor Restricted&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Manufacturer&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Dealer&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Boiler&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Commercial Building&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Elevator&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Fire Suppression/Alarm Systems&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Other&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Plumbing&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - POWTS&apos;),
ISPICKVAL(Credential__c , &apos;Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;UDC Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment&apos;),
ISPICKVAL(Credential__c , &apos;Prearrangement Funeral Services&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment Branch&apos;),
ISPICKVAL(Credential__c , &apos;Certificate of Removal Registration&apos;),
ISPICKVAL(Credential__c , &apos;Crematory&apos;),
ISPICKVAL(Credential__c , &apos;Cremated Remains Disposition Permit&apos;),
ISPICKVAL(Credential__c , &apos;Cemetery&apos;),
ISPICKVAL(Credential__c , &apos;Camping Resort Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Course&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Provider&apos;),
ISPICKVAL(Credential__c , &apos;Timeshare Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraisal Management Company&apos;)


)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Primary descriptor of the License.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Liquor</fullName>
                </value>
                <value>
                    <fullName>Animal</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Permit_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_License__c</fullName>
        <formula>OR(ISPICKVAL( Permit_Type__c , &apos;Manufactured Homes Community Permit&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>The permit type. This is typically related to the record type.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Building</fullName>
                    <default>true</default>
                    <label>Building</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Plumbing</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Newsfeed__c.object
<CustomObject>
    <description>The object for news feed items.</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Record Identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Instructions__c</fullName>
        <description>User Instructions for Pages</description>
        <label>Instructions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Describes where the language should show based on the business/application process.</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_License__c</fullName>
        <description>Is this a business license</description>
        <formula>OR(License__r.Business_License__c,
Permit__r.Business_License__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the renewal.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/classes/ApplicationForSObjectConfigTest.cls
@isTest
public class ApplicationForSObjectConfigTest {
    
    @testSetup
    static void setupTestData(){
        Global_Settings__c gs= new Global_Settings__c(SetupOwnerId=UserInfo.getUserId(), Disable_Triggers__c=true);
         insert gs;

        Account citizenAccount = CreateTestDataUtility.createCitizenAccount();
        insert citizenAccount;
        Account account = CreateTestDataUtility.createAccount();
        account.Name = 'Test Account';
        insert account;
       
        Contact contact = CreateTestDataUtility.createContact(account.Id);
        contact.FirstName = 'Test Contact';
        insert contact;
        
        MUSW__License2__c testLicense = CreateTestDataUtility.createLicense( account.id,contact.Id); //License
        insert testLicense;
        
        MUSW__Permit2__c testPermit = CreateTestDataUtility.createPermit( account.id,contact.Id);
        insert testPermit;
        delete gs;
        
    }
    
    @isTest
    static void testfactoryMethod(){
        Test.startTest();
        ApplicationForSObjectConfig.factoryMethod(Label.str_PLAN_REVIEW);
        ApplicationForSObjectConfig.factoryMethod(label.RNT_Renewal);
        ApplicationForSObjectConfig.factoryMethod(label.Str_ManufacturedHomesRenewal);
        ApplicationForSObjectConfig.factoryMethod(label.RNT_Reinstatement);
        ApplicationForSObjectConfig.factoryMethod(label.STR_Service_Request);
        ApplicationForSObjectConfig.factoryMethod(Label.Str_Trades_Credential);
        ApplicationForSObjectConfig.factoryMethod('TestNull');
        Test.stopTest();
    }
    
    @isTest
    static void testLicenseConfigMethods(){
        Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
        MUSW__License2__c testLicense = [Select Id, Application_type__c, credential__c,credential_type__C,application_method__C, MUSW__Type__c, MUSW__Primary_Licensee__c, Business_License__c 
                                         from MUSW__License2__c 
                                         limit 1];
        
        ApplicationForSObjectConfig.LicenseConfig obj = new ApplicationForSObjectConfig.LicenseConfig();
        obj.getContactRelationship();
        obj.createInstance();
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        
        Newsfeed__c news = new Newsfeed__c ();
        news.Credential_Type__c =testLicense.Credential_Type__c;
        news.Credential__c=testLicense.Credential__c;
        news.Application_Type__c=testLicense.Application_Type__c;
        news.Application_Method__c=testLicense.Application_Method__c;
        news.Instructions__c = 'Test Instructions';
        news.RecordTypeId = [select id from RecordType where name = 'Attestation Line' ].id;
        news.Show_For__c = 'Credential';
        news.External_Id__c='abec';
        insert news;
       
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
        ApexPages.currentPage().getParameters().put('applicationType', testlicense.Application_Type__c);
        ApexPages.currentPage().getParameters().put('credential', testlicense.Credential__c);
        ApexPages.currentPage().getParameters().put('credentialType', testlicense.Credential_Type__c);
        ApexPages.currentPage().getParameters().put('accountId', acct.id);
        ApexPages.currentPage().getParameters().put('contactId', contact.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        
        ctrl.existingRecId = testLicense.id;
        ctrl.licenseBy = testlicense.Application_Method__c;

        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
        obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        Newsfeed__c link = new Newsfeed__c ();
        link.Credential_Type__c =testLicense.Credential_Type__c;
        link.Credential__c=testLicense.Credential__c;
        link.Application_Type__c=testLicense.Application_Type__c;
        link.External_Id__c='absec';
        link.Application_Method__c=testLicense.Application_Method__c;
        link.RecordTypeId = [select id from RecordType where name = 'Affidavit Link'].id;
        link.Show_For__c = 'Credential';
        insert link;
        
        obj.getAffidavitLink(ctrl);
        Test.stopTest();
    }
    
    

    @isTest
    static void testLicenseRenewalConfigMethods(){
        /*
        Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
       MUSW__License2__c testLicense = [Select Id, Application_type__c, credential__c,credential_type__C,application_method__C, MUSW__Type__c, MUSW__Primary_Licensee__c, Business_License__c 
                                         from MUSW__License2__c 
                                         limit 1];
        
        Renewal_Application__c renewal = new Renewal_Application__c();
        renewal.Credential_Type__c=testlicense.Credential_Type__c;
        renewal.Credential__c=testlicense.Credential__c;
        renewal.Applicant__c = contact.id;    
        renewal.Licensee__c = acct.id;
        renewal.License__c=testlicense.Id;
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_Renewal;
        insert renewal;
        
        ApplicationForSObjectConfig.RenewalConfig obj = new ApplicationForSObjectConfig.RenewalConfig();
        obj.getContactRelationship();
        obj.createInstance();
        
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        Newsfeed__c news = new Newsfeed__c ();
        news.Credential_Type__c =testLicense.Credential_Type__c;
        news.Credential__c=testLicense.Credential__c;
        news.Application_Type__c=testLicense.Application_Type__c;
        news.Application_Method__c=testLicense.Application_Method__c;
        news.Instructions__c = 'Test Instrsdsductions';
        news.RecordTypeId = [select id from RecordType where name =:label.RT_Attestation_Line ].id;
        news.Show_For__c = label.Str_Credential_Renewal;
        news.External_Id__c='asasas';
        insert news;
        System.debug('anew '+news);
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
        ApexPages.currentPage().getParameters().put('applicationType','Renewal');
           ApexPages.currentPage().getParameters().put('applicationMethod',testlicense.Application_Method__c);
       ApexPages.currentPage().getParameters().put('credentialType', testlicense.Credential_Type__c);
        ApexPages.currentPage().getParameters().put('renewalOrReinstatement', 'Renewal');
        ApexPages.currentPage().getParameters().put('credential', testlicense.Credential__c);
        ApexPages.currentPage().getParameters().put('accountId', acct.id);
        ApexPages.currentPage().getParameters().put('parentId', testLicense.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        ctrl.parentId = testLicense.id;
        System.debug('ctrl.lic '+ctrl.lic);
        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
        obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        Newsfeed__c link = new Newsfeed__c ();
        link.Credential_Type__c =testLicense.Credential_Type__c;
        link.Credential__c=testLicense.Credential__c;
        link.Application_Type__c=testLicense.Application_Type__c;
        link.External_Id__c='absec';
        link.Application_Method__c=testLicense.Application_Method__c;
        link.RecordTypeId = [select id from RecordType where name =:label.RT_Affidavit_Link].id;
        link.Show_For__c = Label.Str_Credential_Renewal;
        link.External_Id__c='asasass';
        link.Link__c='www.google.com';
        insert link;
        
      //  obj.getAffidavitLink(ctrl);
        
        //ctrl.parentId = renewal.id;
        obj.setFieldValues(ctrl);
        Test.stopTest();*/
    }
    
    
     @isTest
    static void testReinstatementConfigMethods(){
        /*
       Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
       MUSW__License2__c testLicense = [Select Id, Application_type__c, credential__c,credential_type__C,application_method__C, MUSW__Type__c, MUSW__Primary_Licensee__c, Business_License__c 
                                         from MUSW__License2__c 
                                         limit 1];
        
        Renewal_Application__c renewal = new Renewal_Application__c();
        renewal.Credential_Type__c=testlicense.Credential_Type__c;
        renewal.Credential__c=testlicense.Credential__c;
        renewal.Applicant__c = contact.id;    
        renewal.Licensee__c = acct.id;
        renewal.License__c=testlicense.Id;
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_Reinstatement;
        insert renewal;
        
        ApplicationForSObjectConfig.ReinstatementConfig obj = new ApplicationForSObjectConfig.ReinstatementConfig();
        obj.getContactRelationship();
        obj.createInstance();
        
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        Newsfeed__c news = new Newsfeed__c ();
        news.Credential_Type__c =testLicense.Credential_Type__c;
        news.Credential__c=testLicense.Credential__c;
        news.Application_Type__c=testLicense.Application_Type__c;
        news.Application_Method__c=testLicense.Application_Method__c;
        news.Instructions__c = 'Test Instrsdsductions';
        news.RecordTypeId = [select id from RecordType where name =:label.RT_Attestation_Line ].id;
        news.Show_For__c = label.Str_Credential_Reinstatement;
        news.External_Id__c='asasas';
        insert news;
        System.debug('anew '+news);
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
        ApexPages.currentPage().getParameters().put('applicationType','Renewal');
           ApexPages.currentPage().getParameters().put('applicationMethod',testlicense.Application_Method__c);
       ApexPages.currentPage().getParameters().put('credentialType', testlicense.Credential_Type__c);
        ApexPages.currentPage().getParameters().put('renewalOrReinstatement', 'Reinstatement');
        ApexPages.currentPage().getParameters().put('credential', testlicense.Credential__c);
        ApexPages.currentPage().getParameters().put('accountId', acct.id);
        ApexPages.currentPage().getParameters().put('parentId', testLicense.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        ctrl.parentId = testLicense.id;
        System.debug('ctrl.lic '+ctrl.lic);
        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
        obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        Newsfeed__c link = new Newsfeed__c ();
        link.Credential_Type__c =testLicense.Credential_Type__c;
        link.Credential__c=testLicense.Credential__c;
        link.Application_Type__c=testLicense.Application_Type__c;
        link.External_Id__c='absec';
        link.Application_Method__c=testLicense.Application_Method__c;
        link.RecordTypeId = [select id from RecordType where name =:label.RT_Affidavit_Link].id;
        link.Show_For__c = Label.Str_Credential_Reinstatement;
        link.External_Id__c='asasass';
        link.Link__c='www.google.com';
        insert link;
        
      //  obj.getAffidavitLink(ctrl);
        
        //ctrl.parentId = renewal.id;
        obj.setFieldValues(ctrl);
        Test.stopTest();
        */
    }
    
     @isTest
    static void testPermtiConfigMethods(){
        Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
        MUSW__Permit2__c testLicense = [Select Id, Application_type__c, permit_type__c,program_area__C,application_method__C, MUSW__Account__c, Business_License__c 
                                         from MUSW__Permit2__c 
                                         limit 1];
        
        ApplicationForSObjectConfig.PermitConfig obj = new ApplicationForSObjectConfig.PermitConfig();
        obj.getContactRelationship();
        obj.createInstance();
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        
        Newsfeed__c news = new Newsfeed__c ();
        news.Program_Area__c =testLicense.Program_Area__c;
        news.Permit_Type__c=testLicense.Permit_Type__c;
        news.Application_Type__c=testLicense.Application_Type__c;
        news.Application_Method__c=testLicense.Application_Method__c;
        news.Instructions__c = 'Test Instructions';
        news.RecordTypeId = [select id from RecordType where name = 'Attestation Line' ].id;
        news.Show_For__c = 'Permit';
        news.External_Id__c='abec';
        insert news;
       
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
        ApexPages.currentPage().getParameters().put('applicationType', testlicense.Application_Type__c);
        ApexPages.currentPage().getParameters().put('programArea', testlicense.Program_Area__c);
        ApexPages.currentPage().getParameters().put('permitType', testlicense.Permit_Type__c);
        ApexPages.currentPage().getParameters().put('accountId', acct.id);
        ApexPages.currentPage().getParameters().put('contactId', contact.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        
        ctrl.existingRecId = testLicense.id;
        ctrl.licenseBy = testlicense.Application_Method__c;

        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
        obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        Newsfeed__c link = new Newsfeed__c ();
         link.Program_Area__c =testLicense.Program_Area__c;
        link.Permit_Type__c=testLicense.Permit_Type__c;
        link.Application_Type__c=testLicense.Application_Type__c;
        link.External_Id__c='absec';
        link.Application_Method__c=testLicense.Application_Method__c;
        link.RecordTypeId = [select id from RecordType where name = 'Affidavit Link'].id;
        link.Show_For__c = 'Permit';
        insert link;
        
       // obj.getAffidavitLink(ctrl);
        Test.stopTest();
    }
    
     @isTest
    static void testPermitRenewalConfigMethods(){
        Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
        MUSW__Permit2__c testLicense = [Select Id, Application_type__c, permit_type__c,program_area__C,application_method__C, MUSW__Account__c, Business_License__c 
                                         from MUSW__Permit2__c 
                                         limit 1];
        
        ApplicationForSObjectConfig.RenewalPermitConfig obj = new ApplicationForSObjectConfig.RenewalPermitConfig();
        obj.getContactRelationship();
        obj.createInstance();
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        
        Newsfeed__c news = new Newsfeed__c ();
        news.Program_Area__c =testLicense.Program_Area__c;
        news.Permit_Type__c=testLicense.Permit_Type__c;
        news.Application_Type__c=testLicense.Application_Type__c;
        news.Application_Method__c=testLicense.Application_Method__c;
        news.Instructions__c = 'Test Instructions';
        news.RecordTypeId = [select id from RecordType where name = 'Attestation Line' ].id;
        news.Show_For__c = Label.Str_Permit_Renewal;
        news.External_Id__c='abec';
        insert news;
       
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
         ApexPages.currentPage().getParameters().put('applicationType',Label.Str_ManufacturedHomesRenewal);
        ApexPages.currentPage().getParameters().put('programArea', testlicense.Program_Area__c);
        ApexPages.currentPage().getParameters().put('renewalOrReinstatement', 'Renewal');
        ApexPages.currentPage().getParameters().put('permitType', testlicense.Permit_Type__c);
        ApexPages.currentPage().getParameters().put('accountId', acct.id);
        ApexPages.currentPage().getParameters().put('parentId', testLicense.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        
        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
      //  obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        Newsfeed__c link = new Newsfeed__c ();
         link.Program_Area__c =testLicense.Program_Area__c;
        link.Permit_Type__c=testLicense.Permit_Type__c;
        link.Application_Type__c=testLicense.Application_Type__c;
        link.External_Id__c='absec';
        link.Application_Method__c=testLicense.Application_Method__c;
        link.RecordTypeId = [select id from RecordType where name = 'Affidavit Link'].id;
        link.Show_For__c = Label.Str_Permit_Renewal;
        insert link;
        
       // obj.getAffidavitLink(ctrl);
        Test.stopTest();
    }
    
         @isTest
    static void testSRConfigMethods(){
        Test.startTest();
        Contact contact = [select id from Contact where FirstName = 'Test Contact'];
        Account acct =  [select id from Account limit 1];
        MUSW__Permit2__c testLicense = [Select Id, Application_type__c, permit_type__c,program_area__C,application_method__C, MUSW__Account__c, Business_License__c 
                                         from MUSW__Permit2__c 
                                         limit 1];
        
        ApplicationForSObjectConfig.ServiceRequestConfig obj = new ApplicationForSObjectConfig.ServiceRequestConfig();
        obj.getContactRelationship();
        obj.createInstance();
        obj.getObjectName();
        obj.getCurrentRecordWhereClause();
        obj.getFeeRequirementWhereClause('1234');
        obj.setPageTitle();
        obj.getQuestionObjectLookup();
        obj.getAttachmentObjectLookup();
        obj.getStatusField();
        
        PageReference pageRef = Page.Application;
        Test.setCurrentPage(pageRef);  
         ApexPages.currentPage().getParameters().put('applicationType',Label.STR_Service_Request);
        ApexPages.currentPage().getParameters().put('credential', testlicense.Program_Area__c);
        ApexPages.currentPage().getParameters().put('credentialType', testlicense.Permit_Type__c);
        ApexPages.currentPage().getParameters().put('srType', 'Change Name');
        ApexPages.currentPage().getParameters().put('parentId', testLicense.id);
        ApplyForSObjectCtlr ctrl = new ApplyForSObjectCtlr();
        obj.getBoardLicenseType(ctrl);
        obj.getExistingRecord(ctrl);
        obj.setFieldValues(ctrl);
        obj.setRecordTypeField(ctrl);
        obj.setBoardLicenseType(ctrl);
        obj.setLicenseId(ctrl);
        obj.getLegalText(ctrl);
        
        obj.getAffidavitLink(ctrl);
        Test.stopTest();
    }
      
}