src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associations__c.object
<CustomObject>
    <label>License Relationship</label>
    <nameField>
        <displayFormat>LRN-{0000000}</displayFormat>
        <label>License Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Licensee Email</description>
        <formula>MUSW__Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Licensee Email</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LnP_DashboardApexController_2_Test.cls
@isTest
public class LnP_DashboardApexController_2_Test {
    @isTest static void test_method_one(){
        string businessLicenseType = LnP_DashboardApexController_2.getRecordTypeId('MUSW__License2__c','Business');
        Id businessAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc= DOL_TestDataFactory.createAccount(businessAccount);
        acc.Email__c = 'test@mailinator.com';
        update acc;
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(businessLicenseType, acc.Id, 'Architects', 'Architect', 'General Application');
        lic.MUSW__Status__c='In Review';
        update lic;
        
        Associations__c association = DOL_TestDataFactory.createAssociation(lic.Id);
        
        Id conRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecordTypeId, acc.Id);
        
        MUSW__Account_Contact__c accCon = DOL_TestDataFactory.createAccountContact(con.Id, acc.Id);
        
        try{
            LnP_DashboardApexController_2.getEducationalHistory(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
       //     System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setLicenseToInreview(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
         //   System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setCurrentLicenseTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
           // System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.ProfessionalRelationshipTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.DraftNewLicenseApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setDraftRenewApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setDraftMaintananceRequestApplicationsData();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setDraftAMRAppLicenseData(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.PendingNewLicenseApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.showExamsTabOnDashboard(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.PendingRenewApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.PendingMaintananceRequestApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.CompletedMaintananceRequestApplicationsTable();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.fetchLicenseDetailsTable(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.fetchEndorsementDetails(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.getBusinessRelationShipData(lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.setPeerRelationShipTable('Architect', lic.Id);
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.getContact();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
        //    System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.isValidCommunityUser();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
          //  System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.helptextFetch();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        try{
            LnP_DashboardApexController_2.checkActiveCart();
        }
        catch(Exception ex){
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            //System.debug('Error');
        }
        
        Test.startTest();
        LnP_DashboardApexController_2.fetchLicenseDetails(lic.Id);
        LnP_DashboardApexController_2.createAssociationTask(association.Id);
        //LnP_DashboardApexController_2.getEducationalHistory(lic.Id);
        LnP_DashboardApexController_2.uploadAdditionalDocuments(lic.Id);
        //LnP_DashboardApexController_2.setLicenseToInreview(lic.Id);
        //LnP_DashboardApexController_2.fetchLicenseDetailsTable(lic.Id);
        //LnP_DashboardApexController_2.fetchEndorsementDetails(lic.Id);
        LnP_DashboardApexController_2.seperateAccountContactRelationship(accCon.Id);
        //LnP_DashboardApexController_2.getBusinessRelationShipData(lic.Id);
        LnP_DashboardApexController_2.setPeerRelationShipTable('Architect', lic.Id);
        //LnP_DashboardApexController_2.setDraftAMRAppLicenseData(lic.Id);
        //LnP_DashboardApexController_2.showExamsTabOnDashboard(lic.Id);
        //fetchLicenseRelatedEmploymentNEducationalHistoryRecords(String relatedRecordId);
        //fetchRenewalRelatedEmploymentNEducationalHistoryRecords(String relatedRecordId);
              LnP_DashboardApexController.getDBJSON();  
        Test.stopTest();
    }
}