src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>User_Account</fullName>
        <active>true</active>
        <description>User Account</description>
        <label>User Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account associated with the application. This is only referred to by Account Carts.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact applicant associated with the application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Planning Applications</relationshipLabel>
        <relationshipName>Application2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit the service request is linked to</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <label>Program Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <label>Section Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Service_Request</fullName>
        <active>true</active>
        <label>Service Request</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>Portal field.</description>
        <label>Section Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>This helps in portal validation.</description>
        <label>Section Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Universal_Default_Permit_Record_Type</fullName>
        <active>true</active>
        <description>This is the record type for any plan review/permits.</description>
        <label>Universal Default Permit Record Type</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact on the Renewal</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the renewal.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This is the type of permit being renewed.</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This is used for permit renewal.</description>
        <label>Program Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Type__c</fullName>
        <description>Type of reinstatement.</description>
        <label>Renewal Reinstatement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal PTO</fullName>
                </value>
                <value>
                    <fullName>Renewal Plan Review</fullName>
                </value>
                <value>
                    <fullName>ReinstatementPTO</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPTO</label>
                </value>
                <value>
                    <fullName>ReinstatementPlanReview</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPlanReview</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Number__c</fullName>
        <description>Used on the portal</description>
        <label>Section Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/classes/BaseValidatorTest.cls
@isTest
public class BaseValidatorTest {
    
    @testSetup
    static void createData(){
        MUSW__License2__c lic = new MUSW__License2__c();
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('User_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecordTypeId);
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(contactRecordTypeId, acc.Id);
        Id licRecordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        lic = DOL_TestDataFactory.createLicense(licRecordTypeId, acc.Id, 'Timeshares', 'Timeshare Company', 'General Application');
        lic.MUSW__Applicant__c = con.Id;
        lic.MUSW__Primary_Licensee__c = acc.Id;
        update lic;
        Schema.sObjectType tokenA = lic.getSObjectType();
        
        Id permitRecordType = Schema.SObjectType.MUSW__Permit2__c.getRecordTypeInfosByDeveloperName().get('Universal_Default_Permit_Record_Type').getRecordTypeId();
        MUSW__Permit2__c permit = DOL_TestDataFactory.createPermit(permitRecordType);
        permit.MUSW__Applicant__c = con.Id;
        permit.MUSW__Account__c = acc.Id;
        update permit;
        
        Id renewalRecordTypeId = Schema.SObjectType.Renewal_Application__c.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
        Renewal_Application__c renewal = DOL_TestDataFactory.createRenewalApplication(renewalRecordTypeId, lic.Id);
        renewal.Applicant__c = con.Id;
        renewal.Licensee__c = acc.Id;
        renewal.Permit__c = permit.Id;
        update renewal;
        
        Id applicationRecordType = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByDeveloperName().get('Service_Request').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(applicationRecordType);
    }
    
    @isTest
    static void createValidatorTest(){
        
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.LICENSE, 'Delegated Agent Record Type');
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.LICENSE, 'Manufactured Homes Record Type');
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.PERMIT, 'Permit');
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.PERMIT, 'POWTS Plan Review');
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.RENEWAL, 'Universal Default Renewal/Reinstatement');
        BaseValidator.createValidator(BaseValidator.ApplicationObjectType.SERVICEREQUEST, 'Universal Default Renewal/Reinstatement');
        
        
    }
    
    @isTest
    static void validateContactTest(){
        MUSW__License2__c lic = [SELECT Id, MUSW__Applicant__c, Credential_Type__c, Credential__c FROM MUSW__License2__c LIMIT 1];       
        MUSW__Permit2__c permit = [SELECT Id, MUSW__Applicant__c, Program_Area__c, Permit_Type__c FROM MUSW__Permit2__c LIMIT 1];
        Renewal_Application__c renewal = [SELECT Id, Renewal_Reinstatement_Type__c, Applicant__c, License__c, Permit__c, Credential__c, Credential_Type__c, Permit_Type__c, Program_Area__c FROM Renewal_Application__c];
        BaseValidator b = new BaseValidator();
        b.validateContact(BaseValidator.ApplicationObjectType.LICENSE, lic);
        b.validateContact(BaseValidator.ApplicationObjectType.PERMIT, permit);
        b.validateContact(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_Reinstatement;
        update renewal;
        b.validateContact(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_RenewalPTO;
        update renewal;
        b.validateContact(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
    }
    
    @isTest
    static void validateAccountTest(){
        MUSW__License2__c lic = [SELECT Id, MUSW__Primary_Licensee__c, Credential_Type__c, Credential__c FROM MUSW__License2__c LIMIT 1];       
        MUSW__Permit2__c permit = [SELECT Id, MUSW__Account__c, Program_Area__c, Permit_Type__c FROM MUSW__Permit2__c LIMIT 1];
        Renewal_Application__c renewal = [SELECT Id, Renewal_Reinstatement_Type__c, Licensee__c, License__c, Permit__c, Credential__c, Credential_Type__c, Permit_Type__c, Program_Area__c FROM Renewal_Application__c];
        BaseValidator b = new BaseValidator();
        b.validateAccount(BaseValidator.ApplicationObjectType.LICENSE, lic);
        b.validateAccount(BaseValidator.ApplicationObjectType.PERMIT, permit);
        b.validateAccount(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_Reinstatement;
        update renewal;
        b.validateAccount(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_RenewalPTO;
        update renewal;
        b.validateAccount(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
    }
    
    @isTest
    static void validateAddress(){
        MUSW__License2__c lic = [SELECT Id, MUSW__Primary_Licensee__c, Credential_Type__c, Credential__c FROM MUSW__License2__c LIMIT 1];       
        MUSW__Permit2__c permit = [SELECT Id, MUSW__Account__c, Program_Area__c, Permit_Type__c FROM MUSW__Permit2__c LIMIT 1];
        Renewal_Application__c renewal = [SELECT Id, Renewal_Reinstatement_Type__c, Licensee__c, License__c, Permit__c, Credential__c, Credential_Type__c, Permit_Type__c, Program_Area__c FROM Renewal_Application__c];
        BaseValidator b = new BaseValidator();
        b.validateAddress(BaseValidator.ApplicationObjectType.LICENSE, lic);
        b.validateAddress(BaseValidator.ApplicationObjectType.PERMIT, permit);
        b.validateAddress(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_Reinstatement;
        update renewal;
        b.validateAddress(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.Renewal_Reinstatement_Type__c = Label.RNT_RenewalPTO;
        update renewal;
        b.validateAddress(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
        
        renewal.License__c = null;
        update renewal;
        b.validateAddress(BaseValidator.ApplicationObjectType.RENEWAL, renewal);
    }
    
    @isTest
    static void validateServiceRequestTest(){
        MUSW__Application2__c app = [SELECT Id FROM MUSW__Application2__c LIMIT 1];
        app.Section_Number__c = 99;
        update app;
        BaseValidator b = new BaseValidator();
        b.validateServiceRequest(BaseValidator.ApplicationObjectType.SERVICEREQUEST, app);
    }
    
    @isTest
    static void validateTest(){
        MUSW__Application2__c app = [SELECT Id FROM MUSW__Application2__c LIMIT 1];
        MUSW__License2__c lic = [SELECT Id, MUSW__Primary_Licensee__c, Credential_Type__c, Credential__c FROM MUSW__License2__c LIMIT 1];       
        
        app.Section_Number__c = 99;
        update app;
        BaseValidator b = new BaseValidator();
        b.validate(app, lic);
        b.runConfigurableValidations();
    }
}