src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>User_Account</fullName>
        <active>true</active>
        <description>User Account</description>
        <label>User Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Various credential types available under a functional area and division</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/LnP_WizardApexController_Test.cls
@isTest
public class LnP_WizardApexController_Test {

    @isTest
    public static void unitTest01(){
        test.startTest();
        List<MUSW__License2__c> licList = LnP_WizardApexController.fetchLicenseList('Geologist', 'Geologist');
        test.stopTest();
    }
    
    @isTest
    public static void unitTest02(){
        test.startTest();
        List<MUSW__License2__c> licList = LnP_WizardApexController.fetchLicenseList('Geologist', 'Architect');
        LnP_WizardApexController.questionForLicenceTyep('Geologist', 'Geologist', 'General Application', 'MUSW__License2__c', 'Reinstatement');
        test.stopTest();
    }
    
    @isTest
    public static void unitTest03(){
        test.startTest();
        Integer licCount = LnP_WizardApexController.validationForTemporaryLicenses('Appraisers - Real Estate', 'Temporary Certified General', 'General Application', 'MUSW__License2__c');
        LnP_WizardApexController.questionForLicenceTyep('Geologist', 'Geologist','General Application' ,'MUSW__License2__c' , 'Renewal');
        LnP_WizardApexController.fetchCnBLabels('Eligible_Not_Pub', 'Notary Public');
        test.stopTest();
    }
    
    
    @isTest
    public static void unitTest04(){
        test.startTest();
        Map<String,Question__c> questMap = LnP_WizardApexController.questionForLicenceTyep('Geologist', 'Geologist', 'General Application', 'MUSW__License2__c');
        LnP_WizardApexController.fetchInstructions('Geologist', 'Geologist', 'General Application','MUSW__License2__c' , '', '');
        LnP_WizardApexController.fetchLicenseType('Business');
        LnP_WizardApexController.fetchLicenseType('Individual');
        LnP_WizardApexController.getAllStaticTexts();
        LnP_WizardApexController.getPicklistOptions('MUSW__License2__c', 'Application_Type__c', 'Credential_Type__c');
        test.stopTest();
        
    }
    
    @isTest
    public static void unitTest05(){
        test.startTest();
        LnP_WizardApexController.fetchAccountList('Appraisal Management Companies', 'Appraisal Management Company');
        test.stopTest();
    }
    
    @isTest
    public static void unitTest06(){
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('User_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecordTypeId);
        
        Id contactRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(contactRecordTypeId, acc.Id);
        
        MUSW__Account_Contact__c accCon = DOL_TestDataFactory.createAccountContact();
               
        Id licRecordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId();
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(licRecordTypeId, acc.Id, 'Timeshares', 'Timeshare Company', 'General Application');
        lic.MUSW__Applicant__c = con.Id;
        update lic;
        String licId = lic.id;
        String accId = acc.id;
       
        test.startTest();
            LnP_WizardApexController.startAnApplication('Timeshares', 'Timeshare Company', 'General Application', accId, licId);
            LnP_WizardApexController.startRenewalApplication('Timeshares', 'Timeshare Company', 'General Application',accId , 'True', licId);
       
       test.stopTest();
    }
    
    
    
}