src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>Indicates the status of the account</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Associate_Flag__c.object
<CustomObject>
    <description>This object is for create a flag based on severity</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description for the flag to check</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <formula>CASE(TEXT(Severity__c), 
&apos;Low&apos;, Image(&apos;/resource/Flag_Low&apos;, &apos;Good&apos;, 30, 30),
&apos;Medium&apos;, Image(&apos;/img/msg_icons/warning32.png&apos;, &apos;Warning&apos; , 30, 30),
&apos;High&apos;, Image(&apos;/img/msg_icons/error32.png&apos;, &apos;Bad&apos;, 30, 30),
&apos;Info&apos;, Image(&apos;/img/msg_icons/info32.png&apos;, &apos;Bad&apos;, 30, 30),
&apos;&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PTO_Plan_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for PTO/Plan Review(Permit Object)</description>
        <label>PTO/Plan Review</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Associate Flags</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associate Flag</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Flag Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associate Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Name_Value_Pair__mdt.object
<CustomObject>
    <description>To store name value pairs - similar to key value pairs in a map</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value field for name value pair</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Name Value Pair</label>
    <pluralLabel>Name Value Pairs</pluralLabel>
</CustomObject>

classes/FlagPermit_CC.cls
/*************************************************************************************************************
** User Story: 282 -- Adding Alerts to a Credential/Plan Review/PTO
**************************************************************************************************************
** Class Name    : FlagPermit_CC
** Description   : Controller for Permit Related List (Associate Flag)
** Version       : 1.0
** Built By      : Srikanth Kottam
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Srikanth Kottam                07/20/2018                    1                          Created
** 
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
**  **********************************************************************************/
public class FlagPermit_CC {
    ApexPages.StandardController controller;
    public MUSW__Permit2__c record {get; set;}
    public list<Associate_Flag__c> lstFlag {get; set;}
    public String flagObjectPrefix;
    public String permitFieldId;
    public Boolean isContactOnHold {get; set;}
    
    public FlagPermit_CC(ApexPages.StandardController controller){
        this.controller = controller;
        this.record = (MUSW__Permit2__c)controller.getrecord();
        
        lstFlag = [SELECT Id, Name, Flag__c, Description__c, Severity__c, Effective_Date__c, End_Date__c FROM Associate_Flag__c  WHERE PTO_Plan_Review__c =: record.id];  
        flagObjectPrefix = Schema.getGlobalDescribe().get('Associate_Flag__c').getDescribe().getKeyPrefix();
        List<Name_Value_Pair__mdt> lstNVP = [Select Value__c from Name_Value_Pair__mdt where DeveloperName = 'FlagPermitId'];
        if(lstNVP.size() > 0){
            permitFieldId = lstNVP[0].Value__c;
        }
        
        isContactOnHold = false;
        MUSW__Permit2__c per = [Select MUSW__Applicant__r.Contact_Status__c, MUSW__Account__r.Account_Status__c From MUSW__Permit2__c where Id = :record.Id];
        if(per.MUSW__Applicant__r.Contact_Status__c == 'On Hold' || per.MUSW__Account__r.Account_Status__c == 'On Hold'){
            isContactOnHold = true;
        }
    }
    
    public pagereference customnew(){
        PageReference pageRef;
        
        MUSW__Permit2__c permit = [select id, name from MUSW__Permit2__c where id =: Record.Id];
        String url = '/' + flagObjectPrefix + '/e?' + permitFieldId + '=' + permit.name + '&' + permitFieldId + '_lkid=' + permit.Id;
        
        pageRef = new PageReference(url);
        pageRef.setRedirect(true);
        return pageRef;
    }
    
}