src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>App_Submitted_Date__c</fullName>
        <description>App Submitted Date</description>
        <label>First App Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel_Contact2__c.object
<CustomObject>
    <description>Contacts associated to a Parcel eg. Owner</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parcel or address this contact is related to.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Parcel_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parcel_Account__c.object
<CustomObject>
    <description>Store Address for Accounts</description>
    <label>Parcel Account</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Dwelling Contractor</fullName>
        <isActive>false</isActive>
        <label>Dwelling Contractor</label>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/classes/CredentialParcel_CC_Test.cls
/**
* User Story: 78 - Associate addresses to a Credential Type
* Name: CredentialParcel_CC_Test
* Type: Test Class
* Description: Test Class for CredentialParcel_CC
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 07/18/2018   Srikanth Kottam/Deloitte           Initial Creation
**/
@isTest
public class CredentialParcel_CC_Test {
    public static testmethod void testIndividualLicense(){
        List<Account> accList = new List<Account>();
        
        /** Account Creation **/ 
        Account a = CreateTestDataUtility.createAccount();
        accList.add(a);
        insert accList;
        
        /** Contact Creation **/
        Contact c = CreateTestDataUtility.createContact(a.Id);
        insert c;
        Id recordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Universal Default License Record Type').getRecordTypeId();
        MUSW__License2__c license = new MUSW__License2__c(RecordTypeId = recordTypeId,
                                                          MUSW__Status__c='Pending',
                                                          App_Submitted_Date__c=System.today(),
                                                          Application_Type__c = 'Trades Credential', 
                                                          Credential_Type__c = 'Dwelling Contractor', 
                                                          Credential__c = 'Dwelling Contractor', 
                                                          Application_Method__c = 'General Application');
        license.MUSW__Applicant__c =c.id;
        insert license;
        test.startTest();
        List<MUSW__Parcel__c> lstParcelAddresses = new List<MUSW__Parcel__c>();
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '801 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '901 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        insert lstParcelAddresses;

        MUSW__License_Parcel__c licenseParcel = new MUSW__License_Parcel__c(MUSW__License2__c = license.Id, MUSW__Parcel__c = lstParcelAddresses[0].Id);
        insert licenseParcel;

        ApexPages.StandardController sc = new ApexPages.StandardController(licenseParcel);
        CredentialParcel_CC lp= new CredentialParcel_CC(sc);
        
        system.debug('mailingAddressId'+lp.mailingAddressId);
        system.debug('publicAddressId'+lp.publicAddressId);
        system.debug('physicalAddressId'+lp.physicalAddressId);
        // system.debug('licId'+lp.licId);
        // system.debug('licenseBoard'+lp.licenseBoard);
        //LicenseParcelControllerExt.ArchivP = licenseParcel;
        List<SelectOption> so = new List<SelectOption>();
        //LicenseParcelControllerExt.addressOptions = so;
            
        MUSW__Parcel_Contact2__c parcelContact = CreateTestDataUtility.createParcelContactJunction(lstParcelAddresses[0].id, c.id);
        insert parcelContact;
        parcelContact = CreateTestDataUtility.createParcelContactJunction(lstParcelAddresses[1].id, c.id);
        insert parcelContact;
            
        List<SelectOption> lstAddressOptions = lp.addressOptions;
        //system.assertEquals(lstParcelAddresses.size(), lstAddressOptions.size());
            
        lp.mailingAddressId = lstParcelAddresses[0].Id;
        lp.publicAddressId = lstParcelAddresses[0].Id;
            
        lp.saveCredentialAddress();

        List<MUSW__License_Parcel__c> lstParcelAddressesSaved = [SELECT MUSW__License2__c FROM MUSW__License_Parcel__c WHERE MUSW__Parcel__c=:lstParcelAddresses[0].Id];

        //System.assertEquals(lstParcelAddressesSaved.size(), 2);
            
        //Trying to force an exception
        lp.mailingAddressId = license.Id;
        lp.saveCredentialAddress();
        test.stopTest();  
        List<Apexpages.Message> msgs = ApexPages.getMessages();
            boolean b = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getSeverity() == ApexPages.Severity.ERROR) b = true;
            }
            //System.assert(b);

    }
    
 /*   public static Testmethod void testBusinessLicense(){
        List<Account> accList = new List<Account>();
        
        // Account Creation  
        Account a = CreateTestDataUtility.createAccount();
        accList.add(a);
        insert accList;
        
        // Contact Creation 
        Contact c = CreateTestDataUtility.createContact(a.Id);
        insert c;
        
        Id recordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Universal Default License Record Type').getRecordTypeId();
        MUSW__License2__c license = new MUSW__License2__c(RecordTypeId = recordTypeId,
                                                          MUSW__Status__c='Pending',
                                                          App_Submitted_Date__c=System.today(),
                                                          Application_Type__c = 'Trades Credential', 
                                                          Credential_Type__c = 'Dwelling Contractor', 
                                                          Credential__c = 'Dwelling Contractor', 
                                                          Application_Method__c = 'General Application',
                                                          MUSW__Primary_Licensee__c=a.id);
        license.MUSW__Applicant__c =c.id;
        insert license;
        test.startTest();
        List<MUSW__Parcel__c> lstParcelAddresses = new List<MUSW__Parcel__c>();
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '801 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '901 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        insert lstParcelAddresses;

        //system.assertNotEquals(lstParcelAddresses[0].Id, null);

        MUSW__License_Parcel__c licenseParcel = new MUSW__License_Parcel__c(MUSW__License2__c = license.Id, MUSW__Parcel__c = lstParcelAddresses[0].Id);
        insert licenseParcel;

        ApexPages.StandardController sc = new ApexPages.StandardController(licenseParcel);
        CredentialParcel_CC lp= new CredentialParcel_CC(sc);
            
        Parcel_Account__c parcelAccount = CreateTestDataUtility.createParcelAccountJunction(lstParcelAddresses[0].id, a.id);
        insert parcelAccount;
        parcelAccount = CreateTestDataUtility.createParcelAccountJunction(lstParcelAddresses[1].id, a.id);
        insert parcelAccount;
        
        //system.assertEquals(lp.licenseBoard,Label.BRD_SAN );

        List<SelectOption> lstAddressOptions = lp.addressOptions;
        //system.assertEquals(lstParcelAddresses.size(), lstAddressOptions.size());

        //system.assertEquals(lp.licenseBoard,Label.BRD_SAN );
            
        lp.mailingAddressId = lstParcelAddresses[0].Id;
        lp.publicAddressId = lstParcelAddresses[0].Id;
        //lp.physicalAddressId = lstParcelAddresses[0].Id;
            
        lp.saveCredentialAddress();
        test.stopTest();
        List<MUSW__License_Parcel__c> lstParcelAddressesSaved = [SELECT MUSW__License2__c FROM MUSW__License_Parcel__c WHERE MUSW__Parcel__c=:lstParcelAddresses[0].Id];

        //System.assertEquals(lstParcelAddressesSaved.size(), 3);
    }  */
    @isTest 
    static void testConstructor(){
        CredentialParcel_CC controller = new CredentialParcel_CC();
    }   
}