src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>Indicates the status of the account</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Out of Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FEIN_Number_Encrypted__c</fullName>
        <description>Encrypted field for FEIN Number</description>
        <inlineHelpText>FEIN Number Encrypted</inlineHelpText>
        <label>FEIN Number Encrypted</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Social_Security_Number_Encrypted__c</fullName>
        <description>Encrypted SSN field</description>
        <label>Social Security Number Encrypted</label>
        <length>12</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Social_Security_Number_Encrypted__c</fullName>
        <label>Social Security Number Encrypted</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Business_License__c</fullName>
        <description>Business License</description>
        <formula>OR(ISPICKVAL( Credential__c , &apos;Dwelling Contractor&apos;), 
ISPICKVAL( Credential__c , &apos;Dwelling Contractor Restricted&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Manufacturer&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Dealer&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Boiler&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Commercial Building&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Elevator&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Fire Suppression/Alarm Systems&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Other&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Plumbing&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - POWTS&apos;),
ISPICKVAL(Credential__c , &apos;Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;UDC Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment&apos;),
ISPICKVAL(Credential__c , &apos;Prearrangement Funeral Services&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment Branch&apos;),
ISPICKVAL(Credential__c , &apos;Certificate of Removal Registration&apos;),
ISPICKVAL(Credential__c , &apos;Crematory&apos;),
ISPICKVAL(Credential__c , &apos;Cremated Remains Disposition Permit&apos;),
ISPICKVAL(Credential__c , &apos;Cemetery&apos;),
ISPICKVAL(Credential__c , &apos;Camping Resort Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Course&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Provider&apos;),
ISPICKVAL(Credential__c , &apos;Timeshare Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraisal Management Company&apos;)


)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Business_License__c</fullName>
        <formula>OR(ISPICKVAL( Permit_Type__c , &apos;Manufactured Homes Community Permit&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact on the Renewal</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_License__c</fullName>
        <description>Is this a business license</description>
        <formula>OR(License__r.Business_License__c,
Permit__r.Business_License__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the renewal.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This is the type of permit being renewed.</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/classes/TVSVerifyApplication.cls
public with sharing class TVSVerifyApplication {
    public static String dorResponse;
    
    public TVSVerifyApplication(){
        
    }
    public static string verifyDetails(Id credentialId, Boolean certificateSent){
        String recId = '';
        String customerType = '';
        String idType = '';
        String objectToUpdate = '';
        String objectName = '';
        String objectId = '';
        String applicantId = '';
        String applicantLastName = '';
        String applicantFirstName = '';
        String credentialType = '';
        String credentialNumber = '';
        Boolean isOnHold = false;
        String onHoldStatus = label.ST_NoAction;
        
        system.debug('Entered verifyDetails');
        
        try{
        if(credentialId.getSobjectType().getDescribe().getName() == 'MUSW__License2__c'){
            MUSW__License2__c lic = [Select Id, Name, MUSW__Applicant__c, MUSW__Applicant__r.Social_Security_Number_Encrypted__c, 
                                     MUSW__Applicant__r.FirstName, MUSW__Applicant__r.LastName, Credential__c, Business_License__c, 
                                     MUSW__Primary_Licensee__c, MUSW__Primary_Licensee__r.FEIN_Number_Encrypted__c, MUSW__Primary_Licensee__r.Name,
                                     MUSW__Applicant__r.Contact_Status__c, MUSW__Primary_Licensee__r.Account_Status__c 
                                     From MUSW__License2__c where Id = :credentialId];
            
            if(lic.Business_License__c == true){
                idType = 'FEIN';
                recId = lic.MUSW__Primary_Licensee__r.FEIN_Number_Encrypted__c;
                applicantLastName = lic.MUSW__Primary_Licensee__r.Name;
                applicantFirstName = '';
                customerType = 'Business';
                objectToUpdate = 'Account';
                objectName = lic.MUSW__Primary_Licensee__r.Name;
                objectId = lic.MUSW__Primary_Licensee__c;
                isOnHold = (lic.MUSW__Primary_Licensee__r.Account_Status__c == 'On Hold');
            }else{
                idType = 'SSN';
                recId = lic.MUSW__Applicant__r.Social_Security_Number_Encrypted__c;
                applicantLastName = lic.MUSW__Applicant__r.LastName;
                applicantFirstName = lic.MUSW__Applicant__r.FirstName;
                customerType = 'Individual';
                objectToUpdate = 'Contact';
                objectName = lic.MUSW__Applicant__r.FirstName + ' ' + lic.MUSW__Applicant__r.LastName;
                objectId = lic.MUSW__Applicant__c;
                isOnHold = (lic.MUSW__Applicant__r.Contact_Status__c == 'On Hold');
            }
            
            applicantId = lic.MUSW__Applicant__c;
            //applicantId = String.valueOf(lic.MUSW__Applicant__c).substring(0, 15);
            credentialType = lic.Credential__c;
            credentialNumber = lic.Name;
        }else if(credentialId.getSobjectType().getDescribe().getName() == 'MUSW__Permit2__c'){
            MUSW__Permit2__c lic = [Select Id, Name, MUSW__Applicant__c, MUSW__Applicant__r.Social_Security_Number_Encrypted__c, 
                                    MUSW__Applicant__r.FirstName, MUSW__Applicant__r.LastName, Permit_Type__c, Business_License__c, 
                                    MUSW__Account__c, MUSW__Account__r.FEIN_Number_Encrypted__c, MUSW__Account__r.Name,
                                    MUSW__Applicant__r.Contact_Status__c, MUSW__Account__r.Account_Status__c     
                                    From MUSW__Permit2__c where Id = :credentialId];
            
            if(lic.Business_License__c == true){
                idType = 'FEIN';
                recId = lic.MUSW__Account__r.FEIN_Number_Encrypted__c;
                applicantLastName = lic.MUSW__Account__r.Name;
                applicantFirstName = '';
                customerType = 'Business';
                objectToUpdate = 'Account';
                objectName = lic.MUSW__Account__r.Name;
                objectId = lic.MUSW__Account__c;
                isOnHold = (lic.MUSW__Account__r.Account_Status__c == 'On Hold');
            }else{
                idType = 'SSN';
                recId = lic.MUSW__Applicant__r.Social_Security_Number_Encrypted__c;
                applicantLastName = lic.MUSW__Applicant__r.LastName;
                applicantFirstName = lic.MUSW__Applicant__r.FirstName;
                customerType = 'Individual';
                objectToUpdate = 'Contact';
                objectName = lic.MUSW__Applicant__r.FirstName + ' ' + lic.MUSW__Applicant__r.LastName;
                objectId = lic.MUSW__Applicant__c;
                isOnHold = (lic.MUSW__Applicant__r.Contact_Status__c == 'On Hold');
            }
            
            applicantId = lic.MUSW__Applicant__c;
            //applicantId = String.valueOf(lic.MUSW__Applicant__c).substring(0, 15);
            credentialType = lic.Permit_Type__c;
            credentialNumber = lic.Name;
        } else if(credentialId.getSobjectType().getDescribe().getName() == 'Renewal_Application__c'){
            Renewal_Application__c renReins = [Select Id, name, Applicant__c, Applicant__r.Social_Security_Number_Encrypted__c, 
                                               Applicant__r.FirstName, Applicant__r.LastName, Applicant__r.Contact_Status__c,
                                               Credential__c, Permit_Type__c, Permit__r.Name, License__r.Name,
                                               Business_License__c, Licensee__c, Licensee__r.FEIN_Number_Encrypted__c, Licensee__r.Name,
                                               Licensee__r.Account_Status__c from Renewal_Application__c where Id = :credentialId];
            if(renReins.Business_License__c == true){
                idType = 'FEIN';
                recId = renReins.Licensee__r.FEIN_Number_Encrypted__c;
                applicantLastName = renReins.Licensee__r.Name;
                applicantFirstName = '';
                customerType = 'Business';
                objectToUpdate = 'Account';
                objectName = renReins.Licensee__r.Name;
                objectId = renReins.Licensee__c;
                isOnHold = (renReins.Licensee__r.Account_Status__c == 'On Hold');
            }else{
                idType = 'SSN';
                recId = renReins.Applicant__r.Social_Security_Number_Encrypted__c;
                applicantLastName = renReins.Applicant__r.LastName;
                applicantFirstName = renReins.Applicant__r.FirstName;
                customerType = 'Individual';
                objectToUpdate = 'Contact';
                objectName = renReins.Applicant__r.FirstName + ' ' + renReins.Applicant__r.LastName;
                objectId = renReins.Applicant__c;
                isOnHold = (renReins.Applicant__r.Contact_Status__c == 'On Hold');
            }
            applicantId = renReins.Applicant__c;
            //applicantId = String.valueOf(lic.MUSW__Applicant__c).substring(0, 15);
            if(renReins.License__r.Name != null && renReins.License__r.Name != ''){
                credentialType = renReins.Credential__c;
            	credentialNumber = renReins.License__r.Name;
            }else if(renReins.Permit__r.Name != null && renReins.Permit__r.Name != ''){
                credentialType = renReins.Permit_Type__c;
            	credentialNumber = renReins.Permit__r.Name;
            } else{
                if(renReins.Permit_Type__c != null && renReins.Permit_Type__c != ''){
                	credentialType = renReins.Permit_Type__c;
                }else{
                    credentialType = renReins.Credential__c;
                }
                credentialNumber = renReins.Name;
            }
			system.debug('credentialNumber>>>'+credentialNumber);
            system.debug('credentialType>>>'+credentialType);
            system.debug('renReins.License__r.Name>>>'+renReins.License__r.Name);
            system.debug('renReins.Credential__c>>>'+renReins.Credential__c);
            
            system.debug('renReins.Permit__r.Name>>>'+renReins.Permit__r.Name);
            system.debug('renReins.Permit_Type__c>>>'+renReins.Permit_Type__c);
        }
        
        transient Boolean org = [Select Id, isSandbox From Organization][0].isSandbox;
        String url = '';
        if(org == true){
            url = 'callout:Wisconsin_Endpoint_Test/tvs/v1/verify';
            // Un-comment status to bypass TVS check in sandbox
             string status = label.ST_Active;
             return status;
            
        }else{
            url = 'callout:Wisconsin_Endpoint_Prod/tvs/v1/verify';
        }
        
        url = url + '?Id={0}&ApplicantId={1}&IdType={2}&LastName={3}&FirstName={4}&LicenseType={5}&LicenseNumber={6}&CustomerType={7}';
        List<String> fillers = new String[]{recId, applicantId, idType, applicantLastName, applicantFirstName, credentialType, credentialNumber, customerType};
            
        url = String.format(url, fillers);
        url = url.replace(' ', '+');
        
        if(certificateSent){
            url = url + '&CertificateSent=true';
        }
        system.debug(url);
        system.debug('isOnHold>>>'+isOnHold);
        
            HttpRequest req = new HttpRequest();
            req.setEndpoint(url);
            req.setMethod('GET');
            // Set Timeout request for 2 min
            req.setTimeout(120000);
            
            Http h = new Http();
            HttpResponse res = h.send(req);
            
            system.debug(res.getBody());
            
            JSONParser parser = JSON.createParser(res.getBody());
            while (parser.nextToken() != null) {
                if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
                    String fieldName = parser.getText();
                    parser.nextToken();
                    String fieldValue = parser.getText();
                    if(fieldName == 'Response'){
                        dorResponse = fieldValue;
                    }
                }
            }
            system.debug('dorResponse>>>'+dorResponse);
            if(dorResponse == 'CD' || dorResponse == 'HD' || dorResponse == 'AA'){
                onHoldStatus = label.ST_OnHold;
            }else{
                onHoldStatus = label.ST_Active;
            }
            system.debug('onHoldStatus>>>'+onHoldStatus);
            
        }catch(exception ex){
            ErrorLogger.logGeneralException(ex, UserInfo.getUserId(), 'TVSVerifyApplication', 'Error Occured while Submitting the application from Portal TVS integration', 'verifyDetails', dorResponse, label.Str_HIGH);
        }finally{
            return onHoldStatus;
        } 
        return onHoldStatus;
    }
}