src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <formula>Ultimate_Parent_Account__r.UBI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBI Number</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/select2TestCtrl_test.cls
@isTest
public class select2TestCtrl_test {

    @testSetup
    private static void testdataSetup() {
       Account account = new Account(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Accountuni',UBI_Number__c ='79068467');
        insert account;
    }
    @isTest
    public static void testmethod1() {
        List<Account> lstAcc =[select id from Account where name ='Test Accountuni' limit 1];
        Account account = new Account(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Accountunirrr1',UBI_Number__c ='79068467');
        select2TestCtrl.saveAccount(account);
    }
     @isTest
    public static void testmethod2() {
       MUSW__License2__c obj = new MUSW__License2__c(); 
       select2TestCtrl.getselectOptions(obj,'Application_Type__c');  
    }
}