src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account associated with the application. This is only referred to by Account Carts.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact applicant associated with the application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Planning Applications</relationshipLabel>
        <relationshipName>Application2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit the service request is linked to</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <label>Program Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact on the Renewal</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the renewal.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This is the type of permit being renewed.</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This is used for permit renewal.</description>
        <label>Program Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Type__c</fullName>
        <description>Type of reinstatement.</description>
        <label>Renewal Reinstatement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal PTO</fullName>
                </value>
                <value>
                    <fullName>Renewal Plan Review</fullName>
                </value>
                <value>
                    <fullName>ReinstatementPTO</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPTO</label>
                </value>
                <value>
                    <fullName>ReinstatementPlanReview</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPlanReview</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/classes/BaseValidator.cls
/**
* Name: BaseValidator
* Type: Class
* Description: Helps in validating por
* Date:        Developer/Company                 	Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 06/1/2018   Akosa Okwudiafor/Deloitte           Initial Creation
**/
public virtual class BaseValidator {
    
    protected ValidationError e = new ValidationError();
    /**
* enum to list the valid SObject Types
*/
    public enum ApplicationObjectType {LICENSE, RENEWAL, REINSTATEMENT,PERMIT, SERVICEREQUEST}
    
    
    /***************************************************************************************************
* @Description : Decide which Validator to instantiate based on the record type and the objType can be a License, Renewal, Reinstatement or Endorsement
* @Param       : ApplicationObjectType objType, String recordTypeName
* @Return      : NA
****************************************************************************************************/
    public static BaseValidator createValidator(ApplicationObjectType objType, String recordTypeName)
    {
        //The contact, account and address valiations are enterprise level and are determined based on the Pages, Sections.. config.
        //Therefore, there are common validators for these validations. Only create a record type specific validator if any additional
        //validation is to be added. Otherwise, return the empty default validator.
        System.debug('Basevalidator  '+recordTypeName);
        if ( ApplicationObjectType.LICENSE == objType && recordTypeName == Label.RT_Delegated_Agent_Record_Type) {
            return new ValidatorDAGeneralLicensing();
        }
        else if ( ApplicationObjectType.LICENSE == objType && recordTypeName == Label.RT_Manufactured_Homes_Record_Type) {
            return new ManufacturedHomesValidator();
        }
        else if ( ApplicationObjectType.PERMIT == objType && recordTypeName == Label.RT_Permit) {
            return new ManufacturedHomesCommunityValidator();
        }
        else if ( ApplicationObjectType.PERMIT == objType && recordTypeName == Label.RT_POWTS_Plan_Review) {
            return new POWTSGeneralValidator();
        }else if ( ApplicationObjectType.RENEWAL == objType && recordTypeName ==Label.RT_Universal_Default_Renewal_Reinstatement) {
            return new DefaultRenewalLicensing();
        }
        else{
            return new DefaultValidator();
        }

    }
    
    
    
    
    /***************************************************************************************************
* @Description : Method to validate Contact
* @Param       : ApplicationObjectType objType, SObject newRecord
* @Return      : NA
****************************************************************************************************/
    public void validateContact(ApplicationObjectType objType, SObject newRecord) {
        if(ApplicationObjectType.LICENSE == objType) {
            MUSW__License2__c l = (MUSW__License2__c)newRecord;
            e = ContactValidator.validate(e, l.MUSW__Applicant__c, l.Credential_Type__c, l.Credential__c, Label.API_License_Field);
        }
        else if(ApplicationObjectType.PERMIT == objType) {
            MUSW__Permit2__c p= (MUSW__Permit2__c)newRecord;
            e = ContactValidator.validate(e, p.MUSW__Applicant__c, p.Program_Area__c, p.Permit_Type__c, Label.Api_Permitfield);
        }
        else {
            Renewal_Application__c r = (Renewal_Application__c)newRecord;
            String appType = '';
            String licType = '';
            String grouping='';
            if(r.Renewal_Reinstatement_Type__c == Label.RNT_Renewal&&r.License__c!=null){
                licType = r.Credential__c;
                appType = Label.Api_LicenseRenewalfield;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c == Label.RNT_Reinstatement){
                appType = Label.Api_Reinstatementfield;
                licType = r.Credential__c;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c == Label.RNT_RenewalPTO&&r.Permit__c!=null ){
                appType = Label.Api_PermitRenewalfield;
                licType = r.Permit_Type__c;
                grouping= r.Program_Area__c;
            }
            
            e = ContactValidator.validate(e, r.Applicant__c, grouping, licType, appType);
        }
        
        System.debug('===>Value of e: ' + e);
    }
    
    
    
    /***************************************************************************************************
* @Description : Method to validate Account
* @Param       : ApplicationObjectType objType, SObject newRecord
* @Return      : NA
****************************************************************************************************/
    public void validateAccount(ApplicationObjectType objType, SObject newRecord) {
        if(ApplicationObjectType.LICENSE == objType) {
            MUSW__License2__c l = (MUSW__License2__c)newRecord;
            e = AccountValidator.validate(e, l.MUSW__Primary_Licensee__c, l.Credential_Type__c, l.Credential__c, Label.API_License_Field);
        }
        else if(ApplicationObjectType.PERMIT == objType) {
            MUSW__Permit2__c p = (MUSW__Permit2__c)newRecord;
            e = AccountValidator.validate(e, p.MUSW__Account__c, p.Program_Area__c, p.Permit_Type__c, Label.Api_Permitfield);
        }
        else {
            Renewal_Application__c r = (Renewal_Application__c)newRecord;            
            String appType = '';
            String licType = '';
            String grouping='';
            if(r.Renewal_Reinstatement_Type__c == Label.RNT_Renewal&&r.License__c!=null){
                appType = Label.Api_LicenseRenewalfield;
                licType = r.Credential__c;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c == Label.RNT_Reinstatement){
                appType = Label.Api_Reinstatementfield;
                licType = r.Credential__c;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c == Label.RNT_RenewalPTO&&r.Permit__c!=null){
                appType = Label.Api_PermitRenewalfield;
                licType = r.Permit_Type__c;
                grouping= r.Program_Area__c;
            }
            
            e = AccountValidator.validate(e, r.Licensee__c,grouping,licType, appType);
        }
    }
    
    /***************************************************************************************************
* @Description : Method to validate address
* @Param       : ApplicationObjectType objType, SObject newRecord
* @Return      : NA
****************************************************************************************************/    
    public void validateAddress(ApplicationObjectType objType, SObject newRecord) {
        System.debug('validateAddress ');
        if(ApplicationObjectType.LICENSE == objType) {
            MUSW__License2__c l = (MUSW__License2__c)newRecord;
            e = AddressValidator.validate(e,l.Credential_Type__c, l.Credential__c, Label.API_License_Field,l.Id);
        }
        else if(ApplicationObjectType.PERMIT == objType) {
            System.debug(' validateAddress');
            MUSW__Permit2__c q = (MUSW__Permit2__c)newRecord;
            e = AddressValidator.validate(e,q.Program_Area__c, q.Permit_Type__c, Label.Api_Permitfield,q.Id);
        }
        else {
            Renewal_Application__c r = (Renewal_Application__c)newRecord;  
            String licType = '';
            String grouping='';
            String appType = '';
            if(r.Renewal_Reinstatement_Type__c == Label.RNT_Renewal&&r.License__c!=null){
                licType = r.Credential__c;
                appType = Label.Api_LicenseRenewalfield;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c == Label.RNT_Reinstatement){
                licType = r.Credential__c;
                appType = Label.Api_Reinstatementfield;
                grouping=r.Credential_Type__c;
            }else if(r.Renewal_Reinstatement_Type__c== Label.RNT_RenewalPTO &&r.Permit__c!=null ){
                appType = Label.Api_PermitRenewalfield;
                licType = r.Permit_Type__c;
                grouping= r.Program_Area__c;
            }            
            String licenseId;
            if (r.License__c != null) {
                licenseId = r.License__c;
            }   
            else if(r.Permit__c!=null){
                licenseId=  r.Permit__c;
            }             
            e = AddressValidator.validate(e, grouping, licType, appType, licenseId);
        }
    }
    
    public void validateServiceRequest(ApplicationObjectType objType, SObject newRecord) {
        Decimal secNum = (Decimal)newRecord.get(Label.Api_SectionNumber);
        System.debug('===> section number:' + secNum);
        
        if ( secNum == 99 ) {
            System.debug('===> section number is 99, ... validating all sections');
            if(ApplicationObjectType.SERVICEREQUEST == objType) {
                MUSW__Application2__c sr = (MUSW__Application2__c)newRecord;
                e = ServiceRequestValidator.validate(e, sr);
                
                // now add the errors ( if there were any )
                if ( e.hasErrors() ) {
                    System.debug('***** GOT ERRORS *****');
                    System.debug(e.errorMap);
                    newRecord.addError( e.serializeErrors() );
                }
            }
            System.debug('===>Value of e: ' + e);
        }
    }
    
    /***************************************************************************************************
* @Description : Use Polymorphism to avoid "poluting" the validation with if statements.  We still need to create the specif classes that will perform the validation but that logic
is in one central place - here. Based on the value of the section, instantiate a subclass of the Section class to be used as a parameter to the validate method
* @Param       : SObject newRecord, SObject oldRecord
* @Return      : NA
****************************************************************************************************/
    public void validate(SObject newRecord, SObject oldRecord) {   
        Decimal secNum = (Decimal)newRecord.get(Label.Api_SectionNumber);
        System.debug('===> section number:' + secNum);
        // DO_NOT_VALIDATE VALIDATE_SECTION VALIDATE_FOR_REVIEW VALIDATION_COMPLETE VALIDATION_INCOMPLETE
        // if ( 'DO_NOT_VALIDATE' == l.ValidationStatus__c ) {
        
        if ( secNum == 99 ) {
            System.debug('===> section number is 99, ... validating all sections');
            validate( new AllSections(), newRecord, oldRecord);
            
            // now add the errors ( if there were any )
            if ( e.hasErrors() ) {
                System.debug('***** GOT ERRORS *****');
                System.debug(e.errorMap);
                newRecord.addError( e.serializeErrors() );
            }
        } 
    }
    
    protected virtual void validate(AllSections sec, SObject newRecord, SObject oldRecord) { } 
    /***************************************************************************************************
* @Description : Method to run the validations done through configuration on the FieldsObj 
* @Param       : Map<Id,MUSW__License2__c> newLicenseMap
* @Return      : NA
****************************************************************************************************/
    
    public void runConfigurableValidations() {
        
    }
    
    /**
* Utility Section (and subclasses) to allow for polymorphic validation implementation
*/
    public interface Section{}
    public class AllSections    implements Section{}
    
    /**
* this gives us the ability to validate by different section - if needed in the future
*/
    public class SectionOne     implements Section{}
}