src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Security_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Security Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_4_Digits_of_SSN__c</fullName>
        <externalId>true</externalId>
        <label>Last 4 Digits of SSN</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <externalId>true</externalId>
        <label>Security Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <label>Security Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DOL_License_Linking_Test.cls
@isTest
public class DOL_License_Linking_Test {
    @isTest
    public static void getAccountListTest1(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        a.Security_Code__c = 'abc123';
        update a;
        DOL_License_Linking.getAccountList('abc123');
    }
    
    @isTest
    public static void getAccountListTest2(){
        DOL_License_Linking.getAccountList('abc123');
    }
    
    @isTest
    public static void getAccountListTest3(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        a.Security_Code__c = 'abc123';
        update a;
        DOL_License_Linking.createAccountContact(a.Id);
    }
    
    @isTest
    public static void testVoidMethods(){
        DOL_License_Linking.getLicenseType();
        DOL_License_Linking.getProgramPicklist();
        DOL_License_Linking.sendActivationCodeEmail('abc','test@mailinator.com');
        DOL_License_Linking.searchLicenseNumber('Architects','Lic1234568');
        
    }
    
    @isTest
    public static void testGetLicenseList1(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecTypeId,a.Id); 
        con.Security_Code__c = 'abc123';
        update con;
            Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.MUSW__Applicant__c = con.id;
        update lic1;
        
        DOL_License_Linking.getLicenseList('abc123','test','Test Contact','123',lic1.Name,'Architect', System.today());
    }
    
    @isTest
    public static void testGetLicenseList2(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecTypeId,a.Id); 
        con.Last_4_Digits_of_SSN__c = '8138';
        con.FirstName ='test';
        con.Birthdate = Date.newInstance(1990, 12, 9);
        update con;
        
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.MUSW__Applicant__c = con.id;
        update lic1;
        DOL_License_Linking.getLicenseList('','test','Test Contact','8138',lic1.Name,'Architect', System.today());
    }
    
    @isTest
    public static void testGetLicenseList3(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecTypeId,a.Id); 
        con.Last_4_Digits_of_SSN__c = '8138';
        con.FirstName ='test';
        con.Birthdate = Date.newInstance(1990, 12, 9);
        update con;
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.MUSW__Applicant__c = con.id;
        update lic1;
        DOL_License_Linking.getLicenseList('','test','Test Contact','8138','','', System.today());
    }
    
    @isTest
    public static void testCreateReviewRecord(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        DOL_License_Linking.createReviewRecord('Test Reveiw', lic1.Id, 'abc@mailinator.com');
    }
    
    @isTest
    public static void testUpdateLicenseContact(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id conRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact con = DOL_TestDataFactory.createContact(conRecTypeId,a.Id); 
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.MUSW__Applicant__c = con.id;
        update lic1;
        DOL_License_Linking.createReviewRecord('Test Reveiw', lic1.Id, 'abc@mailinator.com');
        Account acc = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Contact cont = DOL_TestDataFactory.createContactWithLastName(conRecTypeId,acc.Id,'dummyLN'); 
        DOL_License_Linking.updateLicenseContact(cont.Id);
        DOL_License_Linking.searchLicenseNumber('Architects',lic1.Name);
    }
    
}