src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Primary_Contact__c</fullName>
        <description>Primary Contact Email</description>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Account_Email__c</fullName>
        <description>MUSW__Primary_Licensee__r.Email__c</description>
        <formula>MUSW__Primary_Licensee__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_License__c</fullName>
        <description>Business License</description>
        <formula>OR(ISPICKVAL( Credential__c , &apos;Dwelling Contractor&apos;), 
ISPICKVAL( Credential__c , &apos;Dwelling Contractor Restricted&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Manufacturer&apos;),
ISPICKVAL(Credential__c , &apos;Manufactured Homes Dealer&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Boiler&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Commercial Building&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Elevator&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Fire Suppression/Alarm Systems&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Other&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - Plumbing&apos;),
ISPICKVAL(Credential__c , &apos;Delegated Agent - POWTS&apos;),
ISPICKVAL(Credential__c , &apos;Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;UDC Inspection Agency&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment&apos;),
ISPICKVAL(Credential__c , &apos;Prearrangement Funeral Services&apos;),
ISPICKVAL(Credential__c , &apos;Funeral Establishment Branch&apos;),
ISPICKVAL(Credential__c , &apos;Certificate of Removal Registration&apos;),
ISPICKVAL(Credential__c , &apos;Crematory&apos;),
ISPICKVAL(Credential__c , &apos;Cremated Remains Disposition Permit&apos;),
ISPICKVAL(Credential__c , &apos;Cemetery&apos;),
ISPICKVAL(Credential__c , &apos;Camping Resort Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Course&apos;),
ISPICKVAL(Credential__c , &apos;Appraiser Provider&apos;),
ISPICKVAL(Credential__c , &apos;Timeshare Company&apos;),
ISPICKVAL(Credential__c , &apos;Appraisal Management Company&apos;)


)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Renewal_Eligible__c</fullName>
        <description>Formula to determine renewal eligibility</description>
        <formula>IF(TODAY() &gt;= Renewal_Eligible_Start_Date__c  &amp;&amp; Is_Reinstatement_Eligible__c==False , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Notification_Attempt__c</fullName>
        <description>Next Notification Attempt</description>
        <label>Next Notification Attempt</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Notification_Date__c</fullName>
        <description>Next Notification Date</description>
        <label>Next Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>Sub-status is a dependent picklist driven off of Status.</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MUSW__Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Sub_Status</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sub_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Additional Information Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <description>Sub-status is a dependent picklist driven off of Status.</description>
    <masterLabel>Sub Status</masterLabel>
</GlobalValueSet>

src/classes/CredentialNotificationScheduler.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Name                : CredentialNotificationScheduler
** Description         : 
** Version             : 1.0
** Built By            :  
**-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Modification Log:
**--------------------------
** Developer                         Date                    Version                      Description
**-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
** Akosa Okwudiafor                   8/17/2018
**
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
**
*************************************************************************************************************/ 
global with sharing class CredentialNotificationScheduler implements Schedulable {
    global void execute(SchedulableContext ctx) {
        String query = 'Select Id, Name, MUSW__Applicant__r.FirstName, MUSW__Applicant__r.LastName, MUSW__Applicant__r.Name, MUSW__Primary_Licensee__r.Email_Primary_Contact__c, MUSW__Status__c, ' + 
            'MUSW__Expiration_Date__c, Next_Notification_Date__c, Next_Notification_Attempt__c, Business_License__c, OwnerId,Credential__c, ' + 
            'Is_Renewal_Eligible__c, Account_Email__c,Sub_Status__c ' + 
            ' From MUSW__License2__c where Next_Notification_Date__c = TODAY '+
            ' and (MUSW__Status__c = \'Active\'' +
            ' or (MUSW__Status__c = \'Inactive\' AND Sub_Status__c = \'Expired\'))' ;
        try{
            CredentialNotificationBatch batch = new CredentialNotificationBatch(query);            
            Integer BatchSize = Email_Utility.getBatchSize();
            Database.executeBatch(batch, BatchSize);
        }
        catch(Exception e){
            System.debug('error occured '+e);         
        }
    }
}