src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Licensee Email</description>
        <formula>MUSW__Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Licensee Email</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Late_Renewal_Eligible_End_Date__c</fullName>
        <description>Date until which a credential is eligible for late renewal - based on expiration date and logic from Renewal_Reinstatement_Eligibility__c</description>
        <inlineHelpText>Date until which a credential is eligible for late renewal - based on expiration date and logic from Renewal_Reinstatement_Eligibility__c</inlineHelpText>
        <label>Late Renewal Eligible End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Eligible_Start_Date__c</fullName>
        <description>Date when a credential becomes renewal eligible - it is based on expiration date and logic from Global Table- Renewal_Reinstatement_Eligibility__c</description>
        <label>Renewal Eligible Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Grace_Period_End_Date__c</fullName>
        <label>Renewal Grace Period End Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Dol_Batch_UpdateLicenseStatusTest.cls
@istest
public class Dol_Batch_UpdateLicenseStatusTest{
    @isTest static void test_method_one(){
        Id businessAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account acc= DOL_TestDataFactory.createAccount(businessAccount);
        acc.Email__c = 'test@mailinator.com';
        update acc;
        
        Id businessLicenseType = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(businessLicenseType, acc.Id, 'Architects', 'Architect', 'General Application');
        lic.MUSW__Expiration_Date__c = System.today();
        lic.MUSW__Status__c= 'Active';
        update lic;
        system.debug('lic'+lic);
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(businessLicenseType, acc.Id, 'Architects', 'Architect', 'General Application');
        lic1.MUSW__Expiration_Date__c= System.today();
        lic1.Late_Renewal_Eligible_End_Date__c = System.today();
		lic1.MUSW__Status__c= 'Expired';
        update lic1;
        
        test.startTest();
        list<MUSW__License2__c> lstlic =[SELECT ID,Name,MUSW__Expiration_Date__c,Late_Renewal_Eligible_End_Date__c,Renewal_Grace_Period_End_Date__c,Renewal_Eligible_Start_Date__c,MUSW__Status__c from MUSW__License2__c WHERE MUSW__Expiration_Date__c <= Today AND  MUSW__Status__c   in ('Active','Expired')];
        system.debug('lstlic'+lstlic);
        Dol_Batch_UpdateLicenseStatus sh1 = new Dol_Batch_UpdateLicenseStatus();

        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, sh1); 
        test.stopTest();
    }
}