src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Security Code</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Security_Code__c</fullName>
        <externalId>true</externalId>
        <label>Security Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <label>UBI #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>Account_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for SoS Integration</description>
        <inlineHelpText>Used for SoS Integration</inlineHelpText>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for SoS Integration</description>
        <inlineHelpText>Used for SoS Integration</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>Used for SoS Integration</description>
        <inlineHelpText>Used for SoS Integration</inlineHelpText>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Administrator</fullName>
                </value>
				<value>
                    <fullName>Owner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending Add</fullName>
                    <isActive>false</isActive>
                    <label>Pending Add</label>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                    <isActive>false</isActive>
                    <label>Pending Remove</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Used for SoS Integration</description>
        <inlineHelpText>Used for SoS Integration</inlineHelpText>
        <label>Title</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isAdminContact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAdminContact</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Licensee Email</description>
        <formula>MUSW__Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Licensee Email</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Code__c</fullName>
        <label>Security Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <formula>Ultimate_Parent_Account__r.UBI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBI Number</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <inlineHelpText>Person applying for license on behalf of licensee as indicated in Subject</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License DO NOT USE</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses DO NOT USE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Account_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Contact</label>
        <referenceTo>MUSW__Account_Contact__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person who is making the request.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/DOL_License_Linking.cls
/*
* classname 	:  DOL_License_Linking
* @description 	:  This class is used to link all  the data from  one contact to  another contact
* @author 		:  Mangesh
* @date 		:  07/11/2019
* MODIFICATION LOG:
* DEVELOPER                     DATE                               DESCRIPTION
* ---------------------------------------------------------------------------------------------
* Mangesh	      07/11/2019	     This class is created as part of user stories 2385 and 2386
**/

public without Sharing class DOL_License_Linking {
/**
* method 		: getAccountList
* @description 	: Get list of accounts basis security code
* @author 		: MAngesh
* @param <SecurityCode> <Security code on account object>
* @return <Returns list of account> 
* */
    @AuraEnabled
    public static List<Account> getAccountList(String securityCode) {
        DOL_AppUtility.isAuthenticatedUser() ;
        List<Account> lstAcc = new List<Account>();
        
        for(Account accCon  : [select id ,Name, UBI_Number__c,ShippingAddress from Account where Security_Code__c =:securityCode ]) {
            lstAcc.add(accCon);
        }
        if(!lstAcc.isEmpty()){
           return lstAcc;  
        } else {
          return lstAcc;
        }
    }
/**
* method 		: createAccountContact
* @description 	: Create account contact association
* @author 		: Mangesh
* @param <accID> <AccountID to  create account contact association
* @return <Success/Failure message> 
* */
     @AuraEnabled
    public static String  createAccountContact(String accID) {
     //Boolean isInsert = Add_BusinessController.createAccountContactObject(accID);
         DOL_AppUtility.isAuthenticatedUser() ;
        MUSW__Account_Contact__c retRes ;
        String message = '';
        User currentUser = [SELECT Id,Name,firstname,lastname,ContactId,email from User Where ID = :UserInfo.getUserId() LIMIT 1];
        list<MUSW__Account_Contact__c> businessList = new list<MUSW__Account_Contact__c>([SELECT Id, MUSW__Contact__c, MUSW__Account__r.Name, MUSW__Account__r.BillingStreet, MUSW__Account__r.BillingCity, MUSW__Account__r.BillingState, MUSW__Account__r.BillingPostalCode, MUSW__Account__r.BillingCountry FROM MUSW__Account_Contact__c WHERE MUSW__Contact__c =: currentUser.ContactId AND MUSW__Account__c =: accID ]);
        list<MUSW__Account_Contact__c> lstac = new list<MUSW__Account_Contact__c>();
        try{
            if(businessList.size()==0){
                MUSW__Account_Contact__c ac = new MUSW__Account_Contact__c();
                ac.MUSW__Account__c = accID;
                ac.MUSW__Contact__c = currentUser.ContactId;
                ac.Status__c= 'Active' ;
                ac.isAdminContact__c = True;
                ac.Role__c = 'Administrator';
                ac.Account_Admin__c = true;
                ac.Email__c = currentUser.Email;
                ac.First_Name__c = currentUser.firstname;
                ac.Middle_Name__c = currentUser.firstname;
                ac.Last_Name__c = currentUser.lastName;
                ac.Email__c = currentUser.email;
                ac.Title__c = 'Administrator';
                lstac.add(ac);
                Utilityclass_withsharing.insertList(lstac);
                system.debug('ac234567'+ac);
                message = 'User linked with  account succeessfully!'; 
            } else {
                message = 'Account already  linked with  your contact';
            }
        } catch(Exception e){
            message = 'Error occurred please contact system admin!';  
            DOL_CreateErrorLog_Exception.addError(e,'DOL_License_Linking','createAccountContact');
        }
        return message;
    }
/**
* method 		: getLicenseList
* @description 	: Get license details of a contact
* @author 		: Mangesh
* @return <List of license> 
* */
    @AuraEnabled
    public static List<MUSW__License2__c> getLicenseList(String securityCode,String firstname,string lastname,string ssn, String licenseNumber, String licenseType, Date dob) {
        DOL_AppUtility.isAuthenticatedUser() ;
        List<MUSW__License2__c> lstlicense = new List<MUSW__License2__c>();
        system.debug('abcd123'+securityCode);
        if(securityCode != '') {
            system.debug('abcd'+securityCode);
            for(MUSW__License2__c accCon  : [select id ,MUSW__Applicant__r.Name,MUSW__Applicant__c,Name,Credential_Type__c,MUSW__Status__c,Email__c
                                             from MUSW__License2__c where MUSW__Applicant__r.Security_Code__c =:securityCode ]) {
                                                 // MUSW__License__c license = new MUSW__License__c(); 
                                                 lstlicense.add(accCon);                                              
                                             }
        } else if(licenseType != '' && licenseNumber != '') {
            for(MUSW__License2__c accCon  : [select id ,MUSW__Applicant__c,MUSW__Applicant__r.Name,Name,Credential_Type__c,MUSW__Status__c,Email__c
                                             from MUSW__License2__c 
                                             where Name =:licenseNumber and MUSW__Applicant__r.FirstName= :firstname
                                             and MUSW__Applicant__r.LastName= :lastname and MUSW__Applicant__r.Last_4_Digits_of_SSN__c =:ssn
                                             and Credential_Type__c =:licenseType and Date_of_Birth__c=: dob]) {
                                                 lstlicense.add(accCon);                                              
                                             }
        } else {            
            for(MUSW__License2__c accCon  : [select id ,MUSW__Applicant__c,MUSW__Applicant__r.Name,Name,Credential_Type__c,MUSW__Status__c,Email__c
                                             from MUSW__License2__c 
                                             where  MUSW__Applicant__r.FirstName= :firstname
                                             and MUSW__Applicant__r.LastName= :lastname and MUSW__Applicant__r.Last_4_Digits_of_SSN__c =:ssn
                                             and Date_of_Birth__c=: dob]) {
                                                 lstlicense.add(accCon);                                              
                                             }
            
        }

        if(!lstlicense.isEmpty()){
            return lstlicense;  
        } else {
            return lstlicense;
        }
    }
    /**
* method 		: updateLicenseContact
* @description 	: To move all the details from one account to  loggedin user account
* @author 		: Mangesh
* @param <contactId> <contactId> to move all the details from one account to  loggedin user account
* @return <Success/Failure message> 
* */
   @AuraEnabled    
    public static String updateLicenseContact(String contactId) {
        DOL_AppUtility.isAuthenticatedUser() ;
        string str = '';
        Boolean isSucccess = false;
        List<Request__c>  lstrequset = new List<Request__c>();
        List<MUSW__Account_Contact__c> lstAssociation = new List<MUSW__Account_Contact__c>();
        List<BGBK__Cart__c> lstCart = new List<BGBK__Cart__c>();
        List<MUSW__License2__c> lstlicense = new List<MUSW__License2__c>();
        List<Contact>  lstContacts =[select id, (select id,ownerId,Contact__c from Requests__r),(select id,ownerId,MUSW__Contact__c from MUSW__Account_Contacts__r),
                                  (select id,MUSW__Applicant__c,ownerId from  MUSW__License2s__r),(select id,ownerId,BGBK__Contact__c from  BGBK__Carts__r) 
                                   from  Contact where Id =:contactId LIMIT 1];

        if(!lstContacts.isEmpty()) {
            if(!lstContacts[0].Requests__r.isEmpty()){
               lstrequset.addAll(lstContacts[0].Requests__r); 
            }
            if(!lstContacts[0].MUSW__Account_Contacts__r.isEmpty()){
                lstAssociation.addAll(lstContacts[0].MUSW__Account_Contacts__r);
            }
            if(!lstContacts[0].MUSW__License2s__r.isEmpty()) {
               lstlicense.addAll(lstContacts[0].MUSW__License2s__r);
            }
            if(!lstContacts[0].BGBK__Carts__r.isEmpty()) {
               lstCart.addAll(lstContacts[0].BGBK__Carts__r);   
            }
        } 
        
        User currentUser = [SELECT Id,Name,firstname,lastname,ContactId,email from User Where ID = :UserInfo.getUserId() LIMIT 1];
        Id owner = currentUser.Id;
        Savepoint sp = Database.setSavepoint();
        if(!lstlicense.isEmpty()){
            for(MUSW__License2__c license : lstlicense){
                license.MUSW__Applicant__c = currentUser.ContactId;
                license.ownerId = owner;
            }
            try{
              Database.update(lstlicense);
              //Utilityclass_withsharing.updateList(lstlicense);
              isSucccess = true;
            } catch (Exception ex) {
                isSucccess = false;
                DOL_CreateErrorLog_Exception.addError(ex,'DOL_License_Linking','updateLicenseContact');
                Database.rollback(sp);

            }
        } 
       if(!lstrequset.isEmpty()){
            for(Request__c request : lstrequset){
                request.Contact__c = currentUser.ContactId;
                request.ownerId = owner;
            }
            try {
                Database.update(lstrequset);
              //  Utilityclass_withsharing.updateList(lstrequset);
                isSucccess = true;        
            } catch (Exception ex) {
                isSucccess = false;
                DOL_CreateErrorLog_Exception.addError(ex,'DOL_License_Linking','updateLicenseContact');
                Database.rollback(sp);
            }
        } 
        if(!lstAssociation.isEmpty()){
            for(MUSW__Account_Contact__c accCon : lstAssociation){
                accCon.MUSW__Contact__c = currentUser.ContactId;
                accCon.ownerId = owner;
            }
            try {
              //  Utilityclass_withsharing.updateList(lstAssociation);
               Database.update(lstAssociation);
                isSucccess = true;        
            } catch (Exception ex) {
                isSucccess = false;
                DOL_CreateErrorLog_Exception.addError(ex,'DOL_License_Linking','updateLicenseContact');
                Database.rollback(sp);
            }
        } 
        if(!lstCart.isEmpty()){
            for(BGBK__Cart__c cart : lstCart){
                cart.BGBK__Contact__c = currentUser.ContactId;
                cart.ownerId = owner;
            }
            try {
                Database.update(lstCart);
              //   Utilityclass_withsharing.updateList(lstCart);
                 isSucccess = true;        
            } catch (Exception ex) {
                isSucccess = false;
                DOL_CreateErrorLog_Exception.addError(ex,'DOL_License_Linking','updateLicenseContact');
                Database.rollback(sp);
            }
        }        
        if(isSucccess) {
            str = 'Linked successfully';
        } else  {
            str= 'Some error occured ! Please contact system admin';
        }
        return  str;
    }

    @AuraEnabled
    public static List<String> getLicenseType() {
      DOL_AppUtility.isAuthenticatedUser() ;
      List<String> options = new List<String>();
        if(!Polaris_UtilityClass.getPicklist().isEmpty()) {
            options.addAll(Polaris_UtilityClass.getPicklist());
        }
        return options;
        
    }
    @AuraEnabled
    public static string sendActivationEmail(){
        DOL_AppUtility.isAuthenticatedUser() ;
        User currentUser = [SELECT Id,Name,firstname,lastname,ContactId,email 
                            from User Where ID = :UserInfo.getUserId() LIMIT 1];
        List<Contact> currentContact = [Select Email,Id,Last_4_Digits_of_SSN__c,FirstName,LastName,Birthdate 
                                        from Contact where ID =: currentUser.ContactId lIMIT 1];
        string message='';
        String maskedEmail ='';

        if(!currentContact.isEmpty()) {
            List<String> email= new List<String>();
            email.add(currentContact[0].Email);
            maskedEmail = email[0].replaceAll('(^[^@]{3}|(?!^)\\G)[^@]', '$1*');
        }
        message = 'Activation code will be emailed to' + ' ' + maskedEmail;
        return message;
    } 
    @AuraEnabled
    public static string sendActivationCodeEmail(){
        DOL_AppUtility.isAuthenticatedUser() ;
        User currentUser = [SELECT Id,Name,firstname,lastname,ContactId,email 
                            from User Where ID = :UserInfo.getUserId() LIMIT 1];
        List<Contact> currentContact = [Select Email,Id,Last_4_Digits_of_SSN__c,FirstName,LastName,Birthdate 
                                        from Contact where ID =: currentUser.ContactId lIMIT 1];
        OrgWideEmailAddress orgWideAddress = [select Id, DisplayName, Address from OrgWideEmailAddress where DisplayName = :label.Str_Org_Wide_Address];
          List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        String message='';
        List<Contact> lstContact = new List<Contact>();
        List<String> email= new List<String>();
        if(!currentContact.isEmpty()) {
            email.add(currentContact[0].Email);
             lstContact = [SELECT Email,Id,Name,Security_Code__c 
                                        from contact where Id !=: currentUser.ContactId
                                        AND FirstName =:currentContact[0].FirstName 
                                       AND LastName =: currentContact[0].LastName AND Last_4_Digits_of_SSN__c =:currentContact[0].Last_4_Digits_of_SSN__c Limit 1];
            
            
        } else {
            message =  Label.System_Admin_Contact_Message;
            return message;
        }
        if(!lstContact.isEmpty() && orgWideAddress != null && !email.isEmpty()) {
            for(Contact con : lstContact) {

                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setSubject('Activation code for professional linking license');
                mail.setHtmlBody('ActivationCode : ' +con.Security_Code__c);
                mail.setToAddresses(email);
                mail.setOrgWideEmailAddressId(orgWideAddress.Id);
                mails.add(mail);
            }

        } else {
            message= Label.System_Admin_Contact_Message;
            return message;
        }
        
        if(!mails.isEmpty()){
            Messaging.sendEmail(mails);
            string maskedEmail = email[0].replaceAll('(^[^@]{3}|(?!^)\\G)[^@]', '$1*');
            message = Label.Activation_Code_Sent_Message + ' ' + maskedEmail;
        }
        
        return message;
    }
}