src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <inlineHelpText>The Unified Business Identifier (UBI) is issued by the Business Licensing Service (BLS) of the Department of Revenue (DOR). State or local government agencies in Washington that regulate businesses use the UBI to identify a business.</inlineHelpText>
        <label>UBI</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <description>Business Account</description>
        <label>Business Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <label>UBI #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DOL_Integration_Batch_Input__c.object
<CustomObject>
    <description>This is used by Integration batches for DOL system. This table will store the json input of DOL system.</description>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Input_Type__c</fullName>
        <label>Input Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REMITTANCE</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>DOR</fullName>
                </value>
				<value>
                    <fullName>RTPC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Input__c</fullName>
        <label>Input</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FAILED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFUL</fullName>
                </value>
                <value>
                    <fullName>UNPROCESSED</fullName>
                    <default>true</default>
                    <label>UNPROCESSED</label>
                </value>
                <value>
                    <fullName>CONTENT VERSION CREATED</fullName>
                </value>
                <value>
                    <fullName>DATA LOADING COMPLETED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DOL Integration Batch Input</label>
    <nameField>
        <label>DOL Integration Batch Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOL Integration Batch Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associates</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associations</relationshipLabel>
        <relationshipName>Account_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending Add</fullName>
                    <isActive>false</isActive>
                    <label>Pending Add</label>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                    <isActive>false</isActive>
                    <label>Pending Remove</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>UBI_Number__c</fullName>
        <formula>Ultimate_Parent_Account__r.UBI_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UBI Number</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DOL_Process_DOR_Data_Batch_Test.cls
@IsTest
public class DOL_Process_DOR_Data_Batch_Test {
	
    @IsTest
    public static void TestDORBatch(){
        String accUBI = DOL_AppConstants.NULL_EMPTY_STRING+'607241888';
        Id accRecId = SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Account').getRecordTypeId();
        Account acc = DOL_TestDataFactory.createAccount(accRecId);
        acc.UBI_Number__c = accUBI;
        update acc;
        
        Id conRecId = SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Contact').getRecordTypeId();
        Contact c = DOL_TestDataFactory.createContact(conRecId, acc.Id);
        
        Contact cq = [select AccountId from Contact where Id=:c.Id];

        MUSW__Account_Contact__c accCon = new MUSW__Account_Contact__c(MUSW__Account__c=acc.Id,	
                                                                       MUSW__Contact__c=c.Id);
        insert accCon;
        
        Id businessLicenseType = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(businessLicenseType, 
                                                                  acc.Id, 
                                                                  'Architects', 
                                                                  'Architect', 
                                                                  'General Application');
        // Input with existing license
        DOL_DOR_Input rec = TestUtility.getDolDorInput(lic.Id,accUBI);
        DOL_Integration_Batch_Input__c tempBatchInput = new DOL_Integration_Batch_Input__c();
        tempBatchInput.File_Name__c = rec.fileName;
        tempBatchInput.Input__c = JSON.serialize(rec);
        tempBatchInput.Input_Type__c = 'DOR';
        tempBatchInput.Status__c = 'UNPROCESSED';
        insert tempBatchInput;
        
        // Input with new license
        DOL_DOR_Input rec1 = TestUtility.getDolDorInput(DOL_AppConstants.NULL_EMPTY_STRING,accUBI);
        DOL_Integration_Batch_Input__c tempBatchInput1 = new DOL_Integration_Batch_Input__c();
        tempBatchInput1.File_Name__c = rec.fileName;
        tempBatchInput1.Input__c = JSON.serialize(rec1);
        tempBatchInput1.Input_Type__c = 'DOR';
        tempBatchInput1.Status__c = 'UNPROCESSED';
        insert tempBatchInput1;
        
        // Input with incorrect data
        DOL_DOR_Input rec2 = TestUtility.getDolDorInput(DOL_AppConstants.NULL_EMPTY_STRING,accUBI);
        rec2.dorEntityName = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dorBusinessName = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dolProfCode = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dorLicenseStatus = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dorLicenseUBI = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dorLicenseBusID = DOL_AppConstants.NULL_EMPTY_STRING;
        rec2.dorLicenseLocID = DOL_AppConstants.NULL_EMPTY_STRING;
        
        DOL_Integration_Batch_Input__c tempBatchInput2 = new DOL_Integration_Batch_Input__c();
        tempBatchInput2.File_Name__c = rec2.fileName;
        tempBatchInput2.Input__c = JSON.serialize(rec2);
        tempBatchInput2.Input_Type__c = 'DOR';
        tempBatchInput2.Status__c = 'UNPROCESSED';
        insert tempBatchInput2;
        
        test.startTest();
        	Test.setMock(HttpCalloutMock.class, new DOL_MockHttpResponse());
    	    DOL_Process_DOR_Data_Batch batchObj = new DOL_Process_DOR_Data_Batch();
		    id batchJob = database.executeBatch(batchObj);
    	test.stopTest();
    }
}