src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Applicant/Licensee Email</description>
        <formula>MUSW__Applicant__r.Email</formula>
        <inlineHelpText>Applicant/Licensee Email</inlineHelpText>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Late_Renewal_Eligible__c</fullName>
        <description>Formula to determine Late Renewal Eligibility</description>
        <formula>IF((TODAY()&gt;MUSW__Expiration_Date__c &amp;&amp; TODAY()&lt;= Late_Renewal_Eligible_End_Date__c &amp;&amp; (ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;) ||  ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Late Renewal&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Hold&apos;))), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Late Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Renewal_Eligible__c</fullName>
        <description>Formula to determine renewal eligibility</description>
        <formula>IF(TODAY() &gt;= Renewal_Eligible_Start_Date__c  &amp;&amp; Is_Reinstatement_Eligible__c==False , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
	<fields>
        <fullName>Print_Renewal_Letter__c</fullName>
        <label>Print Renewal Letter</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <description>This is the record type for Course Information</description>
        <label>Course</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/DOL_batchRenewalLetterUpdate.cls
global class DOL_batchRenewalLetterUpdate implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = DOL_AppConstants.NULL_EMPTY_STRING + 'SELECT id,MUSW__Primary_Licensee__r.Email__c,License_RecordType_Name__c,Print_Renewal_Letter__c,Credential_Type__c,MUSW__Applicant__r.Email FROM MUSW__License2__c where (MUSW__Status__c =\''+DOL_AppConstants.ACTIVE+'\' OR MUSW__Status__c =\''+DOL_AppConstants.INACTIVE+'\' OR MUSW__Status__c=\''+DOL_AppConstants.EXPIRED+'\' ) AND (Print_Renewal_Letter__c!=\''+DOL_AppConstants.COMPLETED+'\' OR Print_Renewal_Letter__c!=\''+DOL_AppConstants.YES+'\') AND (Is_Late_Renewal_Eligible__c= true OR Is_Renewal_Eligible__c=true  ) ';       
        system.debug('query :'+query );
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<MUSW__License2__c> scope) {
        DOL_AppUtility.runfromDolBatchUpdateLicenseStatus = true;
        system.debug('scope :'+scope);	
        for(MUSW__License2__c lic : scope) {            
            if(lic.License_RecordType_Name__c == DOL_AppConstants.INDIVIDUAL && (lic.MUSW__Applicant__r.Email == null || lic.MUSW__Applicant__r.Email == '' ))
            {        
                lic.Print_Renewal_Letter__c = DOL_AppConstants.YES;
            }
            else if((lic.License_RecordType_Name__c == DOL_AppConstants.BUSINESS || lic.License_RecordType_Name__c == DOL_AppConstants.COURSE) && (lic.MUSW__Primary_Licensee__r.Email__c == null || lic.MUSW__Primary_Licensee__r.Email__c == '' ) )
            {
                lic.Print_Renewal_Letter__c = DOL_AppConstants.YES;
            }            
        }        
         try{
            if(!scope.isEmpty()){
                Database.SaveResult[] srList = Database.update(scope, false);                         
                DOL_CreateErrorLog_Exception.logDataBaseSaveDetails(srList, 'DOL_batchRenewalLetterUpdate', 'execute');
            }
        }
        catch(Exception e){
            System.debug(e);
            DOL_CreateErrorLog_Exception.logApplicationError(e);
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}