src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DOR_Response_Date__c</fullName>
        <description>TVS Response Date</description>
        <label>DOR Response Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DOR_Response__c</fullName>
        <description>DOR Values for TVS Response -- for integration team</description>
        <label>DOR Response</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DOR_Response_Date__c</fullName>
        <description>TVS Response Date -- integration team</description>
        <label>DOR Response Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DOR_Response__c</fullName>
        <description>DOR Values for TVS Response -- integration team</description>
        <label>DOR Response</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether to disable triggers for a profile/user- specially useful during data loads</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <description>This is the record type for Course Information</description>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Permit_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/classes/TVSVerify_CC_Test.cls
@isTest
public class TVSVerify_CC_Test {

    @testSetup
    public static void setupTestData(){
        Global_Settings__c globalSetting = new Global_Settings__c(Name = UserInfo.getUsername(), Disable_Triggers__c = true);
        insert globalSetting;
        
        /*Creating test Account*/
        Account acc = new Account();
        acc = CreateTestDataUtility.createAccount();
        /*Inserting test Account*/
        insert acc;
        
        /*Creating test Contact*/
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        /*Inserting test Contact*/
        insert con;
        
        /*Creating test License*/
        Musw__License2__c license1 = CreateTestDataUtility.createLicense(acc.Id, con.Id);
        license1.Application_Type__c = 'Manufactured Homes'; 
        license1.Credential_type__c = 'Manufactured Homes Credential';
        license1.Credential__c = 'Manufactured Homes Installer';
        license1.Application_Method__c = 'Course Completion';
        insert license1;
        
        Musw__License2__c license2 = CreateTestDataUtility.createLicense(acc.Id, con.Id);
        license2.Application_Type__c = 'Trades Credential'; 
        license2.Credential_type__c = 'Dwelling Contractor';
        license2.Credential__c = 'Dwelling Contractor';
        license2.Application_Method__c = 'General Application';
        insert license2;
        
        Musw__Permit2__c permit1 = CreateTestDataUtility.createPermit(acc.Id, con.Id);
        permit1.Application_Type__c = 'Plan Review';
        permit1.Permit_Type__c = 'POWTS Petition for Variance'; 
        permit1.Program_Area__c = 'POWTS'; 
        permit1.MUSW__Status__c = 'Pending';
        insert permit1;
        
        Musw__Permit2__c permit2 = CreateTestDataUtility.createPermit(acc.Id, con.Id);
        permit2.Application_Type__c = 'Manufactured Homes Communities';
        permit2.Permit_Type__c = 'Manufactured Homes Community Permit'; 
        permit2.Program_Area__c = 'Manufactured Homes Communities'; 
        permit2.MUSW__Status__c = 'Pending';
        insert permit2;
        
        globalSetting.Disable_Triggers__c = false;
        update globalSetting;
    }
    
    @isTest
    public static void testTVSVerify01(){
        Test.startTest();
        PageReference pageRef = Page.TVSVerify;
        Test.setCurrentPage(pageRef);
        
        MUSW__License2__c lic = [Select Id, MUSW__Applicant__c From MUSW__License2__c where Credential__c = 'Manufactured Homes Installer' limit 1];
        
        //set board and lic type parameters
        ApexPages.currentPage().getParameters().put('id', lic.Id);
        
        Test.setMock(HttpCalloutMock.class, new TVSVerify_CC_Test_MockService());
        
        TVSVerify_CC con = new TVSVerify_CC();
      //  con.waitingForResult = true;
        con.verifyDetails();
      //  con.waitingForResult = false;
        Test.stopTest();
        
        Contact con1 = [Select Id, DOR_Response__c, DOR_Response_Date__c From Contact where Id = : lic.MUSW__Applicant__c limit 1];
        system.assert(con1.DOR_Response__c != null);
        system.assert(con1.DOR_Response_Date__c != null);
    }
    
    @isTest
    public static void testTVSVerify02(){
        Test.startTest();
        PageReference pageRef = Page.TVSVerify;
        Test.setCurrentPage(pageRef);
        
        MUSW__License2__c lic = [Select Id, MUSW__Primary_Licensee__c From MUSW__License2__c where Credential__c = 'Dwelling Contractor' limit 1];
        
        //set board and lic type parameters
        ApexPages.currentPage().getParameters().put('id', lic.Id);
        
        Test.setMock(HttpCalloutMock.class, new TVSVerify_CC_Test_MockService());
        
        TVSVerify_CC con = new TVSVerify_CC();
        con.verifyDetails();
        Test.stopTest();
        
        Account acc1 = [Select Id, DOR_Response__c, DOR_Response_Date__c From Account where Id = : lic.MUSW__Primary_Licensee__c limit 1];
        system.assert(acc1.DOR_Response__c != null);
        system.assert(acc1.DOR_Response_Date__c != null);
    }
    
    @isTest
    public static void testTVSVerify03(){
        Test.startTest();
        PageReference pageRef = Page.TVSVerify;
        Test.setCurrentPage(pageRef);
        
        MUSW__Permit2__c per = [Select Id, MUSW__Applicant__c From MUSW__Permit2__c where Permit_Type__c = 'POWTS Petition for Variance' limit 1];
        
        //set board and lic type parameters
        ApexPages.currentPage().getParameters().put('id', per.Id);
        
        Test.setMock(HttpCalloutMock.class, new TVSVerify_CC_Test_MockService());
        
        TVSVerify_CC con = new TVSVerify_CC();
        con.verifyDetails();
        Test.stopTest();
        
        Contact con1 = [Select Id, DOR_Response__c, DOR_Response_Date__c From Contact where Id = : per.MUSW__Applicant__c limit 1];
        system.assert(con1.DOR_Response__c != null);
        system.assert(con1.DOR_Response_Date__c != null);
    }
    
    @isTest
    public static void testTVSVerify04(){
        Test.startTest();
        PageReference pageRef = Page.TVSVerify;
        Test.setCurrentPage(pageRef);
        
        MUSW__Permit2__c per = [Select Id, MUSW__Account__c From MUSW__Permit2__c where Permit_Type__c = 'Manufactured Homes Community Permit' limit 1];
        
        //set board and lic type parameters
        ApexPages.currentPage().getParameters().put('id', per.Id);
        
        Test.setMock(HttpCalloutMock.class, new TVSVerify_CC_Test_MockService());
        
        TVSVerify_CC con = new TVSVerify_CC();
        con.verifyDetails();
        Test.stopTest();
        
        Account acc1 = [Select Id, DOR_Response__c, DOR_Response_Date__c From Account where Id = : per.MUSW__Account__c limit 1];
        system.assert(acc1.DOR_Response__c != null);
        system.assert(acc1.DOR_Response_Date__c != null);
    }
    
}