src/objects/Affiliation__c.object
<CustomObject>
    <description>Affiliation</description>
    <fields>
        <fullName>Permit_Plan_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit / Plan Review</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Affiliation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Affiliation</valueSetName>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFF- {0000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Type_of_Affiliation.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Primary Enforcement Contact</fullName>
        <default>true</default>
        <label>Primary Enforcement Contact</label>
    </customValue>
    <customValue>
        <fullName>Enforcement Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Designer</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Secured Party</fullName>
    </customValue>
    <description>Type of Affiliation</description>
    <masterLabel>Type of Affiliation</masterLabel>
</GlobalValueSet>

src/classes/OwnerDesigner.cls
public without sharing class OwnerDesigner {
    
    @RemoteAction
    public static List<Contact> getContacts(String searchstr){
        List<Contact> lstrsc = [SELECT Id, LastName, FirstName, Email FROM Contact  where Email  LIKE : searchstr  Order by Name ASC];
        return lstrsc;
    }
    
    @RemoteAction
    public static Database.UpsertResult upsertAffiliationRecords(Affiliation__c affiliation){
        Database.UpsertResult srList;
        try{
            if((affiliation.Type__c==Label.Str_Owner||affiliation.Type__c==Label.Str_Designer)&&affiliation.Id==null)
            {
                List<Affiliation__c> owneraffiliations= new  List<Affiliation__c>();
                List<Affiliation__c> designeraffiliations= new  List<Affiliation__c> ();
                List<Affiliation__c> affiliations= [Select id,Type__c from Affiliation__c where Permit_Plan_Review__c=:affiliation.Permit_Plan_Review__c and (Type__c=:Label.Str_Owner or  Type__c=:Label.Str_Designer)];
                for(Affiliation__c aff: affiliations)
                {
                    if(aff.Type__c==Label.Str_Owner)
                    {
                        owneraffiliations.add(aff);
                    }
                    else{
                        designeraffiliations.add(aff);
                    }
                }
                if(owneraffiliations.size()>=1&&affiliation.type__C==Label.Str_Owner)
                {
                    return null;
                }
                else  if(designeraffiliations.size()>=1&&affiliation.type__C==Label.Str_Designer){
                    return null;
                }
            }
            srList = Database.upsert(affiliation, false);
        }
        catch(Exception e){
            ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'OwnerDesigner', 'Upsert Records', 'upsertAffiliationRecords', 'OwnerDesigner', label.Str_HIGH);
        }
        return srList;
    }
}