src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The license with which this answer is related</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Completed_DateTime__c</fullName>
        <description>The date and time when review was completed.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>When Review was completed</inlineHelpText>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Review Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/classes/ReviewCompletionTimeComputation.cls
public class ReviewCompletionTimeComputation {
    
    public Decimal ReviewCompletionTimeComputation(MUSW__Review__c reviewRecord){
        Decimal completionDurationHours = -1.0;
        List<Holiday> holidays = [SELECT Id, Name, ActivityDate FROM Holiday];
        //system.debug(' User Time Zone ID = '+UserInfo.getTimeZone().getID());
        //system.debug(' User Time Zone display name = '+UserInfo.getTimeZone().getDisplayName());
        //system.debug(' User Time Zone display name = '+UserInfo.getTimeZone().getDisplayName());
        
        
                //         List<answer__C> tempcredList = [select id,  renewal_application__r.credential__C, renewal_application__r.license__r.Application_Method__c from answer__C where Id=:tempAns.Id];   
                /*List<MUSW__Review__c> review = [SELECT Id, Start_Date__c, MUSW__Completed_DateTime__c
        FROM MUSW__Review__c
        WHERE Id =:reviewId];*/
        
            Integer holidaysBetweenStartAndEndDate = 0;
            //system.debug(' converted trigger start date = '+ reviewRecord.Start_Date__c.format('yyyy-MM-dd HH:mm:ss', 'CST'));
            /*The date comes in timezone other than user's time zone- converting it to be in local timezone*/
        	DateTime startDateTime = reviewRecord.Start_Date__c;
            DateTime completedDateTime = reviewRecord.MUSW__Completed_DateTime__c;
            String stringStartDateTime = startDateTime.format('yyyy-MM-dd HH:mm:ss', 'CST');
        	String stringCompletedDateTime = completedDateTime.format('yyyy-MM-dd HH:mm:ss', 'CST');
        	Datetime localStartDateTime = Datetime.valueOfGmt(stringStartDateTime);
        	Datetime localCompletedDateTime = Datetime.valueOfGmt(stringCompletedDateTime);
        	Date startDate = date.newinstance(localStartDateTime.year(), localStartDateTime.month(), localStartDateTime.day());
            Date completedDate = date.newinstance(localCompletedDateTime.year(), localCompletedDateTime.month(), localCompletedDateTime.day());
            
        	//old approach where the time was manually being decreased by 5 hours to counter the time conversion
        	//DateTime startDateTime_updated = datetime.newinstance(startDateTime.year(), startDateTime.month(), startDateTime.day(), startDateTime.hour()-5, startDateTime.minute(), startDateTime.second());
            //DateTime completedDateTime_updated = datetime.newinstance(completedDateTime.year(), completedDateTime.month(), completedDateTime.day(), completedDateTime.hour()-5, completedDateTime.minute(), completedDateTime.second());
            
            //System.debug('startDateTime '+startDateTime);
            //System.debug('completedDateTime '+completedDateTime);
            //System.debug('localStartDateTime '+localStartDateTime);
            //System.debug('localCompletedDateTime '+localCompletedDateTime);
            //System.debug('startDate '+startDate);
            //System.debug('completedDate '+completedDate);
            
            
            for(Holiday holi: holidays){
                if(startDate < holi.ActivityDate && holi.ActivityDate < completedDate){
                    //System.debug(holi);
                    holidaysBetweenStartAndEndDate = holidaysBetweenStartAndEndDate + 1;
                }
            }
            
            //Integer numberOfWeekendDays = 0;
            Integer numberOfHolidays = 0;
            Boolean sameDay = startDate.isSameDay(completedDate);
            //System.debug('sameDay '+sameDay);
            if(sameDay){
                Decimal completionTime = ((localCompletedDateTime.getTime())/1000/60);
                Decimal startTime = ((localStartDateTime.getTime())/1000/60);
                completionDurationHours = ((completionTime - startTime)/60).setScale(3);
                //System.debug('completionDurationHours '+completionDurationHours);
            }else{
                Integer totalNumberOfDays = startDate.daysBetween(completedDate);
                //System.debug('totalNumberOfDays '+totalNumberOfDays);
                //System.debug('totalNumberOfHolidays '+holidaysBetweenStartAndEndDate);
                
                Integer referenceDays = (date.newInstance(1985,6,24)).daysBetween(startDate);
                
                Double numberOfWeekendDays = 0;
                //System.debug('referenceDays '+referenceDays);
                Integer a = math.mod(referenceDays,7);
                Integer b = math.mod(totalNumberOfDays,7);
                //System.debug('a '+a);
                //System.debug('b '+b);
                Switch on (math.mod(referenceDays,7)){
                    when 0 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 1{
                                numberOfWeekendDays = 0;
                            }when 2{
                                numberOfWeekendDays = 0;
                            }when 3{
                                numberOfWeekendDays = 0;
                            }when 4{
                                numberOfWeekendDays = 0;
                            }when 5{
                                numberOfWeekendDays = 1;
                            }when 6{
                                numberOfWeekendDays = 2;
                            }when else{
                                numberOfWeekendDays = 0;
                            }
                            
                        }
                        
                    } when 1 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 0{
                                numberOfWeekendDays = 0;
                            }when 1{
                                numberOfWeekendDays = 0;
                            }when 2{
                                numberOfWeekendDays = 0;
                            }when 3{
                                numberOfWeekendDays = 0;
                            }when 4{
                                numberOfWeekendDays = 0;
                            }when 5{
                                numberOfWeekendDays = 2;
                            }when else{
                                numberOfWeekendDays = 2;
                            }
                            
                        }
                        
                    }when 2 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 0{
                                numberOfWeekendDays = 0;
                            }when 1{
                                numberOfWeekendDays = 0;
                            }when 2{
                                numberOfWeekendDays = 0;
                            }when 3{
                                numberOfWeekendDays = 1;
                            }when else{
                                numberOfWeekendDays = 2;
                            }
                            
                        }
                        
                    }when 3 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 0{
                                numberOfWeekendDays = 0;
                            }when 1{
                                numberOfWeekendDays = 0;
                            }when 2{
                                numberOfWeekendDays = 1;
                            }when else{
                                numberOfWeekendDays = 2;
                            }
                            
                        }
                        
                    }when 4 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 0{
                                numberOfWeekendDays = 0;
                            }when 1{
                                numberOfWeekendDays = 1;
                            }when else{
                                numberOfWeekendDays = 2;
                            }
                            
                        }
                        
                    }when 5 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 0{
                                numberOfWeekendDays = 1;
                            }when else{
                                numberOfWeekendDays = 2;
                            }
                            
                        }
                        
                    }when 6 {
                        Switch on (math.mod(totalNumberOfDays, 7)){
                            when 5{
                                numberOfWeekendDays = 2;
                            }when else{
                                numberOfWeekendDays = 1;
                            }
                            
                        }
                        
                    }when else {
                        numberOfWeekendDays =     999;
                    }
                }
                
                numberOfWeekendDays = numberOfWeekendDays + (math.floor(( totalNumberOfDays )/7)*2);
                //System.debug('totalNumberOfweekend days '+numberOfWeekendDays);
                Double hoursWorkedOnOtherDays = (totalNumberOfDays - 1 - numberOfWeekendDays - holidaysBetweenStartAndEndDate)*9;
                 /*standard working hours are 7.30 am to 4.30 pm*/
                //Setting the standard start time to 7.30 am
                //Setting the standard end time to 4.30 pm
                //IMPORTANT:have considered the time conversion as well
                DateTime standardStartDateEndTime = datetime.newInstance(localStartDateTime.year(), 
                                                                         localStartDateTime.month(), 
                                                                         localStartDateTime.day(), 
                                                                         11, 30, 0);
                DateTime standardCompletedDateStartTime = datetime.newInstance(localCompletedDateTime.year(), 
                                                                               localCompletedDateTime.month(), 
                                                                               localCompletedDateTime.day(), 
                                                                               2, 30, 0);
                Decimal startDayHours = ((standardStartDateEndTime.getTime())/1000/60) - ((localStartDateTime.getTime())/1000/60);
                Decimal completedDayHours = ((localCompletedDateTime.getTime())/1000/60) - ((standardCompletedDateStartTime.getTime())/1000/60);
                completionDurationHours = (hoursWorkedOnOtherDays + ((startDayHours + completedDayHours)/60)).setScale(3);
                /*
                System.debug('startDayHours '+startDayHours/60);
                System.debug('completedDayHours '+completedDayHours/60);
                System.debug('hoursWorkedOnOtherDays '+hoursWorkedOnOtherDays);
                System.debug('completionDurationHours '+completionDurationHours);
                System.debug('standardStartDateEndTime '+standardStartDateEndTime);
                System.debug('startDateTime '+ ((startDateTime.getTime())/1000/60));
                System.debug('standardStartDateEndTime '+ ((standardStartDateEndTime.getTime())/1000/60));
                System.debug('standardCompletedDateStartTime '+ ((standardCompletedDateStartTime.getTime())/1000/60));
                System.debug('completedDateTime '+ ((completedDateTime.getTime())/1000/60)) ;
                System.debug('standardCompletedDateStartTime '+standardCompletedDateStartTime);
                System.debug('completionDurationHours '+completionDurationHours);
                System.debug('minutes to hours '+completionDurationHours/60);
                */
            }
        
        return completionDurationHours;
    }
    
}