src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the version of the question that was answered.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BGCK__Answer__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Physical address</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for License Parcel Record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of parcel record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Various credential types available under a functional area and division</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Question&apos;s status values if active or inactive</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>General_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type (To be Deleted)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Profession__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/General_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <description>Status values if active or inactive</description>
    <masterLabel>General Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <customValue>
        <fullName>Reschedule Exam</fullName>
    </customValue>
    <customValue>
        <fullName>CE Audit</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/classes/RequestTriggerHandler_Test.cls
@isTest
public class RequestTriggerHandler_Test {
    @isTest
    public static void testMethod1(){
        
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application_Type__c = 'Notary Public';
        lic1.Credential_Type__c = 'Notary Public';
        update lic1;
        Request__c req = DOL_TestDataFactory.createRequest(lic1.Id, 'Architects', 'Architect');
        Id quesRecTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('License Information').getRecordTypeId();
        Question__c ques = DOL_TestDataFactory.createQuestion(quesRecTypeId);
        
        Answer__c ans = DOL_TestDataFactory.createAnswer(lic1.Id,ques.Id);
        BGCK__Answer__c bgAns = new BGCK__Answer__c();
        bgAns.QuestionDOL__c = ques.Id;
        bgAns.Request__c = req.Id;
        insert bgAns;
        
             MUSW__Parcel__c parcl = new MUSW__Parcel__c();
        parcl.Request_Parcel__c = req.Id;
        insert parcl;
        
        MUSW__License_Parcel__c licParcl = new MUSW__License_Parcel__c();
        licParcl.MUSW__License2__c = lic1.Id;
        licParcl.Physical__c = true;
        licParcl.Status__c = 'Active';
        licParcl.MUSW__Parcel__c = parcl.Id;
        licParcl.Mailing__c = true;
        insert licParcl;
        
        req.Profession__c = 'Notary Public';
        req.License_Type__c = 'Notary Public';
        req.Status__c = 'Approved';
        req.Service_Request_Type__c = 'Update Physical Address';
        update req;
        
    }
    
    @isTest
    public static void testMethod2(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application_Type__c = 'Notary Public';
        lic1.Credential_Type__c = 'Notary Public';
        update lic1;
        Request__c req = DOL_TestDataFactory.createRequest(lic1.Id, 'Architects', 'Architect');
        Id quesRecTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('License Information').getRecordTypeId();
        Question__c ques = DOL_TestDataFactory.createQuestion(quesRecTypeId);
        
        Answer__c ans = DOL_TestDataFactory.createAnswer(lic1.Id,ques.Id);
        
        req.Profession__c = 'Notary Public';
        req.License_Type__c = 'Notary Public';
        req.Status__c = 'Under Review';
        req.Service_Request_Type__c = 'Reschedule Exam';//CE Audit
        update req;
        
    }
    
    @isTest
    public static void testMethod3(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application_Type__c = 'Notary Public';
        lic1.Credential_Type__c = 'Notary Public';
        update lic1;
        Request__c req = DOL_TestDataFactory.createRequest(lic1.Id, 'Architects', 'Architect');
        Id quesRecTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('License Information').getRecordTypeId();
        Question__c ques = DOL_TestDataFactory.createQuestion(quesRecTypeId);
        
        Answer__c ans = DOL_TestDataFactory.createAnswer(lic1.Id,ques.Id);
        Task tsk = new Task();
        tsk.WhatId = req.Id;
        tsk.Status = 'Pending';
        insert tsk;
        system.debug('tsk::'+tsk);
        
        req.Profession__c = 'Notary Public';
        req.License_Type__c = 'Notary Public';
        req.Status__c = 'Under Review';
        req.Service_Request_Type__c = 'CE Audit';
        update req;
        
        
        
    }
    
    @isTest
    public static void testMethod4(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application_Type__c = 'Notary Public';
        lic1.Credential_Type__c = 'Notary Public';
        update lic1;
        Request__c req = DOL_TestDataFactory.createRequest(lic1.Id, 'Architects', 'Architect');
        Id quesRecTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('License Information').getRecordTypeId();
        Question__c ques = DOL_TestDataFactory.createQuestion(quesRecTypeId);
        
        Answer__c ans = DOL_TestDataFactory.createAnswer(lic1.Id,ques.Id);
        BGCK__Answer__c bgAns = new BGCK__Answer__c();
        bgAns.QuestionDOL__c = ques.Id;
        bgAns.Request__c = req.Id;
        insert bgAns;
        
        MUSW__Parcel__c parcl = new MUSW__Parcel__c();
        parcl.Request_Parcel__c = req.Id;
        insert parcl;
        
        MUSW__License_Parcel__c licParcl = new MUSW__License_Parcel__c();
        licParcl.MUSW__License2__c = lic1.Id;
        licParcl.Physical__c = true;
        licParcl.Status__c = 'Active';
        licParcl.MUSW__Parcel__c = parcl.Id;
        insert licParcl;
        
        req.Profession__c = 'Notary Public';
        req.License_Type__c = 'Notary Public';
        req.Status__c = 'Approved';
        req.Service_Request_Type__c = 'Update Print Name';//CE Audit
        try{
            update req;
        }catch(exception ex){}
        
    }
    
    
    @isTest
    public static void testUnusedMethods(){
        RequestTriggerHandler rt = new RequestTriggerHandler();
        rt.onAfterDelete();
        rt.onAfterInsert();
        rt.onAfterUndelete();
        rt.onBeforeDelete();
        rt.onBeforeInsert();
        rt.onBeforeUndelete();
    }
}