src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the version of the question that was answered.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Newsfeed__c.object
<CustomObject>
    <description>The object for news feed items.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FAQ_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>FAQ Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section field categorizes FAQ questions into different types like Registration, Status, Public Search etc</description>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sections_for_Support_Page</valueSetName>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <recordTypes>
        <fullName>FAQ</fullName>
        <active>true</active>
        <description>FAQ questions for Support page on Portal</description>
        <label>FAQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Sections_for_Support_Page.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Privacy and Security</fullName>
    </customValue>
    <customValue>
        <fullName>Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Public Search</fullName>
    </customValue>
    <customValue>
        <fullName>Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>New Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <description>Will be added when confirmed with Functional team</description>
    <masterLabel>Sections for Support Page</masterLabel>
</GlobalValueSet>

src/classes/SupportPageCtrl.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Name                : SupportPageCtrl
** Description         :  
** Version             : 1.0
** Built By            : 
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
**
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
************************************************************************************/
public class SupportPageCtrl {
    
    public Boolean isGuestUser {get;set;}
    public String selectedSection {get; set;}
    public List<SelectOption> sectionSelectOptions {get; set;}    
    public List<Newsfeed__c> sectionFAQs {get; set;} 
    private List<Newsfeed__c> allFAQs;
    
    public SupportPageCtrl() {
        allFAQs = [SELECT id, Name, Section__c, Question__c, Answer__c
                   FROM Newsfeed__c 
                   WHERE RecordType.DeveloperName = :System.label.RT_FAQ
                   AND FAQ_Active__c = true
                  ];
        
        generateSectionSelectList();
        refreshFAQlists();        
        isGuestUser = Utilities.isGuestUserLoggedIn();   
    }
    
    public void refreshFAQlists() {
        refreshSectionFAQlist();
    }
    
    private void generateSectionSelectList() {
        sectionSelectOptions = new List<SelectOption>();
        sectionSelectOptions.add(new SelectOption('', label.Str_All_Topics));
        selectedSection = DOL_AppConstants.NULL_EMPTY_STRING + '';
        Set<String> sections = new Set<String>();
        
        for(Newsfeed__c faq : allFAQs) {
            if(String.isNotEmpty(faq.Section__c)) {
                sections.add(faq.Section__c);
            }
        }
        
        for(String section : sections) {
            sectionSelectOptions.add(new SelectOption(section, section));
        }
    }
    
    private void refreshSectionFAQlist() {
        sectionFAQs = new List<Newsfeed__c>();
        
        for(Newsfeed__c faq : allFAQs) {
            if(String.isNotEmpty(faq.Section__c) && ( faq.Section__c == selectedSection || String.isEmpty(selectedSection) )) {
                sectionFAQs.add(faq);
            }
        }
    }
    
    
}