src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <description>The actual answer that the user responded with for the question</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Answer Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_id_of_Question__c</fullName>
        <description>External id of Question</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External id of Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The license with which this answer is related</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether to disable triggers for a profile/user- specially useful during data loads</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

src/objects/Master_Review_List__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Review_Completion_Time_Hours__c</fullName>
        <label>Estimated Review Completion Time(Hours)</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Master Review List</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Review List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>This field indicates whether the current record is a Plan Review or a Permit. This field has been created instead of using Record Types since there could be multiple record types defined for Plan Reviews and Permits.</description>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permit</fullName>
                </value>
                <value>
                    <fullName>Plan Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Hours_Based_on_Answers__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>To store review hours based on applicant answers which will then be used by DRE to compute the total estimated time required for review completion</description>
        <label>Review Hours Based on Answers</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This is the type of permit being renewed.</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Type__c</fullName>
        <description>Type of reinstatement.</description>
        <label>Renewal Reinstatement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal PTO</fullName>
                </value>
                <value>
                    <fullName>Renewal Plan Review</fullName>
                </value>
                <value>
                    <fullName>ReinstatementPTO</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPTO</label>
                </value>
                <value>
                    <fullName>ReinstatementPlanReview</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPlanReview</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <description>This is the renewal status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Renewal_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Review_Completion_Time_Computation__c.object
<CustomObject>
    <description>Hold data to compute the expected review completion time for plan reviews</description>
    <fields>
        <fullName>Answer_Comparison_Type__c</fullName>
        <description>Added the range comparison type to accommodate answer comparison for gpd</description>
        <label>Answer Comparison Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Normal</fullName>
                    <default>true</default>
                    <label>Normal</label>
                </value>
                <value>
                    <fullName>Range</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Answer__c</fullName>
        <description>Expected Answer for the external question id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Expected Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_id_of_Question__c</fullName>
        <description>Hold external ID to match question with answer</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External id of Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range_End_Value__c</fullName>
        <description>to store end value of the range. such as 1000-3000 gpd (used in answertriggerahndler and review_completion_time_computation__c object)</description>
        <label>Range End Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_Start_Value__c</fullName>
        <description>to store start value of the range. such as 1000-3000 gpd (used in answertriggerahndler and review_completion_time_computation__c object)</description>
        <label>Range Start Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Review_Hours__c</fullName>
        <description>Hours required to review as per the expected answer</description>
        <label>Review Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Review Completion Time Computation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Review Completion Time Computation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Completion Time Computation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Renewal_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Generate Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In-Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submission Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Third Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Applicant Action</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Additional Qualifications</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
        <isActive>false</isActive>
    </customValue>
    <masterLabel>Renewal Status</masterLabel>
</GlobalValueSet>

src/classes/AnswerTriggerHandler.cls
public class AnswerTriggerHandler  implements BGCM.ITriggerHandler{
    public AnswerTriggerHandler()
    {
        System.debug('answertriggerhandler 1');
        //This is to check whether bypass the trigger or not
        Global_Settings__c settings = Global_Settings__c.getInstance(UserInfo.getUserId());
        if (settings.Disable_Triggers__c == true) 
            return;
        System.debug('answertriggerhandler 2');
    }
    
    public void onAfterDelete() {}
    public void onAfterInsert() {
        System.debug('answertriggerhandler 3');
       aftermethod();
    }
    public void onAfterUndelete() {}
    public void onAfterUpdate() {
        System.debug('answertriggerhandler 4');
        aftermethod();
    }
    public void onBeforeDelete() {}
    public void onBeforeInsert() {}
    public void onBeforeUndelete() {}
    public void onBeforeUpdate() {}
    
    public void aftermethod(){
        System.debug('answertriggerhandler 5');
         ParentFieldUpdateTriggerHandler.updateParentFieldAnswer(Trigger.New);
         Map<Id,Answer__c> LrSubmissionMap = new Map<Id,Answer__c>();
        Map<Id,Answer__c> permitRenewalSubmissionMap = new Map<Id,Answer__c>();
        Map<Id,Answer__c> ReinstatementSubmissionMap = new Map<Id,Answer__c>();
        Map<Id,Answer__c> LicenseSubmissionMap = new Map<Id,Answer__c>();
        Map<Id,Answer__c> permitSubmissionMap = new Map<Id,Answer__c>();
        //Map<String,Answer__c> QuestionAnswerMap = new Map<String,Answer__c>();
        Map<Id,Decimal> permitReviewHourMap = new Map<Id,Decimal>();
        Map<Id,Answer__c> SRSubmissionMap = new Map<Id,Answer__c>();
        
        //Calling handler method to check submission list records and create submission records
        //List<Answer__c> answers = new List<Answer__c>();
        Set<Id> RenewalIds = new Set<Id>();
        Set<String> questionExternalId = new Set<String>();
        Map<Id,Renewal_Application__c> RenewalMap = new Map<Id,Renewal_Application__c>();
        if(Trigger.isInsert || Trigger.isUpdate)
        {
            
            for(Answer__c answer :(list<Answer__c>)Trigger.New){
                
                system.debug('answer>>'+answer);
                system.debug('answer>>'+answer.License__r);                
                if(answer.License__c!=null)
                {
                    System.debug('answertriggerhandler 8');
                    system.debug('answer.license__c>>'+answer.License__c);
                    LicenseSubmissionMap.put(Answer.Id,Answer);                    
                }
                
                else if(answer.Renewal_Application__c!=null)
                {
                    System.debug('answertriggerhandler 9');
                    RenewalIds.add(answer.Renewal_Application__c);
                    
                }
                else if(answer.Permit__c!=null){
                    System.debug('encountered Permit in Answer Trigger Handler '+answer.Permit__c);
                    permitSubmissionMap.put(Answer.Id,Answer);
                    //QuestionAnswerMap.put(Answer.External_id_of_Question__c, Answer);
                    questionExternalId.add(Answer.External_id_of_Question__c);
                    if(!permitReviewHourMap.containsKey(Answer.Permit__c)){
                        permitReviewHourMap.put(Answer.Permit__c,0.0);
						                       
                    }                                        
                }
                else if(answer.Service_Request__c!=null){
                    System.debug('Answer Service Request>>>'+answer.Service_Request__c);
                    SRSubmissionMap.put(Answer.Id,Answer);
                }
            }
            System.debug('permitReviewHourMap '+permitReviewHourMap);
            if(!questionExternalId.isEmpty()){
            List<MUSW__Permit2__c> permitsToUpdate = new List<MUSW__Permit2__c>();
                System.debug('questionExternalId '+questionExternalId);
            List<Review_Completion_Time_Computation__c> reviewCompletionTimeList = [SELECT ID, Answer_Comparison_Type__c,Range_Start_Value__c, Range_End_Value__c, Expected_Answer__c, External_id_of_Question__c, Review_Hours__c
                                                                              FROM Review_Completion_Time_Computation__c
                                                                              WHERE External_id_of_Question__c IN :questionExternalId];
                System.debug('reviewCompletionTimeList '+reviewCompletionTimeList);
            Map<ID, MUSW__Permit2__c> permitTypeList = new Map<ID, MUSW__Permit2__c>([SELECT ID, Permit_Type__c
                                                        FROM MUSW__Permit2__c
                                                        WHERE ID IN :permitReviewHourMap.keySet()
                                                        //AND Object_Type__c = 'Plan Review'
                                                                                     ]);
                System.debug('permitTypeList.keySet() '+permitTypeList.keySet());
                System.debug('permitTypeList '+permitTypeList);
                
                Map<ID,String> permitTypeMap = new Map<Id,String>();
                Set<String> permitTypeSet = new Set<String>();
                for(MUSW__Permit2__c permitTypes: permitTypeList.values()){
                    System.debug('permitTypes.Id '+permitTypes.Id);
                    System.debug('permitTypes.Permit_Type__c '+permitTypes.Permit_Type__c);
                    permitTypeMap.put(permitTypes.Id, permitTypes.Permit_Type__c);
                    permitTypeSet.add(permitTypes.Permit_Type__c);
                }
                System.debug('permitTypeSet '+permitTypeSet);
                System.debug('permitTypeMap '+permitTypeMap);
            Map<String, Master_Review_List__C> defaultReviewHours = new Map<String, Master_Review_List__C>([SELECT Permit_Type__c, Estimated_Review_Completion_Time_Hours__c
                                                        FROM Master_Review_List__C
                                                        WHERE Permit_Type__c IN :permitTypeSet
                                                        AND Application_Type__c IN ('Plan Review','Manufactured Homes Communities')
														]);
              System.debug('defaultReviewHours '+defaultReviewHours);
            Map<String, Answer__C> QuestionAnswerMap = new Map<String, Answer__C>([Select External_id_of_Question__c, Permit__c, Answer_Text__c 
                                                    From Answer__c 
                                                    Where Permit__c IN: permitReviewHourMap.keySet()]);
                System.debug('QuestionAnswerMap '+QuestionAnswerMap);
                    for(Id permId: permitReviewHourMap.keySet()){
                        Decimal answerHoursForPermit = 0.0;
                        String permitType = permitTypeMap.get(permId);
                        System.debug('permitType '+permitType);
                        System.debug('permit Id' +permId);
                        System.debug('defaultReviewHours '+defaultReviewHours);  
                        Decimal tempValue = 0.0;
                        for(Master_Review_List__C drh: defaultReviewHours.values()){
                            System.debug('drh.Permit_Type__c '+drh.Permit_Type__c);
                            System.debug('permitType '+permitType);
                            if(drh.Permit_Type__c == permitType){
                                System.debug('in if break ');
                                tempValue = drh.Estimated_Review_Completion_Time_Hours__c;
                                break;
                            }
                            System.debug('after break');
                        }
                        System.debug('temp Value '+tempValue);
                        //MUSW__Permit2__c permitTypeValue = permitReviewHourMap.get(permId);
                        answerHoursForPermit += tempValue;
                              System.debug('answerHoursForPermit '+answerHoursForPermit);                  
                        for(Review_Completion_Time_Computation__c rctl: reviewCompletionTimeList){
                        for(Answer__c answersForPermit: QuestionAnswerMap.values()){
                            if(answersForPermit.Permit__c == permId){
                                if(answersForPermit.external_id_of_Question__c == rctl.External_id_of_Question__c
                                  //&& answersForPermit.Answer_Text__c == rctl.Expected_Answer__c
                                  ){
                                      if(rctl.Answer_Comparison_Type__c == 'Normal' && 
                                         answersForPermit.Answer_Text__c == rctl.Expected_Answer__c){
                                             answerHoursForPermit += rctl.Review_Hours__c;                                    
                                          
                                      }else if(rctl.Answer_Comparison_Type__c == 'Range')
                                      {
                                          try{
                                               	 Decimal answerText;
                                                 if(answersForPermit.Answer_Text__c != null){
                                                   answerText = Decimal.valueOf(answersForPermit.Answer_Text__c);
                                                 }else{
                                                    answerText = 0;
                                                  }
                                              if(answerText >= rctl.Range_Start_Value__c &&
                                             answerText <= rctl.Range_End_Value__c){
                                                 
                                                 answerHoursForPermit += rctl.Review_Hours__c;
                                             }
                                          }
                                          catch(exception e){
                                              ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'AnswerTriggerHandler', 'aftermethod',answersForPermit.Answer_Text__c , 'AnswerTriggerHandler', 'High');
                                          }
                                         
                                         
                                          
                                      }
                                      
                                }
                            }
                        }
                    }
                        MUSW__Permit2__c tempPermit = new MUSW__Permit2__c(ID = permId, 
                                                                           Review_Hours_Based_on_Answers__c=answerHoursForPermit);
                        permitsToUpdate.add(tempPermit);                        
                    }
                    
                
                
                update permitsToUpdate;
                
            }            
            /*
            if(PermitSubmissionMap.size() > 0){
                for (Answer__c answers: PermitSubmissionMap.values()){
                    
                }
            }*/
            
            // Query Renewal Map
            if(!RenewalIds.isEmpty())
            {
                System.debug('answertriggerhandler 10');
                RenewalMap = new Map<Id,Renewal_Application__c>([select Id,Renewal_Reinstatement_Type__c, Renewal_Status__c, Credential__c, Permit_Type__c from Renewal_Application__c where Id IN:RenewalIds]);
            }
            
            for(Answer__c answer:(list<Answer__c>)Trigger.new)
            {
                if(answer.Renewal_Application__c!=null && RenewalMap.containsKey(answer.Renewal_Application__c))
                {
                    Renewal_Application__c renewalRec = RenewalMap.get(answer.Renewal_Application__c);
                    
                    if(renewalRec.Renewal_Reinstatement_Type__c== Label.RNT_Renewal && 
                       renewalRec.Renewal_Status__c == 'Incomplete')
                    {   
                        LrSubmissionMap.put(answer.Id,answer);
                    }
                    else if(renewalRec.Renewal_Reinstatement_Type__c== 'Renewal PTO' && 
                       renewalRec.Renewal_Status__c == 'Incomplete')
                    {   
                        permitRenewalSubmissionMap.put(answer.Id,answer);
                    }
                    else if(renewalRec.Renewal_Reinstatement_Type__c!=null && 
                            renewalRec.Renewal_Reinstatement_Type__c==Label.RNT_Reinstatement && 
                            renewalRec.Renewal_Status__c == Label.ST_Incomplete)
                    {
                        ReinstatementSubmissionMap.put(Answer.Id,Answer);
                    }         
                }
            }
        }
        
        
        
        if(LrSubmissionMap.size()>0)
        {
            
            CredRenewalAnsSubTriggerHandler.updateAnswerSubmissionRecords(LrSubmissionMap,Label.RNT_Renewal);   
        }
        else if(ReinstatementSubmissionMap.size()>0)
        {
            CredRenewalAnsSubTriggerHandler.updateAnswerSubmissionRecords(ReinstatementSubmissionMap,Label.RNT_Reinstatement);
        }
        else if(LicenseSubmissionMap.size()>0)
        {
            CredAnsSubmissionTriggerHandler controller = new CredAnsSubmissionTriggerHandler();
            controller.updateAnswerSubmissionRecords(LicenseSubmissionMap);
        }else if(permitRenewalSubmissionMap.size() > 0){
            PermitRenewalAnsSubmissionTriggerHandler.updateAnswerSubmissionRecords(permitRenewalSubmissionMap,'Renewal PTO');
        }else if(permitSubmissionMap.size() > 0){
            PermitAnsSubmissionTriggerHandler permitController = new PermitAnsSubmissionTriggerHandler();
            permitController.updateAnswerSubmissionRecords(permitSubmissionMap);
        }else if(SRSubmissionMap.size()>0){
            system.debug('Entered SR Submission'+SRSubmissionMap);
            SRAnsSubmissionTriggHandler.updateSubmissionRecords(SRSubmissionMap);
        }
        
       
    }
    
}