src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>External_id_of_Question__c</fullName>
        <description>External id of Question</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External id of Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the version of the question that was answered.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This refers to the credential type being applied for</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Background_Question_Field_API_Name__c</fullName>
        <description>Field to store field API name for background question</description>
        <label>Background Question Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates submission list entries that are always required and will be defaulted to the Portal.</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Answer__c</fullName>
        <description>Expected Answer for the question based on which submission list will be generated</description>
        <label>Expected Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Id_of_Question__c</fullName>
        <description>Question__r.External_Id_of_Parent__c</description>
        <formula>Question__r.External_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External Id of Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question based on which submission list record will be created</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Master Submission Lists</relationshipLabel>
        <relationshipName>Master_Submission_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Change Name</fullName>
                </value>
                <value>
                    <fullName>Withdraw Application</fullName>
                </value>
                <value>
                    <fullName>Submit Additional Documentation</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Title Modification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <label>Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Submission list record show for</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Various credential types available under a functional area and division</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Service Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/classes/SRAnsSubmissionTriggHandler.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Class Name       : SRAnsSubmissionTriggHandler
** Description      : Service Request Answer Submission 
** Version          : 1.0
** Built By         : Srikanth Kottam

**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------------------------
** 
** Review Log:
**---------------
** Reviewer                  Date          Version               Description
**------------------------------------------------------------------------------------------------------------
**
*************************************************************************************************************/
public class SRAnsSubmissionTriggHandler {
	public static void updateSubmissionRecords(Map<Id,Answer__c> newAnswerMap){
        Map<String, List<MUSW__Master_Submission_List__c>> typeToSubmissionMap = new Map<String,List<MUSW__Master_Submission_List__c>>();
        Set<Id> SRIds = new Set<Id>();
        Set<String> credentialType = new Set<String>();
        for(Answer__c tempAns: newAnswerMap.values()){
            List<answer__C> tempansList = [select id, Service_Request__c, Service_Request__r.Credential_Type__c from answer__C where Id=:tempAns.Id]; 
            for(Answer__C a: tempansList ){
                SRIds.add(a.Service_Request__c);
            	credentialType.add(a.Service_Request__r.Credential_Type__c);
            }
        }
        for(MUSW__Master_Submission_List__c masterSubmission:[SELECT Id, Name,External_id__c, Background_Question_Field_API_Name__c, Question__c, External_Id_of_Question__c,
                                                   Expected_Answer__c, Description_Long__c, Application_Type__c, Credential_Type__c, Credential__c, Service_Request_Type__c, 
                                                   Default__c, Show_For__c, Submission_Type__c, Application_Method__c, Document_API_Name__c, BG_File_Location_Type__c
                                                   FROM MUSW__Master_Submission_List__c 
                                                   WHERE Active__c = TRUE 
                                                   AND Object__c = :label.API_Application
                                                   AND Show_for__c = 'Service Request' 
                                                   AND Credential_Type__c IN: credentialType            
                                                   ]){ 
                                                  // AND Service_Request__c IN :SRIds
                                                  // AND Application_Method__C IN: applicationMethodSet
                                                  
            List<MUSW__Master_Submission_List__c> tempSubmissionList = new List<MUSW__Master_Submission_List__c> ();
            if(typeToSubmissionMap.containsKey(masterSubmission.Service_Request_Type__c)){
                tempSubmissionList = typeToSubmissionMap.get(masterSubmission.Service_Request_Type__c);
            }
            tempSubmissionList.add(masterSubmission);
            typeToSubmissionMap.put(masterSubmission.Service_Request_Type__c, tempSubmissionList);
        }
        List<MUSW__Submission__c> submissionUpsertList = new List<MUSW__Submission__c>();
        List<MUSW__Submission__c> submissionDeleteList = new List<MUSW__Submission__c>();
        Map<Id,MUSW__Application2__c> SRMap  = new Map<Id,MUSW__Application2__c>([Select id, (Select Id,Name,LicenseQuestionKey__c FROM MUSW__Submissions__r) FROM MUSW__Application2__c WHERE Id IN:SRIds]);
        for(Answer__c Ans:[Select Id, External_id_of_Question__c, Service_Request__c, Service_Request__r.MUSW__Type__c, Answer_Text__c from Answer__c where Id in : newAnswerMap.keySet()]){
            if(Ans.Service_Request__c!=null){
                if(SRMap.containsKey(Ans.Service_Request__c)){
                    Map<String,MUSW__Submission__c> keyToSubmissionMap = new Map<String,MUSW__Submission__c>();
                    for(MUSW__Submission__c submission: (SRMap.get(Ans.Service_Request__c)).MUSW__Submissions__r){
                        if(submission.LicenseQuestionKey__c != null){
                            keyToSubmissionMap.put(submission.LicenseQuestionKey__c,submission);
                        }
                    }
                    Answer__c newAnswer = newAnswerMap.get(ans.id);
                    if(typeToSubmissionMap.containsKey(Ans.Service_Request__r.MUSW__Type__c)){
                        for(MUSW__Master_Submission_List__c masterSubmission:typeToSubmissionMap.get(Ans.Service_Request__r.MUSW__Type__c)){
                            String licenseSubmissionComboKey = String.valueOf(Ans.Service_Request__c)+String.valueOf(masterSubmission.Id);
                            if(Ans.External_id_of_Question__c == masterSubmission.External_Id_of_Question__c){
                                String questionAnswer;
                                try{
                                    questionAnswer= ans.Answer_Text__c;
                                }catch(Exception ex){
                                    ErrorLogger.logGeneralException(ex, UserInfo.getUserId(), label.Str_User, '', 'Update Answer Submission Records', 'SRAnsSubmissionTriggHandler', label.str_HIGH);
                                }
                                if(questionAnswer!= null && questionAnswer.equalsIgnoreCase(masterSubmission.Expected_Answer__c)){
                                    if(!keyToSubmissionMap.containsKey(licenseSubmissionComboKey)){
                                        MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name = masterSubmission.Name, Description_Long__c = masterSubmission.Description_Long__c,
                                        LicenseQuestionKey__c = licenseSubmissionComboKey, MUSW__Application2__c = ans.Service_Request__c, 
                                        Type__c = (masterSubmission.Submission_Type__c =='Hardcopy: To be Mailed' ? 'Hardcopy: To be Mailed' : 'Softcopy: To be Uploaded'),
                                        Document_API_Name__c = masterSubmission.Document_API_Name__c, Extid_from_Submission_List__c=masterSubmission.External_Id__c,
                                        MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
                                                                                                    // Master_Submission__c=masterSubmission.Id);
                                        submissionUpsertList.add(newSubmission);
                                        
                                    }
                                    system.debug('submissionUpsertList>>>'+submissionUpsertList);
                                }
                                
                                else if((questionAnswer == null || !questionAnswer.equalsIgnoreCase(masterSubmission.Expected_Answer__c)) && keyToSubmissionMap.containsKey(licenseSubmissionComboKey)){
                                    //If answer is 'No' and there is an existing submission, it is deleted
                                    MUSW__Submission__c oldSubmission = keyToSubmissionMap.get(licenseSubmissionComboKey);
                                    submissionDeleteList.add(oldSubmission);
                                }
                            }
                        }
                        
                    }
                }
            }
            
        }
        try{
            upsert submissionUpsertList LicenseQuestionKey__c;
            delete submissionDeleteList;
        }catch(Exception ex){
            ErrorLogger.logGeneralException(ex, UserInfo.getUserId(), label.Str_User, '', 'Update Answer Submission Records', 'SRAnsSubmissionTriggHandler', label.str_HIGH);
        }
    }
}