src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The license with which this answer is related</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the version of the question that was answered.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BG_File_Location_Type__c</fullName>
        <label>BG File Location Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Bluebeam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Background_Question_Field_API_Name__c</fullName>
        <description>Field to store field API name for background question</description>
        <label>Background Question Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates submission list entries that are always required and will be defaulted to the Portal.</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Answer__c</fullName>
        <description>Expected Answer for the question based on which submission list will be generated</description>
        <label>Expected Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object associated with submission list record</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question based on which submission list record will be created</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Master Submission Lists</relationshipLabel>
        <relationshipName>Master_Submission_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Submission list record show for</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Various credential types available under a functional area and division</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Object.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MUSW__License2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal_Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>MUSW__Application2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Musw__Permit2__c</fullName>
    </customValue>
    <description>List of objects</description>
    <masterLabel>Object</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/classes/CredAnsSubmissionTriggerHandler.cls
public class CredAnsSubmissionTriggerHandler {
    public Set < MUSW__License2__c > newLicenses {
        get;
        set;
    }

    public Set < Id > LicenseIds {
        get {
            if (LicenseIds == null) LicenseIds = new Set < Id > ();
            return LicenseIds;
        }
        set;
    }

    public Map < Id, MUSW__License2__c > LicenseId_License_Map {
        get {
            if (LicenseId_License_Map == null) LicenseId_License_Map = new Map < Id, MUSW__License2__c > ();
            return LicenseId_License_Map;
        }
        set;
    }
    
   public void updateAnswerSubmissionRecords(Map < Id, Answer__c > newAnswerMap) {
       
       Set<String> credentialList = new Set<String>();
       Set<String> applicationMethodSet = new Set<String>();
       for(Answer__C tempAns: newAnswerMap.values()){
       		List<answer__C> tempcredList = [select id, license__c, license__r.credential__C, license__r.Application_Method__c from answer__C where Id=:tempAns.Id];   
           for(Answer__C a:tempcredList ){
               credentialList.add(a.license__r.credential__c);
               applicationMethodSet.add(a.license__r.Application_Method__c);
           }
           System.debug('credential is '+credentialList);
       }
        
        //System.debug('credential List for new Application--'+credentialList);
        Map < String, List < MUSW__Master_Submission_List__c >> typeToSubmissionMap = new Map < String, List < MUSW__Master_Submission_List__c >> ();
        for (MUSW__Master_Submission_List__c masterSubmission: [SELECT Id, Name,External_id__c, Background_Question_Field_API_Name__c, Question__c, 
                                                   Expected_Answer__c, Description_Long__c, Application_Type__c, Credential_Type__c, Credential__c, 
                                                   Default__c, Show_For__c, Submission_Type__c, Application_Method__c, Document_API_Name__c, BG_File_Location_Type__c
                                                   FROM MUSW__Master_Submission_List__c 
                                                   WHERE Active__c = TRUE 
                                                   AND Object__c = :label.API_License2
                                                   AND Show_for__c = 'Credential'
                                                   AND Credential__c IN :credentialList
                                                                AND Application_Method__C IN: applicationMethodSet
                                                               ]) {
		//System.debug('in ansTrigHandler 2');                                                       
            List < MUSW__Master_Submission_List__c > tempSubmissionList = new List < MUSW__Master_Submission_List__c > ();
            if (typeToSubmissionMap.containsKey(masterSubmission.Credential__c)) {
                ///System.debug('in ansTrigHandler 3 '+masterSubmission.Credential__c);                                                       
                tempSubmissionList = typeToSubmissionMap.get(masterSubmission.Credential__c);
            }
              	//System.debug('in ansTrigHandler 4 '+tempSubmissionList);                                                       
            tempSubmissionList.add(masterSubmission);
			//System.debug('in ansTrigHandler 5 '+tempSubmissionList);
            typeToSubmissionMap.put(masterSubmission.Credential__c, tempSubmissionList);
			//System.debug('in ansTrigHandler 6 '+typeToSubmissionMap);
        }

        List < MUSW__Submission__c > submissionUpsertList = new List < MUSW__Submission__c > ();
        List < MUSW__Submission__c > submissionDeleteList = new List < MUSW__Submission__c > ();

        for (Answer__c Ans: [Select Id, Question__c, License__c, License__r.Credential__c, Answer_Text__c from Answer__c where Id in: newAnswerMap.keySet()]) {
            LicenseIds.add(Ans.License__c);
            //System.debug('in ansTrigHandler 7 '+LicenseIds);
        }

        List < Id > LicenseIdsList = new List < Id > ();
        if (LicenseIds.size() > 0) {
            //System.debug('in ansTrigHandler 8 '+LicenseIds.size());
            LicenseIdsList.addAll(LicenseIds);
            //System.debug('in ansTrigHandler 9 '+LicenseIdsList);
            if (newLicenses == null) {
                //System.debug('in ansTrigHandler 10 ');
                newLicenses = new Set < MUSW__License2__c > ([select id, (Select Id, Name, LicenseQuestionKey__c FROM MUSW__Submissions__r) FROM MUSW__License2__c WHERE Id IN: LicenseIdsList]);
            }

            if (newLicenses.size() > 0) {
                System.debug('in ansTrigHandler 11 ');
                for (MUSW__License2__c license: newLicenses) {
                    System.debug('in ansTrigHandler 12');
                    LicenseId_License_Map.put(license.Id, license);
                }
            }
        }
       
       Map<String,Question__c> questionIdextid = new Map<String,Question__c>();
        Map<Id,Question__c> answerQuestionmap = new Map<Id,Question__c>();
        Set<String> QuestionextIds = new Set<String>();
        
       
        for(Answer__c ans:newAnswerMap.values())
        {            
       System.debug('in ansTrigHandler 13 ');
            if(ans.External_id_of_Question__c!=null)
            {
                System.debug('in ansTrigHandler 14 ');
                QuestionextIds.add(ans.External_id_of_Question__c);
            }                
        }
        List<question__c> questions= [Select id ,external_id__c,Parent_Object_API_Name__c,Compliance_Field_API_Name__c,
                                      Question_is_Compliance_Related__c,Expected_Answer_Parent_Field_Value_Map__c,
                                      Parent_Object_Field_API_Name__c from question__c where external_id__C in: QuestionextIds];
        for(Question__c question:questions ){
            System.debug('in ansTrigHandler 15 ');
            questionIdextid.put(question.external_id__C,question);
        }
        for(Answer__c ans:newAnswerMap.values()) {
            System.debug('in ansTrigHandler 16 ');
            if(ans.External_id_of_Question__c!=null)
            {
                System.debug('in ansTrigHandler 17 ');
                answerQuestionmap.put(ans.id,questionIdextid.get(ans.External_id_of_Question__c));
            }                
        }
       
        for (Answer__c Ans: [Select Id, Question__c, License__c, License__r.Credential__c, Answer_Text__c from Answer__c where Id in: newAnswerMap.keySet()]) {
            System.debug('in ansTrigHandler 18 ');
            if (ans.License__c != null && LicenseId_License_Map.containsKey(ans.License__c)) {
                System.debug('in ansTrigHandler 19 ');
                //Creating a map of existing submission records
                Map < String, MUSW__Submission__c > keyToSumissionMap = new Map < String, MUSW__Submission__c > ();
                for (MUSW__Submission__c submission: (LicenseId_License_Map.get(ans.License__c)).MUSW__Submissions__r) {
                    System.debug('in ansTrigHandler 20 ');
                    if (submission.LicenseQuestionKey__c != null) {
                        System.debug('in ansTrigHandler 21 ');
                        keyToSumissionMap.put(submission.LicenseQuestionKey__c, submission);
                    }
                }
                Answer__c newAnswer = newAnswerMap.get(ans.id);
                if (typeToSubmissionMap.containsKey(ans.License__r.Credential__c)) {
                    System.debug('in ansTrigHandler 22 ');
                    for (MUSW__Master_Submission_List__c masterSubmission: typeToSubmissionMap.get(ans.License__r.Credential__c)) {
                        System.debug('in ansTrigHandler 23 ');
                        String licenseSubmissionComboKey = String.valueOf((LicenseId_License_Map.get(ans.License__c)).Id) + masterSubmission.External_Id__c;
                       Question__c ansQuestion =answerQuestionmap.get(ans.Id);
                        if(ansQuestion!=null){
                            System.debug('in ansTrigHandler 24 ');
                            if ( ansQuestion.Id== masterSubmission.Question__c) {
                                System.debug('in ansTrigHandler 25 ');
                            String questionAnswer;
                            try {
                                questionAnswer = ans.Answer_Text__c;
                                System.debug('in ansTrigHandler 26 ');
                            } catch (Exception ex) {
                                ErrorLogger.logGeneralException(ex, UserInfo.getUserId(), label.Str_User, 'while fetching answer text', 'updateAnswerSubmissionRecords', 'CredAnsSubmissionTriggerHandler', label.str_HIGH);
                            }

                            if (questionAnswer != null && questionAnswer.equalsIgnoreCase(masterSubmission.Expected_Answer__c)) {
                                System.debug('in ansTrigHandler 27 ');
                                if (!keyToSumissionMap.containsKey(licenseSubmissionComboKey)) {
                                    System.debug('in ansTrigHandler 28 ');
                                    MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name = masterSubmission.Name, Description_Long__c = masterSubmission.Description_Long__c,
                                        LicenseQuestionKey__c = licenseSubmissionComboKey, MUSW__License2__c = ans.License__c,
                                        Type__c = (masterSubmission.Submission_Type__c =='Hardcopy: To be Mailed' ? 'Hardcopy: To be Mailed' : 'Softcopy: To be Uploaded'),
                                        Document_API_Name__c = masterSubmission.Document_API_Name__c, Extid_from_Submission_List__c=masterSubmission.External_Id__c,
                                        MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
                                    
                                    if(newSubmission.MUSW__BG_File_Location_Type__c == null || newSubmission.MUSW__BG_File_Location_Type__c == '') newSubmission.MUSW__BG_File_Location_Type__c = 'Salesforce';
                                    submissionUpsertList.add(newSubmission);
                                }
                            } else if ((questionAnswer == null || !questionAnswer.equalsIgnoreCase(masterSubmission.Expected_Answer__c)) && keyToSumissionMap.containsKey(licenseSubmissionComboKey)) {
                                System.debug('in ansTrigHandler 29 ');
                                //If answer is 'No' and there is an existing submission, it is deleted
                                MUSW__Submission__c oldSubmission = keyToSumissionMap.get(licenseSubmissionComboKey);
                                submissionDeleteList.add(oldSubmission);
                            }
                        }
                    }
                    }
                }
            }
        }
        try {
            System.debug('in ansTrigHandler 30>>> submissionUpsertList '+submissionUpsertList);
            System.debug('in ansTrigHandler 31>>> submissionDeleteList '+submissionDeleteList);
            if(submissionUpsertList != null && submissionUpsertList.size() > 0){
            	upsert submissionUpsertList LicenseQuestionKey__c;	
            }
            if(submissionDeleteList != null && submissionDeleteList.size() > 0 ){
            	delete submissionDeleteList;	
            }
        } catch (Exception ex) {
            ErrorLogger.logGeneralException(ex, UserInfo.getUserId(), label.Str_User, 'while upsert/delete', 'updateAnswerSubmissionRecords', 'CredAnsSubmissionTriggerHandler', label.str_HIGH);            
        }
    }

}