src/objects/Answer__c.object
<CustomObject>
    <description>To store user&apos;s response to questions</description>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the version of the question that was answered.</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>ANS-{000000}</displayFormat>
        <label>Answer Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Newsfeed__c.object
<CustomObject>
    <description>The object for news feed items.</description>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Record Identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>Section field categorizes FAQ questions into different types like Registration, Status, Public Search etc</description>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sections_for_Support_Page</valueSetName>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Sections_for_Support_Page.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Privacy and Security</fullName>
    </customValue>
    <customValue>
        <fullName>Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Status</fullName>
    </customValue>
    <customValue>
        <fullName>Public Search</fullName>
    </customValue>
    <customValue>
        <fullName>Renewals</fullName>
    </customValue>
    <customValue>
        <fullName>New Applications</fullName>
    </customValue>
    <customValue>
        <fullName>Technical</fullName>
    </customValue>
    <description>Will be added when confirmed with Functional team</description>
    <masterLabel>Sections for Support Page</masterLabel>
</GlobalValueSet>

src/classes/SupportPageCtrl_Test.cls
@isTest
public class SupportPageCtrl_Test {
    
    public static testmethod void test_supportpage(){
        
        Newsfeed__c faqtest = new Newsfeed__c(Name = DOL_AppConstants.NULL_EMPTY_STRING + 'testFAQ', Question__c = DOL_AppConstants.NULL_EMPTY_STRING + 'testQuestion', Answer__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Testanswer', Section__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Privacy and Security', External_Id__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Test_132456');
        insert faqtest;
        SupportPageCtrl cntrl = new SupportPageCtrl();
        
    }
}