src/objects/Application_Field__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Boostrap style for field</description>
        <inlineHelpText>Boostrap style for field</inlineHelpText>
        <label>Class Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Field_Styles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>This is the label for the field which appears on the portal.</description>
        <inlineHelpText>This is the label for the field which appears on the portal.</inlineHelpText>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to license reinstatement?</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a license renewal?</description>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Objects on portal</description>
        <inlineHelpText>Objects on portal</inlineHelpText>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Objects_on_portal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order  Number of the field</description>
        <label>Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>This is the subsection where the field is found.</description>
        <label>Parent</label>
        <referenceTo>Application_Subsection__c</referenceTo>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Permit_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>is this related to a permit renewal?</description>
        <label>Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit?</description>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Read_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a read-only field?</description>
        <inlineHelpText>Is this a read-only field?</inlineHelpText>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this required?</description>
        <inlineHelpText>Is this required?</inlineHelpText>
        <label>Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>These are the field options for fields shown on the portal</description>
        <inlineHelpText>These are the field options for fields shown on the portal</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Field_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validator__c</fullName>
        <description>Validation for the created field</description>
        <inlineHelpText>Validation for the created field</inlineHelpText>
        <label>Validator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Field_Validator</valueSetName>
        </valueSet>
    </fields>
    <label>Application Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Page__c.object
<CustomObject>
    <description>Page configuration for online applications</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for.</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is the license reinstatement.</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to License Renewal?</description>
        <inlineHelpText>Is this page applicable to License Renewal?</inlineHelpText>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to License?</description>
        <inlineHelpText>Is this page applicable to License?</inlineHelpText>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to Permit Renewal?</description>
        <inlineHelpText>Is this page applicable to Permit Renewal?</inlineHelpText>
        <label>Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to Permit?</description>
        <inlineHelpText>Is this page applicable to Permit?</inlineHelpText>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This  is the program related to the the permit</description>
        <label>Program Area</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Page</label>
    <nameField>
        <label>Application Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Section__c.object
<CustomObject>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this for license reinstatement?</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to the license renewal?</description>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number of the section</description>
        <label>Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Master of the section</description>
        <label>Parent</label>
        <referenceTo>Application_Page__c</referenceTo>
        <relationshipLabel>Application Sections</relationshipLabel>
        <relationshipName>Application_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Permit_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit renewal?</description>
        <label>Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit?</description>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Section</label>
    <nameField>
        <label>Sections Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Subsection__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This indicates if the subsection should be shown.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Name__c</fullName>
        <description>Component Name</description>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is the description that would appear on the portal</description>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this for license reinstatement?</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is related to any license renewal?</description>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is the related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number</description>
        <label>Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>This is the section that the subsection is found</description>
        <label>Parent</label>
        <referenceTo>Application_Section__c</referenceTo>
        <relationshipLabel>Application Subsections</relationshipLabel>
        <relationshipName>Application_Subsections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Permit_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to permit renewal?</description>
        <label>Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit?</description>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>to make subsection required</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of component</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Component_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Video_URL__c</fullName>
        <description>This is the link to the video if a  video is needed</description>
        <inlineHelpText>This is the link to the video if a  video is needed</inlineHelpText>
        <label>Video URL</label>
        <type>Url</type>
    </fields>
    <label>Application Subsection</label>
    <nameField>
        <label>Subsection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Subsections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Component_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Component</fullName>
    </customValue>
    <customValue>
        <fullName>Fieldset</fullName>
    </customValue>
    <description>Component Type</description>
    <masterLabel>Component Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Field_Styles.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>col-md-11</fullName>
    </customValue>
    <customValue>
        <fullName>col-md-4</fullName>
    </customValue>
    <customValue>
        <fullName>col-md-6</fullName>
    </customValue>
    <description>Different bootstrap classes for field</description>
    <masterLabel>Field Styles</masterLabel>
</GlobalValueSet>

src/globalValueSets/Field_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Formula</fullName>
    </customValue>
    <customValue>
        <fullName>Lookup</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Select</fullName>
    </customValue>
    <customValue>
        <fullName>Picklist</fullName>
    </customValue>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <description>Types of field on the portal</description>
    <masterLabel>Field Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Field_Validator.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>Text-Only</fullName>
    </customValue>
    <description>Field Validator</description>
    <masterLabel>Field Validator</masterLabel>
</GlobalValueSet>

src/globalValueSets/Objects_on_portal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main Object</fullName>
    </customValue>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Parent of Main Object</fullName>
    </customValue>
    <description>Objects on portal</description>
    <masterLabel>Objects on portal</masterLabel>
</GlobalValueSet>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/classes/PageDefService.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Name                : PageDefService
** Description         : 
**                       It also provides the data structure to determine the state for the Progress Bar
**                       The Progress Bar keeps track of what sections the user has visited/not visited, if the sections is complete/incomplete
**                       and if the Application has been reviewed and no errors were found. 
** Version             : 1.0
** Built By            : 
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Akosa Okwudiafor                  8/17/2018
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
************************************************************************************/
public class PageDefService {
    
    // public PageObj pageObj {get; set;}
    
    /**
* enum to determine the type of application we are working on
*/
    public enum ApplicationType { License, Renewal, Reinstatement, Permit, ServiceRequest,PermitRenewal}
    public PageObj pageObj {get; set;}
    
    public PageDefService(String board, String licenseType, ApplicationType t,String apptype) { 
        pageObj = new PageObj(board, licenseType, t,apptype, null);
    }
    public PageDefService(String board, String licenseType, ApplicationType t,String apptype, String serviceRequestType) { 
        pageObj = new PageObj(board, licenseType, t,apptype, serviceRequestType);
    }
    /**
* get the filter for the application type
*/
    public static String getApplicationTypeFilter(ApplicationType t) {
        String param = '';
        if (ApplicationType.License == t) {
            param = 'and License__c = true ';
        }
        if ((ApplicationType.Renewal == t)) {
            param = 'and License_Renewal__c = true ';
        }
        if ((ApplicationType.Reinstatement == t) ) {
            param = 'and License_Reinstatement__c = true ';
        }
        if (ApplicationType.Permit == t) {
            param = 'and Permit__c = true ';
        }
         if (ApplicationType.PermitRenewal == t) {
            param = 'and Permit_Renewal__c  = true ';
        }
        if (ApplicationType.ServiceRequest == t) {
            param = 'and Service_Request__c = true ';
        }
        return param;
    }
    
    /**
* this method handles the result of a save operation
* It determines if there were errors during the operation, if so, it changes the section
* status accordingly
* @see ValidationError
*/
    public void handleSaveOperation(Map<String,ValidationError.FieldError> errorMap) {
        // clear all the errors first
        //pageObj.removeFieldErrors(); not needed Save clears errors before upserting
        
        // for each error, find the Error under the pageObj and copy the error message
        // also, flag the section as incomplete if there was an error under that section
        
        for(String k: errorMap.keySet()) {
            //FieldObj fieldObj = pageObj.findField(k);
            //fieldObj.errorMessage =  errorMap.get(k).errorMessage;
            pageObj.setFieldError( k, errorMap.get(k).errorMessage );
        }
    }
    
    /** 
* conveninience method
* return the Serialized version of the sections
*/
    public String getAllSectionsSerialized() {
        return JSON.serialize( pageObj.sectionObjMap );
    }
    
    public String getAllSectionsAsListSerialized() {
        return JSON.serialize( pageObj.sectionObjMap.values() );
    }
    
    /**
* method to deserailize the page reference - this is when the user wants to do an edit operation
*/
    public void setAllSectionsAsList(String serializedListOfSections) {
        List<SectionObj> listSections = (List<SectionObj>)JSON.deserialize(serializedListOfSections, List<SectionObj>.class);
        pageObj = new PageObj(listSections);     
    }
    
    /**
* convenience method to serialized the State of the Page for the Progress Bar
* TODO: there could be a potential issue/errors when the serialized state of this Page 
*          is different from the current Page Definition because there have been updates 
*          to the metadata
*/
    public String getPageObjSerialized() {
        return JSON.serialize( pageObj );
    }
    
    /**
* convenience method to set the ProgressBarStatus
*/
    public void setSectionProgressBarStatus(Integer orderNumber, String status) {
        pageObj.findSection(orderNumber).progressBarStatus = status;
    }
    
    /**
* convenience method to get the Section Maps for a page as a List
*/    
    public List<SectionObj> allSectionsAsList {
        get{ return pageObj.sectionObjMap.values(); }
    }
    
    /**
* class representing a Field**/
    public class FieldObj {
        public String id {get; set;}
        public String name {get; set;}
        public String label {get; set;}
        public String sType {get; set;}        
        public String parent {get; set;}
        public String errorMessage {get; set;}
        public String className {get; set;}
        public Boolean readOnly {get; set;}
        public Boolean required {get; set;}
        public String objectName {get; set;}
        public String validator {get; set;}
        /**
* constructor
*/
        
        public FieldObj(String id, String name, String label, String sType, String parent, String className, Boolean readOnly, Boolean required, String objectName, String validator) {
            this.id = id;
            this.name = name;
            this.label = label;
            this.sType = sType;
            this.parent = parent;
            this.className = className;
            this.readOnly = readOnly;
            this.required = required;
            this.objectName = objectName;
            this.validator = validator;
        }
        
        public String debug() {
            return '---> field: ' + this.name + ' type: ' + sType;
        }
    }
    
    /**
* class representing a Sub-Section
* Ideally, we would want a subsection to use a reference to its parent as an object, but SFDC JSON.serialize method chokes
* complaining about a cycle reference
*/
    public class SubSectionObj {
        public String id {get; set;}
        public String componentName {get; set;}
        public String name {get; set;}
        public String description {get; set;}
        public String videoUrl {get;set;}
        public Decimal orderNumber {get; set;}
        public String sType {get; set;}
        public String parent {get; set;}
        public String progressBarStatus {get; set;}
        public String errorMessage {get; set;}
        public Map<String, FieldObj> fieldObjMap {get; set;}
        //added for DOL
        public boolean isRequired {get; set;}
        
        
        //added for DOL
        /************/
        public SubSectionObj(boolean isRequired,String name, String description, String componentName, Decimal orderNumber, String id, String sType, String parent, ApplicationType t) 
        {
            this.isRequired = isRequired;
            this.fieldObjMap = new Map<String, FieldObj>();
            this.name = name;
            this.description = description;
            this.componentName = componentName;  
            this.orderNumber = orderNumber;
            this.id = id;   
            this.sType = sType;
            this.parent = parent;
            String qry = 'select id, Name, Label__c, Type__c, Parent__c, Class_Name__c, Read_Only__c, Required__c, Object_Name__c, Validator__c ' +
                'from Application_Field__c ' +
                'where Parent__c = :id ' +
                getApplicationTypeFilter(t) +
                'order by Order_Number__c ASC';
            
            System.debug('qry '+qry);
            System.debug('Id '+Id);
            List<Application_Field__c> fieldList = Database.query(qry);
            
            // for each Field__c build a custom FieldObj
            for( Application_Field__c sObj: fieldList ) {
                fieldObjMap.put(sObj.Name, 
                                new FieldObj( sObj.Id, 
                                             sObj.Name,
                                             sObj.Label__c, 
                                             sObj.Type__c, 
                                             id,
                                             sObj.Class_Name__c,
                                             sObj.Read_Only__c,
                                             sObj.Required__c,
                                             sObj.Object_Name__c,
                                             sObj.Validator__c) );
                
            }
        }
        /************/
        
        // constructor
        public SubSectionObj(String name, String description, String componentName, Decimal orderNumber, String id, String sType, String parent, ApplicationType t) 
        {
            this.fieldObjMap = new Map<String, FieldObj>();
            this.name = name;
            this.description = description;
            this.componentName = componentName;  
            this.orderNumber = orderNumber;
            this.id = id;   
            this.sType = sType;
            this.parent = parent;
            String qry = 'select id, Name, Label__c, Type__c, Parent__c, Class_Name__c, Read_Only__c, Required__c, Object_Name__c, Validator__c ' +
                'from Application_Field__c ' +
                'where Parent__c = :id ' +
                getApplicationTypeFilter(t) +
                'order by Order_Number__c ASC';
            
            System.debug('qry '+qry);
            System.debug('Id '+Id);
            List<Application_Field__c> fieldList = Database.query(qry);
            
            // for each Field__c build a custom FieldObj
            for( Application_Field__c sObj: fieldList ) {
                fieldObjMap.put(sObj.Name, 
                                new FieldObj( sObj.Id, 
                                             sObj.Name,
                                             sObj.Label__c, 
                                             sObj.Type__c, 
                                             id,
                                             sObj.Class_Name__c,
                                             sObj.Read_Only__c,
                                             sObj.Required__c,
                                             sObj.Object_Name__c,
                                             sObj.Validator__c) );
                
            }
        }
        
        public SubSectionObj(String videoLink , String name, String description, String componentName, Decimal orderNumber, String id, String sType, String parent, ApplicationType t) 
        {
            this.videoUrl = videoLink ;            
            this.fieldObjMap = new Map<String, FieldObj>();
            this.name = name;
            this.description = description;
            this.componentName = componentName;  
            this.orderNumber = orderNumber;
            this.id = id;   
            this.sType = sType;
            this.parent = parent;
            String qry = 'select id, Name, Label__c, Type__c, Parent__c, Class_Name__c, Read_Only__c, Required__c, Object_Name__c, Validator__c ' +
                'from Application_Field__c ' +
                'where Parent__c = :id ' +
                getApplicationTypeFilter(t) +
                'order by Order_Number__c ASC';
            
                        System.debug('qry '+qry);
            System.debug('Id '+Id);
            List<Application_Field__c> fieldList = Database.query(qry);
            
            // for each Field__c build a custom FieldObj
            for( Application_Field__c sObj: fieldList ) {
                fieldObjMap.put(sObj.Name, 
                                new FieldObj( sObj.Id, 
                                             sObj.Name,
                                             sObj.Label__c, 
                                             sObj.Type__c, 
                                             id,
                                             sObj.Class_Name__c,
                                             sObj.Read_Only__c,
                                             sObj.Required__c,
                                             sObj.Object_Name__c,
                                             sObj.Validator__c) );
                
            }
        }
        
        public String debug() {
            String val =  '---> ' + label.Str_subsection + ': ' + this.name + label.Str_Contains + '' + fieldObjMap.values().size() + '' + label.Str_fields;
            for( FieldObj f: fieldObjMap.values() ) {
                val = val + f.debug();
            }
            return val;
        }
    }
    
    
    public class SectionObj {
        public String id {get; set;}
        public String name {get; set;}
        public Decimal orderNumber {get; set;}        
        public String progressBarStatus {get; set;}
        public Map<String, SubSectionObj> subSectionObjMap {get; set;}
        
        /**
* utility method used for debgging
*/
        public String debug() {
            String val =  '--->' + this.name + label.Str_Contains + '' + subSectionObjMap.values().size() + '' + label.Str_subsections;
            for( SubSectionObj ss: subSectionObjMap.values() ) {
                val = val = ss.debug();
            }
            return val;
        }
        
        public void flagSectionWithError() {
            this.progressBarStatus = label.Err_Error;
        }
        
        public void flagSectionAsInProgress() {
            this.progressBarStatus = label.ST_In_Progress;
        }
        
        public void flagSectionAsComplete() {
            this.progressBarStatus = label.Str_complete;
        }        
        
        public void flagSectionAsActive() {
            this.progressBarStatus = this.progressBarStatus + '' + label.ST_in_progress_active;
        }
        
        /**
* constructor
*/
        public SectionObj(String name, Decimal orderNumber, String id, String progressBarStatus, ApplicationType t) {
            this(name, orderNumber, id, t);
            this.progressBarStatus = label.ST_NOT_VISITED;
        }
        
        /**
* constructor
*/             
        public SectionObj(String name, 
                          Decimal orderNumber, 
                          String id,
                          ApplicationType t) {
                              this.subSectionObjMap = new Map<String, subSectionObj>();
                              this.name = name;
                              this.orderNumber = orderNumber;
                              this.id = id;   
                              // set by default the first section as active
                              if ( this.orderNumber == 1 ) {
                                  this.progressBarStatus = label.ST_in_progress_active;
                              }
                              // 20-03-19 - modified for DOL
                              String qry = 'select Id,Required__c , Video_URL__c ,Component_Name__c, Name, Description__c, Order_Number__c, Type__c, Parent__c ' +
                                  'from Application_Subsection__c ' +
                                  'where Parent__c = :id  and  active__c=true ' +
                                  getApplicationTypeFilter(t) +
                                  'order by Order_Number__c asc';
                              
                              List<Application_Subsection__c> subSectionList = Database.query(qry);
                              // for each SubSection__c build a custom SubSectionObj
                              // 20-03-19 - modified for DOL
                              for( Application_Subsection__c sObjSection: subSectionList ) {                             
                                  subSectionObjMap.put(sObjSection.Name, 
                                                                       new SubSectionObj( 
                                                                           sObjSection.Required__c,
                                                                           sObjSection.Name, 
                                                                           sObjSection.Description__c, 
                                                                           sObjSection.Component_Name__c, 
                                                                           sObjSection.Order_Number__c, 
                                                                           sObjSection.Id, 
                                                                           sObjSection.Type__c, 
                                                                           id,
                                                                           t
                                                                       ) 
                                                      );
                              }
                              
                          }
    }
    
    
    public class PageObj {
        public String pageName {get; set;}
        public ApplicationType t {get; set;}
        public Map<String, SectionObj> sectionObjMap {get; set;}
        public Integer reviewSectionNumber {get; set;} // the page knows the last section
        
        /**
* Need to determine when the user click on the reviewSection.
* When that happens, we need to tell that to validation logic - by setting
* the value to 99
* for instance , if on the UI the review section number is 6, 
* on the page Def service is also 6, but on the DB, it's 99
*/
        public Integer mapToDBSectionNumber(Integer iNumber) {
            if (iNumber == this.reviewSectionNumber) {
                return 99;
            }
            else {
                return iNumber;
            }
        }
        
        public String debug() {
            String val =  '--->' + this.pageName + label.Str_Contains + '' + sectionObjMap.values().size() + '' + label.Str_Sections;
            for( SectionObj sec: sectionObjMap.values() ) {
                val = val + sec.debug();
            }
            return val;
        }
        
        public PageObj(List<SectionObj> listSections) {
            this.sectionObjMap = new Map<String, SectionObj>();
            for( SectionObj s: listSections) {
                this.sectionObjMap.put(s.Name, s);  
            }            
        }
        
        // constructor
        public PageObj(String credentialtype, String credential, ApplicationType t,String apptype, String serviceRequestType) {
            
                 Set<String> allcredentials =Utilities.getallCredentials();
        Set<String> allplanreviewsandpermits =Utilities.getallPlanreviewsandpermits();
            this.t = t;
            System.debug(' credentialtype '+credentialtype);
             System.debug(' credential '+credential);
            sectionObjMap = new Map<String, SectionObj>();
            String qry='';
            if(allcredentials.contains(apptype)||apptype == Label.RNT_Renewal||apptype == Label.RNT_Reinstatement){
             qry = 'select id, Name, Order_Number__c, Parent__r.Name ,Parent__r.Credential__c, Parent__r.Credential_Type__c,License__c,License_renewal__c from Application_Section__c where ' +
                'Parent__r.Credential__c =:credential  and Parent__r.Credential_Type__c=: credentialtype ' +
                getApplicationTypeFilter(t) +
                'order by Order_Number__c asc';
            } 
            else if (allplanreviewsandpermits.contains(apptype )|| apptype == Label.Str_ManufacturedHomesRenewal){
                 qry = 'select id, Name, Order_Number__c, Parent__r.Name ,Parent__r.Credential__c, Parent__r.Credential_Type__c,License__c,License_renewal__c from Application_Section__c where ' +
                'Parent__r.Program_Area__c =: credentialtype and Parent__r.Permit_Type__c=:credential  ' +
                getApplicationTypeFilter(t) + 
                'order by Order_Number__c asc';
            }
            else if (apptype == Label.Str_Service_Request){
                Id pageId = null;
                for(Application_Page__c appPage : [Select Id, Credential__c, Credential_Type__c From Application_Page__c where Service_Request_Type__c = :serviceRequestType and Service_Request__c = true]){
                    if(appPage.Credential__c == credential && appPage.Credential_Type__c == credentialtype){
                        pageId = appPage.Id;
                    }else if((appPage.Credential__c == '' || appPage.Credential__c == null) && (appPage.Credential_Type__c == '' || appPage.Credential_Type__c == null)){
                        pageId = appPage.Id;
                    }
                }
                 qry = 'select id, Name, Order_Number__c, Parent__r.Name ,Parent__r.Credential__c, Parent__r.Credential_Type__c,License__c,License_renewal__c from Application_Section__c where ' +
                ' parent__c = :pageId order by Order_Number__c asc';
            }
            
            System.debug('qry '+qry);
            System.debug('credentialtype '+credentialtype);
            System.debug('credential '+credential);
            List<Application_Section__c> sectionList = Database.query(qry);
            this.buildSections(sectionList, t);           
            
        }
        
        /**
* method to set all sections as completed 
* when there aren't any errors during review and submit
*/
        public void handleReviewAndSubmitSuccess() {
            for( SectionObj sec : sectionObjMap.values() ) {
                if ( sec.orderNumber != reviewSectionNumber ) sec.flagSectionAsComplete();
            }        
        }        
        
        public void flagSectionAsActive(Integer sectionNum) {
            
            try{
                for( SectionObj sec : sectionObjMap.values() ) {
                    // Clear previously active section
                    if(sec.progressBarStatus == label.ST_in_progress_active){
                        sec.progressBarStatus = null;
                    }
                    // Add active section
                    if (sec.orderNumber == sectionNum) {
                        sec.progressBarStatus = label.ST_in_progress_active;
                    }
                }
            }catch(System.Exception e){
            SYstem.debug('e '+E);
            }
            
        }
        
        /**
* loop through all the sections for the page and build it 
*/
        private void buildSections(List<Application_Section__c> sectionList, ApplicationType t) {
            // for each Section__c build a custom SectionObj
            for( Application_Section__c sObjSection: sectionList ) {
                sectionObjMap.put(sObjSection.Name, 
                                  new SectionObj(sObjSection.Name, 
                                                 sObjSection.Order_Number__c, 
                                                 sObjSection.Id,
                                                 t) );
                this.reviewSectionNumber = (Integer)sObjSection.Order_Number__c; // set the value of the last section;
            }             
        }        
        
        /**
* find the parent section for the specified field
*/
        public SectionObj findSectionForField(String fieldName) {
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj ssObj: sectionObj.subSectionObjMap.values() ) {
                    if (ssObj.Name == fieldName) {
                        return sectionObj;
                    }                    
                }
            }    
            return null;            
        }
        
        /**
* find the specified field 
*/
        public FieldObj findField(String fieldName) {
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    for( FieldObj fieldObj : sSectionObj.fieldObjMap.values() ) {
                        if ( fieldObj.Name == fieldName) {
                            return fieldObj;
                        }
                    }    
                }
            } 
            return null;              
        }
        
        /**
* When a validation error occurs, we store the error message and flag the field.SubSection.Section as INCOMPLETE
* this had to be written in this way, ideally, we could just find a field and set its error value,
* then navigate the object tree to the field.subsection.section to set the section status
* but trying object references from child to parent caused JSON.serialize to choke - cycled object error
*/
        public void setFieldError(String fieldName, String errorMessage) {
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    for( FieldObj fieldObj : sSectionObj.fieldObjMap.values() ) {
                        if ( fieldObj.Name == fieldName) {
                            fieldObj.errorMessage = errorMessage;
                            sSectionObj.progressBarStatus = label.Err_Error;
                            sectionObj.progressBarStatus = label.Err_Error;
                        }
                    } 
                    
                    if(sSectionObj.componentName == fieldName) {
                        sSectionObj.errorMessage = errorMessage;
                        sSectionObj.progressBarStatus = label.Err_Error;
                        sectionObj.progressBarStatus = label.Err_Error;
                    }   
                }
            }            
        }
        
        /**
* clear all the fields error messages
* this is needed before save operations - right before we run the validations
*/
        public void removeFieldErrors() {
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    sSectionObj.errorMessage = null;
                    sSectionObj.progressBarStatus = null;
                    sectionObj.progressBarStatus = null;
                    for( FieldObj fieldObj : sSectionObj.fieldObjMap.values() ) {
                        fieldObj.errorMessage = null;
                        sSectionObj.progressBarStatus = null;
                        sectionObj.progressBarStatus = null;
                    }    
                }
            }            
        }
        
        /**
* utility method to get a list of all the fields that contain an error message
* When the save method completes, the pageDefinition is passed a list of errors and those error messages
* are populated on the appropriate field
* usefull for Test classes
*/
        public List<FieldObj> getAllFieldsWithError() {
            
            try{
                List<FieldObj> fieldObjList = new List<FieldObj>();
                for( SectionObj sectionObj: sectionObjMap.values() ) {
                    for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                        for( FieldObj fieldObj : sSectionObj.fieldObjMap.values() ) {
                            if (fieldObj.errorMessage != null) {
                                fieldObjList.add(fieldObj);
                            }
                        }    
                    }
                } 
                return fieldObjList; 
            }catch(System.Exception e){
                 SYstem.debug('e '+E);
                return null;
            }
            
        }        
        
        /**
* return all the fields names for the sections
* if any field is not added SQOL field missing exception occurs
*/
        public List<String> getAllFields() {
            List<String> fieldListName = new List<String>();
            
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    for( FieldObj fieldObj: sSectionObj.fieldObjMap.values() ) {
                        fieldListName.add( fieldObj.Name );
                    }
                }
            }
            return fieldListName;
        }
        
        /**
* return all the fields names for the sections
* if any field is not added SQOL field missing exception occurs
*/
        public List<FieldObj> getAllFieldObjects() {
            List<FieldObj> fieldList = new List<FieldObj>();
            
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    for( FieldObj fieldObj: sSectionObj.fieldObjMap.values() ) {
                        fieldList.add( fieldObj );
                    }
                }
            }
            return fieldList;
        }
        
        /**
* return all the fields names for the sections
* if any field is not added SQOL field missing exception occurs
*/
        public String getAllFieldsAsString() {
            List<String> fieldListName = new List<String>();
            
            for( SectionObj sectionObj: sectionObjMap.values() ) {
                for( SubSectionObj sSectionObj: sectionObj.subSectionObjMap.values() ) {
                    for( FieldObj fieldObj: sSectionObj.fieldObjMap.values() ) {
                        
                        if(fieldObj.objectName == label.Str_Main_Object||fieldObj.objectName == 'Parent of Main Object') {
                            fieldListName.add( fieldObj.Name );
                        }
                        else if(fieldObj.objectName == label.API_Contact) {
                            if(ApplicationType.License == t||ApplicationType.Permit == t) {
                                fieldListName.add( label.API_MUSW_Applicant_r + '.' + fieldObj.Name );
                            }
                            else {
                                fieldListName.add(label.API_Applicant_r + '.' + fieldObj.Name );
                            }
                        }
                        else if(fieldObj.objectName == label.API_Account) {
                            if(ApplicationType.License == t) {
                                fieldListName.add(label.API_MUSW_Primary_Licensee_r + '.' + fieldObj.Name );
                            }
                            else if(ApplicationType.Permit == t) {
                                //changed to Api_account_rel
                                fieldListName.add('MUSW__Account__r' + '.' + fieldObj.Name );
                            }
                            else {
                                fieldListName.add(label.API_Licensee_r + '.' + fieldObj.Name );
                            }
                        }
                    }
                }
            }
            // we need to add a ', ' to the query 
            if ( fieldListName.size() > 0 ) {
                return ', ' + String.join(fieldListName, ', ');
            }
            else {
                return '';
            }
        }        
        
        /**
* return the section identified by the orderNumber
*/
        public SectionObj findSection(Integer orderNumber) {
            List<SectionObj> sectionList = sectionObjMap.values();
            SectionObj section;
            for( SectionObj s: sectionList ) {
                if ( s.orderNumber == orderNumber ) {
                    section = s;
                    break;
                }
            }
            return section;
        }
        
    }
    
    
    
    
    
}