src/objects/Application_Page__c.object
<CustomObject>
    <description>Page configuration for online applications</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Types- Credential/License, Plan Review, Permit, etc.</description>
        <inlineHelpText>Application Types- Credential/License, Plan Review, Permit, etc.</inlineHelpText>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External ID for the record. Once populated, it should not be changed for that record as it may impact data loads to other environments.</description>
        <externalId>true</externalId>
        <inlineHelpText>External ID for the record. Once populated, it should not be changed for that record as it may impact data loads to other environments.</inlineHelpText>
        <label>External Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is the license reinstatement.</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to License Renewal?</description>
        <inlineHelpText>Is this page applicable to License Renewal?</inlineHelpText>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to License?</description>
        <inlineHelpText>Is this page applicable to License?</inlineHelpText>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this page applicable to Permit?</description>
        <inlineHelpText>Is this page applicable to Permit?</inlineHelpText>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Page</label>
    <nameField>
        <label>Application Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Section__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>License_Reinstatement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this for license reinstatement?</description>
        <label>License Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to the license renewal?</description>
        <label>License Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a license?</description>
        <label>License</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>Order Number of the section</description>
        <label>Order Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Master of the section</description>
        <label>Parent</label>
        <referenceTo>Application_Page__c</referenceTo>
        <relationshipLabel>Application Sections</relationshipLabel>
        <relationshipName>Application_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this related to a permit?</description>
        <label>Permit</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Section</label>
    <nameField>
        <label>Sections Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Automation_Rule__c.object
<CustomObject>
    <description>Automation Rule Outcomes to apply when specific data criteria is met.</description>
    <label>Automation Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Automation Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question based on which submission list record will be created</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Master Submission Lists</relationshipLabel>
        <relationshipName>Master_Submission_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Sequence_Number__c.object
<CustomObject>
    <description>Reset-able numbers and formats for tracking anything visible to constituents</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sequence Number</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Source Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sequence Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Newsfeed__c.object
<CustomObject>
    <description>The object for news feed items.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique Record Identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <description>This field is used to order the questions in a particular order</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DataMigrationUtilTest.cls
@isTest
private class DataMigrationUtilTest {

    static DataMigrationUtil dmu = new DataMigrationUtil('MUSW__Automation_Rule__c', 'Parent');
    static List<Newsfeed__c> newsFeed = new List<Newsfeed__c>();
    static List<Question__c> questions = new List<Question__c>();
    static List<MUSW__Sequence_Number__c> seqNumbers = new List<MUSW__Sequence_Number__c>();
    static List<Application_Page__c> pagesed = new List<Application_Page__c>();
    static List<Application_Section__c> sectionsed = new List<Application_Section__c>();
      static List<MUSW__Master_Submission_List__c> sublist = new List<MUSW__Master_Submission_List__c>();
    
    static {
        // setup test data        
        for (integer i = 0; i < 10; i++){
            newsFeed.add(new Newsfeed__c(Name = 'OHNF no.' + (i + 1),External_Id__c='i+1'+i,Application_type__c='Trades Credential'));
             sublist.add(new MUSW__Master_Submission_List__c(Name = 'OHNF no.' + (i + 1),External_Id__c='i+1'+i,Application_type__c='Trades Credential'));
            questions.add(new Question__c(External_Id__c='i+1'+i,Application_type__c='Trades Credential'));//sfxid__c = 'QuestionNumber' + (i + 1)
            seqNumbers.add(new MUSW__Sequence_Number__c(Name = 'SEQ no.' + (i + 1)));
            pagesed.add(new Application_Page__c(External_Id__c='i+1'+i,Application_type__c='Trades Credential'));
            sectionsed.add(new Application_Section__c(External_Id__c='i+1'));
        }
        insert questions;
    }
    
    @isTest static void testInsertRecords() {
        Test.startTest();
        List<Application_Section__c> sections = new  List<Application_Section__c>(); 
        Application_Page__c p = new Application_Page__c();
        p.Name = 'pageName';
        p.License__c = true;
        p.Permit__c = true;
        p.License_Renewal__c = true;
        p.License_Reinstatement__c = true;
        insert p;
    
        Application_Section__c s = new Application_Section__c();
        s.Name = 'Personal Information Test';
        s.Parent__c = p.Id;
        s.Order_Number__c = 1;
        s.License__c = true;
        s.Permit__c = true;
        s.License_Renewal__c = true;
        s.License_Reinstatement__c = true;
        insert s;
        
        s.External_Id__c=s.Id;
        update s;
        sections.add(s);

        dmu = new DataMigrationUtil('Application_Section__c', 'Application_Page__c');
        Boolean result = dmu.insertRecords(sections, 50000);
        System.assertEquals(result, true);
        Test.stopTest();
    }
    
    @isTest static void testInsertNewsRecords2() {
        Test.startTest();
        Database.insert(newsFeed, false);
        dmu = new DataMigrationUtil('Newsfeed__c', '');
        Boolean result = dmu.insertRecords(newsFeed, 50001);
        System.assertEquals(result, true);
        Test.stopTest();
    }
    
      @isTest static void testInsertSublist() {
        Test.startTest();
        Database.insert(sublist, false);
        dmu = new DataMigrationUtil('MUSW__Master_Submission_List__c', '');
        Boolean result = dmu.insertRecords(sublist, 50);
        System.assertEquals(result, true);
        Test.stopTest();
    }
    
    @isTest static void testInsertRecordsTestlimit() {
        Test.startTest();
        Database.insert(pagesed, false);
        Database.insert(sectionsed, false);
        dmu = new DataMigrationUtil('Application_Section__c', 'Application_Page__c');
        try{
             dmu.insertRecords(sectionsed, 5);
        }
        catch(Exception e){
            
        }
        Test.stopTest();
    }
    
    @isTest static void testInsertNewsRecords() {
        Test.startTest();
        Database.insert(newsFeed, false);
        dmu = new DataMigrationUtil('Newsfeed__c', '');
        Boolean result = dmu.insertNewsRecords(newsFeed);
        System.assertEquals(result, true);
        Test.stopTest();
    }

    @isTest static void testInsertQuestionRecords() {
        Test.startTest();
        Database.insert(questions, false);
        dmu = new DataMigrationUtil('Question__c', '');
        Boolean result = dmu.insertQuestionRecords(questions);
        System.assertEquals(result, true);
        Test.stopTest();
    }
    
    @isTest static void testInsertSequenceNumbers() {
        Test.startTest();
        seqNumbers.add(new MUSW__Sequence_Number__c(name='DEFAULT'));
        Database.insert(seqNumbers, false);
        dmu = new DataMigrationUtil('MUSW__Sequence_Number__c', '');
        Boolean result = dmu.insertSequenceNumbers(seqNumbers);
        System.assertEquals(result, true);
        Test.stopTest();
    }

    @isTest static void testPurgeRecords() {
        Test.startTest();
        dmu = new DataMigrationUtil('Application_Page__c', 'Parent');
        Boolean result = dmu.purgeRecords();
        System.assertEquals(result, true);
        Test.stopTest();
    }
}