src/objects/Associations__c.object
<CustomObject>
    <fields>
        <fullName>Child_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>License Relationships (Parent Licenses)</relationshipLabel>
        <relationshipName>Associations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Add</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Relationship</label>
    <nameField>
        <displayFormat>LRN-{0000000}</displayFormat>
        <label>License Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending Add</fullName>
                    <isActive>false</isActive>
                    <label>Pending Add</label>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                    <isActive>false</isActive>
                    <label>Pending Remove</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Polaris_RelationshipsUtilty.cls
public class Polaris_RelationshipsUtilty {
     
    @AuraEnabled 
    public static Polaris_RelationshipsUtilty.resultWrapper removeAssociationRecord(String associationId)
    {
        Polaris_RelationshipsUtilty.resultWrapper result;
        
        Database.SaveResult sr;
        
        Associations__c association = [SELECT id, Status__c,End_Date__c,Child_License__r.MUSW__Applicant__c FROM Associations__c where id=:associationId ];
        
         
        
        if(association != null ){
            
            association.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Canceled';
            
            association.End_Date__c = system.today();
            
            sr = Database.update(association,false);
             
            if(sr.isSuccess()){
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(True,'The association has been successfully removed');
              
                List<task> task = [select id,Whatid,Status from task where Whatid=:association.Id limit 1];
                
                if(!task.isEmpty()){
                    
                  task[0].Status = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed';
              }
              
              update task;
                
            }else{
            
             String Errormessage = DOL_AppConstants.NULL_EMPTY_STRING + 'Please contact system administrator\n';
             
             for(Database.Error err: sr.getErrors()){
                 
                 Errormessage = Errormessage+err.getFields()+' '+err.getMessage()+' '+err.getStatusCode()+'\n';
                 break;
             }
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(False,Errormessage);
            }
        }else{
            
           result  = new Polaris_RelationshipsUtilty.resultWrapper(false,'Please contact system administrator');
        }
        return result; 
    }
    
    @AuraEnabled 
    public static Polaris_RelationshipsUtilty.resultWrapper updateAssociationRecord(String associationId,String statusOfAssociation)
    {
        Polaris_RelationshipsUtilty.resultWrapper result;
        
        Database.SaveResult sr;
        
        Associations__c association = [SELECT id, Status__c,End_Date__c,Child_License__r.MUSW__Applicant__c FROM Associations__c where id=:associationId ];
        
         
        
        if(association != null && statusOfAssociation == 'Cancel' && statusOfAssociation == 'resend' && statusOfAssociation == 'remove'){
            
            if(statusOfAssociation == 'Cancel'){
                
                association.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Declined';
            }
            if(statusOfAssociation == 'resend'){
                
                association.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Invited';
            }
            if(statusOfAssociation == 'remove'){
                
                association.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Deleted';
            }
            
            sr = Database.update(association,false);
             
            if(sr.isSuccess()){
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(True,'The Operation has been successfull');
              
                List<task> task = [select id,Whatid,Status from task where Whatid=:association.Id limit 1];
                
                if(!task.isEmpty() && statusOfAssociation != 'resend'){
                    
                  task[0].Status = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed';
                  
                  
              }
              if(!task.isEmpty() && statusOfAssociation == 'resend'){
                    
                  task[0].Status = DOL_AppConstants.NULL_EMPTY_STRING + 'Pending';
                  
                  
              }
              
              update task;
                
            }else{
            
             String Errormessage = DOL_AppConstants.NULL_EMPTY_STRING + 'Please contact system administrator\n';
             
             for(Database.Error err: sr.getErrors()){
                 
                 Errormessage = Errormessage+err.getFields()+' '+err.getMessage()+' '+err.getStatusCode()+'\n';
                 break;
             }
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(False,Errormessage);
            }
        }else{
            
           result  = new Polaris_RelationshipsUtilty.resultWrapper(false,'Please contact system administrator');
        }
        return result; 
    }
    
    @AuraEnabled 
    public static Polaris_RelationshipsUtilty.resultWrapper removeAffliationRecord(String affliationId)
    {
        Polaris_RelationshipsUtilty.resultWrapper result;
        
        Database.SaveResult sr;
        
        MUSW__Account_Contact__c accountContact = [SELECT id, Status__c FROM MUSW__Account_Contact__c where id=:affliationId LIMIT 1];
        
        if(accountContact != null ){
            
           accountContact.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Deleted';
           
           sr = Database.update(accountContact,false);
           
            if(sr.isSuccess()){
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(True,'The association has been successfully removed');
              
                 List<task> task = [select id,Whatid,Status from task where Whatid=:accountContact.Id limit 1];
                
                    if(!task.isEmpty()){
                        
                      task[0].Status = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed';
                  }
              
                  update task;
                
            }else{
            
             String Errormessage = DOL_AppConstants.NULL_EMPTY_STRING + 'Please contact system administrator'+'\n';
             
             for(Database.Error err: sr.getErrors()){
                 
                 Errormessage = Errormessage+err.getFields()+' '+err.getMessage()+' '+err.getStatusCode()+'\n';
                 break;
             }
                
              result =  new Polaris_RelationshipsUtilty.resultWrapper(False,Errormessage);
            }
        }else{
            
           result  = new Polaris_RelationshipsUtilty.resultWrapper(false,'Please contact system administrator');
        }
        return result;  
    }
    
    public class resultWrapper{
        
        public boolean isSuccess;
        
        public String message;
        
        resultWrapper(boolean isSuccess, String Message){
            
            this.isSuccess = isSuccess;
            
            this.message = Message;
        }
    }
}