src/objects/Associate_Flag__c.object
<CustomObject>
    <description>This object is for create a flag based on severity</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associate Flags</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description for the flag to check</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Effective Date</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <formula>CASE(TEXT(Severity__c), 
&apos;Low&apos;, Image(&apos;/resource/Flag_Low&apos;, &apos;Good&apos;, 30, 30),
&apos;Medium&apos;, Image(&apos;/img/msg_icons/warning32.png&apos;, &apos;Warning&apos; , 30, 30),
&apos;High&apos;, Image(&apos;/img/msg_icons/error32.png&apos;, &apos;Bad&apos;, 30, 30),
&apos;Info&apos;, Image(&apos;/img/msg_icons/info32.png&apos;, &apos;Bad&apos;, 30, 30),
&apos;&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flag</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Associate Flag</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Flag Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associate Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Name_Value_Pair__mdt.object
<CustomObject>
    <description>To store name value pairs - similar to key value pairs in a map</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value field for name value pair</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Name Value Pair</label>
    <pluralLabel>Name Value Pairs</pluralLabel>
</CustomObject>

src/classes/FlagContact_CC.cls
/*************************************************************************************************************
** User Story: 283 -- Adding Alerts to a Contact
**************************************************************************************************************
** Class Name    : FlagContact_CC
** Description   : Controller for Contact Related List (Associate Flag)
** Version       : 1.0
** Built By      : Srikanth Kottam
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Srikanth Kottam                07/20/2018                    1                          Created
** 
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
**************************************************************************************/
public class FlagContact_CC {
    //Set up the standard controller connection and get current record 
    ApexPages.StandardController controller;
    public contact record {get; set;}
    public list<Associate_Flag__c> lstFlag {get; set;}
    public String flagObjectPrefix;
    public String contactFieldId;
    public Boolean isContactOnHold {get; set;}
    
    public FlagContact_CC(ApexPages.StandardController controller){
        this.controller = controller;
        this.record = (contact)controller.getrecord();
        
        lstFlag = [SELECT Id, Name, Flag__c, Description__c, Severity__c, Effective_Date__c, End_Date__c FROM Associate_Flag__c  WHERE Contact__c =: record.id];  
   		
   		flagObjectPrefix = Schema.getGlobalDescribe().get('Associate_Flag__c').getDescribe().getKeyPrefix();
   		List<Name_Value_Pair__mdt> lstNVP = [Select Value__c from Name_Value_Pair__mdt where DeveloperName = 'FlagContactId'];
   		if(lstNVP.size() > 0){
   			contactFieldId = lstNVP[0].Value__c;
   		}
        
        isContactOnHold = false;
        Contact con = [Select Contact_Status__c From Contact where Id = :record.Id];
        if(con.Contact_Status__c == 'On Hold'){
            isContactOnHold = true;
        }
    } 
    public pagereference customnew() {
        
        PageReference pageRef;   
            
        contact con = [select id, name from contact where id =: Record.Id];
        String url = '/' + flagObjectPrefix + '/e?' + contactFieldId + '=' + con.name + '&' + contactFieldId + '_lkid=' + con.Id;
        
        pageRef =new PageReference(url);
        pageRef.setRedirect(true);
        
        return pageRef;
    }
}