src/objects/Associations__c.object
<CustomObject>
    <fields>
        <fullName>Association_Type__c</fullName>
        <label>Association Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Designated Architect</fullName>
                </value>
                <value>
                    <fullName>Designated Funeral Director</fullName>
                </value>
                <value>
                    <fullName>Designated Engineer</fullName>
                </value>
                <value>
                    <fullName>Designated Land Surveyor</fullName>
                </value>
                <value>
                    <fullName>Appraiser Trainee</fullName>
                </value>
                <value>
                    <fullName>Funeral Director Intern</fullName>
                </value>
                <value>
                    <fullName>Embalmer Intern</fullName>
                </value>
                <value>
                    <fullName>Timeshare Salesperson</fullName>
                </value>
                <value>
                    <fullName>Camping Resort Salesperson</fullName>
                </value>
                <value>
                    <fullName>Authorized Location</fullName>
                    <isActive>false</isActive>
                    <label>Authorized Location</label>
                </value>
                <value>
                    <fullName>Designated Controlling Person</fullName>
                    <isActive>false</isActive>
                    <label>Designated Controlling Person</label>
                </value>
                <value>
                    <fullName>Designated Person</fullName>
                    <isActive>false</isActive>
                    <label>Designated Person</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Child_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>License Relationships (Parent Licenses)</relationshipLabel>
        <relationshipName>Associations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_License__c</fullName>
        <label>Parent License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>License Relationships (Child Licenses)</relationshipLabel>
        <relationshipName>Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Add</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Relationship</label>
    <nameField>
        <displayFormat>LRN-{0000000}</displayFormat>
        <label>License Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Licensing_RelationShip__mdt.object
<CustomObject>
    <fields>
        <fullName>Child_License_Credential__c</fullName>
        <label>Child License Credential</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Columns_To_Dsiplay_In_Professional_Dashb__c</fullName>
        <label>Columns To Dsiplay In Professional Dashb</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Childs_Allowed__c</fullName>
        <label>Max Childs Allowed</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_License_Credential__c</fullName>
        <label>Parent License Credential</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Popup_Error_Message__c</fullName>
        <label>Popup (Error) Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Licensing Relationship</label>
    <pluralLabel>Licensing Relationships</pluralLabel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Branch Licenses</relationshipLabel>
        <relationshipName>Branch_Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/AssociationUtility.cls
/**
 * 
    Trigger Name    : AssociationUtility
    Description     : Utility Methods of Associations__c object. 
    Created By      : Deloitte Inc.,
    Created Date    : 19th June 2019
    Modification Log:
    -------------------------------------------------------------------------------------------------------------
    Developer                   Date                        Description
    --------------------------------------------------------------------------------------------------------------            
    Pramod                   19 june 2019                  Initial Creation

*/
public class AssociationUtility {

    public static void restrictChildLicensesCount(List<Associations__c> triggerNewAssociationList){
        
   	 Set<Id> parentIds =new Set<Id>();
   	 
   	 Map<id,String> parentLicenseId2LicenseNameMap = new Map<id,String>();
   	 
   	 Map<id,String> childLicenseId2LicenseNameMap = new Map<id,String>();
   	 
   	 Map<id,List<Id>> parentLicense2ChildLicenseIdListMap = new Map<id,List<Id>>();
   	 
   	 Map<String,String> parent2ChildLicenseTypes_cstm_mdtMap = new Map<String,String>();
   	 
   	 Set<id> parentIdsMaxedOut = new Set<id>();
   	 
   	 Map<String, Integer> parentLicense2MaxChildCountMap = new Map<String, Integer>();
   	 
   	 Map<String, String> parentLicense2ErrorMessage = new Map<String, String>();
   	 
   	 
   	 
   	 for(Licensing_RelationShip__mdt licenseRelation_Metadata: [SELECT Child_License_Credential__c,Columns_To_Dsiplay_In_Professional_Dashb__c,DeveloperName,Id,Is_Parent__c,Label,Language,MasterLabel,Max_Childs_Allowed__c,NamespacePrefix,Parent_License_Credential__c,Popup_Error_Message__c,QualifiedApiName FROM Licensing_RelationShip__mdt]){
   	     
   	     if(licenseRelation_Metadata.Is_Parent__c && licenseRelation_Metadata.MasterLabel!=null && licenseRelation_Metadata.Child_License_Credential__c != null){
   	         
   	         parent2ChildLicenseTypes_cstm_mdtMap.put(licenseRelation_Metadata.MasterLabel, licenseRelation_Metadata.Child_License_Credential__c);
   	         
   	         parentLicense2MaxChildCountMap.put(licenseRelation_Metadata.MasterLabel, (Integer)licenseRelation_Metadata.Max_Childs_Allowed__c);
   	         
   	         parentLicense2ErrorMessage.put(licenseRelation_Metadata.MasterLabel, licenseRelation_Metadata.Popup_Error_Message__c);
   	         
   	     } 
   	     
   	 }
   	 
   	 for(Associations__c assocObj : triggerNewAssociationList){
   	     
   	     if(assocObj.Parent_License__c != null ){
   	         
   	         parentIds.add(assocObj.Parent_License__c);
   	     }
   	     
   	 }
   	 
   	 List<Associations__c> siblingAssociationRecords = [SELECT Association_Type__c,Child_License__c,Id,Parent_License__c, Parent_License__r.Credential_Type__c, Child_License__r.Credential_Type__c 
   	                                                    FROM Associations__c 
   	                                                    where Status__c = 'Active' AND
   	                                                          Parent_License__c IN: parentIds];
   	 
        
      for(Associations__c siblingassociationRecord :siblingAssociationRecords){

          parentLicenseId2LicenseNameMap.put(siblingassociationRecord.Parent_License__c, siblingassociationRecord.Parent_License__r.Credential_Type__c);
          
          childLicenseId2LicenseNameMap.put(siblingassociationRecord.Child_License__c, siblingassociationRecord.Child_License__r.Credential_Type__c);
          
          if(parentLicense2ChildLicenseIdListMap.containsKey(siblingassociationRecord.Parent_License__c)){
              
            parentLicense2ChildLicenseIdListMap.get(siblingassociationRecord.Parent_License__c).add(siblingassociationRecord.Child_License__c);
            
          }else{
              
              parentLicense2ChildLicenseIdListMap.put(siblingassociationRecord.Parent_License__c, new List<Id>{siblingassociationRecord.Child_License__c});
          }
     }
     
     system.debug('AssociationUtility :: restrictChildLicensesCount all relationships'+JSON.serialize(parentLicense2ChildLicenseIdListMap)); 
     
     for(Id parentLicense_id :parentLicense2ChildLicenseIdListMap.keyset()){
         
         String parentLicenseName = parentLicenseId2LicenseNameMap.get(parentLicense_id);
          
          Integer count_Childs = 0;
          
          Integer Max_Childs_Allowed  = parentLicense2MaxChildCountMap.get(parentLicenseName);
          
          for(Id childLicense_id : parentLicense2ChildLicenseIdListMap.get(parentLicense_id)){
              
              String childLicenseName = childLicenseId2LicenseNameMap.get(childLicense_id);
              
              if(childLicenseName ==  parent2ChildLicenseTypes_cstm_mdtMap.get(parentLicenseName)){
                  
                  count_Childs++;
                  
                  if(count_Childs > Max_Childs_Allowed){
                      
                      parentIdsMaxedOut.add(parentLicense_id);
                      
                  }
                  
              }
          }
         
     }
     
     for(Associations__c assoc_Obj: triggerNewAssociationList){
         
         system.debug('In Restrict CHild license COunt........'+JSON.serialize(assoc_Obj));
         system.debug('In Restrict CHild license COunt........ maxed out'+JSON.serialize(parentIdsMaxedOut));
         
         if(parentIdsMaxedOut.contains(assoc_Obj.Parent_License__c)){
             
             if(parentLicenseId2LicenseNameMap.containsKey(assoc_Obj.Parent_License__c) && parentLicense2ErrorMessage.containsKey(parentLicenseId2LicenseNameMap.get(assoc_Obj.Parent_License__c)) && parentLicense2ErrorMessage.get(parentLicenseId2LicenseNameMap.get(assoc_Obj.Parent_License__c)) != null){
               assoc_Obj.addError(parentLicense2ErrorMessage.get(parentLicenseId2LicenseNameMap.get(assoc_Obj.Parent_License__c)));  
             }else{
                assoc_Obj.addError('You had reached the Maximum Limit of licensees');    
             }
             
             
         }
     }
          
    }
        
        
}