src/objects/Auto_Renew_Reinstate__mdt.object
<CustomObject>
    <description>Licenses that should be Auto Renewed and Auto Reinstated.</description>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auto Renew/Reinstate</label>
    <pluralLabel>Auto Renew/Reinstates</pluralLabel>
</CustomObject>

src/objects/BGCK__Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <label>Answer Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Reinstatement Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Applicant_Full_Name__c</fullName>
        <description>Built for referencing in letters</description>
        <formula>MUSW__Applicant__r.FirstName &amp; &apos; &apos; &amp; MUSW__Applicant__r.MiddleName &amp; &apos; &apos; &amp; MUSW__Applicant__r.LastName</formula>
        <label>Applicant Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Late_Renewal_Eligible__c</fullName>
        <description>Formula to determine Late Renewal Eligibility</description>
        <formula>IF((TODAY()&gt;MUSW__Expiration_Date__c &amp;&amp; TODAY()&lt;= Late_Renewal_Eligible_End_Date__c &amp;&amp; (ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;) ||  ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Late Renewal&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Hold&apos;))), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Late Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Reinstatement_Eligible__c</fullName>
        <description>Formula to check Reinstatement Eligibility</description>
        <formula>IF(AND(OR((TODAY() &gt; Late_Renewal_Eligible_End_Date__c &amp;&amp; ( ISPICKVAL(MUSW__Status__c, &apos;Canceled&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;))), 
(AND ( OR (ISPICKVAL(Credential_Type__c, &apos;Temporary Certified General&apos;), ISPICKVAL(Credential_Type__c, &apos;Temporary State Licensed&apos;), ISPICKVAL(Credential_Type__c, &apos;Temporary Certified Residential&apos;)), OR( ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;), ISPICKVAL(MUSW__Status__c, &apos;Active&apos;), ISPICKVAL(MUSW__Status__c, &apos;Canceled&apos;)) ))), 
(NOT(OR(ISPICKVAL(Credential_Type__c, &apos;Funeral Establishment&apos;), ISPICKVAL(Credential_Type__c, &apos;Crematory&apos;), ISPICKVAL(Credential_Type__c, &apos;Certificate of Removal Registration&apos;), ISPICKVAL(Credential_Type__c, &apos;Funeral Establishment Branch&apos;), ISPICKVAL(Credential_Type__c, &apos;Cremated Remains Disposition Permit&apos;))))) 
, TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Reinstatement Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Issue_Date__c</fullName>
        <description>Date when license was issued</description>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Renewal_Date__c</fullName>
        <description>Date when the license was renewed</description>
        <inlineHelpText>Date License was renewed or extended</inlineHelpText>
        <label>Renewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <description>This is the record type for Course Information</description>
        <label>Course</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the review.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved with Conditions</fullName>
                </value>
                <value>
                    <fullName>Corrections Required</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Exam Approved</fullName>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Audit Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <formula>License__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>License Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Type__c</fullName>
        <description>Type of reinstatement.</description>
        <label>Renewal Reinstatement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal PTO</fullName>
                </value>
                <value>
                    <fullName>Renewal Plan Review</fullName>
                </value>
                <value>
                    <fullName>ReinstatementPTO</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPTO</label>
                </value>
                <value>
                    <fullName>ReinstatementPlanReview</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPlanReview</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <description>This is the renewal status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Renewal_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Renewal_Application__c.object
    <fields>
        <fullName>Applicant_Full_Name__c</fullName>
        <formula>Applicant__r.FirstName &amp; &apos; &apos; &amp; Applicant__r.MiddleName &amp; &apos; &apos; &amp; Applicant__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Applicant Full Name</label>
        <type>Text</type>
    </fields>

objects/Renewal_Application__c.object
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <label>Course</label>
    </recordTypes>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Renewal_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Generate Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In-Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submission Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Third Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Applicant Action</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Additional Qualifications</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
        <isActive>false</isActive>
    </customValue>
    <masterLabel>Renewal Status</masterLabel>
</GlobalValueSet>

src/classes/RenewalReinstatement.cls
public class RenewalReinstatement{
  
public static Map<Id,Boolean> autoRenewReinstatement(List<Renewal_Application__c> renewReinstateList){
    Map<Id,Boolean> autoIdRenwewalMap = new Map<Id,Boolean>();
    Set<Id> setId = new Set<Id>();
    system.debug('renewReinstateList-----'+renewReinstateList);
    Set<Id> licenseSet = new Set<Id>();
    Map<Id,Date> idDateMap= new Map<Id,Date>();
    for(Renewal_Application__c renewreinstate :renewReinstateList ){
        setId.add(renewreinstate.id);
        licenseSet.add(renewreinstate.License__c);
    }
    
    for(MUSW__License2__c  msl: [select id,MUSW__Expiration_Date__c from MUSW__License2__c where id IN: licenseSet]){
        idDateMap.put(msl.id,msl.MUSW__Expiration_Date__c );
    }
    
    List<BGCK__Answer__c> ansList = [select id,Answer_Text__c,QuestionDOL__c,Renewal_Reinstatement_Application__c from BGCK__Answer__c where Renewal_Reinstatement_Application__c IN:setId AND QuestionDOL__r.Section__c =: DOL_AppConstants.NULL_EMPTY_STRING + 'Legal Background Questions' AND QuestionDOL__r.Data_Type__c =: DOL_AppConstants.NULL_EMPTY_STRING + 'Yes_No' ];
    system.debug('ansList---'+ansList);
    
    Map<id,Boolean> reneUpdate = new Map<id,Boolean>();
    
    List<MUSW__License2__c> licenseList = new List<MUSW__License2__c>();
    
    if(!ansList.isEmpty()){
       for(Renewal_Application__c rene : renewReinstateList ){
            Integer numberOfQue = 0;
            Integer numberOfNo = 0;
            for(BGCK__Answer__c ans : ansList){
                if(ans.Renewal_Reinstatement_Application__c == rene.Id){
                    numberOfQue++;
                    if(ans.Answer_Text__c == 'No'){
                        numberOfNo++;
                    }
                }
            }
            system.debug('rene ---'+rene);
            system.debug('rene ---'+rene.Renewal_Status__c);
            system.debug('rene ---'+rene.License__c);
            system.debug('rene ----'+rene.License__r.MUSW__Expiration_Date__c);
            if(rene.Renewal_Status__c == 'Pending Payment' && numberOfQue != 0 && (numberOfQue == numberOfNo)){
                MUSW__License2__c license = new MUSW__License2__c(id= rene.License__c);
                license.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Active';
                license.Application_Type__c = rene.Application_Type__c;
                license.MUSW__Issue_Date__c = System.today();
                system.debug('MUSW__Issue_Date__c ::'+license.MUSW__Issue_Date__c);
                license.MUSW__Renewal_Date__c = System.today();
                license.Renew_Reinstatement_in_progress__c = false;
                system.debug('MUSW__Renewal_Date__c i.e. Renewed/Reinstated Date::'+license.MUSW__Renewal_Date__c);
                /*if(rene.License__r.Is_Late_Renewal_Eligible__c || rene.License__r.Is_Reinstatement_Eligible__c){
                
                    license.MUSW__Issue_Date__c = System.today();
                    system.debug('MUSW__Issue_Date__c ::'+license.MUSW__Issue_Date__c);
                }else{
                    if(idDateMap.get(rene.License__c) != null){
                        license.MUSW__Issue_Date__c  = idDateMap.get(rene.License__c) + 1;
                        system.debug('MUSW__Issue_Date__c ::'+license.MUSW__Issue_Date__c);
                    }
                } */   
                
                licenseList.add(license);  
                system.debug('licenseList---'+licenseList);
                autoIdRenwewalMap.put(rene.Id,true);
            }   
        } 
    }
        
        
        if(!licenseList.isEmpty()){
           update licenseList;
        }
        
        return autoIdRenwewalMap;
    }
    
    @future
    public static void createReviewOnRenewal(List<Id> renewalIdList){
       try{ 
           system.debug('renewalIdList::'+ renewalIdList);
           Map<Id,Boolean> autoReneMap = new Map<Id,Boolean>();
           List<MUSW__Review__c> revList = new List<MUSW__Review__c>();
           Set<MUSW__Review__c> setReview = new Set<MUSW__Review__c>();
           List<MUSW__Review__c> resultRevList = new List<MUSW__Review__c>();
           List<Renewal_Application__c> renewList = new List<Renewal_Application__c>();
           List<Renewal_Application__c> renewToUpdate = new List<Renewal_Application__c>();
           List<String> LicensetoRenew =  new List<String>();
           List<String> LicensetoReinstate = new List<String>();
           List<Auto_Renew_Reinstate__mdt> renewMdt = [select Id,DeveloperName,License_Type__c  from Auto_Renew_Reinstate__mdt where DeveloperName =: DOL_AppConstants.NULL_EMPTY_STRING + 'Auto_Renewal' and DeveloperName != null limit 1];
           LicensetoRenew = (!renewMdt.isEmpty()) ? renewMdt[0].License_Type__c.split(',') : null;
           system.debug('LicensetoRenew::'+ LicensetoRenew);
           List<Auto_Renew_Reinstate__mdt> reinstateMdt = [select Id,DeveloperName,License_Type__c  from Auto_Renew_Reinstate__mdt where DeveloperName =: DOL_AppConstants.NULL_EMPTY_STRING + 'Auto_Reinstate' and DeveloperName != null limit 1];
           LicensetoReinstate = (!reinstateMdt.isEmpty())?reinstateMdt[0].License_Type__c.split(',') : null;
           system.debug('LicensetoReinstate::'+ LicensetoReinstate);
           List<Renewal_Application__c> getRenewRecords = [select id,Name,License__r.MUSW__Expiration_Date__c,Renewal_Status__c,licenserecordtype__c,AccountStatus__c,Physical_Address_Modified__c,renewal_reinstatement_type__c,license_business_name__c,license_number__c,applicant_full_name__c,License__c,application_type__c,Credential_Type__c from Renewal_Application__c where id IN:renewalIdList];
           system.debug('inside renewal');
           for(Renewal_Application__c renewal : getRenewRecords){
               System.debug('renewal:: '+renewal.Renewal_Status__c );
               system.debug('renewal.License__r.MUSW__Primary_Licensee__r.AccountStatus__c ');
               if(renewal.Renewal_Status__c == 'Pending Payment' && renewal.LicenseRecordType__c == DOL_AppConstants.BUSINESS && renewal.AccountStatus__c == DOL_AppConstants.ACTIVE){
                   system.debug('accc'+LicensetoRenew);
                   if(renewal.Renewal_Reinstatement_Type__c == 'Renewal' && LicensetoRenew!= null && LicensetoRenew.contains(renewal.Credential_Type__c) && (renewal.Physical_Address_Modified__c != true)){
                       system.debug('acc2Insidetext');
                       renewList.add(renewal);
                   }else if(renewal.Renewal_Reinstatement_Type__c == 'Reinstatement' && LicensetoReinstate !=null && LicensetoReinstate.contains(renewal.Credential_Type__c) && (renewal.Physical_Address_Modified__c != true)){
                       renewList.add(renewal);
                   }
               }
               else if(renewal.Renewal_Status__c == 'Pending Payment' && renewal.LicenseRecordType__c != DOL_AppConstants.BUSINESS ){
                   system.debug('inside inreview'+LicensetoRenew);
                   if(renewal.Renewal_Reinstatement_Type__c == 'Renewal' && LicensetoRenew!= null && LicensetoRenew.contains(renewal.Credential_Type__c) && renewal.Physical_Address_Modified__c != true){
                       system.debug('acc2');
                       renewList.add(renewal);
                   }else if(renewal.Renewal_Reinstatement_Type__c == 'Reinstatement' && LicensetoReinstate !=null && LicensetoReinstate.contains(renewal.Credential_Type__c) && (renewal.Physical_Address_Modified__c != true)){
                       renewList.add(renewal);
                   }
                   
               }
           }
           if(!renewList.isEmpty()){
               autoReneMap = autoRenewReinstatement(renewList);
           }
           for(Renewal_Application__c ren : getRenewRecords){
                MUSW__Review__c rev = new MUSW__Review__c();
                rev.name = (ren.licenserecordtype__c == 'Business' || ren.licenserecordtype__c == 'Course') ? (ren.renewal_reinstatement_type__c + ' Review - '+ ren.license_business_name__c + '/'+ ren.license_number__c) : (ren.renewal_reinstatement_type__c + ' Review - '+ ren.applicant_full_name__c + '/'+ ren.license_number__c) ;
                rev.MUSW__Status__c = (autoReneMap.keyset().contains(ren.id)) ? 'Approved' : 'Pending';
                rev.Application_Type__c = ren.application_type__c;
                rev.License_Type__c = ren.Credential_Type__c;
                rev.Review_Type__c = ren.renewal_reinstatement_type__c;
                rev.License__c = ren.License__c;
                rev.Renewal_Application__c = ren.id;
                revList.add(rev);
                if(autoReneMap.keyset().contains(ren.id)){
                   ren.Auto_Renew__c = autoReneMap.get(ren.id);
                   ren.Renewal_Status__c = DOL_AppConstants.COMPLETE;
                   
                }else{
                    ren.Renewal_Status__c = DOL_AppConstants.IN_REVIEW;
                }
                renewToUpdate.add(ren);
           
           }
           setReview.addAll(revList);
           resultRevList.addAll(setReview);
           if(!resultRevList.isEmpty()){
                insert resultRevList;
           }
           if(!renewToUpdate.isEmpty()){
                update renewToUpdate;
            } 
          }catch(Exception ex){
                DOL_CreateErrorLog_Exception.logApplicationError(ex);
          }
    }
}