src/objects/BGBK__Bill__c.object
<CustomObject>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship with Permit</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Total_Fees__c</fullName>
        <description>Sum of the Amount field less the Waived Amount of all fees related to this record.</description>
        <label>Total Fees</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Universal_Default_License_Record_Type</fullName>
        <active>true</active>
        <description>This is the record type if the application type doesn&apos;t appear on any other record types.</description>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Generate_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is checked when answered Yes to generate invoice</description>
        <label>Generate Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Total_Fees__c</fullName>
        <description>Total amount owing against this permit. This is automatically calculated.</description>
        <inlineHelpText>Automatically Refreshed after Fee updates</inlineHelpText>
        <label>Total Fees</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Generate_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is checked when answered Yes to generate invoice</description>
        <label>Generate Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Fees__c</fullName>
        <description>Total Fees</description>
        <label>Total Fees</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UtilitiesTest.cls
@isTest
public class UtilitiesTest 
{
    public static Id ContactId;
    public static Id AccountId;
    @testSetup static void setup() {
        Account acc = new Account();
        acc = CreateTestDataUtility.createAccount();
        insert acc;
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        insert con;  
        ContactId = con.Id;
        MUSW__Permit2__c activePermit = CreateTestDataUtility.createPermit(acc.Id, con.Id);
        activePermit.musw__status__c = 'Active';
        List<MUSW__Permit2__c> permits = new List<MUSW__Permit2__c>{activePermit};
        insert permits;
        Renewal_Application__c renewalApplication = new Renewal_Application__c(Permit__c = permits[0].Id);
        insert renewalApplication;
    }
    
    public static testmethod void unitTestForRecordTypeCheck()
    {
        Test.startTest ();
        Id recId = [Select Id from RecordType where DeveloperName = 'Universal_Default_License_Record_Type' and sObjectType = 'MUSW__License2__c' limit 1 ].Id  ;
        
        system.assertEquals(recId,Utilities.getRecordTypeForName('MUSW__License2__c' , 'Universal Default License Record Type') ) ;
        Test.stopTest ();	
    }
    
    public static testMethod void unitTestToCheckGuestUser()
    {
        Test.startTest ();
        //Below should assert
        system.assert(!Utilities.isGuestUserLoggedIn()) ;
        
        // Create contact 
        Account acct = new Account(Name = 'Citizen') ;
        INSERT acct ;
        Contact profileRecord = new Contact(FirstName='Mr Profile ' , LastName = 'demo LastName' , AccountId = acct.Id ) ;
        INSERT profileRecord ;
        
        Contact con2 = Utilities.getFullProfileDetails(profileRecord.Id) ;
        
        system.assertEquals(profileRecord.Id , con2.Id) ;
        
        // All fields getAllFieldsSObject
        
        List<String> fieldsList = Utilities.getAllFieldsSObject('Contact' , new set<string>{'FirstName','LastName'}) ;
        List<String> fieldsLists = Utilities.getAllFieldsSObject('Contact' , new set<string>{'FirstName','LastName'},true) ;
        system.assert(fieldsList.size() > 0 ) ;
        Test.stopTest ();
    }    
    
    public static testMethod void checkedBlockedEmails()
    {
        Test.startTest ();
        //Below should assert
        system.assert(!Utilities.isGuestUserLoggedIn()) ;
        
        // Create contact 
        Account acct = new Account(Name = 'Citizen') ;
        INSERT acct ;
        Contact profileRecord = new Contact(FirstName='Mr Profile ' , LastName = 'demo LastName' , AccountId = acct.Id ,email='testing@test.com') ;
        INSERT profileRecord ;
        Utilities.checkBlockedEmail(profileRecord);
        utilities.runningInASandbox();
        Test.stopTest ();
    }    
    
    @isTest
    public static void testCreateInvoiceFail(){
        MUSW__Permit2__c permit = [Select Id from MUSW__Permit2__c limit 1];
        Test.startTest();
        Utilities.createInvoice(permit);
        Test.stopTest();
        List<BGBK__Bill__c> invoices = [Select Id from BGBK__Bill__c];
        System.assert(invoices.size() == 0, 'Invoices should not be created');
    }
    
    @isTest
    public static void testCreateInvoiceForPermit(){
        MUSW__Permit2__c permit = [Select Id from MUSW__Permit2__c limit 1];
        permit.Generate_Invoice__c = true;
        permit.MUSW__Total_Fees__c = 150.00;
        update permit;
        Test.startTest();
        Utilities.createInvoice(permit);
        Test.stopTest();
        List<BGBK__Bill__c> invoices = [Select Id from BGBK__Bill__c];
        System.assert(invoices.size() == 1, 'One Invoices should be created');
    }
    
    @isTest
    public static void testCreateInvoiceForPermitRenwal(){
        Renewal_Application__c renewal = [Select Id from Renewal_Application__c limit 1];
        renewal.Generate_Invoice__c = true;
        renewal.Total_Fees__c = 150.00;
        update renewal;
        Test.startTest();
        Utilities.createInvoice(renewal);
        Test.stopTest();
        List<BGBK__Bill__c> invoices = [Select Id from BGBK__Bill__c];
        System.assert(invoices.size() == 1, 'One Invoices should be created');
    }
    
    @isTest
    public static void testCommonUtilMethods(){
        String testString;
        System.assertEquals(true, CommonUtil.isBlank(testString), 'String should be blank');
        Decimal testNumber;
        System.assertEquals(true, CommonUtil.isNull(testNumber), 'Decimal should be null');
        testString = 'test';
        System.assertEquals(true, CommonUtil.isNotBlank(testString), 'String should not be null');
        Date testDate;
        System.assertEquals(true, CommonUtil.isDateBlank(testDate), 'Date should be blank');
        System.assertEquals(true, CommonUtil.isEmpty(new List<String>()), 'List should be blank');
        System.assertEquals(true, CommonUtil.isNotEmpty(new List<String>{'Test'}), 'List should not be Empty');
        System.assertEquals(10, CommonUtil.toInteger('10'), 'Should return number 10');
        System.assertEquals(10, CommonUtil.toDecimal('10'), 'Should return number 10');
        System.assertEquals(null, CommonUtil.getDateValue(''), 'Should return null date');
        System.assertEquals(Date.newInstance(2018, 10, 15), CommonUtil.getDateValue('2018-10-15'), 'Should return null date');
        System.assert(CommonUtil.getRecordTypes('Account') != null);
        System.assert(CommonUtil.getFields('Account') != null);
    }
}