src/objects/BGBK__Payment_Batch__c.object
<CustomObject>
    <description>A payment batch groups associated payments. For example, payments entered by an operator on a particular date.</description>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cash Register</label>
        <referenceTo>Cash_Register__c</referenceTo>
        <relationshipLabel>Payment Batches</relationshipLabel>
        <relationshipName>Payment_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_check_credit_card__c</fullName>
        <label>Total check + Credit card</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_credit_card_receipts__c</fullName>
        <label>Total credit card receipts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Batch</label>
    <nameField>
        <label>Payment Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cash_Register__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <label>Cash Register</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Back-Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cash Register</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cash Register Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Polaris_PaymentBatchTriggerHandler_Test.cls
@isTest
public class Polaris_PaymentBatchTriggerHandler_Test {
	@isTest
    public static void testHandleBeforeInsert(){
        Id cashRegisterRecTypeId = Schema.SObjectType.Cash_Register__c.getRecordTypeInfosByName().get('Cash Register').getRecordTypeId();
        Cash_Register__c cashRegister = DOL_TestDataFactory.createCashRegister(cashRegisterRecTypeId);
        BGBK__Payment_Batch__c pb = DOL_TestDataFactory.createPaymentBatch(cashRegister.Id);
    }
    
    @isTest
    public static void testHandleAfterInsert(){
        Id cashRegisterRecTypeId = Schema.SObjectType.Cash_Register__c.getRecordTypeInfosByName().get('Cash Register').getRecordTypeId();
        Cash_Register__c cashRegister = DOL_TestDataFactory.createCashRegister(cashRegisterRecTypeId);
        BGBK__Payment_Batch__c pb = DOL_TestDataFactory.createPaymentBatch(cashRegister.Id);
        pb.Total_check_credit_card__c = 10;
        pb.Total_credit_card_receipts__c = 10;
        update pb;
    }
}