src/objects/BGBK__Cart__c.object
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Cart</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DOL_Integration_Batch_Input__c.object
<CustomObject>
    <description>This is used by Integration batches for DOL system. This table will store the json input of DOL system.</description>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>INFO__c</fullName>
        <label>INFO</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Input_Type__c</fullName>
        <label>Input Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>REMITTANCE</fullName>
                </value>
                <value>
                    <fullName>NCR</fullName>
                </value>
                <value>
                    <fullName>DOR</fullName>
                </value>
				<value>
                    <fullName>RTPC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Input__c</fullName>
        <label>Input</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FAILED</fullName>
                </value>
                <value>
                    <fullName>SUCCESSFUL</fullName>
                </value>
                <value>
                    <fullName>UNPROCESSED</fullName>
                    <default>true</default>
                    <label>UNPROCESSED</label>
                </value>
                <value>
                    <fullName>CONTENT VERSION CREATED</fullName>
                </value>
                <value>
                    <fullName>DATA LOADING COMPLETED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DOL Integration Batch Input</label>
    <nameField>
        <label>DOL Integration Batch Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DOL Integration Batch Inputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Effective_Date__c</fullName>
        <description>Deprecated</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Fee_Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The system sets this value to true when the outstanding amount is $0.</description>
        <label>Paid in Full</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Deprecated. Used for the simple implementation of historical data.</description>
        <label>Paid By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Fees Paid</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <description>Deprecated. Used for the simple implementation of historical data.</description>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                    <default>true</default>
                    <label>Check</label>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Authorized__c</fullName>
        <description>Card Authorization</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Card Authorized</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_4_digits_of_Credit_Card_or_ACH__c</fullName>
        <description>Last four digits of the credit card number or ACH account number</description>
        <inlineHelpText>Last four digits of the credit card number or ACH account number sent from payment gateway</inlineHelpText>
        <label>Last 4 digits of Credit Card or ACH</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MUSW__Card_Type__c</fullName>
        <description>Deprecated.</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Effective_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paid By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receipts (Paid By)</relationshipLabel>
        <relationshipName>Receipts_Paid_by</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Gateway_Transaction_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Gateway Transaction Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Receipt_Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Payee</inlineHelpText>
        <label>Receipt Paid By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Receipts Paid</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payer_First_Name__c</fullName>
        <description>Credit Card/ACH payer first name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Credit Card payer first name from payment gateway</inlineHelpText>
        <label>Payer First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Last_Name__c</fullName>
        <description>Credit Card/ACH payer last name</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Credit Card/ACH payer last name from payment gateway</inlineHelpText>
        <label>Payer Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Fees__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Selected Fees</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Confirmation_ID__c</fullName>
        <description>Transaction confirmation from US Bank</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Confirmation ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DOL_ProcessRTPC_Batch.cls
/**
* User Story: ****
* Class Name: DOL_ProcessRTPC_Batch
* Test Class Name: ****
* Description: To process RTPC records in Batch
* Date:        Developer/Company                    Description
* ------------------------------------------------------------------------------------------------*
* 07/29/2019   Laltu Banerjee/Deloitte           Initial Creation
**/
global with sharing class DOL_ProcessRTPC_Batch implements Database.Batchable<sObject>{

    public DOL_ProcessRTPC_Batch() {}

    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('DOL_Epayment_ProcessRemittanceData::start...');
        Datetime dt = Datetime.now().addMinutes(-15); // Get date time for one 15 min back
        return Database.getQueryLocator([ select id, File_Name__c, INFO__c, Input__c, Status__c, Input_Type__c 
                                        from DOL_Integration_Batch_Input__c 
                                        where Status__c = 'UNPROCESSED' and 
                                        Input_Type__c = 'RTPC' and 
                                        CreatedDate <=: dt ]
                                        );
    }

    global void execute(Database.BatchableContext BC, List<DOL_Integration_Batch_Input__c> rtpcRecords){
        if(rtpcRecords != null && !rtpcRecords.isEmpty()){
            
            DOL_RTPC_Input tempRtpcInput;
            List<DOL_RTPC_Input.Parameter> tempParameterList;
            String receiptId,cartId,SFDCappId;
            Map<String,String> parameterMap;
            MUSW__Receipt__c receipt;
            DOL_ProcessPayment processPayment;
            List<MUSW__Receipt__c> lstReceipts = new List<MUSW__Receipt__c>();
            
            for(DOL_Integration_Batch_Input__c record : rtpcRecords){
                try{
                    parameterMap = new Map<String,String>();
                    record.INFO__c = DOL_AppConstants.NULL_EMPTY_STRING;
                    tempRtpcInput = DOL_RTPC_Input.parse(record.Input__c);
                    for(DOL_RTPC_Input.Parameter parameter : tempRtpcInput.Parameter ){
                        parameterMap.put(parameter.ParameterName,parameter.ParameterValue);
                    }
                    
                    receiptId = parameterMap.get('SFDClicId');
                    cartId = parameterMap.get('SFDCId');
                    SFDCappId = parameterMap.get('SFDCappId');

                    if(String.isBlank(receiptId)){
                       throw new CustomException('Input Receipt Id is null or blank, Parameter name for reading receipt is SFDClicId'); 
                    }
                    receipt = [select id, Status__c, Selected_Fees__c, MUSW__Payment_Method__c, MUSW__Paid_By__c, MUSW__Receipt_Paid_by__c from MUSW__Receipt__c where id =: receiptId and id!=null];
                    if(receipt == null){
                        throw new CustomException('Invalid receipt Id, receipt Id = '+receiptId+' is not present in ORG ');
                    }
                    updateReceiptFromRTPCPojo(tempRtpcInput, receipt);
                    if(receipt.Status__c == 'Complete'){
                        lstReceipts.add(receipt);
                    }else if(isFeesAlreadyPaid(receipt.Selected_Fees__c.split(',')) ){
                        record.INFO__c = DOL_AppConstants.NULL_EMPTY_STRING+'Fees Already Paid';
                        lstReceipts.add(receipt);
                    }
                    else{
                        receipt.BGBK__Cart__c = null;
                        processPayment = new DOL_ProcessPayment(Id.valueOf(SFDCappId),
                                        Id.valueOf(cartId),
                                        receipt.Selected_Fees__c.split(','),
                                        receipt,
                                        Decimal.valueOf(tempRtpcInput.PaymentAmount)
                                        );
                        processPayment.doPayment();
                        
                    }
                    record.INFO__c += DOL_AppConstants.PROCESS_COMPLETED_SUCCESSFULLY;
                    record.Status__c = DOL_AppConstants.SUCCESSFULL_STRING; 

                }catch(Exception error){
                    record.INFO__c += 'error Msg = '+error.getMessage()+' StackTrace = '+error.getStackTraceString();
                    record.Status__c = DOL_AppConstants.FAILED_STRING;
                }
            }
            if(lstReceipts <> null && !lstReceipts.isEmpty())
            update lstReceipts;
            
            update rtpcRecords;
        }
    }

    global void finish(Database.BatchableContext BC){   
        
    }

    private Boolean isFeesAlreadyPaid(List<String> feeIds){
        List<MUSW__Fee__c> feeLst = [ Select Id, MUSW__Fee_Paid__c from MUSW__Fee__c where MUSW__Fee_Paid__c = false and Id IN :feeIds];
        if( feeLst != null && feeLst.size() > 0 )
            return false;
        return true;
    }

    private void updateReceiptFromRTPCPojo(DOL_RTPC_Input rtpcData, MUSW__Receipt__c receipt){
        if(! String.isBlank(rtpcData.ConfirmationId)){
            receipt.Transaction_Confirmation_ID__c = rtpcData.ConfirmationId;
            receipt.MUSW__Payment_Gateway_Transaction_Number__c = rtpcData.ConfirmationId;
        }
        if(! String.isBlank(rtpcData.PaymentMethod))
            receipt.MUSW__Payment_Method__c = rtpcData.PaymentMethod;
        if(!String.isBlank(rtpcData.PaymentEffectiveDate))
            receipt.MUSW__Effective_Date__c = DOL_AppUtility.getDate(rtpcData.PaymentEffectiveDate,'YYYY-MM-DD');
        if(!String.isBlank(rtpcData.DueDate))
            receipt.Date__c = DOL_AppUtility.getDate(rtpcData.DueDate,'YYYY-MM-DD');
        if(!String.isBlank(rtpcData.PayerFirstName))
            receipt.Payer_First_Name__c = rtpcData.PayerFirstName;
        if(!String.isBlank(rtpcData.PayerLastName))
            receipt.Payer_Last_Name__c = rtpcData.PayerLastName;
        if(!String.isBlank(rtpcData.LastFourAccountNumber) && DOL_AppUtility.isValidDecimalValue(rtpcData.LastFourAccountNumber))
            receipt.Last_4_digits_of_Credit_Card_or_ACH__c = Decimal.valueOf(rtpcData.LastFourAccountNumber);
        if(!String.isBlank(rtpcData.CardType))
            receipt.MUSW__Card_Type__c = rtpcData.CardType;
        if(!String.isBlank(rtpcData.PaymentAuthorization))
            receipt.Card_Authorized__c = rtpcData.PaymentAuthorization;
    }
}