src/objects/BGBK__CartSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Cart Settings</description>
    <fields>
        <fullName>BGBK__Cart_Expiration_Hours__c</fullName>
        <description>Deprecated - set to null.</description>
        <label>Manual Cart Expiration Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BGBK__Payable_Parents__c</fullName>
        <description>Deprecated.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>List of object API names whose Fees can be paid (e.g. Lien__c, Obj1__c). Super parents and Invoices need not be included.</inlineHelpText>
        <label>Payable Parents</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BGBK__Payment_Gateway_Data_Encryption_Key__c</fullName>
        <description>Used for a 3rd party payment gateway integration.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Needs to be 16 characters long. Otherwise will throw error. Example can be &apos;BasicGovPayments&apos;</inlineHelpText>
        <label>Payment Gateway Data Encryption Key</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BGBK__Payment_Gateway_Form_Post_URL__c</fullName>
        <description>Used for a 3rd party payment gateway integration.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Gateway Form Post URL</label>
        <type>Url</type>
    </fields>
    <label>Cart Settings</label>
</CustomObject>

src/objects/BGBK__FinancialObjects__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Specifies parents for Fees as well as Account and Contact for Cart and Transactions. Object name goes in the Name field.</description>
    <fields>
        <fullName>BGBK__Account_Field_Name__c</fullName>
        <description>The field API name for the account lookup (e.g. MUSW__Account__c) to define the responsible party (account).</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The field API for Account lookup (e.g. MUSW__Account__c)</inlineHelpText>
        <label>Account Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BGBK__Contact_Field_Name__c</fullName>
        <description>The field API name for the contact lookup (e.g. MUSW__Applicant__c) to define responsible party (contact).</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The field API for Contact lookup (e.g. MUSW__Applicant__c)</inlineHelpText>
        <label>Contact Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Financial Objects</label>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parcel for which the application is being submitted.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Complaint2__c.object
<CustomObject>
    <description>Cases to track violations</description>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>If Parcel is selected this value will be filled in via workflow from the Parcel City field</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaint2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Complaint</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Inspection__c.object
<CustomObject>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Complaint.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Parcel (Address).</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <recordTypes>
        <fullName>Inspection</fullName>
        <active>true</active>
        <label>Inspection</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Inspection_Violation__c.object
<CustomObject>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Complaint.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Inspection Violations</relationshipLabel>
        <relationshipName>Inspection_Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Parcel (Address).</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Inspection Violations</relationshipLabel>
        <relationshipName>Inspection_Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection Violation</label>
    <nameField>
        <displayFormat>IV-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parcels (Account)</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>The City this parcel or address is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel_Number2__c</fullName>
        <description>Unique parcel identification number.</description>
        <externalId>true</externalId>
        <label>Parcel Number</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Street2__c</fullName>
        <description>The full address or street this parcel or address is located on.</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Street_Number__c</fullName>
        <description>The unique number associated to the building of this parcel or address&apos;s street</description>
        <label>Street Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>City location of permit.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Violation__c.object
<CustomObject>
    <description>Violation cited on Complaints</description>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated complaint record.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated parcel record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Violation</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <recordTypes>
        <fullName>Inspection</fullName>
        <active>true</active>
        <label>Inspection</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parcel_Account__c.object
<CustomObject>
    <description>Store Address for Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Master lookup field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address (Accounts)</relationshipLabel>
        <relationshipName>Parcel_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Parcel Account</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTrigger.cls
//@isTest(seeAllData=true)
@isTest
public class TestTrigger
{
   @testSetup static void setup() {
        initCustomSettings();
        initCitizenAccount();     
    }


    static void initCustomSettings(){       
        BGBK__CartSettings__c defaultCartSetting = new BGBK__CartSettings__c();
        defaultCartSetting.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'Default';
        defaultCartSetting.BGBK__Cart_Expiration_Hours__c = 60;
        defaultCartSetting.BGBK__Payment_Gateway_Form_Post_URL__c = DOL_AppConstants.NULL_EMPTY_STRING + 'http://google.com';
        defaultCartSetting.BGBK__Payment_Gateway_Data_Encryption_Key__c = DOL_AppConstants.NULL_EMPTY_STRING + '1234567890123456';
        defaultCartSetting.BGBK__Payable_Parents__c = DOL_AppConstants.NULL_EMPTY_STRING + 'MUSW__License2__c,MUSW__Permit2__c,MUSW__Complaint2__c,MUSW__Application2__c';
        insert defaultCartSetting;  

        BGBK__FinancialObjects__c finObjSetting = new BGBK__FinancialObjects__c();
        finObjSetting.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'Parcel_Account__c';
        finObjSetting.BGBK__Account_Field_Name__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Account__c';
        finObjSetting.BGBK__Contact_Field_Name__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Primary_Contact__c';
        insert finObjSetting;
            
    }

    static void initCitizenAccount(){
        Account citizen = new Account();
        citizen.name = DOL_AppConstants.NULL_EMPTY_STRING + 'Citizen';
        citizen.BillingCity = DOL_AppConstants.NULL_EMPTY_STRING + 'Tristram';
        citizen.Phone = DOL_AppConstants.NULL_EMPTY_STRING + '(123) 456-7890';
        citizen.BillingState = DOL_AppConstants.NULL_EMPTY_STRING + 'AL';
        citizen.BillingPostalCode= DOL_AppConstants.NULL_EMPTY_STRING + '67890';
        citizen.BillingStreet = DOL_AppConstants.NULL_EMPTY_STRING + 'Black smith';
        insert citizen;
    }
    
    static testmethod void testViolationCloseInspectionTree()
    {
        Id[] ids = new Id[]{};
        
        MUSW__Parcel__c par = new MUSW__Parcel__c(MUSW__Street2__c= DOL_AppConstants.NULL_EMPTY_STRING + 'East Blvd', MUSW__Street_Number__c= DOL_AppConstants.NULL_EMPTY_STRING + '7777', MUSW__City__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Vancouver', MUSW__Parcel_Number2__c= DOL_AppConstants.NULL_EMPTY_STRING + '2000Test400');
        insert par;
        
        MUSW__Complaint2__c com = new MUSW__Complaint2__c(MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Multiple Issues', MUSW__Origin__c= DOL_AppConstants.NULL_EMPTY_STRING + '311', MUSW__Parcel__c=par.Id);
        insert com;
        
        MUSW__Inspection__c ins = new MUSW__Inspection__c (MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'First Inspection');
        insert ins;
        
        ids.add(ins.Id);
        
        //TriggerService.setLock();
        
        //Branch1
        MUSW__Inspection__c reins11 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c= ins.Id);
        insert reins11;
        ids.add(reins11.Id);
        ins.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed with open violations';
        update ins;
        
        MUSW__Inspection__c reins12 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c= reins11.Id);
        insert reins12;
        ids.add(reins12.Id); 
        reins11.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed with open violations';
        update reins11;
          
        MUSW__Inspection__c reins13 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c = reins12.Id);
        insert reins13;
        ids.add(reins13.Id);
        reins12.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed with open violations';
        update reins12;
         
           
        //Branch 2
        MUSW__Inspection__c reins21 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id,  MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c = ins.Id);
        insert reins21;
        ids.add(reins21.Id);
        
        MUSW__Inspection__c reins22 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c= reins21.Id);
        insert reins22;
        ids.add(reins22.Id); 
        reins21.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed with open violations';
        update reins21;
          
        MUSW__Inspection__c reins23 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection',MUSW__Previous_Inspection__c = reins22.Id);
        insert reins23;
        ids.add(reins23.Id);
        reins22.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Completed with open violations';
        update reins22;
        
        //TriggerService.releaseLock();
        //Check if the ins Inspection_Chain_Closed__c = false
        MUSW__Inspection__c insBefore = [select Inspection_Chain_Closed__c from MUSW__Inspection__c where Id = :ins.Id ]; 
        system.assert(insBefore.Inspection_Chain_Closed__c == false);
        
        //Close one leaf
        reins13.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Closed';
        update reins13;
        MUSW__Inspection__c[] insClosedOneLeaf = [select IsClosed__c, Inspection_Chain_Closed__c from MUSW__Inspection__c where Id in:ids and Inspection_Chain_Closed__c = true]; 
        
        /*system.assert(insClosedOneLeaf.size()==3, 'size: '+insClosedOneLeaf.size());
        
        //Close both leaves
        reins23.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Closed';
        update reins23;
        MUSW__Inspection__c[] insClosedBoth = [select Inspection_Chain_Closed__c from MUSW__Inspection__c where Id in:ids and Inspection_Chain_Closed__c = true]; 
        
        system.assert(insClosedBoth.size()==7, 'size: '+insClosedBoth.size());*/
    }
    
    
    static testmethod void testViolationCloseInspection()
    {
        Test.startTest();
        MUSW__Parcel__c par = new MUSW__Parcel__c(MUSW__Street2__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Test St', MUSW__Street_Number__c= DOL_AppConstants.NULL_EMPTY_STRING + '14B', MUSW__City__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Testville', MUSW__Parcel_Number2__c= DOL_AppConstants.NULL_EMPTY_STRING + '1000TEST400');
        insert par;
        MUSW__Violation_Type__c ord = new MUSW__Violation_Type__c(MUSW__Code_Number__c= DOL_AppConstants.NULL_EMPTY_STRING + '1=234.5TEST', Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Ordinance X');
        insert ord;
        //TriggerService.setLock();
        MUSW__Complaint2__c com = new MUSW__Complaint2__c(MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'TestTypeComp', MUSW__Origin__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Test', MUSW__Parcel__c=par.Id);
        insert com;
        //system.debug('com======' + com);
        MUSW__Inspection__c ins = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Complaint2__c=com.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'TESTInspection');
        insert ins;
        MUSW__Violation__c v1 = new MUSW__Violation__c(MUSW__Type__c=ord.Id, MUSW__Complaint2__c=com.Id);
        MUSW__Violation__c v2 = new MUSW__Violation__c(MUSW__Type__c=ord.Id, MUSW__Complaint2__c=com.Id);
        insert new MUSW__Violation__c[]{v1, v2};
        MUSW__Inspection_Violation__c iv1 = new MUSW__Inspection_Violation__c(MUSW__Inspection__c=ins.Id, MUSW__Violation__c=v1.Id, MUSW__Complaint2__c=com.Id);
        MUSW__Inspection_Violation__c iv2 = new MUSW__Inspection_Violation__c(MUSW__Inspection__c=ins.Id, MUSW__Violation__c=v2.Id, MUSW__Complaint2__c=com.Id);
        insert new MUSW__Inspection_Violation__c[]{iv1, iv2};
        
        v1.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Closed - Corrected';
        v2.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Closed - Corrected';
        update new MUSW__Violation__c[]{v1, v2};
        
        MUSW__Inspection__c insq = [select Close_Inspection__c from MUSW__Inspection__c where Id = :ins.Id];
        //MOS: no DRE rule to close yet - system.assert(insq.Close_Inspection__c == true);
        
        Test.stopTest();
    }   
     
    static testmethod void testIVDeduper()
    {
        //TriggerService.setLock();
        MUSW__Parcel__c par = new MUSW__Parcel__c(MUSW__Street2__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Test St', MUSW__Street_Number__c= DOL_AppConstants.NULL_EMPTY_STRING + '14B', MUSW__City__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Testville', MUSW__Parcel_Number2__c= DOL_AppConstants.NULL_EMPTY_STRING + '1000TEST400');
        insert par;
        MUSW__Violation_Type__c ord = new MUSW__Violation_Type__c(MUSW__Code_Number__c= DOL_AppConstants.NULL_EMPTY_STRING + '1=234.5TEST', Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Test Ordinance X');
        insert ord;
        MUSW__Inspection__c ins = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Field Observation');
        insert ins;
        MUSW__Violation__c v = new MUSW__Violation__c(MUSW__Type__c=ord.Id, MUSW__Parcel__c=par.Id);
        insert v;
        MUSW__Inspection__c reins1 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection', MUSW__Previous_Inspection__c=ins.Id);
        insert reins1;
        MUSW__Inspection__c reins2 = new MUSW__Inspection__c(MUSW__Parcel__c=par.Id, MUSW__Type__c= DOL_AppConstants.NULL_EMPTY_STRING + 'Re-inspection', MUSW__Previous_Inspection__c=ins.Id);
        insert reins2;
        MUSW__Inspection_Violation__c iv1 = new MUSW__Inspection_Violation__c(MUSW__Inspection__c=reins1.Id, MUSW__Violation__c=v.Id, MUSW__Parcel__c=par.Id);
        MUSW__Inspection_Violation__c iv2 = new MUSW__Inspection_Violation__c(MUSW__Inspection__c=reins2.Id, MUSW__Violation__c=v.Id, MUSW__Parcel__c=par.Id);
        insert new MUSW__Inspection_Violation__c[]{iv1, iv2};
        
        //only works if workflow and DRE rules are in the system
        MUSW__Inspection__c[] insq = [select Id from MUSW__Inspection__c where MUSW__Previous_Inspection__c = :ins.Id];
        //only works if workflow and DRE rules are in the system TO DO
        system.assert(insq.size() == 1);
        MUSW__Inspection_Violation__c[] ivq = [select Id from MUSW__Inspection_Violation__c where MUSW__Inspection__r.MUSW__Previous_Inspection__c = :ins.Id];
        system.assert(ivq.size() == 1);
    }
    
}