src/objects/BGBK__Cart__c.object
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <label>Cart</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>BGBK__Cart_Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Outstanding_Fee__c</fullName>
        <description>Amount outstanding based on the following formula: (Amount) - (Amended Amount) - (Waived Amount) - (Paid Amount).</description>
        <formula>If(MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c &lt; 0, 0, MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_To_Id__c</fullName>
        <formula>IF(MUSW__Permit2__c != null, MUSW__Permit2__c, 
IF(MUSW__Application2__c != null, MUSW__Application2__c,
IF(MUSW__License2__c != null, MUSW__License2__c, 
IF(Renewal_Application__c!=null,Renewal_Application__c, 
IF(Fine__c!=null,Fine__c, 
null)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To_Name__c</fullName>
        <formula>IF(MUSW__Permit2__c != null, MUSW__Permit2__r.Name, 
IF(MUSW__Application2__c != null, MUSW__Application2__r.Name, 
IF(MUSW__License2__c != null, MUSW__License2__r.Name, 
IF(Renewal_Application__c!=null,Renewal_Application__r.Name, 
IF(Fine__c!=null,Fine__r.Name, 
null)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To_Type__c</fullName>
        <formula>IF(OR(ISNULL( Fine__c ), Fine__c = &quot;&quot;), 
IF(OR(ISNULL( MUSW__Permit2__c ), MUSW__Permit2__c = &quot;&quot;), 
If(OR(ISNULL( MUSW__Application2__c ), MUSW__Application2__c = &quot;&quot;), 
If(OR(ISNULL( Renewal_Application__c), Renewal_Application__c= &quot;&quot;), 
IF(OR(ISNULL( MUSW__License2__c ), MUSW__License2__c = &quot;&quot;), 
&quot;&quot;, &quot;Credential&quot;), 
TEXT(Renewal_Application__r.Renewal_Reinstatement_Type__c)), 
&quot;Service Request&quot;), 
TEXT(MUSW__Permit2__r.Object_Type__c)),
&quot;Fine&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To Type</label>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Fees__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Selected Fees</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Gateway_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Biller_Group_ID__c</fullName>
        <label>Biller Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Biller_ID__c</fullName>
        <label>Biller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Gateway Setting</label>
    <pluralLabel>Payment Gateway Settings</pluralLabel>
</CustomObject>

src/classes/ECart_CC.cls
public with sharing class ECart_CC{
	public Contact con { get; set; }
	public String activeTab { get; set; }
	public Id receiptId {get; set;}
	public Boolean renderPaymentForm {get; set;}
    public Payment_Gateway_Settings__mdt paymentGatewaySettings {get; set;}
	private BGBK.CartService m_cs;
	
	public List<SelectOption> payForOptions {get; set;} //Credential, Permit, PTO
    public String selectedPayForOption {get; set;}
    
    public ECart_CC(){
    	activeTab = 'fees';
    	renderPaymentForm = false;
    	m_cs = new BGBK.CartService();
        
        paymentGatewaySettings = [Select Id, DeveloperName, Endpoint__c, Biller_ID__c, Biller_Group_ID__c, Product_Code__c From Payment_Gateway_Settings__mdt where DeveloperName = 'US_Bank_Settings' limit 1];
    }
    
    public void onPageLoad(){
    	system.debug('onPageLoad start');
    	con = m_cs.getActiveContact();
    	
    	Set<String> setRelatedType = new Set<String>();
        for(MUSW__Fee__c f : feeList){
            System.debug('f>>>>>>>>>' +f);
              if(f.Related_To_Type__c!=null)
    			setRelatedType.add(f.Related_To_Type__c);
        }

        payForOptions = new List<SelectOption>();
        payForOptions.add(new SelectOption('None', 'None'));
        for(String relatedType : setRelatedType){
            System.debug(' relatedType '+relatedType);
        	payForOptions.add(new SelectOption(relatedType, relatedType));
        }
        
        if(payForOptions.size() == 2){
            selectedPayForOption = payForOptions[1].getValue();
        }
    }
    
    public List <MUSW__Fee__c> feeList {
        get {
        	system.debug('feeList ' + feeList);
            if (feeList == null) {
                feeList = m_cs.getCartFees(true);
                system.debug('feeList2 ' + feeList);
            }
            return feeList;
        }
        private set;
    }
    
    public List <FeeWrapper> fees {
        get {
            if(fees == null) {
            	fees = new List <FeeWrapper>();
            	
                Map<Id,String> mapHeaderText = new Map<Id,String>();
            	if(!String.isEmpty(selectedPayForOption)){
            		Map<Id, List<MUSW__Fee__c>> mapParentFees = new Map<Id, List<MUSW__Fee__c>>();
            		for (MUSW__Fee__c fee: feeList) {
            			if(fee.BGBK__Cart_Exclude__c) continue;
            			
            			if(fee.Related_To_Type__c == selectedPayForOption){
            				List<MUSW__Fee__c> lstFee = mapParentFees.get(fee.Related_To_Id__c);
            				if(lstFee == null){
            					lstFee = new List<MUSW__Fee__c>();
            				}
            				lstFee.add(fee);
            				mapParentFees.put(fee.Related_To_Id__c, lstFee);
                            mapHeaderText.put(fee.Related_To_Id__c, fee.Related_To_Type__c + ' Fee for ' + fee.Related_To_Name__c);
            			}
            		}
            		
            		for(Id parentId : mapParentFees.keySet()){
                        FeeWrapper feeWrap = new FeeWrapper(false, mapHeaderText.get(parentId), mapParentFees.get(parentId));
            			fees.add(feeWrap);
            		}
            	}
            }
            
            return fees;
        }
        set;
    }
    
    public void resetFeeList() {
        system.debug('in resetFee List');
        fees = null;
    }
    
    public Decimal totalAmount {
        get {
            Decimal amount = 0.0;
            for (FeeWrapper feeWrapper: fees) {
                if (feeWrapper.checked == true) {
                    for (MUSW__Fee__c f: feeWrapper.lstFee) {
                        amount += f.MUSW__Outstanding_Fee__c;
                    }
                }
                
            }
            return amount;
        }
        set;
    }
    
    public void continueToCheckout(){
    	activeTab = 'checkout';
    }
    
    public void backToItems(){
    	activeTab = 'fees';
    }
    
    public void redirectToPaymentGateway(){
    	MUSW__Receipt__c receipt = new MUSW__Receipt__c();
    	receipt.BGBK__Cart__c = m_cs.getCart().Id;
    	receipt.Status__c = 'Draft';
    	
    	List<String> feeIds = new List<String>();
    	for (FeeWrapper feeWrapper: fees) {
            if (feeWrapper.checked == true) {
                for (MUSW__Fee__c f: feeWrapper.lstFee) {
                    feeIds.add(f.Id);
                }
            }
        }
        receipt.Selected_Fees__c = String.join(feeIds, ',');
    	
    	insert receipt;
    	
    	receiptId = receipt.Id;
    	renderPaymentForm = true;
    }
    
    public class FeeWrapper {
    	public Boolean checked {get; set;}
    	public String headerText {get; set;}
    	public List<MUSW__Fee__c> lstFee {get; set;}
    	
        public FeeWrapper(Boolean checked, String headerText, List<MUSW__Fee__c> lstFee){
            this.checked = checked;
            this.headerText = headerText;
            this.lstFee = lstFee;
        }
    }
}