src/objects/BGBK__Payment_Batch__c.object
<CustomObject>
    <description>A payment batch groups associated payments. For example, payments entered by an operator on a particular date.</description>
    <fields>
        <fullName>Total_Cash_In_Register__c</fullName>
        <label>Total Cash In Register</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_check_credit_card__c</fullName>
        <label>Total check + Credit card</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_credit_card_receipts__c</fullName>
        <label>Total credit card receipts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Batch</label>
    <nameField>
        <label>Payment Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>Intake_Method__c</fullName>
        <label>Intake Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Counter</fullName>
                </value>
                <value>
                    <fullName>Validation Room</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Batch_Id__c</fullName>
        <formula>BGBK__Cart__r.BGBK__BG_Payment_Batch__c</formula>
        <label>Payment Batch Id</label>
        <type>Text</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Polaris_ReceiptTriggerHandler.cls
public class Polaris_ReceiptTriggerHandler {
    
    public static void handleAfterInsert(List<MUSW__Receipt__c> newList){
        Set<String> paymentBatchIds = new Set<String>();
        for(MUSW__Receipt__c rec: newList){
            if(rec.Payment_Batch_Id__c != null){
                paymentBatchIds.add(String.valueOf(rec.Payment_Batch_Id__c).substring(0, 15));
            }
        }
        if(paymentBatchIds.size() >0){
            doCalculation(newList,paymentBatchIds);
        }
    }
    
    public static void handleAfterDelete(List<MUSW__Receipt__c> oldList){
        Set<String> paymentBatchIds = new Set<String>();
        for(MUSW__Receipt__c rec: oldList){
            if(rec.Payment_Batch_Id__c != null){
                paymentBatchIds.add(String.valueOf(rec.Payment_Batch_Id__c).substring(0, 15));
            }
        }
        if(paymentBatchIds.size() >0){
            doCalculation(oldList,paymentBatchIds);
        }
    }
    
    public static void doCalculation(List<MUSW__Receipt__c> newList, Set<String> pbIds){
        system.debug('Inside doCalculation');
        system.debug('newList::'+newList);
        system.debug('pbIds::'+pbIds);
        List<BGBK__Payment_Batch__c> paymentBatchToBeUpdated = new List<BGBK__Payment_Batch__c>();
        List<MUSW__Receipt__c> recRes = [Select MUSW__Amount_Tendered__c,MUSW__Payment_Method__c,Payment_Batch_Id__c from MUSW__Receipt__c where Intake_Method__c = 'Counter' and Payment_Batch_Id__c IN: pbIds];
        system.debug('recRes::'+recRes);
        for(MUSW__Receipt__c receipt: newList){
            if(receipt.Payment_Batch_Id__c != null){
                Decimal totalCash = 0;
                Decimal totalCheck = 0;
                Decimal totalCC = 0;
                BGBK__Payment_Batch__c pb;
                for(MUSW__Receipt__c rec: recRes){
                    if(rec.Payment_Batch_Id__c == receipt.Payment_Batch_Id__c){
                        pb = new BGBK__Payment_Batch__c(id = rec.Payment_Batch_Id__c);
                        if(rec.MUSW__Payment_Method__c == 'Cash'){
                             totalCash += rec.MUSW__Amount_Tendered__c;
                        }else if(rec.MUSW__Payment_Method__c == 'Check/Cashier\'s Check'){
                            totalCheck += rec.MUSW__Amount_Tendered__c;
                        }else if(rec.MUSW__Payment_Method__c == 'Credit Card'){
                            if(receipt.MUSW__Amount_Tendered__c != null){
                                totalCC += rec.MUSW__Amount_Tendered__c;
                            }
                            
                        }
                	}
                }
                if(pb != null){
                    pb.Total_Cash_In_Register__c = totalCash;
                	pb.Total_check_credit_card__c = totalCheck + totalCC;
                	//pb.Total_credit_card_receipts__c = totalCC;
                    system.debug('pb::'+pb);
                    
                	paymentBatchToBeUpdated.add(pb);
                }
                
            }
        }
        
        try{
            system.debug('paymentBatchToBeUpdated::'+paymentBatchToBeUpdated);
            if(paymentBatchToBeUpdated.size() >0){
                update paymentBatchToBeUpdated;
            }
        }catch(DmlException ex){
            system.debug('Exception::'+ex.getStackTraceString());
        }
       
    }
}