src/objects/BGBK__CartSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Cart Settings</description>
    <fields>
        <fullName>BGBK__Payable_Parents__c</fullName>
        <description>Deprecated.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>List of object API names whose Fees can be paid (e.g. Lien__c, Obj1__c). Super parents and Invoices need not be included.</inlineHelpText>
        <label>Payable Parents</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BGBK__Payment_Gateway_Data_Encryption_Key__c</fullName>
        <description>Used for a 3rd party payment gateway integration.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Needs to be 16 characters long. Otherwise will throw error. Example can be &apos;BasicGovPayments&apos;</inlineHelpText>
        <label>Payment Gateway Data Encryption Key</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Cart Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Fees (Contact)</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>An obligation amount (fee) that needs to be paid.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated application record.</description>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated license record.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Header_CC_Test.cls
@isTest
public class Header_CC_Test {

    @testSetup
    public static void setupTestData(){
        BGBK__CartSettings__c cartSettings = new BGBK__CartSettings__c(Name = 'Default', BGBK__Payable_Parents__c = 'MUSW__License2__c, MUSW__Application2__c, License_Renewal__c', BGBK__Payment_Gateway_Data_Encryption_Key__c = 'BasicGovPayments');
        insert cartSettings;
        
        Account acc = new Account();
        acc = CreateTestDataUtility.createAccount();
        insert acc;
        
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        insert con;
    }
    
    @isTest
    public static void test01(){
        Account acc = [Select Id From Account limit 1];
        Contact con = [Select Id From Contact limit 1];
        User u = CreateTestDataUtility.createCommunityUser(con.Id);
        
        Test.startTest();
        
        System.runAs(u){
            Musw__License2__c license1 = CreateTestDataUtility.createLicense(acc.Id, con.Id);
            insert license1;
            
            MUSW__Fee__c fee = new MUSW__Fee__c();
            fee.MUSW__Amount__c = 188;
            fee.Contact__c = con.Id;
            fee.MUSW__License2__c = license1.Id;
            insert fee;
            
        	Header_cc controller = new Header_cc();
            Integer count = controller.cartCount;
            
            PageReference pageRef = Page.ECart;
            Test.setCurrentPage(pageRef);
            Resources_CC rec = new Resources_CC();
        }
        
        Test.stopTest();
    }
}