src/objects/BGBK__Cart__c.object
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <fields>
        <fullName>BGBK__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the account that is related to the cart record.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BGBK__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact that is related to the cart record.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BGBK__Expiration_DateTime__c</fullName>
        <description>Deprecated.</description>
        <label>Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>The total Amount that needs to be collected.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Transfered_In_Amount__c</fullName>
        <description>Total amount that has been transferred in to this deposit.</description>
        <label>Transfered In Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>pending</fullName>
                    <default>true</default>
                    <label>pending</label>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>AFRS_Cash_Code__c</fullName>
        <defaultValue>&quot;AFR-MG-MS-SubSrc-GLCH&quot;</defaultValue>
        <label>xAFRS Cash Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>An obligation amount (fee) that needs to be paid.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated license record.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>The type of fee. Each type may have a different accounting code.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>DHP</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Staff Hours</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Mileage</fullName>
                </value>
                <value>
                    <fullName>Trust - Prearrangement Funeral Services Deposit</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance (AMR)</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Code__c</fullName>
        <defaultValue>&quot;AFR-MG-MS-SubSrc-GLRV&quot;</defaultValue>
        <label>Revenue Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMS_Cash_Code__c</fullName>
        <defaultValue>&quot;TMS-MG-MS-SubSrc-GLCH&quot;</defaultValue>
        <label>xTMS Cash Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TMS_Revenue_Code__c</fullName>
        <defaultValue>&quot;TMS-MG-MS-SubSrc-GLRV&quot;</defaultValue>
        <label>xTMS Revenue Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Primary descriptor of the License.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Liquor</fullName>
                </value>
                <value>
                    <fullName>Animal</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>BGBK__Cart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>BGBK__Cart__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount_Available__c</fullName>
        <description>Amount outstanding based on the following formula: (amount tendered) - (amount used) - (amount refunded) - (change amount) - (amount rejected)</description>
        <label>Amount Remaining</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the receipt</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Fees__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Selected Fees</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LnP_UpdateOvershortAmountClass_Test.cls
/* 
*Class Name   : LnP_UpdateOvershortAmountClass_Test
* Description  : Testclass for LnP_UpdateOvershortAmountClass
* Created By   : Chiranth Aradhya
* Created On   : 07/03/2019 
* Modification Log:  
*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                    Date                        Description
*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*
*/
@isTest
public class LnP_UpdateOvershortAmountClass_Test {
    
    
    static testMethod void testMethod1(){
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        //Account testAccount = DOL_TestDataFactory.createAccount(devRecordTypeId);
        Account testAccount = new Account();
        testAccount.Name = 'Test123';
        testAccount.RecordTypeId = devRecordTypeId;
        insert testAccount;
        
        System.assertNotEquals(testAccount.Id, null);
        
        Contact testContact = CreateTestDataUtility.createContact(testAccount.id);  
        insert testContact;
        
        /*
        MUSW__License2__c testLicense = CreateTestDataUtility.createLicense(testAccount.id, testContact.id); //License
        testLicense.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Active';
        insert testLicense; 
        */
        
        
        BGBK__Cart__c testCart = new BGBK__Cart__c(BGBK__Account__c= testContact.AccountId, BGBK__Contact__c= testContact.Id, BGBK__Expiration_DateTime__c=system.now().addDays(1));
        insert testCart;
        
       
        
        MUSW__Fee__c f1 = new MUSW__Fee__c(MUSW__Amount__c=0.1, BGBK__Cart__c = testCart.Id,MUSW__Type__c='General',Revenue_Code__c='AFR-MG-MS-SubSrc-GLRV',AFRS_Cash_Code__c='AFR-MG-MS-SubSrc-GLCH',TMS_Revenue_Code__c='TMS-MG-MS-SubSrc-GLRV',TMS_Cash_Code__c='TMS-MG-MS-SubSrc-GLCH');
        MUSW__Fee__c f2 = new MUSW__Fee__c(MUSW__Amount__c=0.2,  BGBK__Cart__c = testCart.Id,MUSW__Type__c='General',Revenue_Code__c='AFR-MG-MS-SubSrc-GLRV',AFRS_Cash_Code__c='AFR-MG-MS-SubSrc-GLCH',TMS_Revenue_Code__c='TMS-MG-MS-SubSrc-GLRV',TMS_Cash_Code__c='TMS-MG-MS-SubSrc-GLCH');
        MUSW__Fee__c[] fees = new MUSW__Fee__c[]{f1,f2};
        insert fees;
        
        Double totalDue = 0;
        List<String> feeIds = new List<String>();
        for(MUSW__Fee__c fee : fees){
            feeIds.add(fee.id);
            totalDue += fee.MUSW__Amount__c;
        }
        
        // create Receipt
        MUSW__Receipt__c receipt = DOL_TestDataFactory.createReceipt('Credit Card',200.0,'Portal');
        //receipt.BGBK__Cart__c = testCart.Id;
        //receipt.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Draft';
        receipt.MUSW__Amount_Available__c = 10;
        //receipt.Selected_Fees__c = String.join(feeIds,',');
        update receipt;
        
        List<MUSW__Deposit__c> dep = DOL_TestDataFactory.createDeposit('Geologist');
        //dep.MUSW__Transfered_In_Amount__c = 10;
        //update dep;
        
         /*try{
            LnP_UpdateOvershortAmountClass.updateovershortdepositMethod(dep.Id);
        }
        catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e,'LnP_UpdateOvershortAmountClass',fees[0].Id);
            
        //    System.debug('Error');
        }*/
        
        Test.startTest();
        //LnP_UpdateOvershortAmountClass.updateovershortdepositMethod(dep.Id);
        LnP_UpdateOvershortAmountClass.updateovershortreceiptMethod(receipt.Id);
        //LnP_UpdateOvershortAmountClass.payFromOverShort(fees[0].Id);
        Test.stopTest();
        
    }

}