src/objects/BGBK__Fund2__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <label>Fund</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BGBK__Item__c.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <formula>IF(ISBLANK(Fee_Payment__c),
  IF(ISBLANK(BGBK__Fee__c),
    &quot;240&quot;,
    TEXT(BGBK__Fee__r.Agency_Number__c)
  ),
  TEXT(Fee_Payment__r.MUSW__Fee__r.Agency_Number__c))</formula>
        <label>Agency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BGBK__Amount__c</fullName>
        <description>Transaction amount</description>
        <formula>BGBK__Price_Per_Unit__c * BGBK__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BGBK__Fee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated fee record.</description>
        <label>Fee</label>
        <referenceTo>MUSW__Fee__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BGBK__Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated General Ledger account.</description>
        <label>Fund</label>
        <referenceTo>BGBK__Fund2__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BGBK__Transaction__c</fullName>
        <description>Lookup to the associated transaction record.</description>
        <label>Transaction</label>
        <referenceTo>BGBK__Transaction__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GL_To_AFRS__c</fullName>
        <formula>BGBK__Fund__r.GL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GL (To AFRS)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Intake_Method__c</fullName>
        <formula>IF(ISBLANK(Deposit__c),
  IF(ISBLANK(BGBK__Fee__c),
    IF( ISBLANK(Fee_Payment__c) , 
      IF( ISBLANK( BGBK__Receipt__c ) , 
        text(Payable_Receipt__r.MUSW__Receipt__r.Intake_Method__c) , 
        text(BGBK__Receipt__r.Intake_Method__c) ) , 
      text(Fee_Payment__r.MUSW__Receipt__r.Intake_Method__c) )
    ,&quot;N/A&quot;),
  &quot;Validation Room&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Intake Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Voucher_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Voucher Detail</label>
        <referenceTo>Journal_Voucher_Detail__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Journal_Voucher_Type__c</fullName>
        <formula>RIGHT(TEXT(BGBK__Type__c),LEN(TEXT(BGBK__Type__c))-5)</formula>
        <label>Journal Voucher Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Voucher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal Voucher</label>
        <referenceTo>Journal_Voucher__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>IF(ISBLANK(BGBK__Fee__c),IF( ISBLANK(Fee_Payment__c) , IF( ISBLANK( BGBK__Receipt__c ) , text(Payable_Receipt__r.MUSW__Receipt__r.MUSW__Payment_Method__c) , text(BGBK__Receipt__r.MUSW__Payment_Method__c) ) , text(Fee_Payment__r.MUSW__Receipt__r.MUSW__Payment_Method__c) ),&quot;N/A&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Index__c</fullName>
        <formula>IF(ISBLANK( BGBK__Fee__c ), IF(ISBLANK(  Fee_Payment__c  ),  IF( ISBLANK( Payable_Receipt__c ) , &quot;From Receipt - Receipt doesn&apos;t have PI&quot;,  Payable_Receipt__r.MUSW__Deposit__r.wadol_Professional_Code__c) ,  Fee_Payment__r.MUSW__Fee__r.Profession_Code__c ) ,  BGBK__Fee__r.Profession_Code__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Index</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Accounting_System__c</fullName>
        <formula>Case( 
    BGBK__Fund__r.Accounting_System__c, 
    &quot;AFRS&quot;,IF(
        IF(BGBK__Amount__c &lt;0,
            CASE(BGBK__Type__c , 
                &quot;001X&quot;,1,&quot;006X&quot;,1,&quot;008R&quot;,1,&quot;012X&quot;,1,&quot;049X&quot;,1,&quot;071X&quot;,1,
                &quot;074R&quot;,1,&quot;090X&quot;,1,&quot;132X&quot;,1,&quot;198R&quot;,1,&quot;214X&quot;,1,&quot;298X&quot;,1,
                &quot;449X&quot;,1,&quot;455X&quot;,1,&quot;803X&quot;,1,&quot;966X&quot;,1,
                0
            ), 
            CASE(BGBK__Type__c, 
                &quot;001R&quot;,1,&quot;006R&quot;,1,&quot;008X&quot;,1,&quot;012R&quot;,1,&quot;049R&quot;,1,&quot;071R&quot;,1,
                &quot;074X&quot;,1,&quot;199X&quot;,1,&quot;951X&quot;,1,&quot;955X&quot;,1, &quot;965X&quot;,1,
                0
            )
        )=1,
            &quot;AFRS&quot;,
            &quot;N/A&quot;
    ),
    IF(BGBK__Amount__c &lt; 0,
        IF(Transaction_Code_Type__c == &quot;R&quot;,
            &quot;TMS&quot;,
            &quot;N/A&quot; 
        ),
        IF(Transaction_Code_Type__c == &quot;X&quot;,
            &quot;TMS&quot;,
            &quot;N/A&quot;
        )
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Accounting System</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Code__c</fullName>
        <formula>LEFT( Text(BGBK__Type__c)  , 3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transaction Code</label>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BGBK__Transaction__c.object
<CustomObject>
    <customHelp>MUSW__HelpInterface</customHelp>
    <fields>
        <fullName>BGBK__Effective_Date__c</fullName>
        <description>Transaction posting date.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Effective Date</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journal_Voucher__c.object
<CustomObject>
    <description>Used to capture header and footer information for the Journal Voucher .pdf and interface file.</description>
    <fields>
        <fullName>Agency_Name__c</fullName>
        <defaultValue>&apos;Department of Licensing&apos;</defaultValue>
        <label>Agency Name</label>
        <length>23</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agency_No__c</fullName>
        <defaultValue>TEXT(2400)</defaultValue>
        <label>Agency No.</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Journal_Voucher_Detail__c.Amount__c</summarizedField>
        <summaryForeignKey>Journal_Voucher_Detail__c.JournalVoucher__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <label>Approved By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approved_by_Date__c</fullName>
        <label>Approved by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Document_Number__c</fullName>
        <label>Current Document Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Deposit__c</fullName>
        <label>Date of Deposit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distribution__c</fullName>
        <label>Distribution</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Title__c</fullName>
        <label>Document Title</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CRJS</fullName>
                </value>
                <value>
                    <fullName>Journal Voucher</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Explanation_of_Entry__c</fullName>
        <label>Explanation of Entry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Voucher_Type__c</fullName>
        <label>Journal Voucher Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Counter Funds Received</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                    <default>true</default>
                    <label>Manual</label>
                </value>
                <value>
                    <fullName>Portal Credit Card Pending JV</fullName>
                </value>
                <value>
                    <fullName>Validation Room Funds Suspense JV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prepared_By__c</fullName>
        <label>Prepared By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prepared_by_Date__c</fullName>
        <label>Prepared by Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ref_Document_Number__c</fullName>
        <label>Ref. Document Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Journal Voucher</label>
    <nameField>
        <displayFormat>JV-{0000}</displayFormat>
        <label>Journal Voucher  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journal_Voucher_Detail__c.object
<CustomObject>
    <description>Used to capture an aggregation of item records pulled onto the Journal Voucher .pdf and interface file</description>
    <fields>
        <fullName>Add_to_Interface__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to Interface</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Add_to_PDF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fund</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Group__c</fullName>
        <label>Major Group</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Source__c</fullName>
        <label>Major Source</label>
        <length>2</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Program_Index__c</fullName>
        <label>Program Index</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Document_Suffix__c</fullName>
        <label>Reference Document Suffix</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reversal__c</fullName>
        <label>Reversal</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Source__c</fullName>
        <label>Sub Source</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Accounting_System__c</fullName>
        <label>Target Accounting System</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Code__c</fullName>
        <label>Transaction Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Journal Voucher Detail</label>
    <nameField>
        <displayFormat>JVD-{0000}</displayFormat>
        <label>Journal Voucher Detail  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Voucher Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LnP_Journal_Voucher.cls
/**
    * Batch class which Creates JV and JVD records
    * <p /><p />
    * @author Nazneen Begum
    */
    global class LnP_Journal_Voucher implements Database.batchable<SObject>, Database.Stateful {
        
        private static List<DOL_AppUtility.JournalWrapper> lstData = new List<DOL_AppUtility.JournalWrapper>();
        
        /**
         * Starts the execution of the scheduled process.
         *
         * @param objSchedulableContext Schedulable context.
         */
        public Database.QueryLocator start(Database.BatchableContext objContext) {
             system.debug('the queried item records');
            string strValueIntakeMethod='Counter';
            string strValuePaymentMethodCash='Cash';
            string strValuePaymentMethodCheck='Check';
            string strValuePaymentMethodMoneyOrder='Money Order';
            string strValuePaymentMethodVitalCheck='Vital Check';
            string strTargetAccountingSystemTMS='TMS';
            string strTargetAccountingSystemAFRS='AFRS';
            string strTraansactionCode='770';
            string strGL='7110';  
            
           String strQuery = 'SELECT id, name,BGBK__Fund__r.GL__c,Transaction_Code__c,Program_Index__c,BGBK__Amount__c,GL_To_AFRS__c,BGBK__Fund__r.Accounting_System__c,BGBK__Fee__r.Agency__c, ';
            strQuery+='BGBK__Fund__r.Fund__c,Intake_Method__c,Payment_Method__c,BGBK__Fund__r.Major_Group__c,BGBK__Fund__r.Major_Source__c,BGBK__Fund__r.Sub_Source__c ';
            strQuery+='FROM BGBK__Item__c WHERE BGBK__Fund__r.Accounting_System__c IN '+'('+'\''+String.escapeSingleQuotes(strTargetAccountingSystemAFRS)+'\'';
			strQuery+=','+'\''+String.escapeSingleQuotes(strTargetAccountingSystemTMS)+'\''+') AND Payment_Method__c IN ('+'\''+String.escapeSingleQuotes(strValuePaymentMethodCash)+'\'';
            strQuery+=','+'\''+String.escapeSingleQuotes(strValuePaymentMethodCheck)+'\''+','+'\''+String.escapeSingleQuotes(strValuePaymentMethodMoneyOrder)+'\'';
            strQuery+=','+'\''+String.escapeSingleQuotes(strValuePaymentMethodVitalCheck)+'\''+')';
            strQuery+=' AND Intake_Method__c=\''+String.escapeSingleQuotes(strValueIntakeMethod)+ '\'';
            //strQuery+=','+'\''+String.escapeSingleQuotes(BGBK__Transaction__r.BGBK__Effective_Date__c)+'\''+')';
            //strQuery+=' AND Intake_Method__c=\''+String.escapeSingleQuotes(strValueIntakeMethod)+ '\'';
            //CreatedDate = YESTERDAY
            
            return Database.getQueryLocator(strQuery);
            
        }
        
        /**
         * Executes the required operations over the found records.
         *
         * @param objBatchableContext Batchable context.
         * @param lstJVRecordsToInsert List of records of the current batch.
         */
        public void execute(Database.BatchableContext objContext, List<BGBK__Item__c> lstRecords) {
            system.debug('inside execute method');
           system.debug('the queried item records' +lstRecords.size());
          
            List<BGBK__Item__c> lstAFRS = new List<BGBK__Item__c>();
            List<BGBK__Item__c> lstTMS = new List<BGBK__Item__c>();
            
            Map<String, List<BGBK__Item__c>> mapItemsData = new Map<String, List<BGBK__Item__c>>();
            Map<String, Decimal> mapTotalItemAmount = new Map<String, Decimal>();
            String sToBeSortedFields= null;
                
            for(BGBK__Item__c items:lstRecords){
                system.debug('inside for loop' +items);
                if((items.BGBK__Fund__r.Accounting_System__c == 'TMS')) 
               {
                   sToBeSortedFields = items.Transaction_Code__c+''+items.Program_Index__c+''
                    +items.BGBK__Fund__r.Fund__c+''+items.GL_To_AFRS__c+items.BGBK__Fund__r.GL__c+'';
               }
                    //lstAFRS.add(items);//10 records
                     //String sToBeSortedFields=null;
                   //if(){if TMS
                   //sToBeSortedFields=;
                   //}
                  /*  String sToBeSortedFields = items.Transaction_Code__c+''+items.Program_Index__c+''
                    +items.BGBK__Fund__r.Fund__c+''+items.GL_To_AFRS__c+items.BGBK__Fund__r.GL__c+'';*/
                if((items.BGBK__Fund__r.Accounting_System__c == 'AFRS')){
                    
                    sToBeSortedFields = items.Transaction_Code__c+''+items.Program_Index__c+''
                    +items.BGBK__Fund__r.Fund__c+''+items.GL_To_AFRS__c+items.BGBK__Fund__r.GL__c+'';

                }
                
                    if(mapItemsData <> null && mapItemsData.get(sToBeSortedFields) <> null)
                    {
                        mapItemsData.get(sToBeSortedFields).add(items);
                    }
                    else
                    {
                        mapItemsData.put(sToBeSortedFields, new List<BGBK__Item__c>{items});
                    }
                    Decimal dTemp = 0.0;
                    if(mapTotalItemAmount <> null && mapTotalItemAmount.get(sToBeSortedFields) <> null)
                    {
                        dTemp+= mapTotalItemAmount.get(sToBeSortedFields) + items.BGBK__Amount__c.abs();
                        mapTotalItemAmount.remove(sToBeSortedFields);
                        
                    }
                    else
                    {
                        dTemp+= items.BGBK__Amount__c.abs();
                    }
                    
                    System.debug('What is the Amount Coming in For Nazneen to Check '+dTemp);
                    mapTotalItemAmount.put(sToBeSortedFields, dTemp);
                    
                
                             
            }
           
            List<String> lstNewSort = new List<String>();
            lstNewSort.addAll(mapTotalItemAmount.keyset());
            
            lstNewSort.sort();
            
            if(mapTotalItemAmount <> null)
            {
                for(String s :lstNewSort)
                {
                    if(mapItemsData <> null && mapItemsData.get(s) <> null)
                    {
                        DOL_AppUtility.JournalWrapper oData = new DOL_AppUtility.JournalWrapper(mapItemsData.get(s)[0], mapTotalItemAmount.get(s));
                        lstData.add(oData);
                    }
                }
            }
            
            
            System.debug(' Nazneen To Get Sorted Date '+ lstData);
            
            //Logic to insert JV records   
        Journal_Voucher__c journalVoucher = new Journal_Voucher__c();
        journalVoucher.Journal_Voucher_Type__c='Counter Funds Received';
        journalVoucher.Document_Title__c = 'CRJS';
        journalVoucher.Agency_Name__c='Department of Licensing';
        journalVoucher.Agency_No__c='2400';
        journalVoucher.Document_Date__c=Date.today();
        journalVoucher.Current_Document_Number__c = '240EXXXX';
        journalVoucher.Ref_Document_Number__c='';
        journalVoucher.Explanation_of_Entry__c = 'CRJS to record daily receipts from counter.';
            for(BGBK__Item__c items:lstRecords){
        journalVoucher.Distribution__c = items.BGBK__Fund__r.Accounting_System__c;
            }
        journalVoucher.Prepared_By__c='System Generated';
        journalVoucher.Telephone_Number__c='';
        journalVoucher.Prepared_by_Date__c=date.today();
        journalVoucher.Approved_By__c='BATCH';
        journalVoucher.Approved_by_Date__c=date.today();
        journalVoucher.Date_of_Deposit__c=date.today();
        system.debug('the journalVoucher records are:' +journalVoucher);
        insert journalVoucher;
        
        //Logic to insert child record
      List <Journal_Voucher_Detail__c> listJVD = new List <Journal_Voucher_Detail__c>();
            //chcek lst is not eqaul to empty, and is empty should be false
            if(!lstData.isEmpty() && lstData <> null){
            for(DOL_AppUtility.JournalWrapper lst:lstData){
              Journal_Voucher_Detail__c JVD=new Journal_Voucher_Detail__c();
         JVD.Target_Accounting_System__c =lst.objItemsData.BGBK__Fund__r.Accounting_System__c;
         //JVD.Add_to_PDF__c=lst.objItemsData.
         //JVD.Add_to_Interface__c=
         JVD.Reference_Document_Suffix__c= '';
         JVD.Transaction_Code__c = lst.objItemsData.Transaction_Code__c;
         if( lst.objItemsData.Transaction_Code__c !=null &&  lst.objItemsData.Transaction_Code__c == 'R'){       
         JVD.Reversal__c='R';
          }else{
                JVD.Reversal__c ='';
                 }
         //JVD.Agency__c =  lst.objItemsData.BGBK__Fee__r.Agency__c;
         JVD.Fund__c =  lst.objItemsData.BGBK__Fund__r.Fund__c;
        // JVD.Program_Index__c= lst.objItemsData.Program_Index__c;
        JVD.Program_Index__c= '';
         JVD.Major_Group__c = lst.objItemsData.BGBK__Fund__r.Major_Group__c;
         JVD.Major_Source__c =  lst.objItemsData.BGBK__Fund__r.Major_Source__c;
         JVD.Sub_Source__c =  lst.objItemsData.BGBK__Fund__r.Sub_Source__c;
                 if( lst.objItemsData.BGBK__Amount__c != null &  lst.objItemsData.BGBK__Amount__c<0){
         JVD.Debit_Credit__c='CR';
             }else{
                JVD.Debit_Credit__c='DR'; 
             }
                 
         JVD.Amount__c= lst.iTotalAmount;
        // JVD.General_Ledger_Account__c= lst.objItemsData.GL_To_AFRS__c;
         //JVD.Subsidiary_Account_Debit__c = '';
         //JVD.Subsidiary_Account_Credit__c ='';
         JVD.JournalVoucher__c = journalVoucher.Id; 
                
                listJVD.add(JVD);
            }     
            
          system.debug('before insert' +listJVD);  
         insert listJVD;
        }
            
        }
        
        /**
         * Implemented method on finish.
         *
         * @param objBatchableContext Batchable context.
         */
        global void finish(Database.BatchableContext objBatchableContext) {}
    }