src/objects/BGCK__Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <label>Answer Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Reinstatement Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Response</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <description>The data type using which the user response should be displayed</description>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Data_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Object_API_Name__c</fullName>
        <description>Parent Object API Name to perform the filed update upon Answering the Background Question</description>
        <label>Parent Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionFieldAPI__c</fullName>
        <label>QuestionFieldAPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Body__c</fullName>
        <description>Question text</description>
        <label>Question Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <description>This is the renewal status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Renewal_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Data_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Multi Select Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Picklist</fullName>
    </customValue>
    <customValue>
        <fullName>Single Select Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <customValue>
        <fullName>Yes_No</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Checkbox</fullName>
    </customValue>
    <customValue>
        <fullName>Textarea</fullName>
    </customValue>
    <customValue>
        <fullName>number</fullName>
    </customValue>
    <customValue>
        <fullName>Currency</fullName>
    </customValue>
    <customValue>
        <fullName>Decimal</fullName>
    </customValue>
    <description>The data type using which the user response should be displayed</description>
    <masterLabel>Data Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Renewal_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Generate Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In-Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submission Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Third Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Applicant Action</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Additional Qualifications</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
        <isActive>false</isActive>
    </customValue>
    <masterLabel>Renewal Status</masterLabel>
</GlobalValueSet>

src/classes/RenewalReinstatementTest.cls
@isTest
public class RenewalReinstatementTest {
    public static testmethod void testautoRenewReinstatementMethod(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('User Account').getRecordTypeId();
        Id ConRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Id LicRecTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Id renewalRecordTypeId = Schema.SObjectType.Renewal_Application__c.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
        Id quesRecTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByName().get('License Information').getRecordTypeId();
        
        Test.startTest();
        //Insert Account
        Account acc = DOL_TestDataFactory.createAccount(AccRecTypeId); 
        
        //Insert Contact
        Contact con = DOL_TestDataFactory.createContact(ConRecTypeId,acc.id);
        
        //Insert License
        MUSW__License2__c license = DOL_TestDataFactory.createLicense(LicRecTypeId, acc.Id, 'Architects', 'Architect', 'General Application');
        license.MUSW__Applicant__c = con.Id;
        license.MUSW__Expiration_Date__c = System.today()+10;
        update license;
                
        //Insert Renewal Application
        Renewal_Application__c renew = DOL_TestDataFactory.createRenewalApplication(renewalRecordTypeId, license.Id, null);
        renew.Renewal_Status__c = 'Pending Payment';
        update renew;
        
        //Insert Question
        Question__c ques = new Question__c();
        ques.Question_Body__c = 'Total number of full months of experience in real estate appraising';
        ques.Data_Type__c = 'Yes_No';
        ques.Parent_Object_API_Name__c = 'Renewal_Application__c';
        ques.RecordTypeId = quesRecTypeId;
        ques.Application_Type__c = 'Notary Public';
        ques.External_Id__c = 'abc123';
        ques.QuestionFieldAPI__c = 'Name';
        ques.Section__c = 'Legal Background Questions';
        insert ques;
        
        //Insert Answer
        BGCK__Answer__c ans = new BGCK__Answer__c();
        ans.Answer_Text__c = 'No';
        ans.QuestionDOL__c = ques.Id;
        ans.Renewal_Reinstatement_Application__c = renew.id;
        insert ans;
        
        //Insert Answer
		BGCK__Answer__c ans1 = new BGCK__Answer__c();
        ans1.Answer_Text__c = 'No';
        ans1.QuestionDOL__c = ques.Id;
        ans1.Renewal_Reinstatement_Application__c = renew.id; 
        insert ans1;
        
        Test.stopTest();
    }
}