src/objects/Cash_Register__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <label>Cash Register</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Back-Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cash Register</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cash Register Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dol_CashRegisterTrigger_Test.cls
@isTest
public class Dol_CashRegisterTrigger_Test {
    @isTest
    public static void validateHandleBeforeInsert() {
        Id validationRoomRecTypeId = Schema.SObjectType.Cash_Register__c.getRecordTypeInfosByName().get('Validation Room').getRecordTypeId();
        Test.startTest();
        try{
            MUSW__Receipt__c rec1 = DOL_TestDataFactory.createReceipt('NCR - cash',10,'Validation Room');
            MUSW__Receipt__c rec2 = DOL_TestDataFactory.createReceipt('NCR - check',10,'Validation Room');
            MUSW__Receipt__c rec3 = DOL_TestDataFactory.createReceipt('Cash',10,'Validation Room');
            MUSW__Receipt__c rec4 = DOL_TestDataFactory.createReceipt('Check/Cashier\'s Check',10,'Validation Room');
            MUSW__Receipt__c rec5 = DOL_TestDataFactory.createReceipt('Vitalcheck',10,'Validation Room');
            
            Cash_Register__c cashRegister = DOL_TestDataFactory.createValidationRoomCashRegister(validationRoomRecTypeId, 100, 100, 100, 100);
        }catch(Exception ex){
            //System.debug('ex:'+ex.getMessage());
            system.assert(ex.getMessage().contains('is not matching'));
        }
        test.stopTest();
    }
}