src/objects/Cash_Register__c.object
<CustomObject>
    <fields>
        <fullName>Cash_Register__c</fullName>
        <label>Cash Register</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Back-Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Amount_for_NCR_cash__c</fullName>
        <label>Total Amount for NCR-cash</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_for_NCR_check__c</fullName>
        <label>Total Amount for NCR-check</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_for_Vouchers__c</fullName>
        <label>Total Amount for Vouchers</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_of_Cash__c</fullName>
        <label>Total Amount of Cash</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount_of_Cheque__c</fullName>
        <label>Total Amount of Cheque</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_from_Vitalcheck__c</fullName>
        <label>Total from Vitalcheck</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Room_Cash_Total__c</fullName>
        <label>Validation Room Cash Total</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Room_Cheque_Total__c</fullName>
        <label>Validation Room Cheque Total</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_Room_Vitalcheck_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Validation Room Vitalcheck Total</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Cash Register</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Cash Register Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CashRegisterTriggerHandler.cls
public class CashRegisterTriggerHandler {
    public static void handleBeforeInsert(List<Cash_Register__c> newList){
        Id validationRoomRecTypeId = Schema.SObjectType.Cash_Register__c.getRecordTypeInfosByName().get('Validation Room').getRecordTypeId();
        List<AggregateResult> aggRes = [Select sum(MUSW__Amount_Tendered__c),MUSW__Payment_Method__c from MUSW__Receipt__c where createdDate = Today group by MUSW__Payment_Method__c ];
        Map<String,Decimal> paymentTypeToAmountMap = new Map<String,Decimal>();
        for(AggregateResult agr :aggRes){
            paymentTypeToAmountMap.put((String)agr.get('MUSW__Payment_Method__c'),(Decimal)agr.get('expr0'));
        }
        system.debug('Map::'+paymentTypeToAmountMap);
        
        for(Cash_Register__c cr: newList){
            
            if(cr.RecordTypeId == validationRoomRecTypeId ){
                if((paymentTypeToAmountMap.containsKey('Cash') &&  cr.Total_Amount_of_Cash__c != paymentTypeToAmountMap.get('Cash')) || (!paymentTypeToAmountMap.containsKey('Cash') && cr.Total_Amount_of_Cash__c >0 ) ){
                    cr.Total_Amount_of_Cash__c.addError('Total Amount of Cash entered is not matching the system\'s calculated value '+paymentTypeToAmountMap.get('Cash'));
                }
                if((paymentTypeToAmountMap.containsKey('Check/Cashier\'s Check') && cr.Total_Amount_of_Cheque__c != paymentTypeToAmountMap.get('Check/Cashier\'s Check')) || (!paymentTypeToAmountMap.containsKey('Check/Cashier\'s Check') && cr.Total_Amount_of_Cheque__c >0) ){
                    cr.Total_Amount_of_Cheque__c.addError('Total Amount of Cheque entered is not matching the system\'s calculated value '+paymentTypeToAmountMap.get('Check/Cashier\'s Check'));
                }
                if((paymentTypeToAmountMap.containsKey('Vitalcheck') && cr.Total_from_Vitalcheck__c != paymentTypeToAmountMap.get('Vitalcheck')) || (!paymentTypeToAmountMap.containsKey('Vitalcheck') && cr.Total_from_Vitalcheck__c > 0) ){
                    cr.Total_from_Vitalcheck__c.addError('Total from Vitalcheck entered is not matching the system\'s calculated value '+paymentTypeToAmountMap.get('Vitalcheck'));
                }
                if((paymentTypeToAmountMap.containsKey('Voucher') && cr.Total_Amount_for_Vouchers__c != paymentTypeToAmountMap.get('Voucher')) || (!paymentTypeToAmountMap.containsKey('Voucher') && cr.Total_Amount_for_Vouchers__c >0) ){
                    cr.Total_Amount_for_Vouchers__c.addError('Total Amount for Vouchers entered is not matching the system\'s calculated value '+paymentTypeToAmountMap.get('Voucher'));
                }
                
                if(paymentTypeToAmountMap.containsKey('NCR - cash')){
                    cr.Total_Amount_for_NCR_cash__c = paymentTypeToAmountMap.get('NCR - cash');
                }
                if(paymentTypeToAmountMap.containsKey('NCR - check')){
                    cr.Total_Amount_for_NCR_check__c = paymentTypeToAmountMap.get('NCR - check');
                }
                if(paymentTypeToAmountMap.containsKey('Cash')){
                    cr.Validation_Room_Cash_Total__c = paymentTypeToAmountMap.get('Cash');
                }
                if(paymentTypeToAmountMap.containsKey('Check/Cashier\'s Check')){
                    cr.Validation_Room_Cheque_Total__c = paymentTypeToAmountMap.get('Check/Cashier\'s Check');
                }
                if(paymentTypeToAmountMap.containsKey('Vitalcheck')){
                    cr.Validation_Room_Vitalcheck_Total__c = paymentTypeToAmountMap.get('Vitalcheck');
                }
                
            }
            
        }
        
    }
}