src/objects/Classes__c.object
<CustomObject>
    <description>To store class information</description>
    <fields>
        <fullName>CE_Status__c</fullName>
        <label>CE Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Applied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Credential for which the Class has been created</description>
        <label>Credential</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>To store class end date</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <description>Duration the class is for</description>
        <label>Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>CE_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll up summary field from class to show the total of hours</description>
        <label>CE Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Cycle_End_Date__c</fullName>
        <description>To calculate the renewal cycle duration- Multiplying the renewal window by 12 as it is in years</description>
        <formula>ADDMONTHS(MUSW__Expiration_Date__c,Renewal_Window__c*12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Cycle End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Window__c</fullName>
        <formula>CASE( Credential__c, &quot;Manufactured Homes Salesperson&quot;, 4,&quot;Manufactured Homes Installer&quot;, 4,&quot;Manufactured Homes Dealer&quot;, 4,&quot;Manufactured Homes Manufacturer&quot;, 4, &quot;Soil Tester&quot;, 4,&quot;Soil Erosion Inspector&quot;, 4, &quot;UDC Inspection Agency&quot;, 4, &quot;UDC Electrical Inspector&quot;, 4, &quot;UDC HVAC Inspector&quot;, 4, &quot;UDC Plumbing Inspector&quot;, 4, &quot;UDC Construction Inspector&quot;, 4, &quot;Dwelling Contractor&quot;, 1, &quot;Dwelling Contractor Qualifier&quot;, 2, &quot;Dwelling Contractor Restricted&quot;, 1, &quot;Delegated Agent - Commercial Building&quot;, 5, &quot;Delegated Agent - Fire Supression/Alarm Systems&quot;, 5, &quot;Delegated Agent - Plumbing&quot;, 5, &quot;Delegated Agent - POWTS&quot;, 5, &quot;Delegated Agent - Elevator&quot;, 5, &quot;Delegated Agent - Boiler&quot;, 5, &quot;Delegated Agent - Other&quot;, 5, &quot;Manufactured Homes Community Permit&quot;, 2, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Window</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

classes/CredCEhoursFix.cls
/**
* Name: CredCEhoursFix
* Type: Class
* Description: Report Class to identify Credential CE hours
* Date:        Developer/Company                   Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 02/05/2018   Srikanth Kottam/Deloitte          Initial Creation
**/
global class CredCEhoursFix implements Database.Batchable<sObject>, Database.stateful {
    
    global Map<Id, Decimal> classTotalHrs= new Map<Id, Decimal>();
    global Map<Id, Decimal> credCeHrsMap= new Map<Id, Decimal>();
    global final String query;
    global String csvColumnHeader;
    global List<String> csvRowValues = new List<String>();
    global Map<Id, String> csvValues = new Map<Id, String>();
    
    global CredCEhoursFix(String q){        
        query=q;        
       // System.debug('query>>>'+ query);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<MUSW__License2__c> scope){
        List<Classes__c> classList = new List<Classes__c>();
        decimal addHours = 0.0;
       // System.debug('scope>>>'+scope);
        if(scope.size()>0){
            classList = [Select id, name, End_Date_Time__c, Hours__c, CE_Status__c, CreatedBy.name, Credential__c from Classes__c 
                         where Credential__c in: scope 
                         Order By End_Date_Time__c Desc];
            for(MUSW__License2__c cred : scope){
                credCeHrsMap.put(cred.Id, cred.CE_Hours__c);
                if(cred.MUSW__Expiration_Date__c != null){
                    Date credentialExpirationDate = cred.MUSW__Expiration_Date__c;
                    integer newYear = credentialExpirationDate.year() - (Integer)cred.Renewal_window__c;
                    Date previousReviewCycleDate = date.newinstance(newYear, 
                                                                    credentialExpirationDate.month(), 
                                                                    credentialExpirationDate.day());
                    for(Classes__c classRec : classList){
                        if(cred.Id == classRec.Credential__c){
                            if(classRec.End_Date_Time__c > previousReviewCycleDate && classRec.End_Date_Time__c <=  cred.Renewal_Cycle_End_Date__c){
                                addHours = addHours + classRec.Hours__c;
                            }
                        }
                    }
                    classTotalHrs.put(cred.Id,addHours);
                    addHours = 0.0;
                } 
            }
        }
        
        // Create CSV file
        decimal actualHrs;
        decimal credHrs;
        decimal ceHrsdiff;
        if(credCeHrsMap.size() > 0){
            for(id credId : credCeHrsMap.keyset()){
                actualHrs = classTotalHrs.get(credId);
                credHrs = credCeHrsMap.get(credId);
                if(actualHrs == null){
                    actualHrs = 0.0;
                }
                if(credHrs == null){
                    credHrs = 0.0;
                }
                ceHrsdiff = credHrs - actualHrs;
           
                String rowStr = credId + ',' + credHrs + ',' + actualHrs + ',' + ceHrsdiff;
                csvValues.put(credId, rowStr);
               
            }
        }
      //  system.debug('csvRowValues>>>'+csvRowValues);
    }
    
    global void finish(Database.BatchableContext bc){
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        
      if(csvValues.size() > 0){
            for(id credId : csvValues.keyset()){
                string str = csvValues.get(credId);
                csvRowValues.add(str);
            }
        }
       // system.debug('csvValues>>>'+csvValues);
        if(csvRowValues.size()>0){
            String documentName = 'CEhourreport-'+ Datetime.now().format('MMM') + Datetime.now().year() + '.csv';
            csvColumnHeader = 'Id, Credential CE hours, Actual CE hours, CE Difference\n';
            String csvFile = csvColumnHeader + String.join(csvRowValues,'\n');
            Messaging.EmailFileAttachment csvAttachment = new Messaging.EmailFileAttachment();
            Blob csvBlob = blob.valueOf(csvFile);
            csvAttachment.setFileName(documentName);
            csvAttachment.setBody(csvBlob);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[]{'skottam@deloitte.com'};
           // String[] ccAddresses = new String[]{'anamathur@deloitte.com'};
            String subject = 'CE Hours Report';
            email.setSubject(subject);
            email.setToAddresses(toAddresses);
          //  email.setccAddresses(ccAddresses);
            email.setPlainTextBody('CE Hours details');
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttachment});
            //system.debug('email>>>'+email);
            Messaging.SendEmailResult[] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});  
		}        
    }
    
}