src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>App_Submitted_Date__c</fullName>
        <description>App Submitted Date</description>
        <label>First App Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel_Contact2__c.object
<CustomObject>
    <description>Contacts associated to a Parcel eg. Owner</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parcel or address this contact is related to.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Parcel_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>App_Submitted_Date__c</fullName>
        <description>App Submitted Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>App Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <description>This field indicates whether the current record is a Plan Review or a Permit. This field has been created instead of using Record Types since there could be multiple record types defined for Plan Reviews and Permits.</description>
        <label>Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Permit</fullName>
                </value>
                <value>
                    <fullName>Plan Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a Permit</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits as Property</relationshipLabel>
        <relationshipName>Parcel_Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Permit2_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/classes/PermitParcel_CC_Test.cls
/**
* User Story: 78 - Associate addresses to a Plan Review/PTO Type
* Name: PermitParcel_CC_Test
* Type: Test Class
* Description: Test Class for PermitParcel_CC
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 07/19/2018   Srikanth Kottam/Deloitte           Initial Creation
**/
@isTest
public class PermitParcel_CC_Test {
    public static testmethod void testIndividualLicense(){
        List<Account> accList = new List<Account>();
        
        /** Account Creation **/ 
        Account a = CreateTestDataUtility.createAccount();
        accList.add(a);
        insert accList;
        
        /** Contact Creation **/
        Contact c = CreateTestDataUtility.createContact(a.Id);
        insert c;
        Id recordTypeId = Schema.SObjectType.MUSW__Permit2__c.getRecordTypeInfosByName().get('All').getRecordTypeId();
        MUSW__Permit2__c permit = new MUSW__Permit2__c(RecordTypeId = recordTypeId,
                                                          MUSW__Status__c='Pending',
                                                          App_Submitted_Date__c=System.today(),
                                                          Object_Type__c = 'Plan Review', 
                                                          Application_Type__c = 'Plan Review', 
                                                       	  Program_Area__c = 'POWTS', 
                                                       	  Permit_Type__c = 'POWTS Petition for Variance');
        permit.MUSW__Applicant__c =c.id;
        insert permit;
        test.startTest();
        List<MUSW__Parcel__c> lstParcelAddresses = new List<MUSW__Parcel__c>();
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '801 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        lstParcelAddresses.add(CreateTestDataUtility.createContactParcel(c.id,  '901 International Pkwy', 'Lake Mary','FL', '32746', 'United States'));
        insert lstParcelAddresses;

        MUSW__Permit_Parcel__c permitParcel = new MUSW__Permit_Parcel__c(MUSW__Permit2__c = permit.Id, MUSW__Parcel__c = lstParcelAddresses[0].Id);
        insert permitParcel;

        ApexPages.StandardController sc = new ApexPages.StandardController(permitParcel);
        PermitParcel_CC lp= new PermitParcel_CC(sc);
        
        system.debug('mailingAddressId'+lp.mailingAddressId);
        system.debug('publicAddressId'+lp.publicAddressId);
        system.debug('physicalAddressId'+lp.physicalAddressId);
        // system.debug('licId'+lp.licId);
        // system.debug('licenseBoard'+lp.licenseBoard);
        //LicenseParcelControllerExt.ArchivP = licenseParcel;
        List<SelectOption> so = new List<SelectOption>();
        //LicenseParcelControllerExt.addressOptions = so;
            
        MUSW__Parcel_Contact2__c parcelContact = CreateTestDataUtility.createParcelContactJunction(lstParcelAddresses[0].id, c.id);
        insert parcelContact;
        parcelContact = CreateTestDataUtility.createParcelContactJunction(lstParcelAddresses[1].id, c.id);
        insert parcelContact;
            
        List<SelectOption> lstAddressOptions = lp.addressOptions;
        //system.assertEquals(lstParcelAddresses.size(), lstAddressOptions.size());
            
        lp.mailingAddressId = lstParcelAddresses[0].Id;
        lp.publicAddressId = lstParcelAddresses[0].Id;
            
        lp.savePermitAddress();

        List<MUSW__License_Parcel__c> lstParcelAddressesSaved = [SELECT MUSW__License2__c FROM MUSW__License_Parcel__c WHERE MUSW__Parcel__c=:lstParcelAddresses[0].Id];

        //System.assertEquals(lstParcelAddressesSaved.size(), 2);
            
        //Trying to force an exception
        lp.mailingAddressId = permit.Id;
        lp.savePermitAddress();
        test.stopTest();  
        List<Apexpages.Message> msgs = ApexPages.getMessages();
            boolean b = false;
            for(Apexpages.Message msg:msgs){
                if (msg.getSeverity() == ApexPages.Severity.ERROR) b = true;
            }
            //System.assert(b);
    }
    
    @isTest 
    static void testConstructor(){
        PermitParcel_CC controller = new PermitParcel_CC();
    }   
}