src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked then the record will be deleted using batch class</description>
        <label>Marked for Deletion</label>
        <type>Checkbox</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Object_API_Setting__mdt.object
<CustomObject>
    <description>Used to store the Object API Names, this is used for Batch Deletion.</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>Used to store the Object API name</description>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Object API Setting</label>
    <pluralLabel>Object API Settings</pluralLabel>
</CustomObject>

src/classes/RecordDeletionBatch_Test.cls
/**
* User Story: 212 - Deletion of Records
* Name: RecordDeletionScheduler_Test
* Type: Test Class
* Description: Test Class for RecordDeletionScheduler
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 07/30/2018   Kotam/Babita K/Deloitte           Initial Creation
**/
@isTest
public class RecordDeletionBatch_Test {
	public static testmethod void testBatch(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('User Account').getRecordTypeId();
        Id ConRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Id LicRecTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        Account acc = DOL_TestDataFactory.createAccount(AccRecTypeId);  
        
        Contact con = DOL_TestDataFactory.createContact(ConRecTypeId,acc.id);
        
        MUSW__License2__c lic = DOL_TestDataFactory.createLicense(LicRecTypeId, acc.Id, 'Architects', 'Architect', 'General Application');
        lic.MUSW__Applicant__c =  con.Id;
        lic.Marked_for_Deletion__c =true;
        update lic;
        
        for(Object_API_Setting__mdt objApi : [Select Id, MasterLabel, Object_API_Name__c from Object_API_Setting__mdt limit 200]){
            if(objApi.Object_API_Name__c != null){
                String Query = DOL_AppConstants.NULL_EMPTY_STRING + 'Select Id, Marked_for_Deletion__c from ' + objApi.Object_API_Name__c + ' where Marked_for_Deletion__c=true';
                RecordDeletionBatch batch = new RecordDeletionBatch(Query);
                Database.executeBatch(batch, 1);
            }
        }
    }
}