src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Envelope__c.object
<CustomObject>
    <description>This object is to store the record of  application with its check number for the validation purpose.</description>
    <fields>
        <fullName>Validation_number__c</fullName>
        <displayFormat>BPD-{000000000}</displayFormat>
        <label>Validation Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Customer Envelope</label>
    <nameField>
        <displayFormat>CENV{YY}-{0000}</displayFormat>
        <label>Customer Envelope Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account that is associated with the deposit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Transfered_In_Amount__c</fullName>
        <description>Total amount that has been transferred in to this deposit.</description>
        <label>Transfered In Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation number</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wadol_Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
	<fields>
        <fullName>Validation_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Validation Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Customer_Envelope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Envelope</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LnP_CustomerEnvelopeDetailPageCtrlTest.cls
@isTest
public class LnP_CustomerEnvelopeDetailPageCtrlTest {

    public static testMethod void ceDetailsPageMethod(){
        Customer_Envelope__c ce = new Customer_Envelope__c();
        insert ce;
        
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('User Account').getRecordTypeId();
        Id ConRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Id LicRecTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        Account acc = DOL_TestDataFactory.createAccount(AccRecTypeId);         
        Contact con = DOL_TestDataFactory.createContact(ConRecTypeId,acc.id);        
        
        MUSW__Deposit__c depRec = new MUSW__Deposit__c();       
        depRec.Amount__c = 100;
        depRec.MUSW__Transfered_In_Amount__c = 100;
        depRec.Validation_number__c = ce.Id;
        depRec.wadol_Program_Type__c = 'Architects';
        depRec.Contact__c = con.Id;
        depRec.MUSW__Account__c = acc.Id;
        insert depRec;   
        
             
        test.startTest();
        LnP_CustomerEnvelopeDetailPageCtrl.fetchDeposits(ce.Id);
        LnP_CustomerEnvelopeDetailPageCtrl.getObjViews();
        LnP_CustomerEnvelopeDetailPageCtrl.submitDeposits(ce.Id);
        test.stopTest();

        
    }
        
}