src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>BGBK__Cart_Exclude__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude from Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_To_Id__c</fullName>
        <formula>IF(MUSW__Permit2__c != null, MUSW__Permit2__c, 
IF(MUSW__Application2__c != null, MUSW__Application2__c,
IF(MUSW__License2__c != null, MUSW__License2__c, 
IF(Renewal_Application__c!=null,Renewal_Application__c, 
IF(Fine__c!=null,Fine__c, 
null)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To Id</label>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Header_CC.cls
/*******************************************************************************
* Name          :   Header_CC
* Author        :   
* Date          :   
* Description   :   Controller for Header Component
*-------------------------------------------------------------------------------
UPDATES
Version         Developer               Date            Description
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
Test class Name
                
*******************************************************************************/

public with sharing class Header_CC {
    public Contact userContact {get; set;}
    public Integer cartCount {
    	get{
    		BGBK.CartService bgCartService = new BGBK.CartService();
            cartCount = 0;
            Set<Id> feeParentIds = new Set<Id>();
            List<MUSW__Fee__c> feeList = bgCartService.getCartFees(true);
            for (MUSW__Fee__c fee: feeList) {
            	if(fee.BGBK__Cart_Exclude__c || fee.Related_To_Id__c == null) continue;
            	feeParentIds.add(fee.Related_To_Id__c);
            }
            cartCount = feeParentIds.size();
            
            return cartCount;
    	}
    	set;
	}
    
    public Header_CC(){
        try{
            User currentUser = [Select Id, contactId From User where Id = :UserInfo.getUserId()];
            userContact = [Select Id, FirstName, LastName, Contact_Status__c From Contact Where Id = :currentUser.contactId];
            }
        catch(Exception ex){
            userContact = new Contact();
        }
    }

}