src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parcels (Account)</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels (Contact)</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Field to Store Country details.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_of_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>Field to Store county</description>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MUSW__State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>The City this parcel or address is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Post_Zip_Code__c</fullName>
        <description>Address associated with this parcel&apos;s Post or Zip Code.</description>
        <label>Post/Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__State__c</fullName>
        <description>The state this parcel or address is located in.</description>
        <label>State/ Prov.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WA</fullName>
                    <default>true</default>
                    <label>WA</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Street2__c</fullName>
        <description>The full address or street this parcel or address is located on.</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Unit__c</fullName>
        <description>The number or letter of the condo or apartment unit.</description>
        <label>Unit</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Melissa_Address_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Melissa Address Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/County.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Asotin</fullName>
    </customValue>
    <customValue>
        <fullName>Benton</fullName>
    </customValue>
    <customValue>
        <fullName>Chelan</fullName>
    </customValue>
    <customValue>
        <fullName>Clallam</fullName>
    </customValue>
    <customValue>
        <fullName>Clark</fullName>
    </customValue>
    <customValue>
        <fullName>Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Cowlitz</fullName>
    </customValue>
    <customValue>
        <fullName>Douglas</fullName>
    </customValue>
    <customValue>
        <fullName>Ferry</fullName>
    </customValue>
    <customValue>
        <fullName>Franklin</fullName>
    </customValue>
    <customValue>
        <fullName>Garfield</fullName>
    </customValue>
    <customValue>
        <fullName>Grant</fullName>
    </customValue>
    <customValue>
        <fullName>Grays Harbor</fullName>
    </customValue>
    <customValue>
        <fullName>Island</fullName>
    </customValue>
    <customValue>
        <fullName>Jefferson</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>Kitsap</fullName>
    </customValue>
    <customValue>
        <fullName>Kittitas</fullName>
    </customValue>
    <customValue>
        <fullName>Klickitat</fullName>
    </customValue>
    <customValue>
        <fullName>Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Mason</fullName>
    </customValue>
    <customValue>
        <fullName>Okanogan</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Pend Oreille</fullName>
    </customValue>
    <customValue>
        <fullName>Pierce</fullName>
    </customValue>
    <customValue>
        <fullName>San Juan</fullName>
    </customValue>
    <customValue>
        <fullName>Skagit</fullName>
    </customValue>
    <customValue>
        <fullName>Skamania</fullName>
    </customValue>
    <customValue>
        <fullName>Washington</fullName>
        <isActive>false</isActive>
        <label>Washington</label>
    </customValue>
    <description>County Picklist</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

src/globalValueSets/List_of_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina</fullName>
    </customValue>
    <customValue>
        <fullName>Burma</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <description>List of countries for selection on Applications</description>
    <masterLabel>List of Countries</masterLabel>
</GlobalValueSet>

src/classes/Dol_AddressValidationService_Test.cls
@isTest(seeAllData=true)
public class Dol_AddressValidationService_Test{
    public static String responsebody = DOL_AppConstants.NULL_EMPTY_STRING + '<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\">'+
   '<s:Body xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"' + 'xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">'+
     '<doAddressCheckResponse xmlns=\"urn:MelissaDataAddressCheckService\">'+
        ' <doAddressCheckResult>'+
           '<Version xmlns="urn:mdWebServiceAddress">2.0.62</Version>'+
           '<TransmissionReference xmlns="urn:mdWebServiceAddress">?</TransmissionReference>'+
            '<Results xmlns="urn:mdWebServiceAddress"></Results>'+
            '<TotalRecords xmlns="urn:mdWebServiceAddress">1</TotalRecords>'+
           '<Record xmlns="urn:mdWebServiceAddress">'+
               '<RecordID>?</RecordID>'+
               '<Results>AC13,AS01</Results>'+
               '<Address>'+
                  '<Company>?</Company>'+
                  '<Urbanization>'+
                     '<Name>?</Name>'+
                  '</Urbanization>'+
                  '<Address1>501 Murphy Ranch Rd</Address1>'+
                  '<Address2></Address2>'+
                  '<Suite>Apt 450</Suite>'+
                  '<PrivateMailBox></PrivateMailBox>'+
                  '<City>'+
                     '<Name>Milpitas</Name>'+
                     '<Abbreviation>Milpitas</Abbreviation>'+
                  '</City>'+
                  '<State>'+
                     '<Name>California</Name>'+
                     '<Abbreviation>CA</Abbreviation>'+
                  '</State>'+
                  '<Zip>95035</Zip>'+
                  '<Plus4>7976</Plus4>'+
                  '<CarrierRoute>C053</CarrierRoute>'+
                  '<DeliveryPointCode>00</DeliveryPointCode>'+
                  '<DeliveryPointCheckDigit>9</DeliveryPointCheckDigit>'+
                  '<CongressionalDistrict>17</CongressionalDistrict>'+
                  '<Type>'+
                     '<Address>'+
                        '<Code>H</Code>'+
                        '<Description>Highrise</Description>'+
                     '</Address>'+
                     '<Zip>'+
                        '<Code></Code>'+
                        '<Description>Standard ZIP Code</Description>'+
                     '</Zip>'+
                  '</Type>'+
                  '<Country>'+
                     '<Abbreviation>US</Abbreviation>'+
                     '<Name>United States of America</Name>'+
                  '</Country>'+
                  '<AddressKey>95035797600</AddressKey>'+
                  '<Parsed>'+
                     '<StreetName></StreetName>'+
                     '<AddressRange></AddressRange>'+
                     '<Suffix></Suffix>'+
                     '<Direction>'+
                        '<Post></Post>'+
                        '<Pre></Pre>'+
                     '</Direction>'+
                     '<Suite>'+
                        '<Range></Range>'+
                        '<Name></Name>'+
                     '</Suite>'+
                     '<PrivateMailbox>'+
                        '<Name></Name>'+
                        '<Range></Range>'+
                     '</PrivateMailbox>'+
                     '<Garbage></Garbage>'+
                     '<RouteService></RouteService>'+
                     '<LockBox></LockBox>'+
                     '<DeliveryInstallation></DeliveryInstallation>'+
                  '</Parsed>'+
               '</Address>'+
           '</Record>'+
         '</doAddressCheckResult>'+
      '</doAddressCheckResponse>'+
   '</s:Body>'+
'</s:Envelope>';

  @isTest 
     public static void testmethod1(){
         test.startTest();
         
     		Dol_AddressValidationService.validateAddress('501 MURPHY RANCH RD','','MILPITAS', 'CA', '95035');
         	Dol_AddressValidationServiceBckOffice.validateAddress('501 MURPHY RANCH RD','','MILPITAS', 'CA', '95035');
          test.stopTest();
  }
  
    @isTest 
     public static void testmethod2(){
         Account acc = new Account(name = DOL_AppConstants.NULL_EMPTY_STRING + 'testaccount');
         insert acc;
         contact con = new contact(LastName = DOL_AppConstants.NULL_EMPTY_STRING + 'test Last' , Accountid = acc.id);
         insert con;
         test.startTest();
     		Dol_AddressValidationService.getObjAPI(con.id);
         	MUSW__Parcel__c parcelobj = new MUSW__Parcel__c();
         	Dol_AddressValidationService.getStates(parcelobj, 'MUSW__State__c');
         	Dol_AddressValidationServiceBckOffice.getStates(parcelobj, 'MUSW__State__c');
         	Dol_AddressValidationServiceBckOffice.getCountyValue('WA', 'Washington');
         	Dol_AddressValidationService.saveAddress('501 MURPHY RANCH RD,apt 286,MILPITAS,CA,95035,United States',false, con.id,'');
        	Dol_AddressValidationServiceBckOffice.saveAddress('501 MURPHY RANCH RD,MILPITAS,CA,95035,United States',false,TRUE,'', acc.id);
         	
         //string selectedAddress,Boolean isAptInfo,Boolean isAddrValidated, String countyValue,String parentId
          test.stopTest();
  }
    @isTest 
     public static void testmethod3(){
         Account acc = new Account(name = DOL_AppConstants.NULL_EMPTY_STRING + 'testaccount');
         insert acc;
         contact con = new contact(LastName = DOL_AppConstants.NULL_EMPTY_STRING + 'test Last' , Accountid = acc.id);
         insert con;
         MUSW__Parcel__c parcel = new MUSW__Parcel__c();
         parcel.Primary_Account__c = acc.id;
         parcel.Contact__c = con.id;
         parcel.MUSW__Primary_Contact__c = con.id;
         parcel.MUSW__Street2__c ='501 MURPHY RANCH RD';
         parcel.MUSW__City__c= 'MILPITAS';
         parcel.MUSW__City__c= 'MILPITAS';
         parcel.MUSW__State__c= 'CA';
         parcel.MUSW__Post_Zip_Code__c= '95035'; 
         parcel.Country__c = 'United States';
         insert parcel; 
         //List<MUSW__Parcel__c> existingParcel = [SELECT id,Account__c,Contact__c,Primary_Account__c ,MUSW__Primary_Contact__c ,MUSW__Unit__c,County__c ,Melissa_Address_Verified__c  from MUSW__Parcel__c where MUSW__Street2__c =:addres1 AND MUSW__Street2__c != null AND MUSW__City__c=:city AND MUSW__City__c !=null AND MUSW__State__c=:state AND MUSW__State__c!= null AND MUSW__Post_Zip_Code__c=:zip AND MUSW__Post_Zip_Code__c != null AND Country__c=:country AND Country__c != null Limit 1];
                
         test.startTest();
         	Dol_AddressValidationServiceBckOffice.getCountyValue('CA', 'Milpitas');
     		Dol_AddressValidationServiceBckOffice.saveAddress('501 MURPHY RANCH RD,apt 286,MILPITAS,CA,95035,United States',TRUE,TRUE,'', acc.id);
         	Dol_AddressValidationServiceBckOffice.saveAddress('501 MURPHY RANCH RD,apt 286,MILPITAS,CA,95035,United States',TRUE,TRUE,'', con.id);
            Dol_AddressValidationServiceBckOffice.saveAddress('501 MURPHY RANCH RD,MILPITAS,CA,95035,United States',false,false,'', acc.id);
          test.stopTest();
  }
  
}