src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parcels (Account)</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel_Contact2__c.object
<CustomObject>
    <description>Contacts associated to a Parcel eg. Owner</description>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact. Typically, it&apos;s the owner or a resident, such as renter.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Contact_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parcel or address this contact is related to.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Parcel_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Public address</description>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Business_License__c</fullName>
        <formula>OR(ISPICKVAL( Permit_Type__c , &apos;Manufactured Homes Community Permit&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit account.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Public_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Public Address - lookup on Parcel</description>
        <label>Public Address</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits (Public Address)</relationshipLabel>
        <relationshipName>Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a Permit</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address</relationshipLabel>
        <relationshipName>Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits as Property</relationshipLabel>
        <relationshipName>Parcel_Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Permit2_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to check if address is physical address.</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Primary address</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Public address</description>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of address picklist</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Mailing</fullName>
                </value>
                <value>
                    <fullName>Physical</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Permit Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Newsfeed__c.object
<CustomObject>
    <description>The object for news feed items.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>Defines the type of news item- instruction, attestation, video, etc.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>News_Type</valueSetName>
        </valueSet>
    </fields>
    <label>News</label>
    <nameField>
        <label>News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parcel_Account__c.object
<CustomObject>
    <description>Store Address for Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Master lookup field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address (Accounts)</relationshipLabel>
        <relationshipName>Parcel_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parcel__c</fullName>
        <description>Parcel object master lookup field</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Address (Accounts2)</relationshipLabel>
        <relationshipName>Parcel_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Physical__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is physical address</description>
        <label>Physical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Primary address</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Public address</description>
        <label>Public</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel Account</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/News_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Affidavit Link</fullName>
    </customValue>
    <customValue>
        <fullName>Attestation Line</fullName>
    </customValue>
    <customValue>
        <fullName>Board Address</fullName>
    </customValue>
    <customValue>
        <fullName>FAQ</fullName>
    </customValue>
    <customValue>
        <fullName>Helpful Links</fullName>
    </customValue>
    <customValue>
        <fullName>Notifications</fullName>
    </customValue>
    <customValue>
        <fullName>Page Instructions</fullName>
    </customValue>
    <customValue>
        <fullName>Portal News</fullName>
    </customValue>
    <customValue>
        <fullName>Portal Video</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Links</fullName>
    </customValue>
    <customValue>
        <fullName>Section Instructions</fullName>
    </customValue>
    <customValue>
        <fullName>Website News</fullName>
    </customValue>
    <description>Defines the type of news item- instruction, attestation, video, etc.</description>
    <masterLabel>News Type</masterLabel>
</GlobalValueSet>

src/classes/PermitParcel_CC.cls
/****************************************************************************************************************************************
** Class Name       : PermitParcel_CC 
** Description      : This class serves as backend controller for PermitParcel component 
**                    (User Story: 78 - Associate addresses to a Permit Type)
** Version          : 1.0
** Built By         : Srikanth Kottam
**----------------------------------------------------------------------------------------------------------------------------------------
** Modification Log:
**----------------------------------------------------------------------------------------------------------------------------------------
** Developer                        Date            Reference               Description
** 
**----------------------------------------------------------------------------------------------------------------------------------------
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**-----------------------------------------------------------------------------------------------------------------------------------------
**
*******************************************************************************************************************************************/ 
public with sharing class PermitParcel_CC
{
    private ApexPages.StandardController con;

    public String mailingAddressId {get; set;}
    public String publicAddressId {get; set;}
    public String physicalAddressId {get; set;}
/*  public MUSW__Permit_Parcel__c licenseParcel{get;set;}
    public Newsfeed__c instructions{get;set;} 
    public Boolean showProfileAddress{get;set;}   */
    private Id licId{get;set;}
    public static List<MUSW__Permit_Parcel__c> ArchivP {get;set;}
    
    /**
    * Method name  : addressOptions
    * Description  : gets the address options, if the license is flagged as a business license, then get parcel 
    *                account junction objects, if the license is not a business license, then get parcel contact
    *                junction objects, creates select options out of them
    * Return Type  : the select options for the addresses
    * Parameter    : None
    **/
    public List<SelectOption> addressOptions
    {
        get
        {   
            try{
                List<MUSW__Parcel__c> aRecs;
                if(addressOptions == null){
                   
                    licId = ((MUSW__Permit_Parcel__c)con.getRecord()).MUSW__Permit2__c;
                    MUSW__Permit2__c permit = [SELECT Business_License__c, MUSW__Account__c, MUSW__Applicant__c
                                               FROM MUSW__Permit2__c
                                               WHERE Id=:licId LIMIT 1];
                    
                    //if permit is a business license, get the account parcel objects
                    if(permit.Business_License__c){
                        aRecs = [SELECT Name FROM MUSW__Parcel__c 
                                                        WHERE Id in (SELECT Parcel__c FROM Parcel_Account__c 
                                                                        WHERE Account__c=:permit.MUSW__Account__c)];
                    }else{
                    //else get the contact parcel objects
                        aRecs = [SELECT Name FROM MUSW__Parcel__c 
                                                        WHERE Id in (SELECT MUSW__Parcel__c FROM MUSW__Parcel_Contact2__c 
                                                                        WHERE MUSW__Contact__c=:permit.MUSW__Applicant__c)];
                    }    
                    system.debug(aRecs);                                       
                    addressOptions = new List<SelectOption>();
                    for(MUSW__Parcel__c addressRecord : aRecs){
                        addressOptions.add(new SelectOption(addressRecord.Id, addressRecord.Name));
                    }
                }
            }catch(DmlException e){
              //  ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'MUSW__Parcel__c', 'Getting addresseson licenses', 'addressOptions', 'LicenseParcelControllerExt', 'HIGH');
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,System.Label.Err_pagestatement));

            }
            return addressOptions;
        }
        private set;
    }

    public PermitParcel_CC(ApexPages.StandardController controller){
        con = controller;
    }
    
    public PermitParcel_CC()
    {
     /*   instructions = new FetchInstructions().getInstructionObject('Apply for a license Address', 'BIZC Section Instructions');
        System.debug('The instructions are: ' +instructions);
        licenseParcel = new MUSW__Permit_Parcel__c();
        showProfileAddress=false;  */
    }

    /**
    * Method name  : savePermitAddress
    * Description  : creates permit parcel junction objects out of the address user chooses
    * Return Type  : PageReference
    * Parameter    : None
    **/
    public PageReference savePermitAddress()
    { 
        try{
            licId = ((MUSW__Permit_Parcel__c)con.getRecord()).MUSW__Permit2__c;
            ArchivP = [SELECT Id, Account__c, Mailing__c, MUSW__Parcel__c,
                       Physical__c, Primary__c, Public__c, Type__c,
                       MUSW__Permit2__c, MUSW__Permit2__r.MUSW__Applicant__c, MUSW__Permit2__r.MUSW__Status__c  
                       FROM MUSW__Permit_Parcel__c WHERE MUSW__Permit2__c = :licId limit 100];
            if (Schema.sObjectType.MUSW__Permit_Parcel__c.isDeletable()) {
                delete [SELECT Id FROM MUSW__Permit_Parcel__c WHERE MUSW__Permit2__c = :licId];
            }
            insert new List<MUSW__Permit_Parcel__c>
            {
                new MUSW__Permit_Parcel__c(MUSW__Permit2__c = licId, MUSW__Parcel__c = mailingAddressId, Mailing__c = true),
                new MUSW__Permit_Parcel__c(MUSW__Permit2__c = licId, MUSW__Parcel__c = publicAddressId, Public__c = true)
            };
            
            if(physicalAddressId != null){
                insert new MUSW__Permit_Parcel__c(MUSW__Permit2__c = licId, MUSW__Parcel__c = physicalAddressId, Physical__c = true);
            }
        }catch(DmlException e){
            // ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'MUSW__Permit_Parcel__c', 'Inserting license parcels', 'saveLicenseAddress', 'LicenseParcelControllerExt', 'HIGH');
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,System.Label.Err_pagestatement));

        } 
        ApexPages.StandardController sc = new ApexPages.StandardController(new MUSW__Permit2__c(Id = licId, MUSW__Parcel__c = mailingAddressId, Public_Address__c = publicAddressId));
        return sc.save();
    }
}