src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parcels (Account)</relationshipLabel>
        <relationshipName>Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Field to Store Country details.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_of_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <description>Field to Store county</description>
        <label>County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MUSW__State__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>County</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>The City this parcel or address is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Post_Zip_Code__c</fullName>
        <description>Address associated with this parcel&apos;s Post or Zip Code.</description>
        <label>Post/Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__State__c</fullName>
        <description>The state this parcel or address is located in.</description>
        <label>State/ Prov.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WA</fullName>
                    <default>true</default>
                    <label>WA</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Street2__c</fullName>
        <description>The full address or street this parcel or address is located on.</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if validated through geocode service</description>
        <label>Validated</label>
        <type>Checkbox</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel_Contact2__c.object
<CustomObject>
    <description>Contacts associated to a Parcel eg. Owner</description>
    <fields>
        <fullName>MUSW__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related contact. Typically, it&apos;s the owner or a resident, such as renter.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Contact_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parcel or address this contact is related to.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Parcel_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parcel_Account__c.object
<CustomObject>
    <description>Store Address for Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account Master lookup field</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Address (Accounts)</relationshipLabel>
        <relationshipName>Parcel_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parcel__c</fullName>
        <description>Parcel object master lookup field</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Address (Accounts2)</relationshipLabel>
        <relationshipName>Parcel_Accounts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Parcel Account</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/County.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adams</fullName>
    </customValue>
    <customValue>
        <fullName>Asotin</fullName>
    </customValue>
    <customValue>
        <fullName>Benton</fullName>
    </customValue>
    <customValue>
        <fullName>Chelan</fullName>
    </customValue>
    <customValue>
        <fullName>Clallam</fullName>
    </customValue>
    <customValue>
        <fullName>Clark</fullName>
    </customValue>
    <customValue>
        <fullName>Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Cowlitz</fullName>
    </customValue>
    <customValue>
        <fullName>Douglas</fullName>
    </customValue>
    <customValue>
        <fullName>Ferry</fullName>
    </customValue>
    <customValue>
        <fullName>Franklin</fullName>
    </customValue>
    <customValue>
        <fullName>Garfield</fullName>
    </customValue>
    <customValue>
        <fullName>Grant</fullName>
    </customValue>
    <customValue>
        <fullName>Grays Harbor</fullName>
    </customValue>
    <customValue>
        <fullName>Island</fullName>
    </customValue>
    <customValue>
        <fullName>Jefferson</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>Kitsap</fullName>
    </customValue>
    <customValue>
        <fullName>Kittitas</fullName>
    </customValue>
    <customValue>
        <fullName>Klickitat</fullName>
    </customValue>
    <customValue>
        <fullName>Lewis</fullName>
    </customValue>
    <customValue>
        <fullName>Lincoln</fullName>
    </customValue>
    <customValue>
        <fullName>Mason</fullName>
    </customValue>
    <customValue>
        <fullName>Okanogan</fullName>
    </customValue>
    <customValue>
        <fullName>Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Pend Oreille</fullName>
    </customValue>
    <customValue>
        <fullName>Pierce</fullName>
    </customValue>
    <customValue>
        <fullName>San Juan</fullName>
    </customValue>
    <customValue>
        <fullName>Skagit</fullName>
    </customValue>
    <customValue>
        <fullName>Skamania</fullName>
    </customValue>
    <description>County Picklist</description>
    <masterLabel>County</masterLabel>
</GlobalValueSet>

src/globalValueSets/List_of_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina</fullName>
    </customValue>
    <customValue>
        <fullName>Burma</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <description>List of countries for selection on Applications</description>
    <masterLabel>List of Countries</masterLabel>
</GlobalValueSet>

src/classes/Address_CC.cls
/*************************************************************************************************************
** User Story: 77--Addresses on Contacts and Accounts
**************************************************************************************************************
** Class Name    : Address_CC
** Description   : Creates new addresses and junction objects between either contact or account
** Version       : 1.0
** Built By      : Srikanth Kottam
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Srikanth Kottam                09/07/2018                    1                          Created
** 
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
**  **********************************************************************************/

public class Address_CC
{
    @TestVisible
    private ApexPages.StandardController con;
    public boolean countryIsSelected {get; set;}
    public boolean localAddressIsSelected {get; set;}
    public boolean isInternational {get; set;}
    public List<GeoResult> geoResults {get; set;}
    public Integer selectedIndex {get; set;}
    public String selectedInternationalCountry {get; set;}
    public Id recordId {get;set;}
    public boolean newAddress{get;set;}
    public string retURL{get;set;}
   

    public Address_CC(ApexPages.StandardController controller) 
    {
        con = controller;

        if(String.isNotEmpty(((MUSW__Parcel__c)con.getRecord()).Country__c))
            selectCountry();

        geoResults = new List<GeoResult>();
        newAddress = false;
    }
    
    /**
    * Method name  : selectCountry
    * Description  : determines if selected country is international or not
    * Return Type  : void
    * Parameter    : None
    **/
    public void selectCountry()
    {
        retURL = ApexPages.currentPage().getParameters().get('retURL'); 
        String country = ((MUSW__Parcel__c)con.getRecord()).Country__c;
        
        isInternational = false;
        if(country != label.Str_United_States)
        {
            selectedInternationalCountry = country;
            isInternational = true;
        }
        countryIsSelected = true;
    }
    
    /**
    * Method name  : getInternationalCountries
    * Description  : Gets the picklist values for all international countries
    * Return Type  : List<SelectOption> -  the picklist options for countries
    * Parameter    : None
    **/
    public List<SelectOption> getInternationalCountries()
    {
        List<SelectOption> options = new List<SelectOption>();    
            
        for(Schema.PicklistEntry f : MUSW__Parcel__c.Country__c.getDescribe().getPicklistValues())
            if(f.getLabel() != label.Str_United_States)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }

    /**
    * Method name  : findAddresses
    * Description  : uses AddressService to validate addresses and get list of geocoded addresess
    * Return Type  : void
    * Parameter    : None
    **/
    public void findAddresses()
    {   
        try{
            localAddressIsSelected = false;
        	geoResults.clear();
        	MUSW__Parcel__c addressRecord = (MUSW__Parcel__c)con.getRecord();
        	/*AddressService.GeocodeServiceSoap geoService = new AddressService.GeocodeServiceSoap();
        
        	//GeocodeWebserviceSettings__c geoSettings = UserInfo.getOrganizationId() == '00Dt0000000GynC' ? GeocodeWebserviceSettings__c.getInstance('production') : GeocodeWebserviceSettings__c.getInstance('sandbox');       
        	GeocodeWebserviceSettings__c geoSettings;
        	Boolean org = [Select Id, isSandbox From Organization limit 1][0].isSandbox;
        	if(org == true){
                	geoSettings = GeocodeWebserviceSettings__c.getInstance(label.Str_Sandbox);
            }else{
	                geoSettings = GeocodeWebserviceSettings__c.getInstance(label.Str_production);
            }
        	List<AddressService.GeocodedResult> geoResultsFromWS = geoService.GeocodeAddress(geoSettings.Username__c, geoSettings.Password__c, addressRecord.MUSW__Street2__c, null, addressRecord.MUSW__City__c, addressRecord.MUSW__State__c, addressRecord.MUSW__Post_Zip_Code__c, True, 2, 'ohcounty').resultSet.GeocodedResult;
        
        	for(AddressService.GeocodedResult gr_ws : geoResultsFromWS){   
            AddressService.ArrayOfString str = gr_ws.boundaryFileResults;
            String county = str.string_x[0];
            if(county != null && county.length() > 5){
                 county = county.substring(5,county.length());
             }
            if(gr_ws.matchCode.left(1) == 'E')
                continue;
        
            GeoResult gr = new GeoResult();
            
            gr.AddressLine1 = gr_ws.AddressLine1;
            gr.AddressLine2 = gr_ws.AddressLine2;
            gr.City = gr_ws.City;
            gr.state = gr_ws.state;
            gr.zipCode = gr_ws.zipCode;
            gr.matchCode = gr_ws.matchCode;
            gr.locationQualityCode = gr_ws.locationQualityCode;
            gr.locationConfidenceCode = gr_ws.locationConfidenceCode;
            gr.latitude = gr_ws.latitude;
            gr.longitude = gr_ws.longitude;
            gr.validated = true;
            gr.index = geoResults.size();
            gr.county = county;
            geoResults.add(gr);
        }*/
            
            // Instantiate a new http object
            Http h = new Http();
            String url = '';
            
            transient Boolean org = [Select Id, isSandbox From Organization][0].isSandbox;
            if(org == true){
                url = 'callout:Wisconsin_Endpoint_Test/address/v1/validate';
            }else{
                url = 'callout:Wisconsin_Endpoint_Prod/address/v1/validate';
            }
            
             // Instantiate a new HTTP request, specify the method (PUT) as well as the endpoint
            HttpRequest req = new HttpRequest();
            req.setEndpoint(url);
            req.setMethod('PUT');
            req.setHeader('Content-Type', 'application/json');
            
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('AddressLine1', addressRecord.MUSW__Street2__c);
            gen.writeStringField('City', addressRecord.MUSW__City__c);
            gen.writeStringField('State', addressRecord.MUSW__State__c);
            if(addressRecord.MUSW__Post_Zip_Code__c != null && addressRecord.MUSW__Post_Zip_Code__c != '') gen.writeStringField('PostalCode', addressRecord.MUSW__Post_Zip_Code__c);
            gen.writeStringField('CountryName', 'US');
            gen.writeEndObject();
            
            String reqBody = gen.getAsString();
            system.debug(reqBody);
            req.setBody(reqBody);
            
            // Send the request, and return a response
            HttpResponse res = h.send(req);
            system.debug(res.getBody());
        
            GeoResult result = new GeoResult();
            result.index = 0;
            result.validated = true;
            
            JSONParser parser = JSON.createParser(res.getBody());
            while (parser.nextToken() != null) {
                if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
                    String fieldName = parser.getText();
                    parser.nextToken();
                    String fieldValue = parser.getText();
                    if(fieldName == 'AddressLine1'){
                        result.addressLine1 = fieldValue;
                    }else if(fieldName == 'AddressLine2'){
                        result.addressLine2 = fieldValue;
                    }else if(fieldName == 'City'){
                        result.city = fieldValue;
                    }else if(fieldName == 'State'){
                        result.state = fieldValue;
                    }else if(fieldName == 'PostalCode'){
                        result.ZipCode = fieldValue;
                    }else if(fieldName == 'CountyName'){
                        result.County = fieldValue;
                    }else if(fieldName == 'Latitude'){
                        result.latitude = Double.valueOf(fieldValue);
                    }else if(fieldName == 'Longitude'){
                        result.longitude = Double.valueOf(fieldValue);
                    }
                }
            }
            
            result.validated = true;
            result.index = geoResults.size();
                
            geoResults.add(result);

        	boolean addressFound = false;
        	for(GeoResult gr : geoResults){
            	if( gr.AddressLine1 == addressRecord.MUSW__Street2__c &&
                	gr.City == addressRecord.MUSW__City__c &&
                	gr.state == addressRecord.MUSW__State__c &&
                	gr.zipCode == addressRecord.MUSW__Post_Zip_Code__c &&
                	gr.county == addressrecord.County__c)
            	{
                addressFound = true;

                selectedIndex = gr.index;
                localAddressIsSelected = true;

                break;
            }
        }

        	if(!addressFound){
            	GeoResult input_gr = new GeoResult();

            	input_gr.AddressLine1 = addressRecord.MUSW__Street2__c;
            	input_gr.City = addressRecord.MUSW__City__c;
            	input_gr.state = addressRecord.MUSW__State__c;
            	input_gr.zipCode = addressRecord.MUSW__Post_Zip_Code__c;
            	input_gr.county = addressRecord.county__c;
            	input_gr.validated = false;
            	input_gr.index = geoResults.size();

            	geoResults.add(input_gr);
        	}
        	}catch(DmlException e){
            	ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'AddressForAccountNewControllerExt', null, 'findAddresses', 'AddressForAccountNewControllerExt', label.str_HIGH);
        	}

    }
    

    /**
    * Method name  : selectAddress
    * Description  : sets localAddressIsSelected flag if address from georesults is chosen
    * Return Type  : PageReference
    * Parameter    : None
    **/
    public PageReference selectAddress()
    {
        localAddressIsSelected = true;
        return null;
    }
    
    /**
    * Method name  : saveLocalAddress
    * Description  : saves parcel object with data from georesults and calls juntction object creation function
    * Return Type  : PageReference
    * Parameter    : None
    **/
    public PageReference saveLocalAddress(){
        MUSW__Parcel__c addressRecord = (MUSW__Parcel__c)con.getRecord();
      /*  GeoResult gr = geoResults[selectedIndex];
        system.debug('addressRecord>>>>>>'+addressRecord);
        addressRecord.MUSW__Street2__c = gr.AddressLine1;
        addressRecord.MUSW__City__c = gr.City;
        addressRecord.MUSW__State__c = gr.state;
        addressRecord.MUSW__Post_Zip_Code__c = gr.zipCode;
        addressRecord.Validated__c = gr.validated;
        addressRecord.county__c = gr.county;  */
        system.debug('addressRecord>>>>>>'+addressRecord);
        boolean newAddress = addressRecord.Id == null ? true : false;
        //PageReference pr = con.save();
        upsert addressRecord;
        PageReference pr = new PageReference('/' + addressRecord.Id);
        
        //system.debug('>>>>>>>>>>>> addressRecord ' + addressRecord.Id);
        createAddressJunctionObj(addressRecord);
        
        if(string.isBlank(retURL)){
            return pr;
        }else{
            return new pagereference(retURL);
        }
    }

    /**
    * Method name  : saveInternationalAddress
    * Description  : saves parcel object and calls junction object creation method
    * Return Type  : PageReference
    * Parameter    : None
    **/
    public PageReference saveInternationalAddress(){
        MUSW__Parcel__c addressRecord = (MUSW__Parcel__c)con.getRecord();
        addressRecord.Country__c = selectedInternationalCountry;
        system.debug('addressRecord>>>>>>'+addressRecord);
        boolean newAddress = addressRecord.Id == null ? true : false;
        //PageReference pr = con.save();
        upsert addressRecord;
        PageReference pr = new PageReference('/' + addressRecord.Id);
        
        //system.debug('>>>>>>>>>>>> addressRecord ' + addressRecord.Id);
        createAddressJunctionObj(addressRecord);
        return pr;
    }

    /**
    * Method name  : createAddressJunctionObj
    * Description  : creates junction object between either the account or the contace with the newly created parcel object
    * Return Type  : void
    * Parameter    : None
    **/    
    public void createAddressJunctionObj(MUSW__Parcel__c addressRecord){
        Parcel_Account__c junctionAccountObj;
        MUSW__Parcel_Contact2__c junctionContactObj;
        
        try{
            if(addressRecord.MUSW__Primary_Contact__c!=null){
                junctionContactObj = new MUSW__Parcel_Contact2__c(MUSW__Contact__c = addressRecord.MUSW__Primary_Contact__c, MUSW__Parcel__c = addressRecord.Id);
                if(junctionContactObj != null){
                    insert junctionContactObj;  
                }
            }
            if(addressRecord.Primary_Account__c !=null){
                junctionAccountObj = new Parcel_Account__c(Account__c =addressRecord.Primary_Account__c, Parcel__c = addressRecord.Id);
                if(junctionAccountObj != null){
                    insert junctionAccountObj;  
                }
            }
        }catch(DmlException e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,System.Label.Err_PageStatement));
           // ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'AddressForAccountNewControllerExt', null, 'createAddressJunctionObj', 'AddressForAccountNewControllerExt', label.str_HIGH);
        }
    }

    /**
    * Wrapper class for holding geo location results
    **/
    public class GeoResult{
        public Integer index {get; set;}
        public String AddressLine1 {get; set;}
        public String AddressLine2 {get; set;}
        public String City {get; set;}
        public String state {get; set;}
        public String zipCode {get; set;}
        public String matchCode {get; set;}
        public String locationQualityCode {get; set;}
        public Integer locationConfidenceCode {get; set;}
        public Double latitude {get; set;}
        public Double longitude {get; set;}
        public boolean validated {get; set;}
        public string County {get; set;}
    }
}