src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <fields>
        <fullName>Disable_Triggers__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine whether to disable triggers for a profile/user- specially useful during data loads</description>
        <label>Disable Triggers</label>
        <type>Checkbox</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

retrieveUnpackaged/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MUSW__Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Non_US_Citizen__c</fullName>
        <description>Filed to check whether the applicant is a US citizen or not</description>
        <label>Non US Citizen</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
    <recordTypes>
        <fullName>Course</fullName>
        <active>true</active>
        <description>This is the record type for Course Information</description>
        <label>Course</label>
    </recordTypes>

retrieveUnpackaged/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Active__c</fullName>
        <formula>IF( AND(Effective_Start_Date__c&lt;TODAY(),
       (OR(ISBLANK(Effective_End_Date__c),
	       Effective_End_Date__c&gt; TODAY())
		) 
		),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Background_Question_Field_API_Name__c</fullName>
        <description>Field to store field API name for background question</description>
        <label>Background Question Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates submission list entries that are always required and will be defaulted to the Portal.</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Submission List record description</description>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Object associated with submission list record</description>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Object</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Submission list record show for</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>MUSW__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Object.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>MUSW__License2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Renewal_Application__c</fullName>
    </customValue>
    <customValue>
        <fullName>MUSW__Application2__c</fullName>
    </customValue>
    <customValue>
        <fullName>Musw__Permit2__c</fullName>
    </customValue>
    <description>List of objects</description>
    <masterLabel>Object</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <description>Generic Picklist for yes/no</description>
    <masterLabel>Yes No</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/License2TriggerHandler_Test.cls
/**
* Name: License2TriggerHandler_Test
* Type: Class
* Description: Test class for License2TriggerHandler
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 06/19/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/

@isTest
public class License2TriggerHandler_Test {        
    
    @isTest static void testTiggerReturn() {
        
        Global_Settings__c globalSetting = new Global_Settings__c(Name = UserInfo.getUsername(), Disable_Triggers__c = true);
        insert globalSetting;       
        
        Test.startTest();
        
        /*Creating test Account*/
        Account acc = new Account();
        acc = CreateTestDataUtility.createAccount();
        /*Inserting test Account*/
        insert acc;
        
        /*Creating test Contact*/
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        /*Inserting test Contact*/
        insert con;   
        
        /*Creating test License*/
        Musw__License2__c license1 = CreateTestDataUtility.createLicense(acc.Id, con.Id);
        /*Inserting test License to fire License Trigger*/
        insert license1;
        List<MUSW__Submission__c> submissionListCreated = [Select ID from MUSW__Submission__c where MUSW__License2__c =:license1.Id];
        System.assertEquals(0, submissionListCreated.size());
        Test.stopTest();
        
    }
    
    @isTest static void testTiggerFiring() {
        
        Global_Settings__c globalSetting = new Global_Settings__c(Name = UserInfo.getUsername(), Disable_Triggers__c = true);
        insert globalSetting;       
        
        /*Creating test Account*/
        Account acc = new Account();
        acc = CreateTestDataUtility.createAccount();
        /*Inserting test Account*/
        insert acc;
        
        /*Creating test Contact*/
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        /*Inserting test Contact*/
        insert con;   
        
        /*User u = new User();
        u = CreateTestDataUtility.createCommunityUser(con.Id);
        
        System.runAs(u){
          */      /*Create Submission List records*/
                List<MUSW__Master_Submission_List__c> masterSubmissionList = new List<MUSW__Master_Submission_List__c>();
                MUSW__Master_Submission_List__c backgroundSubmission = CreateTestDataUtility.createLicenseSubmissionList ('Manufactured Homes', 'Manufactured Homes Credential', 'Manufactured Homes Installer', 'Course Completion', Label.API_License2, 'Softcopy: To be Uploaded', 'Credential');
                backgroundSubmission.Background_Question_Field_API_Name__c= 'Non_US_Citizen__c';
                masterSubmissionList.add(backgroundSubmission);
                MUSW__Master_Submission_List__c backgroundSubmission2 = CreateTestDataUtility.createLicenseSubmissionList ('Manufactured Homes', 'Manufactured Homes Credential', 'Manufactured Homes Installer', 'Course Completion', Label.API_License2, 'Hardcopy: To be Mailed', 'Credential');
                backgroundSubmission2.Default__c = True;
                masterSubmissionList.add(backgroundSubmission2);
                insert masterSubmissionList;
                /*List<MUSW__Master_Submission_List__c> testSubmissionListCount = [SELECT Id, External_id__c, Name, Background_Question_Field_API_Name__c,
                                                  Description__c, Credential_Type__c, Default__c, Show_For__c,
                                                  Submission_Type__c 
                                                  FROM MUSW__Master_Submission_List__c 
                                                  WHERE Active__c = TRUE 
                                                  AND Object__c = :label.API_License2 
                                                  AND Credential_Type__c IN ('License Type A1')];
                System.debug('test submission list count'+testSubmissionListCount.size());*/
            /*Creating test License*/
        globalSetting.disable_triggers__C = false;
        upsert globalSetting;
                Musw__License2__c license = CreateTestDataUtility.createLicense(acc.Id, con.Id);
                /*Inserting test License to fire License Trigger*/
                insert license;        
                
                /*List<MUSW__License2__c> testLicenseCount = [Select ID from MUSW__License2__c where credential_type__c = 'License Type A1'];
                System.debug('testLicenseCount'+testSubmissionListCount.size());
            */
                List<MUSW__Submission__c> submissionListCreated = [Select ID from MUSW__Submission__c where MUSW__License2__c =:license.Id];
                System.assertEquals(2, submissionListCreated.size());
                
                license.Non_US_Citizen__c = 'No';
                license.MUSW__Description__c = 'testing after update trigger';
                upsert license;
                List<MUSW__Submission__c> submissionListDeleted = [Select ID from MUSW__Submission__c where MUSW__License2__c =:license.Id];
                System.assertEquals(1, submissionListDeleted.size());
                   // }
        
        /*Creating Multiple Test Licenses*/
        /*
        integer numOfLicensesToCreate = 5;
        List<MUSW__License2__c> licenseList = CreateTestDataUtility.createMultipleLicenses(numOfLicensesToCreate, 'License Type A1','License Type A2', acc.Id, con.Id);
        insert licenseList;
        
        
        
        for(integer i = 0; i < numOfLicensesToCreate; i++){
            if(math.mod(i, 2) == 0){
                licenselist[i].Non_US_Citizen__c = 'No';
                licenseList[i].MUSW__Description__c = 'a';                
            }
            licenselist[i].Non_US_Citizen__c = 'Yes';
            licenseList[i].MUSW__Description__c = 'b';                            
        }
        upsert licenseList;
        */
        
        
    }

}