src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Field to Store Country details.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_of_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>The City this parcel or address is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__State__c</fullName>
        <description>The state this parcel or address is located in.</description>
        <label>State/ Prov.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WA</fullName>
                    <default>true</default>
                    <label>WA</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Street2__c</fullName>
        <description>The full address or street this parcel or address is located on.</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account</description>
        <label>Primary Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/List_of_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina</fullName>
    </customValue>
    <customValue>
        <fullName>Burma</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <description>List of countries for selection on Applications</description>
    <masterLabel>List of Countries</masterLabel>
</GlobalValueSet>

src/classes/Address_CC_Test.cls
@isTest
public class Address_CC_Test {
    public static TestMethod MUSW__Parcel__c createTestData(){
        list <Account> acctsToInsert = new list <Account> ();
        Account account = CreateTestDataUtility.createAccount(); 
        Database.insert(account);
        
        Contact contact = CreateTestDataUtility.createContact(account.Id);
        Database.insert(contact);
        
        MUSW__Parcel__c objParcel = new MUSW__Parcel__c(MUSW__Primary_Contact__c= contact.Id, Primary_Account__c = account.Id);
        objParcel.MUSW__Street2__c = '500 Main St';
        objParcel.MUSW__City__c = 'Melbourne';
        objParcel.Country__c = 'Australia';
        Database.insert(objParcel);
        return objParcel;
    }
    
    public static TestMethod void testLocalAddress(){
        MUSW__Parcel__c objParcel = createTestData();
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CleanAddress_MockService());
        
        PageReference pageRef = Page.Address;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController con = new ApexPages.StandardController(objParcel);  
        system.debug('objParcel>>>'+objParcel);
        Address_CC controller = new Address_CC(con);
        system.debug('controller>>>'+controller);
         //Test variable initialization
        System.assertEquals(controller.newAddress, false);
        
        List<selectOption> countryOptions = controller.getInternationalCountries();
        System.assertNotEquals(countryOptions.size(),0);
        system.debug('countryOptions>>>'+countryOptions);
        //Test SelectCountry 
        controller.selectCountry();
        System.assert(controller.isInternational);
        
        Test.stopTest();
    }
    
    public static TestMethod void testLocalAddress2(){
        MUSW__Parcel__c objParcel = createTestData();
        objParcel.Country__c = 'United States';
        objParcel.MUSW__Street2__c = '500 Main St';
        objParcel.MUSW__City__c = 'Atlanta';
        objParcel.MUSW__State__c = 'GA';
        update objParcel;
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CleanAddress_MockService());
        
        PageReference pageRef = Page.Address;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController con = new ApexPages.StandardController(objParcel);  
        system.debug('objParcel>>>'+objParcel);
        Address_CC controller = new Address_CC(con);
        
      	controller.findAddresses();
        controller.saveLocalAddress();
        Test.stopTest();
    }
    
    public static TestMethod void testInternationalAddress(){
        MUSW__Parcel__c objParcel = createTestData();
        Test.startTest();
        
        PageReference pageRef = Page.Address;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController con = new ApexPages.StandardController(objParcel);        
        Address_CC controller = new Address_CC(con);
        
         //Test variable initialization
        System.assertEquals(controller.newAddress, false);
        
        List<selectOption> countryOptions = controller.getInternationalCountries();
        System.assertNotEquals(countryOptions.size(),0);
        
        //Test SelectCountry 
        controller.selectCountry();
      //  System.assert(controller.isInternational);
        
        //Set country
        MUSW__Parcel__c record = ((MUSW__Parcel__c)con.getRecord());
        record.Country__c = 'Canada';
        
      //  con.addFields(List<String> fieldNames);
        con.save();
        controller.selectCountry();
        controller.selectedInternationalCountry = 'Canada';
    //    System.assert(!controller.isInternational);
        // controller.findAddresses();
        controller.saveInternationalAddress();
        Test.stopTest();
    }
    
    public static TestMethod void test2(){
        
        Test.startTest ();
        
        list <Account> acctsToInsert = new list <Account> ();
        Account account = CreateTestDataUtility.createAccount(); 
        Database.insert(account);
        
        Contact contact = CreateTestDataUtility.createContact(account.Id);
        Database.insert(contact);
        
        MUSW__Parcel__c objParcel = new MUSW__Parcel__c(MUSW__Primary_Contact__c= contact.Id);
        objParcel.Country__c = 'Australia';
        Database.insert(objParcel);
        
        ApexPages.StandardController con = new ApexPages.StandardController(objParcel);        
        Address_CC controller = new Address_CC(con);
        controller.selectedInternationalCountry = 'Canada';
        
        Test.stopTest ();
    }
    
    @testSetup 
    static void setUpServiceData(){
        Boolean isSandbox = [Select Id, isSandbox From Organization limit 1][0].isSandbox;
     /*   GeocodeWebserviceSettings__c geoSetting = new GeocodeWebserviceSettings__c(Name='Canada',Username__c = 'test username', Password__c = 'test password', Endpoint_URL__c = 'http://www.exampleURL.com');
        geoSetting.name = isSandbox ?   label.Str_sandbox : label.Str_production;
        if(geoSetting != null) insert geoSetting;
      */  
        list <Account> acctsToInsert = new list <Account> ();
        Account account = CreateTestDataUtility.createAccount(); 
        Database.insert(account);
        
        Contact c = CreateTestDataUtility.createContact(account.Id);
        Database.insert(c);
        
        User u = CreateTestDataUtility.createCommunityUser(c.Id);
        Database.insert(u);
        
        list <MUSW__Parcel__c> parsToInsert= new list <MUSW__Parcel__c> ();
        MUSW__Parcel__c par = CreateTestDataUtility.createContactParcel(c.id,  'test',  'Test City', 'test', 'test', 'United States');
        parsToInsert.add(par);
        MUSW__Parcel__c par2 = CreateTestDataUtility.createContactParcel(c.id, '1150 University Ave', 'Madison', 'Wisconsin', '53706', 'United States');
        parsToInsert.add(par2);
        Database.insert(parsToInsert);
        
    }
    
       
}