src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>AFRS_AR_Code__c</fullName>
        <defaultValue>&quot;AFR-MG-MS-SubSrc-GLAR&quot;</defaultValue>
        <label>xAFRS AR Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Gateway_Transaction_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Gateway Transaction Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DOL_Dao_Test.cls
@isTest
public class DOL_Dao_Test {
	
    @isTest
    public static void test(){
        DOL_Dao dao = new DOL_Dao();
        Contact con = TestUtility.getContact();
        insert con;
        
        
        MUSW__Receipt__c receipt = new MUSW__Receipt__c();
        receipt.Bank_Name__c = 'DOL Bank';
        receipt.MUSW__Payment_Gateway_Transaction_Number__c = '000000ABCD';
        insert receipt;
        
        MUSW__Fee__c fees = new MUSW__Fee__c();
        fees.Account_Number__c = '123456UYTR';
        fees.AFRS_AR_Code__c = '8989898';
        insert fees;
        
        List<String> ids = new List<String>();
        ids.add(fees.Id);
        
        List<MUSW__Fee__c> sObjectList = new List<MUSW__Fee__c>();
        sObjectList.add(fees);
        
        dao.getContactDetailsForSessionTransfer(con.Id);
        dao.getReceiptForCartPage(receipt.Id);
        dao.getReceiptByTransactionId(receipt.MUSW__Payment_Gateway_Transaction_Number__c);
        dao.getReceiptByTransactionId('test');
        dao.getFeeAndFeePayment(ids);
        
        Dol_Dao.save(fees);
        Dol_Dao.save(sObjectList);
    }
}