src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Account_Contact__c.object
<CustomObject>
    <description>Junction object representing business associations</description>
    <label>Account Contact</label>
    <nameField>
        <displayFormat>ACX-{00000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Parcel for which the application is being submitted.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>Permit Submissions</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel_Contact2__c.object
<CustomObject>
    <description>Contacts associated to a Parcel eg. Owner</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parcel or address this contact is related to.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Parcel_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parcel Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a Permit</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits as Property</relationshipLabel>
        <relationshipName>Parcel_Permits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Permit2_Parcels</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated submission record(s).</description>
        <label>Submission</label>
        <referenceTo>MUSW__Submission__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review</label>
        <referenceTo>MUSW__Review__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parcel_Account__c.object
<CustomObject>
    <description>Store Address for Accounts</description>
    <label>Parcel Account</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateTestDataUtilityTest.cls
@isTest
public class CreateTestDataUtilityTest {
    @isTest
    static void createTestDataTest(){
        
        Account acc = CreateTestDataUtility.createAccount();
        Account busAcc = CreateTestDataUtility.createBusinessAccount();    
        //Account testAcc = CreateTestDataUtility.createTestAccount();
        Contact con = CreateTestDataUtility.createContact(acc.Id);
        //MUSW__Permit2__c permit = CreateTestDataUtility.createPermit(acc.Id, con.Id);
        
        Datetime startDate = Datetime.newInstance(2019, 02, 01);
        Datetime endDate = Datetime.newInstance(2019, 12, 01);
        //MUSW__Review__c permReview = CreateTestDataUtility.createPermitReview(permit, startDate, endDate);
        
        MUSW__Account_Contact__c accCon = CreateTestDataUtility.createAccountContact(acc.Id, con.Id);
        
        MUSW__Parcel__c accParcel = CreateTestDataUtility.createAccountParcel(acc.Id, con.Id, 'Madison Street', 'New York City', 'New York', '66579', 'United States');
        
        MUSW__License2__c lic = CreateTestDataUtility.createLicense(acc.Id, con.Id);
        MUSW__License_Parcel__c licParcel = CreateTestDataUtility.createLicenseParcel(acc.Id, lic.Id, accParcel.Id, true, false);
        
        //MUSW__Permit_Parcel__c permParcel = CreateTestDataUtility.createPermitParcel(acc.Id, permit.Id, accParcel.Id, true, false);
        
        Renewal_Application__c renewal = CreateTestDataUtility.createRenewal(lic.Id, 'Geologist', 'Geologist', 'Geologist', 'Pending', 'Renewal');
        
        //MUSW__Permit2__c permitMHC = CreateTestDataUtility.createPermitMHC(acc.Id, con.Id);
        
        String randomNo1 = CreateTestDataUtility.generateRandomNumber(5);
        String randomNo2 = CreateTestDataUtility.generateRandomNumber(4);
        
        MUSW__Master_Submission_List__c msl1 =  CreateTestDataUtility.createLicenseSubmissionList('Geologist', 'Geologist', 'Geologist', 'Application Method', 'MUSW__License2__c', 'Softcopy: To be Uploaded', 'License');
        MUSW__Master_Submission_List__c msl2 =  CreateTestDataUtility.createLicenseSubmissionList('Geologist', 'Geologist', 'Geologist', 'Application Method', 'Renewal_Application__c', 'Softcopy: To be Uploaded', 'Permit Renewal');
        MUSW__Master_Submission_List__c msl3 =  CreateTestDataUtility.createLicenseSubmissionList('Geologist', 'Geologist', 'Geologist', 'Application Method', 'Renewal_Application__c', 'Softcopy: To be Uploaded', 'Credential Renewal');
        MUSW__Master_Submission_List__c msl4 =  CreateTestDataUtility.createLicenseSubmissionList('Geologist', 'Geologist', 'Geologist', 'Application Method', 'Musw__Permit2__c', 'Softcopy: To be Uploaded', 'Credential Renewal');
        
        CreateTestDataUtility.createQuestionsForLicense('Geologist', 'Geologist', 'Geologist', 'General Application');
        
        MUSW__Submission__c sub = CreateTestDataUtility.createSubmission();
        
        User usr = CreateTestDataUtility.createCommunityUser(con.Id);
        //User user1 = CreateTestDataUtility.createBackendUser();
        //User user2 = CreateTestDataUtility.createBackendUser2();
        User user3 = CreateTestDataUtility.createCommunityPlusUser(con.Id);
        List<MUSW__License2__c> lstLicenses = CreateTestDataUtility.createMultipleLicenses(3, 'Geologist', 'Geologist', acc.Id, con.Id);
        MUSW__Parcel__c parcel2 = CreateTestDataUtility.createContactParcel(con.Id, 'Madison Street', 'New York City', 'New York', '66579', 'United States');
        
        MUSW__Parcel_Contact2__c parcelCon = CreateTestDataUtility.createParcelContactJunction(parcel2.Id, con.Id);
        
        Parcel_Account__c parAcc = CreateTestDataUtility.createParcelAccountJunction(parcel2.Id, acc.Id);
        
        Account acc2 = CreateTestDataUtility.createCitizenAccount();
        
        User usr4 = CreateTestDataUtility.createCommunityTestUser(con.Id);
        
        MUSW__Application2__c appl2 = CreateTestDataUtility.createServiceRequest();
        
        CreateTestDataUtility.createPageDefinition('Page', 'Geologist', 'Geologist', 'Geologist');
        
        CreateTestDataUtility.createPageDefinitionServiceRequest('Page', 'Update Legal Name');
    }
}