src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dol_Integration_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Field to Store Country details.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>List_of_Countries</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__City__c</fullName>
        <description>The City this parcel or address is located in.</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Post_Zip_Code__c</fullName>
        <description>Address associated with this parcel&apos;s Post or Zip Code.</description>
        <label>Post/Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parcels</relationshipLabel>
        <relationshipName>Parcels2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__State__c</fullName>
        <description>The state this parcel or address is located in.</description>
        <label>State/ Prov.</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WA</fullName>
                    <default>true</default>
                    <label>WA</label>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Street2__c</fullName>
        <description>The full address or street this parcel or address is located on.</description>
        <label>Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/List_of_Countries.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
        <default>true</default>
        <label>United States</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Burkina</fullName>
    </customValue>
    <customValue>
        <fullName>Burma</fullName>
    </customValue>
    <customValue>
        <fullName>Burundi</fullName>
    </customValue>
    <description>List of countries for selection on Applications</description>
    <masterLabel>List of Countries</masterLabel>
</GlobalValueSet>

src/classes/Dol_AddressValidationService.cls
public class Dol_AddressValidationService {
    @auraEnabled
    public static Dol_AddressValidationService.AddrWrapper validateAddress(String addrLine1,String addrLine2,String city, String state, String zip){
		String licenseKey;
		Dol_AddressValidationService.AddrWrapper validatedAddress = new Dol_AddressValidationService.AddrWrapper();
		
		Dol_Integration_Settings__mdt customSettings = [SELECT MasterLabel, DeveloperName, Value__c  FROM Dol_Integration_Settings__mdt where DeveloperName ='Address_LicenseKey' Limit 1];
		if(customSettings != null){
			licenseKey = customSettings.Value__c.trim();
		}
		String requestbody = '<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:MelissaDataAddressCheckService\" xmlns:urn1=\"urn:mdWebServiceAddress\">'
		+'<soapenv:Header/>'
		+'<soapenv:Body>'
		+'<urn:doAddressCheck>'
			+'<urn:Request>'
			+'<urn1:CustomerID>'+licenseKey+'</urn1:CustomerID>'
				+'<urn1:Record>'
				+'<urn1:AddressLine1>'+addrLine1+'</urn1:AddressLine1>'
            	+'<urn1:AddressLine2>'+addrLine2+'</urn1:AddressLine2>'
				+'<urn1:City>'+city+'</urn1:City>'
				+'<urn1:State>'+state+'</urn1:State>'
				+'<urn1:Zip>'+zip+'</urn1:Zip>'
				+'</urn1:Record>'
			+'</urn:Request>'
		+'</urn:doAddressCheck>'
		+'</soapenv:Body>'
		+'</soapenv:Envelope>';
		mdwebserviceaddress.ResponseArray res = new mdwebserviceaddress.ResponseArray();
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		request.setHeader('Content-Type', 'text/xml;charset=UTF-8');
		request.setHeader('SOAPAction', 'urn:MelissaDataAddressCheckService/IService/doAddressCheck');
		request.setEndpoint('https://addresscheck.melissadata.net/v2/SOAP/Service.svc');
		request.setMethod('POST');
		request.setBody(requestbody);
		HttpResponse response = new HttpResponse();
        if(!Test.isRunningTest()){
           response = new Http().send(request); 
        }
        else {
          response.setBody(Dol_AddressValidationService_Test.responsebody);
        }
		Dom.Document xml = response.getBodyDocument();
		Dom.XMLNode envelope = xml.getRootElement();
		Dom.XMLNode address = envelope.getChildElement('Body', 'http://schemas.xmlsoap.org/soap/envelope/').getChildElement('doAddressCheckResponse','urn:MelissaDataAddressCheckService').getChildElement('doAddressCheckResult','urn:MelissaDataAddressCheckService').getChildElement('Record','urn:mdWebServiceAddress').getChildElement('Address', 'urn:mdWebServiceAddress');
		validatedAddress.street = address.getChildElement('Address1', 'urn:mdWebServiceAddress').getText();
        validatedAddress.street2 = address.getChildElement('Suite', 'urn:mdWebServiceAddress').getText();
        System.debug('suite2'+validatedAddress.street2);
       	validatedAddress.city = address.getChildElement('City', 'urn:mdWebServiceAddress').getChildElement('Name', 'urn:mdWebServiceAddress').getText();
       	validatedAddress.state = address.getChildElement('State', 'urn:mdWebServiceAddress').getChildElement('Abbreviation', 'urn:mdWebServiceAddress').getText();
        String zipRange ;
        if(address.getChildElement('Zip', 'urn:mdWebServiceAddress').getText() != null){
          zipRange = address.getChildElement('Zip', 'urn:mdWebServiceAddress').getText();
            System.debug('zip**'+address.getChildElement('Plus4', 'urn:mdWebServiceAddress').getText());
            string plus4 = address.getChildElement('Plus4', 'urn:mdWebServiceAddress').getText();
                
            if(plus4 != null && plus4 != '' && plus4 !=' ' && plus4 != 'undefined'){
               zipRange += '-'+address.getChildElement('Plus4', 'urn:mdWebServiceAddress').getText();
            }
        }
        validatedAddress.zip = zipRange;
		System.debug('zipRange'+zipRange);
        validatedAddress.country = address.getChildElement('Country', 'urn:mdWebServiceAddress').getChildElement('Name', 'urn:mdWebServiceAddress').getText() == 'United States of America' ? 'United States' : '';
        return validatedAddress;
	}

	 @AuraEnabled
    public static String getObjAPI(String recordId) {
        if(recordId == null || recordId == '') {
            return null;
        }
        
        Id sRecordId = recordId;
        String objName = sRecordId.getSObjectType().getDescribe().getName();
        system.debug('!!!! createTimeEntry.objName = ' + objName);
        
        return objName;
    }
	 @AuraEnabled 
    public static List<String> getStates(sObject objObject, string fld) {
      system.debug('objObject:' + objObject);
      system.debug('fld:' + fld);
      List<String> allOpts = new list <String> ();
      // Get the object type of the SObject.
      Schema.sObjectType objType = objObject.getSObjectType();
     
      // Describe the SObject using its object type.
      Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
     
      // Get a map of fields for the SObject
      Map<String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
      List<Schema.PicklistEntry> values = fieldMap.get(fld).getDescribe().getPickListValues();
      for (Schema.PicklistEntry a: values) {
       allOpts.add(a.getValue());
      }
      system.debug('allOpts ---->' + allOpts);
      return allOpts;
    }
	@auraEnabled
	public static Boolean saveAddress(string selectedAddress,Boolean isAptInfo, String parentId){
		Boolean success = false;
        String addres1;
        String aptInfo;
        String city;
        String state;
        String zip;
        String country;
        
        try{
            if(Dol_IntegrationUtil.isNotBlank(selectedAddress)){
                selectedAddress= selectedAddress.replaceAll('\\<.*?\\>', '');
                List<String> Addresslist = selectedAddress.split(',');
                if(Dol_IntegrationUtil.isNotempty(Addresslist)){
                    addres1 = Addresslist[0] != null ? Addresslist[0].trim() : '';
                    //if address line 2 is null
                    if(!isAptInfo){
                        city = Addresslist[1] != null ? Addresslist[1].trim() : '';
                        state = Addresslist[2] != null ? Addresslist[2].trim() : '';
                        zip = Addresslist[3] != null ? Addresslist[3].trim() : '';
                        country = Addresslist[4] != null ? Addresslist[4].trim() : '';
                    }
                     //if address line 2 is NOT null
                    else if(isAptInfo){
                        city = Addresslist[2] != null ? Addresslist[2].trim() : '';
                        state = Addresslist[3] != null ? Addresslist[3].trim() : '';
                        zip = Addresslist[4] != null ? Addresslist[4].trim() : '';
                        country = Addresslist[5] != null ? Addresslist[5].trim() : '';
                    }
                }
                List<MUSW__Parcel__c> existingParcel = [SELECT id,MUSW__Primary_Contact__c from MUSW__Parcel__c where MUSW__Street2__c =:addres1 AND MUSW__City__c=:city AND MUSW__State__c=:state AND MUSW__Post_Zip_Code__c=:zip AND Country__c=:country Limit 1];
                if(Dol_IntegrationUtil.isNotempty(existingParcel)){
                    if(Dol_IntegrationUtil.isNotBlank(parentId)){
                        String sObjectName = getObjAPI(parentId) ;
                        if(sObjectName == 'Contact'){
                        	existingParcel[0].MUSW__Primary_Contact__c = parentId;
                        }
                        upsert existingParcel[0];
                        success = true;
                    }
                }
                else{
                    MUSW__Parcel__c parcel = new MUSW__Parcel__c();
                    parcel.MUSW__Street2__c = addres1;
                    parcel.MUSW__City__c = city;
                    parcel.MUSW__State__c = state;
                    parcel.MUSW__Post_Zip_Code__c = zip;
                    parcel.Country__c = country;
                    if(Dol_IntegrationUtil.isNotBlank(parentId)){
                        String sObjectName = getObjAPI(parentId) ;
                        system.debug('sObjectName'+sObjectName);
                        if(sObjectName == 'Contact'){
                            system.debug('sObjectNameconatct');
                            
                            parcel.MUSW__Primary_Contact__c = parentId;
                        }
                	}
                    System.debug('parcel' + parcel);
                    if(parcel != null){
                        upsert parcel;
                        if(Dol_IntegrationUtil.isNotBlank(parcel.id)){
                            success = true;
                        }
                    } 
                  }
            	}
            }catch(Exception e){
            System.debug('Dol_AddressValidationService - Exception: '+e);
            DebugErrorLoggger.LogError(e, '', '','Dol_AddressValidationService','saveAddress','saveAddress Method failed');  
        }
		
		return success;
	}
    public class AddrWrapper {
		@auraEnabled	public String country {get;set;}
		@auraEnabled	public String street {get;set;}
        @auraEnabled	public String street2 {get;set;}
		@auraEnabled	public String city {get;set;}
		@auraEnabled	public String state {get;set;}
		@auraEnabled	public String zip {get;set;}
	}

}