src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>This is the grouping for related POWTS worker.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Group Type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Group_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group_Resource__c.object
<CustomObject>
    <description>Group Resource</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Group Resource</relationshipLabel>
        <relationshipName>Group_Resource</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Group Resource</relationshipLabel>
        <relationshipName>Group_Resource</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Resource</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Group Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Resource</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Hours_Based_on_Answers__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>To store review hours based on applicant answers which will then be used by DRE to compute the total estimated time required for review completion</description>
        <label>Review Hours Based on Answers</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <recordTypes>
        <fullName>POWTS</fullName>
        <active>true</active>
        <label>POWTS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrgSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Minimum_Slot_duration__c</fullName>
        <label>Minimum Slot duration</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type (To be Deleted)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start Time</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this an active resource?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This is the application type related to resource</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Review_Types__c</fullName>
        <description>Plan Review types</description>
        <label>Permit / Plan Review Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWTS Individual Site Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Petition for Variance</fullName>
                </value>
                <value>
                    <fullName>POWTS Experimental System</fullName>
                </value>
                <value>
                    <fullName>POWTS Miscellaneous Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Sanitary Permit</fullName>
                </value>
                <value>
                    <fullName>POWTS State-Owned Privy Registration</fullName>
                </value>
                <value>
                    <fullName>POWTS Consultation</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Soil Saturation Determination</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Community Permit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the resource.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <recordTypes>
        <fullName>POWTS</fullName>
        <active>true</active>
        <label>POWTS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Resource_Availability_Modifier__c.object
<CustomObject>
    <description>Resource Availability Modifier</description>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Availability Modifiers</relationshipLabel>
        <relationshipName>Resource_Availability_Modifiers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Resource_Modifier_Availability_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Resource Availability Modifier</label>
    <nameField>
        <displayFormat>RMA-{0000}</displayFormat>
        <label>ResourceModifier Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availability Modifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End Time</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This is the Start time</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time_Slot_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TSN-{0000}</displayFormat>
        <label>Time Slots Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Group_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Location</fullName>
        <default>true</default>
        <label>Location</label>
    </customValue>
    <masterLabel>Group Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Resource_Modifier_Availability_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
        <default>true</default>
        <label>Eligible</label>
    </customValue>
    <masterLabel>Resource Modifier Availability Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Time_Slot_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Free</fullName>
    </customValue>
    <customValue>
        <fullName>Available</fullName>
    </customValue>
    <customValue>
        <fullName>Busy</fullName>
    </customValue>
    <masterLabel>Time Slot Status</masterLabel>
</GlobalValueSet>

src/classes/PlanReviewControllerTest.cls
@isTest
public class PlanReviewControllerTest {
    public user usered;
    @testSetup static void setup(){
        List<Account> lstAccounts = new List<Account>();
        Account acc = CreateTestDataUtility.createAccount();
        insert acc;
        Account acc1 = CreateTestDataUtility.createCitizenAccount();   
        lstAccounts.add(acc1);
        insert acc1;
        Contact testContact = CreateTestDataUtility.createContact(acc.id);  
        insert testContact;
        MUSW__Permit2__c testpermit = CreateTestDataUtility.createPermit(acc.id,testContact.id );
        insert testpermit;         
        User u = CreateTestDataUtility.createCommunityTestUser(testContact.id);    
        u.ContactId =    testContact.Id;   
        Database.insert(u); 
        Date currentDate = Date.today();
        Integer currentYear = currentDate.year();
        Integer currentMonth = currentDate.Month();
        Integer currentDay = currentDate.Day();
        DateTime startTime=Datetime.newInstance(currentYear, currentMonth, currentDay);
        DateTime endTime=Datetime.newInstance(currentYear, currentMonth+1, currentDay);
        OrgSettings__c os  = new OrgSettings__c();
        os.Minimum_Slot_duration__c=0.5;
        os.Name='Fbslots';
        insert os;
        BusinessHours bh=[select id from BusinessHours where IsDefault=true limit 1];
        List<Time_Slot__c> newSlots = CommonUtil.generateNewTimeSlots(startTime, endTime, os, bh);
        insert newslots;
    }  
    
    @isTest
    public static  void testMyController() {
        MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
        PageReference pageRef = Page.PlanReviewScheduler;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Time_Slot__c timeslottest = new Time_Slot__c();
        // Insert account as current user
        User user = [SELECT Id, ContactId FROM User WHERE ContactId = :permit.musw__applicant__r.Id  limit 1];
        System.runAs (thisUser) {
            
            User a=CreateTestDataUtility.createBackendUser();
            insert a;
            Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=a.id;
            rsc.Plan_Review_Types__c='POWTS Petition for Variance';
            insert rsc;
            Group__c grp = new Group__c();
            grp.Name	='POWTS';
            grp.Application_Type__c= label.Str_Plan_Review;
            grp.type__C='Location';
            insert grp;
            Group_Resource__c seven = new Group_Resource__c();
            seven.Resource__c= rsc.id;
            seven.Group__c=grp.Id;
            seven.Application_Type__c=label.Str_Plan_Review;
            insert seven;
            
            
            timeslottest.Application_Type__c=label.Str_Plan_Review;
            timeslottest.Resource__c=rsc.id;
            timeslottest.Status__c='Available';
            timeslottest.Start_Time__c=System.now().adddays(1);
            timeslottest.End_Time__c=timeslottest.Start_Time__c.addhours(2);
            insert timeslottest;
            
            Time_slot__c oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Status__c='Available';
            oneslot.Start_Time__c=System.now().adddays(1);
            oneslot.End_Time__c=timeslottest.Start_Time__c.addhours(3);
            insert oneslot;
            
        }
        System.runAs(user){
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('permitId', permit.id);
            test.startTest();
            
            
            
            PlanReviewSchedulerCC controller = new PlanReviewSchedulerCC();  
            controller.schedulereview(); 
            Test.setCurrentPage(pageRef);
            controller.getCounties();
            controller.getItems();
            //List<Resource__c> rsc =controller.getResource('Testibg','Plan Review');
            ApexPages.currentPage().getParameters().put('timeslot', timeslottest.id);
            controller.setThisTimeSlotAsFinal();
            Pagereference pgref= controller.confirm(); 
            test.stopTest();
        }
    }
    
     @isTest
    public static  void testMyController6() {
        MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
        permit.Review_Hours_Based_on_Answers__c=9.0;
        update permit;
        PageReference pageRef = Page.PlanReviewScheduler;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Time_Slot__c timeslottest = new Time_Slot__c();
        // Insert account as current user
        User user = [SELECT Id, ContactId FROM User WHERE ContactId = :permit.musw__applicant__r.Id  limit 1];
        System.runAs (thisUser) {
            
            User a=CreateTestDataUtility.createBackendUser();
            insert a;
            Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=a.id;
            rsc.Plan_Review_Types__c='POWTS Petition for Variance';
            insert rsc;
            Group__c grp = new Group__c();
            grp.Name	='POWTS';
            grp.Application_Type__c= label.Str_Plan_Review;
            grp.type__C='Location';
            insert grp;
            Group_Resource__c seven = new Group_Resource__c();
            seven.Resource__c= rsc.id;
            seven.Group__c=grp.Id;
            seven.Application_Type__c=label.Str_Plan_Review;
            insert seven;
            
            
            timeslottest.Application_Type__c=label.Str_Plan_Review;
            timeslottest.Resource__c=rsc.id;
            timeslottest.Status__c='Available';
            timeslottest.Start_Time__c=System.now().adddays(1);
            timeslottest.End_Time__c=timeslottest.Start_Time__c.addhours(2);
            insert timeslottest;
            
            Time_slot__c oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Status__c='Available';
            oneslot.Start_Time__c=System.now().adddays(1);
            oneslot.End_Time__c=timeslottest.Start_Time__c.addhours(3);
            insert oneslot;
            
        }
        System.runAs(user){
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('permitId', permit.id);
            test.startTest();
            
            
            
            PlanReviewSchedulerCC controller = new PlanReviewSchedulerCC();  
            controller.schedulereview(); 
            Test.setCurrentPage(pageRef);
            controller.getCounties();
            controller.getItems();
            //List<Resource__c> rsc =controller.getResource('Testibg','Plan Review');
            ApexPages.currentPage().getParameters().put('timeslot', timeslottest.id);
            controller.setThisTimeSlotAsFinal();
            Pagereference pgref= controller.confirm(); 
            test.stopTest();
        }
    }
    
    @isTest
    public static  void testMyController2() {
        MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
        PageReference pageRef = Page.PlanReviewScheduler;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Time_Slot__c timeslottest = new Time_Slot__c();
        // Insert account as current user
        User user = [SELECT Id, ContactId FROM User WHERE ContactId = :permit.musw__applicant__r.Id  limit 1];
        User a= new user();
        System.runAs (thisUser) {
            
            a=CreateTestDataUtility.createBackendUser();
            insert a;
            Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=a.id;
            rsc.Plan_Review_Types__c='POWTS Petition for Variance';
            insert rsc;
             Resource__c rsc2 = new Resource__c();
               User b=CreateTestDataUtility.createBackendUser2();
            insert b;
            rsc2.Application_Type__c=label.Str_Plan_Review;
            rsc2.Active__c=true;
            rsc2.User__c=b.id;
            rsc2.Plan_Review_Types__c='POWTS Petition for Variance';
            insert rsc2;
            Group__c grp = new Group__c();
            grp.Name	='POWTS';
            grp.Application_Type__c= label.Str_Plan_Review;
            grp.type__C='Location';
            insert grp;
            Group_Resource__c seven = new Group_Resource__c();
            seven.Resource__c= rsc.id;
            seven.Group__c=grp.Id;
            seven.Application_Type__c=label.Str_Plan_Review;
            insert seven;
            Group_Resource__c sev = new Group_Resource__c();
            sev.Resource__c= rsc2.id;
            sev.Group__c=grp.Id;
            sev.Application_Type__c=label.Str_Plan_Review;
            insert sev;
            
            
            timeslottest.Application_Type__c=label.Str_Plan_Review;
            timeslottest.Resource__c=rsc.id;
            timeslottest.Status__c='Available';
            timeslottest.Start_Time__c=System.now().adddays(1);
            timeslottest.End_Time__c=timeslottest.Start_Time__c.addhours(2);
            insert timeslottest;
            
            Time_slot__c oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Status__c='Available';
            oneslot.Start_Time__c=System.now().adddays(1);
            oneslot.End_Time__c=oneslot.Start_Time__c.addhours(3);
            insert oneslot;
            
            Time_slot__c onesl = new time_slot__C();
            onesl.Application_Type__c=label.Str_Plan_Review;
            onesl.Resource__c=rsc2.id;
            onesl.Status__c='Available';
            onesl.Start_Time__c=System.now().adddays(1);
            onesl.End_Time__c=onesl.Start_Time__c.addhours(2);
            insert onesl;
            
            Time_slot__c oneslt = new time_slot__C();
            oneslt.Application_Type__c=label.Str_Plan_Review;
            oneslt.Resource__c=rsc2.id;
            oneslt.Status__c='Available';
            oneslt.Start_Time__c=System.now().adddays(1);
            oneslt.End_Time__c=oneslt.Start_Time__c.addhours(3);
            insert oneslt;
            
        }
        System.runAs(user){
                        Request__C REQ= NEW Request__C();
            req.Contact__c=permit.MUSW__Applicant__c;
            req.Permit_Plan_Review__c=permit.Id;
            req.Start_Time__c=System.now().adddays(1);
            req.End_Time__c=req.Start_Time__c.addhours(1);
            req.Status__c=Label.ST_Scheduled ;
            insert req;
            Test.setCurrentPage(pageRef);

            ApexPages.currentPage().getParameters().put('permitId', permit.id);
            test.startTest();
            PlanReviewSchedulerCC controller = new PlanReviewSchedulerCC();  
            controller.searchtype=Label.Str_Search_for_reviewer;
            ApexPages.currentPage().getParameters().put('myParam',a.id);
            controller.schedulereview(); 
            Test.setCurrentPage(pageRef);
            controller.getCounties();
            PlanReviewSchedulerCC.getResource('test','test');
            ApexPages.currentPage().getParameters().put('timeslot', timeslottest.id);
            controller.setThisTimeSlotAsFinal();
            test.stopTest();
        }
    }
    
    public static testMethod void testMyController3() {
        PageReference pageRef = Page.PlanReviewScheduler;
         MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
                User user = [SELECT Id, ContactId FROM User WHERE ContactId = :permit.musw__applicant__r.Id  limit 1];
        System.runAs(user){
            test.startTest();
            Test.setCurrentPage(pageRef);
            PlanReviewSchedulerCC controller = new PlanReviewSchedulerCC();            // New Agreement
            test.stopTest();
        }
    }
    
    public static testMethod void testMyController4() {
        PageReference pageRef = Page.PlanReviewScheduler;
         MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
                User user = [SELECT Id, ContactId FROM User WHERE ContactId = :permit.musw__applicant__r.Id  limit 1];
        System.runAs(user){
            test.startTest();
            Test.setCurrentPage(pageRef);
             ApexPages.currentPage().getParameters().put('permitId', permit.id+'23232');
            PlanReviewSchedulerCC controller = new PlanReviewSchedulerCC();            // New Agreement
            test.stopTest();
        }
    }
    
       @isTest
    public static  void testMyController7() {
        MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
        PageReference pageRef = Page.PlanReviewScheduler;
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        Time_Slot__c timeslottest = new Time_Slot__c();
        // Insert account as current user
        System.runAs (thisUser) {
            
            User a=CreateTestDataUtility.createBackendUser();
            insert a;
            Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=a.id;
            rsc.Plan_Review_Types__c='POWTS Petition for Variance';
            insert rsc;
            Group__c grp = new Group__c();
            grp.Name	='POWTS';
            grp.Application_Type__c= label.Str_Plan_Review;
            grp.type__C='Location';
            insert grp;
            Group_Resource__c seven = new Group_Resource__c();
            seven.Resource__c= rsc.id;
            seven.Group__c=grp.Id;
            seven.Application_Type__c=label.Str_Plan_Review;
            insert seven;
            
            
            timeslottest.Application_Type__c=label.Str_Plan_Review;
            timeslottest.Resource__c=rsc.id;
            timeslottest.Status__c=Label.ST_Available;
            timeslottest.Backend_User__c=a.id;
            timeslottest.Start_Time__c=System.now().adddays(1);
            timeslottest.End_Time__c=timeslottest.Start_Time__c.addhours(2);
            insert timeslottest;
            
            Time_slot__c oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Backend_User__c=a.id;
            oneslot.Status__c=Label.ST_Available;
            oneslot.Start_Time__c=System.now().adddays(1);
            oneslot.End_Time__c=timeslottest.Start_Time__c.addhours(3);
            insert oneslot;
            
             oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Backend_User__c=a.id;
            oneslot.Status__c=Label.ST_Available;
            oneslot.Start_Time__c=System.now().adddays(3);
            oneslot.End_Time__c=timeslottest.Start_Time__c.addhours(3);
            insert oneslot;
            
             oneslot = new time_slot__C();
            oneslot.Application_Type__c=label.Str_Plan_Review;
            oneslot.Resource__c=rsc.id;
            oneslot.Backend_User__c=a.id;
            oneslot.Status__c=Label.ST_Available;
            oneslot.Start_Time__c=System.now().adddays(4);
            oneslot.End_Time__c=timeslottest.Start_Time__c.addhours(3);
            insert oneslot;
            
             SYstem.debug('Label.ST_UnAvailable  '+[Select id,Resource__c,Start_Date__c from time_slot__c where Resource__c=:rsc.id and Backend_User__c!='' and status__c=:Label.ST_Available]);
            Resource_Availability_Modifier__c ram = new Resource_Availability_Modifier__c();
            ram.Activity__c=Label.ST_Unavailable;
            ram.Resource__c=rsc.id;
            ram.Date__c=System.today().adddays(1);
            ram.Activity__c=Label.Str_Make_UnAvailable;
            insert ram;
            
            
            Resource_Availability_Modifier__c ram2 = new Resource_Availability_Modifier__c();
            ram2.Activity__c=Label.Str_Make_Available;
            ram2.Resource__c=rsc.id;
            ram2.Date__c=System.today().adddays(3);
            ram2.Time_Availability_per_Day__c='8.00 to 8.30';
            insert ram2;
            
            ram2 = new Resource_Availability_Modifier__c();
            ram2.Activity__c=Label.Str_Make_Available;
            ram2.Resource__c=rsc.id;
            ram2.Date__c=System.today().adddays(3);
            ram2.Time_Availability_per_Day__c=Label.ST_Unavailable;
            insert ram2;
            SYstem.debug('Label.ST_Available  '+[Select id from time_slot__C]);
            
        }
    }
    
   public static testMethod void testMyController8() {
        OrgSettings__c os=TimeSlotsHelper.getFBSlotSettings(null);
        BusinessHours bh=TimeSlotsHelper.getBusinessHours();
       TimeSlotsHelper.createFreeFBSlots(System.now(),  os,  bh, 2);
    }
    
       public static testMethod void testMyController9() {
       MUSW__Permit2__c permit = [Select Id,musw__applicant__c ,MUSW__Applicant__r.iD from MUSW__Permit2__c limit 1];
        permit.State_Owned_Facility__c=true;
           update permit;
        MUSW__Review__c review = new MUSW__Review__c ();
           review.MUSW__Status__c=Label.ST_Pending;
           review.MUSW__Permit2__c=permit.id;
           insert review;
           review.MUSW__Status__c='Approved';
           review.Start_Date__c=System.today();
           review.MUSW__Completed_DateTime__c=System.today().adddays(1);
           update review;
    }

    
    
    
}