src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group__c.object
<CustomObject>
    <description>This is the grouping for related POWTS worker.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Group Type</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Group_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Group_Resource__c.object
<CustomObject>
    <description>Group Resource</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Group Resource</relationshipLabel>
        <relationshipName>Group_Resource</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Group Resource</relationshipLabel>
        <relationshipName>Group_Resource</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group Resource</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Group Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Resource</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OrgSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Minimum_Slot_duration__c</fullName>
        <label>Minimum Slot duration</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this an active resource?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This is the application type related to resource</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Review_Types__c</fullName>
        <description>Plan Review types</description>
        <label>Permit / Plan Review Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWTS Individual Site Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Petition for Variance</fullName>
                </value>
                <value>
                    <fullName>POWTS Experimental System</fullName>
                </value>
                <value>
                    <fullName>POWTS Miscellaneous Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Sanitary Permit</fullName>
                </value>
                <value>
                    <fullName>POWTS State-Owned Privy Registration</fullName>
                </value>
                <value>
                    <fullName>POWTS Consultation</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Soil Saturation Determination</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Community Permit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the resource.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <recordTypes>
        <fullName>POWTS</fullName>
        <active>true</active>
        <label>POWTS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Resource_Availability__c.object
<CustomObject>
    <fields>
        <fullName>Autorenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Autorenewal Schedule</description>
        <label>Autorenewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Backend_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Backend User</description>
        <label>Backend User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_Number__c</fullName>
        <formula>CASE(Day__c ,&apos;Sunday&apos;,0,&apos;Monday&apos;,1,&apos;Tuesday&apos;,2,&apos;Wednesday&apos;,3,&apos;Thursday&apos;,4,&apos;Friday&apos;,5,&apos;Saturday&apos;,6,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day__c</fullName>
        <description>Day</description>
        <label>Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Days_of_the_Week</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Availability_Start_Date__c</fullName>
        <description>New Availability Start Date</description>
        <label>New Availability Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Time_Availability__c</fullName>
        <description>New Time Availability</description>
        <label>New Time Availability</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Working_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource_Week_Availability__c</fullName>
        <description>Resource Week Availability</description>
        <label>Resource Week Availability</label>
        <referenceTo>Resource_Week_Availability__c</referenceTo>
        <relationshipLabel>Resource Availability</relationshipLabel>
        <relationshipName>Resource_Availability</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <description>Resource connected.</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Availability</relationshipLabel>
        <relationshipName>Resource_Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_Availability__c</fullName>
        <description>Time Availability of the resource</description>
        <label>Time Availability</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Working_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_From_Date__c</fullName>
        <formula>Resource_Week_Availability__r.Schedule_Valid_From__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_till_Date__c</fullName>
        <formula>Resource_Week_Availability__r.Schedule_Valid_till__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valid till Date</label>
        <type>Date</type>
    </fields>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Resource Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Resource_Week_Availability__c.object
<CustomObject>
    <fields>
        <fullName>Autorenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Autorenewal</description>
        <label>Autorenewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Backend_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Backend_User__c</description>
        <label>Backend User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Week_Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Week Availability</relationshipLabel>
        <relationshipName>Resource_Group_Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Valid_till__c</fullName>
        <description>Schedule Valid till</description>
        <label>Schedule Valid till</label>
        <type>Date</type>
    </fields>
    <label>Resource Week Availability</label>
    <nameField>
        <displayFormat>RWA-{0000}</displayFormat>
        <label>Resource Week Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Week Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backend_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Backend User</description>
        <label>Backend User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TSN-{0000}</displayFormat>
        <label>Time Slots Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Days_of_the_Week.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Monday</fullName>
    </customValue>
    <customValue>
        <fullName>Tuesday</fullName>
    </customValue>
    <customValue>
        <fullName>Wednesday</fullName>
    </customValue>
    <customValue>
        <fullName>Thursday</fullName>
    </customValue>
    <customValue>
        <fullName>Friday</fullName>
    </customValue>
    <masterLabel>Days of the Week</masterLabel>
</GlobalValueSet>

src/globalValueSets/Group_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Location</fullName>
        <default>true</default>
        <label>Location</label>
    </customValue>
    <masterLabel>Group Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Working_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8.00 to 8.30</fullName>
    </customValue>
    <customValue>
        <fullName>8.30 to 9.00</fullName>
    </customValue>
    <customValue>
        <fullName>9.00 to 9.30</fullName>
    </customValue>
    <customValue>
        <fullName>9.30 to 10.00</fullName>
    </customValue>
    <customValue>
        <fullName>10.00 to 10.30</fullName>
    </customValue>
    <customValue>
        <fullName>10.30 to 11.00</fullName>
    </customValue>
    <customValue>
        <fullName>11.00 to 11.30</fullName>
    </customValue>
    <customValue>
        <fullName>11.30 to 12.00</fullName>
    </customValue>
    <customValue>
        <fullName>12.00 to 12.30</fullName>
    </customValue>
    <customValue>
        <fullName>12.30 to 13.00</fullName>
    </customValue>
    <customValue>
        <fullName>13.00 to 13.30</fullName>
    </customValue>
    <customValue>
        <fullName>13.30 to 14.00</fullName>
    </customValue>
    <customValue>
        <fullName>14.00 to 14.30</fullName>
    </customValue>
    <customValue>
        <fullName>14.30 to 15.00</fullName>
    </customValue>
    <customValue>
        <fullName>15.00 to 15.30</fullName>
    </customValue>
    <customValue>
        <fullName>15.30 to 16.00</fullName>
    </customValue>
    <customValue>
        <fullName>Unavailable</fullName>
    </customValue>
    <description>Working Hours</description>
    <masterLabel>Working Hours</masterLabel>
</GlobalValueSet>

src/classes/TimeMapTest.cls
@isTest
public class TimeMapTest {
    
    public user usered;
    @testSetup static void setup(){
        Account testAccount = CreateTestDataUtility.createAccount();       
        insert testAccount;
        Contact testContact = CreateTestDataUtility.createContact(testAccount.id);  
        insert testContact;
        MUSW__License2__c testLicense = CreateTestDataUtility.createLicense(testAccount.id,testContact.id );
        insert testLicense;         
        User u = CreateTestDataUtility.createCommunityTestUser(testContact.id);    
        u.ContactId =    testContact.Id;   
        Database.insert(u); 
        Date currentDate = Date.today();
        Integer currentYear = currentDate.year();
        Integer currentMonth = currentDate.Month();
        Integer currentDay = currentDate.Day();
        DateTime startTime=Datetime.newInstance(currentYear, currentMonth, currentDay);
        DateTime endTime=Datetime.newInstance(currentYear, currentMonth+1, currentDay);
        OrgSettings__c os  = new OrgSettings__c();
        os.Minimum_Slot_duration__c=1.0;
        os.Name= DOL_AppConstants.NULL_EMPTY_STRING + 'Fbslots';
        insert os;
        BusinessHours bh=[select id from BusinessHours where IsDefault=true limit 1];
        List<Time_Slot__c> newSlots = CommonUtil.generateNewTimeSlots(startTime, endTime, os, bh);
        insert newslots;
    }
    
    public testmethod static void TimeMap_Test2() {
        test.startTest();
                User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
             User testuser=CreateTestDataUtility.createBackendUser();
            insert testuser;
          Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=testuser.id;
            rsc.Plan_Review_Types__c= DOL_AppConstants.NULL_EMPTY_STRING + 'POWTS Petition for Variance';
            insert rsc;
            Group__c grp = new Group__c();
            grp.Name	= DOL_AppConstants.NULL_EMPTY_STRING + 'POWTS';
            grp.Application_Type__c= label.Str_Plan_Review;
            grp.type__C= DOL_AppConstants.NULL_EMPTY_STRING + 'Location';
            insert grp;           
     Group_Resource__c seven = new Group_Resource__c();
            seven.Resource__c= rsc.id;
            seven.Group__c=grp.Id;
            seven.Application_Type__c=label.Str_Plan_Review;
            insert seven;
               Resource_Week_Availability__c nwResLocAvai = new Resource_Week_Availability__c();
        nwResLocAvai.Schedule_Valid_till__c = Date.Today();        
        nwResLocAvai.Resource__c = rsc.ID;
        nwResLocAvai.Backend_User__c=testuser.id;
        nwResLocAvai.Autorenewal__c=true;
        insert nwResLocAvai;
        Resource_Availability__c a =[SELECT Backend_User__c, Valid_till_Date__c, Resource_Week_Availability__c, Day_Number__c, New_Time_Availability__c, Time_Availability__c, Day__c, Autorenewal__c, Resource__c, New_Availability_Start_Date__c, Valid_From_Date__c, Id FROM Resource_Availability__c limit 1];
        a.Time_Availability__c= DOL_AppConstants.NULL_EMPTY_STRING + '8.00 to 8.30';
        List<Resource_Availability__c> rscavails = new  List<Resource_Availability__c>();
        rscavails.add(a);
        update a;
        
        TimeMap t = new TimeMap(rscavails);
        
        t.availbility.add(new Resource_Availability__c());
        t.constructDayTimeMap();
        
        
        t.getTimeByString('666', '777');
        t.getAllTime(21);
        t.getTimeBetweenStartAndEndTime(datetime.now(), datetime.now() + 1);
        
        a.New_Time_Availability__c= DOL_AppConstants.NULL_EMPTY_STRING + '8.00 to 8.30; 8.30 to 9.00';
        List<Resource_Availability__c> rscavails2 = new  List<Resource_Availability__c>();
        rscavails.add(a);
        TimeMap t2 = new TimeMap(rscavails2);        
        t2.availbility.add(a);
        t2.constructDayTimeMap();       
        t2.getTimeByString('666', '777');
        t2.getAllTime(21);
        t2.getTimeBetweenStartAndEndTime(datetime.now(), datetime.now() + 1);
        
        TimeMap mp1 = new TimeMap(rsc.Id);
        mp1.availbility.add(new Resource_Availability__c());
        mp1.constructDayTimeMap();
        mp1.getTimeByString('666', '777');
        mp1.getAllTime(21);
        mp1.getTimeBetweenStartAndEndTime(datetime.now(), datetime.now() + 1);
        System.assert(mp1!=null);
        test.stopTest();
        }
    }
    
}