src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Education_History__c.object
<CustomObject>
    <description>This is an object used to store the education history of the user.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This the application type of the credential.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the credential the license is related to.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Education History</relationshipLabel>
        <relationshipName>Education_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Results Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EDUH-{000000}</displayFormat>
        <label>Education History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <recordTypes>
        <fullName>Exam</fullName>
        <active>true</active>
        <label>Exam</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the review.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved with Conditions</fullName>
                </value>
                <value>
                    <fullName>Corrections Required</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Exam Approved</fullName>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Audit Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_SubStatus__c</fullName>
        <label>Review Sub-Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MUSW__Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FE Approved</fullName>
                </value>
                <value>
                    <fullName>PE Approved</fullName>
                </value>
                <value>
                    <fullName>PE/FE Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Application</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Maintenance Request</fullName>
                </value>
                <value>
                    <fullName>CE Audit</fullName>
                </value>
                <value>
                    <fullName>Comity</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
                <value>
                    <fullName>Exam Review</fullName>
                    <isActive>false</isActive>
                    <label>Exam Review</label>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <isActive>false</isActive>
                    <label>New Application</label>
                </value>
                <value>
                    <fullName>Renew</fullName>
                    <isActive>false</isActive>
                    <label>Renew</label>
                </value>
                <value>
                    <fullName>Sending Activation Code</fullName>
                    <isActive>false</isActive>
                    <label>Sending Activation Code</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Exam_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agricultural &amp; Biological Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Architectural Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Architecture Law Review</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Construction &amp; Evaluation</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Practice Management</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Programming &amp; Analysis</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Project Development &amp; Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Project Management</fullName>
    </customValue>
    <customValue>
        <fullName>ARE - 5.0 Project Planning &amp; Design</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential</fullName>
    </customValue>
    <customValue>
        <fullName>Chemical Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Civil Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Control Systems Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Sciences Exam</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer - State Law Review Exam</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering Law Review Exam</fullName>
    </customValue>
    <customValue>
        <fullName>Environmental Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Fire Protection Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Fundamental of Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Fundamentals of Geology</fullName>
    </customValue>
    <customValue>
        <fullName>Fundamentals of Land Surveying exam (FLS)</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Arts Exam</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director - State Law Review Exam</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial Engineering (PE)</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Law Review</fullName>
    </customValue>
    <customValue>
        <fullName>Land Surveyor Law Review Exam</fullName>
    </customValue>
    <customValue>
        <fullName>LARE - Construction Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>LARE - Design</fullName>
    </customValue>
    <masterLabel>Exam Type</masterLabel>
</GlobalValueSet>

src/classes/ExamReschedule_Test.cls
@isTest
public class ExamReschedule_Test {
    
    @isTest
    public static void getEducationHistoryDataTest(){
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('User Account').getRecordTypeId();
        Id ConRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Id LicRecTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        Id ReviewRecTypeId = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get('License Review').getRecordTypeId();
        Id ExamRecTypeId = Schema.SObjectType.Education_History__c.getRecordTypeInfosByName().get('Exam').getRecordTypeId();
        User newUser;
        
        Account acc = DOL_TestDataFactory.createAccount(AccRecTypeId);  
        //insert acc;
        Contact con = DOL_TestDataFactory.createContact(ConRecTypeId,acc.id);
        //insert con;
        try{
            User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            
            /*Profile p = [select Id,name from Profile where name ='eSLA Customer Community Plus Login User'  limit 1];
            System.debug('***profile***'+p);
            newUser = DOL_TestDataFactory.createPortalUser('lastName', 'nuser',p.id,'pb@ff.com',con.id );
            insert newUser;
            */
            //Insert for License
            MUSW__License2__c licObj = new MUSW__License2__c(
                Name='System Number', 
                RecordTypeId = LicRecTypeId,
                MUSW__Primary_Licensee__c = acc.id, 
                Application_Type__c = 'Geologist',
                Credential_Type__c = 'Geologist',
                Application_Method__c = 'General Application',
                MUSW__Applicant__c =  con.Id);
            insert licObj;
            System.debug('***licObj***'+licObj);
                 
            MUSW__Review__c testReview = new MUSW__Review__c();
            testReview.Name = 'General Application Review';
            testReview.License__c = licObj.Id;
            testReview.Application_Type__c = licObj.Application_Type__c;
            testReview.License_Type__c = licObj.Credential_Type__c;
            testReview.Review_Type__c = 'General Application';
            testReview.RecordTypeId = ReviewRecTypeId;
            testReview.MUSW__Status__c = 'Pending';
            insert testReview;
            
            testReview.MUSW__Status__c = 'Exam Approved';
            testReview.Review_SubStatus__c = 'PE Approved';
            update testReview;
            
            Education_History__c testExamRecord = new Education_History__c();
            testExamRecord.Exam_Type__c = 'Washington State Hydrogeology Exam (PE)';
            testExamRecord.License_Type__c = 'Geologist';
            testExamRecord.Program_Type__c = 'Geologist';
            testExamRecord.Status__c = 'Pending';
            testExamRecord.License__c = licObj.Id;
            insert testExamRecord;
            
            licObj.MUSW__Status__c = 'In-Review';
            update licObj;
            String licenseId = licObj.Id;
            String examRecID = testExamRecord.Id;
            
            List<Education_History__c> examRecs = ExamReschedule.getEducationHistoryData(licenseId);
         
            ExamReschedule.insertRequestExam(licenseId,'Geologist' ,'Geologist', 'Exam Reschedule',examRecID );
        }
        
        }catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e);
            system.debug('Exception e '+ e);
        }
        
       
    }
        
        
    }