src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Issue_Date__c</fullName>
        <description>Date when license was issued</description>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date the permit expires on.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Issue_Date__c</fullName>
        <description>Date the permit was issued (approved).</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/Licenses_Custom_RL_Controller_CC.cls
/*************************************************************************************************************
**************************************************************************************************************
** Name                	: Licenses_Custom_RL_Controller_CC
** Description     		: Controller class for Licenses_Custom_Related_List_On_Contact
** Version            	: 1.0
** Built By             : Aishwaria Rangineni
**-----------------------------------------------------------------------------------------------------------------
** Modification Log:
**--------------------------
** Developer                         Date                    Version                      Description
**----------------------------------------------------------------------------------------------------------------
** 
**
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**---------------------------------------------------------------------------------------------------------------
**
*************************************************************************************************************/
public without sharing class Licenses_Custom_RL_Controller_CC{
    
    //Set up the standard controller connection and get current record 
    ApexPages.StandardController controller;
    public Contact record {get; set;}
    public list<MUSW__License2__c> lstLicense {get; set;}
    public list<MUSW__Permit2__c> lstPlanReviews {get; set;}
    public list<MUSW__Permit2__c> lstPermits {get; set;}
    
    public Licenses_Custom_RL_Controller_CC(ApexPages.StandardController controller){
        this.controller = controller;
        this.record = (Contact)controller.getrecord();
        lstPlanReviews = new  list<MUSW__Permit2__c>();
        lstPermits = new list<MUSW__Permit2__c>();
        
        lstLicense = [Select Id, MUSW__Applicant__c, Name, MUSW__Expiration_Date__c, Credential__c, 
                      MUSW__Status__c, MUSW__Issue_Date__c  
                      From MUSW__License2__c 
                      Where MUSW__Applicant__c =: record.Id 
                      ORDER BY Credential_Type__c DESC NULLS LAST, MUSW__Status__c ASC];  
        
        for(MUSW__Permit2__c permit : [Select Id, MUSW__Applicant__c, Name, Application_Type__c, 
                                       MUSW__Expiration_Date__c, Permit_Type__c, MUSW__Status__c, MUSW__Issue_Date__c 
                                       From MUSW__Permit2__c 
                                       where MUSW__Applicant__c =: record.Id 
                                       ORDER BY MUSW__Expiration_Date__c DESC NULLS FIRST, Permit_Type__c DESC NULLS LAST, MUSW__Status__c ASC
                      				   LIMIT 100]){
            if(permit.Application_Type__c == Label.Str_Permit_to_Operate || permit.Application_Type__c == 'Manufactured Homes Communities'){
                lstPermits.add(permit);
            }else if(permit.Application_Type__c == Label.Str_Plan_Review){
                lstPlanReviews.add(permit);
            }
        } 
    }       
}