src/objects/Customer_Envelope__c.object
<CustomObject>
    <description>This object is to store the record of  application with its check number for the validation purpose.</description>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>draft</fullName>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>pending</fullName>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>processed</fullName>
                    <label>Processed</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Submissions Attached</fullName>
                </value>
                
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_number__c</fullName>
        <displayFormat>BPD-{000000000}</displayFormat>
        <label>Validation Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Customer Envelope</label>
    <nameField>
        <displayFormat>CENV{YY}-{0000}</displayFormat>
        <label>Customer Envelope Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LnP_Licence_Application__c.object
<CustomObject>
    <description>To store Application JSON</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>License Application</relationshipLabel>
        <relationshipName>License_Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Licence Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_type__c</fullName>
        <label>Document type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Application</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Comity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fine_Number__c</fullName>
        <label>Fine Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_number__c</fullName>
        <label>Form number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>wadol_Program_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Form Unknown</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>AR-636-002</fullName>
                </value>
                <value>
                    <fullName>AR-636-003</fullName>
                </value>
                <value>
                    <fullName>AR-636-004</fullName>
                </value>
                <value>
                    <fullName>AR-636-021</fullName>
                </value>
                <value>
                    <fullName>CEM-650-004</fullName>
                </value>
                <value>
                    <fullName>CEM-650-005</fullName>
                </value>
                <value>
                    <fullName>CEM-650-007</fullName>
                </value>
                <value>
                    <fullName>CEM-650-008</fullName>
                </value>
                <value>
                    <fullName>CEM-650-009</fullName>
                </value>
                <value>
                    <fullName>CEM-650-010</fullName>
                </value>
                <value>
                    <fullName>CEM-650-011</fullName>
                </value>
                <value>
                    <fullName>CEM-650-013</fullName>
                </value>
                <value>
                    <fullName>CEM-650-016</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-014</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-015</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-016</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-017</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-018</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-019</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-020</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-021</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-022</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-023</fullName>
                </value>
                <value>
                    <fullName>ENLS-651-031</fullName>
                </value>
                <value>
                    <fullName>FDE-653-002</fullName>
                </value>
                <value>
                    <fullName>FDE-653-004</fullName>
                </value>
                <value>
                    <fullName>FDE-653-006</fullName>
                </value>
                <value>
                    <fullName>FDE-653-018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Application</label>
        <referenceTo>LnP_Licence_Application__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_type__c</fullName>
        <label>License type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>wadol_Program_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account that is associated with the deposit.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Professional_code__c</fullName>
        <label>Professional code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>pending</fullName>
                    <default>true</default>
                    <label>pending</label>
                </value>
                <value>
                    <fullName>completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Validation_number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation number</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>wadol_Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MUSW__Deposit__c.object
    <fields>
        <fullName>Route_to_Miscellaneous_queue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Route to Miscellaneous queue</label>
        <type>Checkbox</type>
    </fields>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
	<fields>
        <fullName>Validation_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Validation Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Customer_Envelope__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Envelope</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>License_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Application</label>
        <referenceTo>MUSW_Application2__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/LnP_CustomerEnvelopeDetailPageCtrl.cls
public class LnP_CustomerEnvelopeDetailPageCtrl {
    @AuraEnabled
    public static List<MUSW__Deposit__c> fetchDeposits(String recordId){
        List<MUSW__Deposit__c> depositList = new List<MUSW__Deposit__c>();
       // List<MUSW__Deposit__c> depositListToBeUpdated = new List<MUSW__Deposit__c>();
       // Set<Id> licenseIds = new Set<Id>();
        if(recordId != null){
            depositList = [Select Id,name,Form_number__c,Date__c,Amount__c,Document_type__c,wadol_Program_Type__c,Professional_code__c,License_type__c,Contact__c,MUSW__Account__c,License__c,License__r.Name,Fine_Number__c,Route_to_Miscellaneous_queue__c from MUSW__Deposit__c where Validation_number__c =: recordId];
        }
        
        return depositList;
    }
    
    @AuraEnabled
    public static void submitDeposits(String recordId){
        List<MUSW__Deposit__c> depositListToUpdate = new List<MUSW__Deposit__c>();
        Map<Id,MUSW__Deposit__c> depositRecordsMap ;
        List<LnP_Licence_Application__c> licenseApplicationsToBeCreated = new List<LnP_Licence_Application__c>();
        
        if(recordId != null){
            depositRecordsMap = new Map<Id,MUSW__Deposit__c>([Select Id,name,Status__c,Date__c,Amount__c,Document_type__c,wadol_Program_Type__c,Professional_code__c,License_type__c,Contact__c,MUSW__Account__c,License__c,License_Application__c,Fine_Number__c,Route_to_Miscellaneous_queue__c from MUSW__Deposit__c where Validation_number__c =: recordId]);
            for(MUSW__Deposit__c dep: depositRecordsMap.values()){
                if(dep.wadol_Program_Type__c != null && (dep.Contact__c != null || dep.MUSW__Account__c != null)){
                    dep.Status__c = 'completed';
                    depositListToUpdate.add(dep);
                }
            }
            
            if(depositListToUpdate.size() >0){
                update depositListToUpdate;
            }
            
            if(depositListToUpdate.size() == depositRecordsMap.values().size()){
                Customer_Envelope__c custEnv = new Customer_Envelope__c(Id=recordId);
            	custEnv.status__c = 'processed';
            	update custEnv;
            }
        }
    }
    
    @AuraEnabled
    public static List<ListView> getObjViews() {
        List<ListView> listviews = 
            [SELECT Id, Name FROM ListView WHERE SobjectType = 'Customer_Envelope__c'];
        
        return listviews;
    }
}