src/objects/de_HomeFooterUrlList__mdt.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>de_HomeFooterUrlList</label>
    <pluralLabel>de_HomeFooterUrlLists</pluralLabel>
</CustomObject>

src/classes/LnP_HomeThemeFooterApexControllerTest.cls
@isTest
public class LnP_HomeThemeFooterApexControllerTest {

    public static testMethod void testMethod1(){
        
        test.startTest();
        List<de_HomeFooterUrlList__mdt> records =[select Label,URL__c from de_HomeFooterUrlList__mdt];
        LnP_HomeThemeFooterApexController.getUrlMap();
        LnP_HomeThemeFooterApexController.getFooterCustomLabels();
        test.stopTest();
    }
}