src/objects/Dol_Batch_Monitor__c.object
<CustomObject>
    <description>Monitor those batches invoked by MuleSoft</description>
    <fields>
        <fullName>Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Batch Monitor</label>
    <nameField>
        <label>BatchId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Monitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dol_Batch_Monitor_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Batch__c</fullName>
        <label>Parent Batch</label>
        <referenceTo>Dol_Batch_Monitor__c</referenceTo>
        <relationshipLabel>Batch Monitor Details</relationshipLabel>
        <relationshipName>Batch_Monitor_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Monitor Detail</label>
    <nameField>
        <displayFormat>Child-{0000}</displayFormat>
        <label>Batch Monitor Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Monitor Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dol_Integration_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Settings</label>
    <pluralLabel>Integration Settings</pluralLabel>
</CustomObject>

src/classes/Dol_Batch_UpdtErrorPostElpasedTime_Test.cls
@isTest(SeeAllData=false)
private class Dol_Batch_UpdtErrorPostElpasedTime_Test {
    
    @isTest static void test_method_one() {
        List<Dol_Integration_Settings__mdt> elapsedSettings = [SELECT MasterLabel, DeveloperName, Value__c  FROM Dol_Integration_Settings__mdt Limit 1];

        Dol_Batch_Monitor__c batchMonitor = new Dol_Batch_Monitor__c();
        batchMonitor.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'INT-004.01';
        batchMonitor.Batch_Name__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Send Life to Death file to Governors Office(OFM)';
        insert batchMonitor;

        Dol_Batch_Monitor_Detail__c batchChild = new Dol_Batch_Monitor_Detail__c();
        batchChild.Parent_Batch__c = batchMonitor.id;
        batchChild.Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Running' ;
        batchChild.Start_Time__c = System.today().addDays(-1);
        insert  batchChild;
        test.startTest();
            Dol_Batch_UpdtErrorPostElpasedTime batchObj = new Dol_Batch_UpdtErrorPostElpasedTime();
            id batchJob = database.executeBatch(batchObj);
        test.stopTest();

    }
}