src/objects/Dol_Batch_Monitor__c.object
<CustomObject>
    <description>Monitor those batches invoked by MuleSoft</description>
    <fields>
        <fullName>Batch_Name__c</fullName>
        <label>Batch Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Batch Monitor</label>
    <nameField>
        <label>BatchId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Monitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dol_Batch_Monitor_Detail__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Error_Details__c</fullName>
        <label>Error Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Batch__c</fullName>
        <label>Parent Batch</label>
        <referenceTo>Dol_Batch_Monitor__c</referenceTo>
        <relationshipLabel>Batch Monitor Details</relationshipLabel>
        <relationshipName>Batch_Monitor_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Running</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Drop_Location__c</fullName>
        <label>Target Drop Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <label>Total Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Monitor Detail</label>
    <nameField>
        <displayFormat>Child-{0000}</displayFormat>
        <label>Batch Monitor Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Monitor Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dol_BatchMonitoring.cls
@RestResource(urlMapping='/Dol_BatchMonitoring/*')
global class Dol_BatchMonitoring{
    @HttpPost
    global static Dol_BatchMonitoringResponse doPost(Dol_BatchMonitoringRequest inputRequest){
        Dol_BatchMonitoringResponse outputResponse = new Dol_BatchMonitoringResponse();
        if(inputRequest!=null && inputRequest.method.equalsIgnoreCase('start')){
            String childID = createBatchRequest(inputRequest.batchId);
            if(Dol_IntegrationUtil.isNotBlank(childID)){
                outputResponse.status = DOL_AppConstants.SUCCESS_STRING_LOWERCASE;
                outputResponse.childRecoRdId = childID;
            }else {
                outputResponse.status = DOL_AppConstants.FAILED_STRING_LOWERCASE;
            }
        }else if(inputRequest!=null && inputRequest.method.equalsIgnoreCase('update')){
             if(updateBatchRequest(inputRequest.childRecoRdId,inputRequest.recordCount,inputRequest.error,inputRequest.status,inputRequest.targetDropLocation)){
                 outputResponse.status = DOL_AppConstants.SUCCESS_STRING_LOWERCASE;
             }else{
                 outputResponse.status = DOL_AppConstants.FAILED_STRING_LOWERCASE;
             }
        }
        return outputResponse;
    }

    global static String createBatchRequest(String batchId){
        System.debug('starting***');
        String childRecordId;
        List<Dol_Batch_Monitor__c> batchList;
        String childRecId=null;
        String response;

        try{
            if(batchId != null && batchId != ''){
            batchList = [Select id,Name,Batch_Name__c from Dol_Batch_Monitor__c where Name =: batchId  AND Name != null Limit 1];
                if(Dol_IntegrationUtil.isNotEmpty(batchList)){
                    Dol_Batch_Monitor_Detail__c childrecord = new Dol_Batch_Monitor_Detail__c();
                    childrecord.Start_Time__c = system.now();
                    childrecord.Parent_Batch__c = batchList[0].id;
                    childrecord.Status__c = DOL_AppConstants.RUNNING_STRING_SENTANCECASE;
                    upsert childrecord; 
                    childRecId = childrecord.id; 
                }
            }
        }catch (Exception e){
            System.debug('exception occoured'+e.getMessage()+e.getStackTraceString());
            DebugErrorLoggger.LogError(e, '', '','Dol_BatchMonitoring','createBatchRequest','Create Method failed');
        }
        
        return childRecId;
    }

    global static boolean updateBatchRequest(String childRecordId, String recordCount, String error, String status, String targetDropLocation){
        Dol_Batch_Monitor_Detail__c childRec;
        try{
            childRec = [Select id,Start_Time__c,End_Time__c,Error_Details__c,Parent_Batch__c,Status__c,Total_Records__c FROM Dol_Batch_Monitor_Detail__c WHERE ID=:childRecordId LIMIT 1];
            if(childRec != null){
                childRec.End_Time__c = System.now();
                childRec.Total_Records__c = recordCount != null ? integer.valueof(recordCount) :0;
                childRec.Error_Details__c = error != null ? error : '';
                childRec.Status__c = status != null ? status : '';
                childRec.Target_Drop_Location__c = targetDropLocation !=null ? targetDropLocation : '';
            }
            upsert childRec;
            return true;
        }catch (Exception e){
            System.debug('exception occoured'+e.getMessage()+e.getStackTraceString());
            DebugErrorLoggger.LogError(e, '', '','Dol_BatchMonitoring','updateBatchRequest','Update Method failed');
            return false;
        }
    }

    global class Dol_BatchMonitoringRequest {
        public String method{get;set;}
        public String batchId{get;set;}
        public String childRecoRdId{get;set;}
        public String status{get;set;}
        public String error{get;set;}
        public String recordCount{get;set;}
        public String targetDropLocation{get;set;}
    }

    global class Dol_BatchMonitoringResponse{
        public String status{get;set;}
        public String childRecoRdId{get;set;}
    }

}