src/objects/Education_History__c.object
<CustomObject>
    <description>This is an object used to store the education history of the user.</description>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Education History</relationshipLabel>
        <relationshipName>Education_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is the start date at the insitution</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>State_Provinces</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Results Pending</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EDUH-{000000}</displayFormat>
        <label>Education History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education History</pluralLabel>
    <recordTypes>
        <fullName>Education</fullName>
        <active>true</active>
        <label>Education</label>
    </recordTypes>
    <recordTypes>
        <fullName>Exam</fullName>
        <active>true</active>
        <label>Exam</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LnP_BackgroundSection__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>LnP_BackgroundSections</relationshipLabel>
        <relationshipName>LnP_BackgroundSections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>State_Provinces</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>LnP_BackgroundSection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>LnP_BackgroundSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LnP_BackgroundSections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <customValue>
        <fullName>Reschedule Exam</fullName>
    </customValue>
    <customValue>
        <fullName>CE Audit</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/State_Provinces.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Guam</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <description>List of US States and Provinces</description>
    <masterLabel>State Provinces</masterLabel>
</GlobalValueSet>

src/globalValueSets/Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Application</fullName>
    </customValue>
    <customValue>
        <fullName>Approve</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Deny</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Confirmation</fullName>
    </customValue>
    <customValue>
        <fullName>Exam Result</fullName>
    </customValue>
    <customValue>
        <fullName>Expired</fullName>
    </customValue>
    <customValue>
        <fullName>Final Close</fullName>
    </customValue>
    <customValue>
        <fullName>Late Renewal Application Sent</fullName>
    </customValue>
    <customValue>
        <fullName>Late Renewal Approved</fullName>
    </customValue>
    <customValue>
        <fullName>New Credential/Old One Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Print Wall Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Renewed</fullName>
    </customValue>
    <customValue>
        <fullName>Rescinded</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawal</fullName>
    </customValue>
    <description>Application Status</description>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

src/classes/LnP_SaveBackgroundDetails_Test.cls
@isTest
public class LnP_SaveBackgroundDetails_Test {
    
    public static testmethod void LnP_SaveBackgroundDetailsConstructor(){
        List<SObject> Iid = new List<SObject>();
        List<SObject> Iid1 = new List<SObject>();
        MUSW__Application2__c testApp=TestUtility.getApp();
        insert testApp;
        LnP_BackgroundSection__c testdel = new LnP_BackgroundSection__c();
        //testdel.RecordTypeId= DOL_AppConstants.NULL_EMPTY_STRING + '012r00000007LasAAE';
        testdel.RecordTypeId = Schema.SObjectType.LnP_BackgroundSection__c.getRecordTypeInfosByName().get('Qualifying Education').getRecordTypeId(); 
        testdel.Name= DOL_AppConstants.NULL_EMPTY_STRING + 'testName';
      //  testdel.Start_Date__c=System.today();
        insert testdel;
        String  ObjectName= DOL_AppConstants.NULL_EMPTY_STRING + 'LnP_BackgroundSection__c';
        String applicationId=testApp.Id;
        String recordTypeID= DOL_AppConstants.NULL_EMPTY_STRING + '012r00000007LasAAE';
        String flowType = 'CE Audit';
        String flowType1 = 'General Application';
        Request__c reqObj = new Request__c();
        reqObj.Service_Request_Type__c = 'Reschedule Exam';
        reqObj.Status__c = 'Approved';
        insert reqObj;
        Education_History__c eduHObj = new Education_History__c();
        eduHObj.State__c = 'California';
        eduHObj.Request__c = reqObj.Id;
        insert eduHObj;
        Test.startTest();
        try{
        Iid= LnP_SaveBackgroundDetails.returnIds(ObjectName,applicationId,recordTypeID,flowType);
        Iid= LnP_SaveBackgroundDetails.returnIds(ObjectName,applicationId,recordTypeID,flowType1);
        }
        catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e);
          //  System.debug('Error Occured');
        }
        try{
        String response = LnP_SaveBackgroundDetails.updateEducationHistoryRecord(eduHObj.Id,reqObj.Id);}
        catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e);
            //System.debug('Error Occured');
        }
        try{LnP_SaveBackgroundDetails.deleteTableRecord(testdel.Id);}
         catch(Exception e){
            DOL_CreateErrorLog_Exception.logApplicationError(e);
            //System.debug('Error Occured');
        }
      //  system.assert(Iid.size() > 0 );
        Test.stopTest();
    }
}