src/objects/Electronic_Notary_Provider_Information__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Endorsement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Endorsement</label>
        <referenceTo>Endorsement__c</referenceTo>
        <relationshipLabel>Electronic Notary Provider Information</relationshipLabel>
        <relationshipName>Electronic_Notary_Provider_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name__c</fullName>
        <label>Provider Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Docusign</fullName>
                </value>
                <value>
                    <fullName>DocVerify</fullName>
                </value>
                <value>
                    <fullName>Pavaso</fullName>
                </value>
                <value>
                    <fullName>Simplifile</fullName>
                </value>
                <value>
                    <fullName>World Wide Notary</fullName>
                </value>
                <value>
                    <fullName>CSC E-recording</fullName>
                </value>
                <value>
                    <fullName>GNUPG (proprietary or in-house software)</fullName>
                </value>
                <value>
                    <fullName>Collier Technologies LLC (Orcas Island ISP)</fullName>
                </value>
                <value>
                    <fullName>Rush</fullName>
                </value>
                <value>
                    <fullName>Translate</fullName>
                </value>
                <value>
                    <fullName>SnapDocs</fullName>
                </value>
                <value>
                    <fullName>Settleware</fullName>
                </value>
                <value>
                    <fullName>Oracle Textura Management</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Electronic Notary Provider Information</label>
    <nameField>
        <displayFormat>Provider-{0000000}</displayFormat>
        <label>Electronic Notary Provider Information N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Notary Provider Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Endorsement__c.object
<CustomObject>
    <description>To store specialties / endorsements of a license (individual / business)</description>
    <fields>
        <fullName>Date_Requested_for_Adding_Endorsement__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Endorsement_Type__c</fullName>
        <label>Endorsement Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Agricultural &amp; Biological</fullName>
                </value>
                <value>
                    <fullName>Both Engineering Geologist and Hydrogeologist</fullName>
                </value>
                <value>
                    <fullName>Building Systems</fullName>
                </value>
                <value>
                    <fullName>Cemetery Pre-arrangement Sales</fullName>
                </value>
                <value>
                    <fullName>Cemetery Pre-arrangement Sales Exemption</fullName>
                </value>
                <value>
                    <fullName>Chemical</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Control Systems</fullName>
                </value>
                <value>
                    <fullName>Crematory</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Electronic Notary</fullName>
                </value>
                <value>
                    <fullName>Electronic Records Notary Public Endorsement</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Engineering Geologist</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Fire Protection</fullName>
                </value>
                <value>
                    <fullName>Funeral Pre-arrangement Contract</fullName>
                </value>
                <value>
                    <fullName>Hydrogeologist</fullName>
                </value>
                <value>
                    <fullName>Industrial</fullName>
                </value>
                <value>
                    <fullName>Land Surveying</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Metallurgical and Materials</fullName>
                </value>
                <value>
                    <fullName>Mining and Mineral Processing</fullName>
                </value>
                <value>
                    <fullName>Naval Architect/Marine</fullName>
                </value>
                <value>
                    <fullName>Nuclear</fullName>
                </value>
                <value>
                    <fullName>Petroleum</fullName>
                </value>
                <value>
                    <fullName>Structural Engineer</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Endorsements</relationshipLabel>
        <relationshipName>Endorsements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Add</fullName>
                </value>
                <value>
                    <fullName>Not Qualified</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending Remove</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                    <default>true</default>
                    <label>In-Review</label>
                </value>
                <value>
                    <fullName>Renew</fullName>
                </value>
                <value>
                    <fullName>Remove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Endorsement</label>
    <nameField>
        <displayFormat>END-{0000000}</displayFormat>
        <label>Endorsement icon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/classes/Polaris_EndorsementRenewCntrl.cls
public class Polaris_EndorsementRenewCntrl {
    
    @AuraEnabled
    public static List<Endorsement__c> fetchEndorsement(String licId)
    {
        try{
        Id licenseId = [SELECT id,Application__c FROM MUSW__License2__c WHERE Application__c=: licId].Id;
        List<Endorsement__c> lstEndo = [SELECT id,Date_Requested_for_Adding_Endorsement__c,License_Type__c,Endorsement_Type__c,License__c,Status__c FROM Endorsement__c where (Status__c='Active' OR Status__c='In-Review' OR Status__c='Pending Add'OR Status__c='Renew' OR Status__c='Remove') AND License__c =:licenseId ];
        for(Endorsement__c endo : [SELECT id,Date_Requested_for_Adding_Endorsement__c,License_Type__c,Endorsement_Type__c,License__c,Status__c FROM Endorsement__c where (Status__c='Active' OR Status__c='In-Review' OR Status__c='Pending Add'OR Status__c='Renew' OR Status__c='Remove') AND License__c =:licenseId ])
        {
            //endo.Status__c = 'Renew';
        }
       // update lstEndo;
        return lstEndo;
        }catch(Exception ex)
        {
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            throw new AuraHandledException('An error occurred: '+ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Electronic_Notary_Provider_Information__c> fetchProvider(String endoId)
    {
        try{
        return [SELECT id,Description__c,Effective_Date__c,Provider_Name__c FROM Electronic_Notary_Provider_Information__c where Endorsement__c =:endoId ];
        }catch(Exception ex)
        {
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            throw new AuraHandledException('An error occurred: '+ex.getMessage());
        }
            
    }
    
    @AuraEnabled
    public static Void removeProvider(String providerId)
    {
       try{
       Electronic_Notary_Provider_Information__c prov = [SELECT id,Description__c,Effective_Date__c,Provider_Name__c FROM Electronic_Notary_Provider_Information__c where Id =:providerId ];
    	delete prov;
       }catch(Exception ex)
        {
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            throw new AuraHandledException('An error occurred: '+ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Endorsement__c> changeStatus(String endoId,String Status,String licId)
    {        
        try{
        Endorsement__c endo = [SELECT id,Date_Requested_for_Adding_Endorsement__c,Endorsement_Type__c,License__c,Status__c FROM Endorsement__c where  Id =:endoId ];
        endo.Status__c = Status;        
        update endo;
        return fetchEndorsement(licId);
        }catch(Exception ex)
        {
            DOL_CreateErrorLog_Exception.logApplicationError(ex);
            throw new AuraHandledException('An error occurred: '+ex.getMessage());
        }
    }
    
}