src/objects/Electronic_Notary_Provider_Information__c.object
<CustomObject>
    <fields>
        <fullName>Endorsement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Endorsement</label>
        <referenceTo>Endorsement__c</referenceTo>
        <relationshipLabel>Electronic Notary Provider Information</relationshipLabel>
        <relationshipName>Electronic_Notary_Provider_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Electronic Notary Provider Information</label>
    <nameField>
        <displayFormat>Provider-{0000000}</displayFormat>
        <label>Electronic Notary Provider Information N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Electronic Notary Provider Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Endorsement__c.object
<CustomObject>
    <description>To store specialties / endorsements of a license (individual / business)</description>
    <label>Endorsement</label>
    <nameField>
        <displayFormat>END-{0000000}</displayFormat>
        <label>Endorsement icon Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endorsements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Registration</fullName>
        <active>true</active>
        <label>Registration</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Polaris_EndorsementRenewCntrl_Test.cls
@isTest
public class Polaris_EndorsementRenewCntrl_Test {
    
    
    @isTest
    public static void test_fetchEndorsement1(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        try{
            Polaris_EndorsementRenewCntrl.fetchEndorsement(app.Id);
        }catch(Exception ex){
            
        }
    }
    
    @isTest
    public static void test_fetchEndorsement2(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application__c = app.id;
        update lic1;
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        try{
            Polaris_EndorsementRenewCntrl.fetchEndorsement(app.Id);
        }catch(Exception ex){
            
        }
    }
    
    @isTest
    public static void test_fetchProvider1(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application__c = app.id;
        update lic1;
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        Electronic_Notary_Provider_Information__c enpi = DOL_TestDataFactory.createElectronicProviderInfo(endo.Id);
        try{
            Polaris_EndorsementRenewCntrl.fetchProvider(endo.Id);
        }catch(Exception ex){}
    }
    
      
    @isTest
    public static void test_removeProvider1(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application__c = app.id;
        update lic1;
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        Electronic_Notary_Provider_Information__c enpi = DOL_TestDataFactory.createElectronicProviderInfo(endo.Id);
        try{
            Polaris_EndorsementRenewCntrl.removeProvider(enpi.Id);
        }catch(Exception ex){}
    }
    
    @isTest
    public static void test_removeProvider2(){
        try{
            Polaris_EndorsementRenewCntrl.removeProvider('Docusign');
        }catch(Exception ex){}
    }
    
    @isTest
    public static void test_changeStatus1(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        try{
            Polaris_EndorsementRenewCntrl.changeStatus(endo.Id, 'In-Review', app.Id);
        }catch(exception ex){}
    }
    
    @isTest
    public static void test_changeStatus2(){
        Id appRecId = Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Registration').getRecordTypeId();
        MUSW__Application2__c app = DOL_TestDataFactory.createApplication(appRecId);
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account a = DOL_TestDataFactory.createAccount(AccRecTypeId);
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c lic1 = DOL_TestDataFactory.createLicense(LicRecTypeId1, a.Id, 'Architects', 'Architect', 'General Application');
        lic1.Application__c = app.id;
        update lic1;
        Endorsement__c endo = DOL_TestDataFactory.createEndorsement(lic1.Id, 'Active');
        try{
            Polaris_EndorsementRenewCntrl.changeStatus(endo.Id, 'In-Review', app.Id);
        }catch(exception ex){}
    }
}