src/objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <formula>Exam_Schedule__r.Exam_Date__c</formula>
        <label>Exam Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam_Location__c</fullName>
        <formula>Exam_Schedule__r.Exam_Location__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Exam Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exam_Schedule__c</fullName>
        <inlineHelpText>Date that exam is scheduled</inlineHelpText>
        <label>Exam Schedule</label>
        <referenceTo>Exam_Schedule__c</referenceTo>
        <relationshipLabel>Exams</relationshipLabel>
        <relationshipName>Exams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam_Type__c</fullName>
        <label>Exam Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UDC Construction Inspector Exam</fullName>
                </value>
                <value>
                    <fullName>UDC Electrical Inspector Exam</fullName>
                </value>
                <value>
                    <fullName>UDC HVAC Inspector Exam</fullName>
                </value>
                <value>
                    <fullName>UDC Plumbing Inspector Exam</fullName>
                </value>
                <value>
                    <fullName>Soil Tester Part 1</fullName>
                </value>
                <value>
                    <fullName>Soil Tester Part 2</fullName>
                </value>
                <value>
                    <fullName>Soil Tester Exam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Exam</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Exam_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Exam</label>
    <nameField>
        <displayFormat>EX-{YY}{MM}{0000}</displayFormat>
        <label>Exam Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Exam_Schedule__c.object
<CustomObject>
    <description>Shows an available time and place for an exam and maximum capacity.</description>
    <fields>
        <fullName>Exam_Date__c</fullName>
        <inlineHelpText>Date that the exam is offered</inlineHelpText>
        <label>Exam Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exam_Location__c</fullName>
        <inlineHelpText>Location of Exam</inlineHelpText>
        <label>Exam Location</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Capacity__c</fullName>
        <inlineHelpText>Maximum number of attendees for an exam</inlineHelpText>
        <label>Maximum Capacity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_of_Exam__c</fullName>
        <inlineHelpText>Time that the Exam is being offered</inlineHelpText>
        <label>Time of Exam</label>
        <type>Time</type>
    </fields>
    <label>Exam Schedule</label>
    <nameField>
        <label>Exam Schedule</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Exam_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <customValue>
        <fullName>Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>No Show</fullName>
    </customValue>
    <customValue>
        <fullName>Ungraded</fullName>
    </customValue>
    <customValue>
        <fullName>Waived</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
        <isActive>false</isActive>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>No Grade</fullName>
        <isActive>false</isActive>
        <label>No Grade</label>
    </customValue>
    <customValue>
        <fullName>Passed</fullName>
        <isActive>false</isActive>
        <label>Passed</label>
    </customValue>
    <description>Holds status of a current exam</description>
    <masterLabel>Exam Status</masterLabel>
</GlobalValueSet>

src/classes/DRE2_Exam_Custom_Test.cls
/**
* User Story:  
* Name: DRE2_Exam_Custom_Test
* Type: Test Class
* Description: Class to create Test Data and test the execution of AutoCloseAbandonedPTOTitlePRBatch
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 10/22/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/
@isTest
public class DRE2_Exam_Custom_Test {
    
    @isTest
    public static void AutoCloseAbandonedCredentialBatchTest1() {
       Exam_Schedule__c examScheduleRecord = new Exam_Schedule__c(Name = 'Test Schedule',
                                        Exam_Date__c=System.today(),
                                        Time_of_Exam__c = Time.newInstance(0, 2, 2, 0),
                                        Exam_Location__c = 'Anywhere',
                                        Maximum_Capacity__c = 10);
        insert examScheduleRecord;
        
        
        Exam__c examRecord = new Exam__c(Exam_Type__c = 'Soil Tester Exam',
                                        Status__c='New',
                                        Exam_Schedule__c = examScheduleRecord.Id);
        insert examRecord;
    }

}