src/objects/FeeTable__c.object
<CustomObject>
    <description>List of All Fees across Boards</description>
    <fields>
        <fullName>Account_Code__c</fullName>
        <description>Account Code</description>
        <label>Account Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Account Number</description>
        <label>Account Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Add_Additional_Fee__c</fullName>
        <description>If configured, additional Transaction Fee will be attached to the Parent fee</description>
        <label>Add Additional Fee</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FEE-OIT-TRANS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Fee Amount</description>
        <label>Amount</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Board__c</fullName>
        <description>Board</description>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Architects Board</fullName>
                </value>
                <value>
                    <fullName>Accountancy Board</fullName>
                </value>
                <value>
                    <fullName>Board of Embalmers and Funeral Directors</fullName>
                </value>
                <value>
                    <fullName>Engineers and Surveyors Board</fullName>
                </value>
                <value>
                    <fullName>Board of Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Casino Control Commission</fullName>
                </value>
                <value>
                    <fullName>Chemical Dependency Professionals Board</fullName>
                </value>
                <value>
                    <fullName>Chiropractic Board</fullName>
                </value>
                <value>
                    <fullName>Cosmetology and Barber Board</fullName>
                </value>
                <value>
                    <fullName>Counselor, Social Worker &amp; MFT Board</fullName>
                </value>
                <value>
                    <fullName>Dental Board</fullName>
                </value>
                <value>
                    <fullName>Dept of Commerce Manufactured Homes</fullName>
                </value>
                <value>
                    <fullName>Medical Board</fullName>
                </value>
                <value>
                    <fullName>Motor Vehicle Repair Board</fullName>
                </value>
                <value>
                    <fullName>Nursing Board</fullName>
                </value>
                <value>
                    <fullName>Vision Professionals Board</fullName>
                </value>
                <value>
                    <fullName>OTPTAT Board</fullName>
                </value>
                <value>
                    <fullName>Psychology Board</fullName>
                </value>
                <value>
                    <fullName>ODH Sanitarian Registration</fullName>
                </value>
                <value>
                    <fullName>Speech and Hearing Professionals Board</fullName>
                </value>
                <value>
                    <fullName>Veterinary Medical Board</fullName>
                </value>
                <value>
                    <fullName>Sanitarian Board</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>Fee Expiry Date</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fee_Type__c</fullName>
        <description>Fee Name on the Cart</description>
        <label>Fee Name on the Cart</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Status_Field_API_Name__c</fullName>
        <description>Parent Status Field API Name</description>
        <label>Parent Status Field API Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <description>Rules Name referenced from Rules Engine to generate Fees</description>
        <label>Rule Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_value_Before_Fee_Generation__c</fullName>
        <description>Status value Before Fee Generation</description>
        <label>Status value Before Fee Generation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Fee Table</label>
    <nameField>
        <label>Fee Table ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Table</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RulesEngineFeeHandlerTest.cls
@isTest
public class RulesEngineFeeHandlerTest {
    public static testmethod void testcheckTransactionFeeMethod(){
		Test.startTest();        
            FeeTable__c feeTable = new FeeTable__c();
            feeTable.Name = 'testFee';
            feeTable.Account_Code__c = '13568';
            feeTable.Account_Number__c ='87644';
            feeTable.Add_Additional_Fee__c = 'FEE-OIT-TRANS';
            feeTable.Amount__c = 1000.0;
            feeTable.Board__c = 'Medical Board';
            feeTable.Fee_type__c = 'FeeType';
            feeTable.Rule_Name__c = 'TestRule';
            feeTable.Expiry_Date__c = System.today()+5;
            feeTable.Parent_Status_Field_API_Name__c= 'test';
            feeTable.Status_value_Before_Fee_Generation__c = 'test';
            insert feeTable;
            RulesEngineFeeHandler.getAll(); 
        Test.stopTest();
        
    }
}