src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting is used to define application settings that can be overridden for specific users or profiles. E.g. Disable Triggers</description>
    <label>Global Settings</label>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <fields>
        <fullName>International_Address__c</fullName>
        <description>Enter the international address using this field.</description>
        <inlineHelpText>Enter the international address</inlineHelpText>
        <label>International Address</label>
        <type>TextArea</type>
    </fields>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ParcelTriggerHandler_Test.cls
@isTest
public class ParcelTriggerHandler_Test {
    
    @isTest
    public static void testonBeforeDelete(){
        ParcelTriggerHandler parcelTriggerHandler = new ParcelTriggerHandler();
        parcelTriggerHandler.onBeforeDelete();
    }
    
    @isTest
    public static void testonBeforeUndelete(){
        ParcelTriggerHandler parcelTriggerHandler = new ParcelTriggerHandler();
        parcelTriggerHandler.onBeforeUndelete();
    }
    
    @isTest
    public static void testonAfterDelete(){
        ParcelTriggerHandler parcelTriggerHandler = new ParcelTriggerHandler();
        parcelTriggerHandler.onAfterDelete();
    }
    
    @isTest
    public static void testonAfterUndelete(){
        ParcelTriggerHandler parcelTriggerHandler = new ParcelTriggerHandler();
        parcelTriggerHandler.onAfterUndelete();
    }
    
    @isTest
    public static void testBypassTrigger(){
        Id recTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByName().get('Address').getRecordTypeId();
        Global_Settings__c globalSetting = DOL_TestDataFactory.createGlobalSetting(UserInfo.getUsername(),true);
        ParcelTriggerHandler parcelTriggerHandler = new ParcelTriggerHandler();
        MUSW__Parcel__c par = DOL_TestDataFactory.createParcel(recTypeId);
    }
    
    @isTest
    public static void insertParcel(){
        Id recTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByName().get('Address').getRecordTypeId();
        MUSW__Parcel__c par = DOL_TestDataFactory.createParcel(recTypeId);
    }
    
    @isTest
    public static void updateParcel(){
        Id recTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByName().get('Address').getRecordTypeId();
        MUSW__Parcel__c par = DOL_TestDataFactory.createParcel(recTypeId);
        par.International_Address__c = DOL_AppConstants.NULL_EMPTY_STRING + '456 Street';
        update par;
    }
}