src/objects/Journal_Voucher__c.object
<CustomObject>
    <description>Used to capture header and footer information for the Journal Voucher .pdf and interface file.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Journal_Voucher_Detail__c.Amount__c</summarizedField>
        <summaryForeignKey>Journal_Voucher_Detail__c.JournalVoucher__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Document_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prepared_by_Date__c</fullName>
        <label>Prepared by Date</label>
        <type>Date</type>
    </fields>
    <label>Journal Voucher</label>
    <nameField>
        <displayFormat>JV-{0000}</displayFormat>
        <label>Journal Voucher  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journal_Voucher_Detail__c.object
<CustomObject>
    <description>Used to capture an aggregation of item records pulled onto the Journal Voucher .pdf and interface file</description>
    <fields>
        <fullName>Add_to_Interface__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to Interface</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Add_to_PDF__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add to PDF</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Debit_Credit__c</fullName>
        <label>Debit Credit</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fund__c</fullName>
        <label>Fund</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>General_Ledger_Account__c</fullName>
        <label>General Ledger Account</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JournalVoucher__c</fullName>
        <label>Journal Voucher</label>
        <referenceTo>Journal_Voucher__c</referenceTo>
        <relationshipLabel>Journal Voucher Details</relationshipLabel>
        <relationshipName>Journal_Voucher_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JournalVoucher__c</fullName>
        <label>Journal Voucher</label>
        <referenceTo>Journal_Voucher__c</referenceTo>
        <relationshipLabel>Journal Voucher Details</relationshipLabel>
        <relationshipName>Journal_Voucher_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Major_Group__c</fullName>
        <label>Major Group</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major_Source__c</fullName>
        <label>Major Source</label>
        <length>2</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>Program_Index__c</fullName>
        <label>Program Index</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Document_Suffix__c</fullName>
        <label>Reference Document Suffix</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reversal__c</fullName>
        <label>Reversal</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Source__c</fullName>
        <label>Sub Source</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidiary_Account_Credit__c</fullName>
        <label>Subsidiary Account Credit</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidiary_Account_Debit__c</fullName>
        <label>Subsidiary Account Debit</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Accounting_System__c</fullName>
        <label>Target Accounting System</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Code__c</fullName>
        <label>Transaction Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Journal Voucher Detail</label>
    <nameField>
        <displayFormat>JVD-{0000}</displayFormat>
        <label>Journal Voucher Detail  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Voucher Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/JVExtension.cls
public class JVExtension {
    
    public List<Journal_Voucher_Detail__c> jvd{get;set;} 
    
    public Journal_Voucher__c jv {get;set;} 
    public string documentDate {get;set;} 
    public string preparedByDate {get;set;} 
    public Decimal Amt {get;set;} 
    
    public JVExtension(ApexPages.StandardController controller) { 
        
            jv = (Journal_Voucher__c)controller.getRecord();  
            jv=[select Document_Date__c,createddate,Prepared_by_Date__c from Journal_Voucher__c where id =:jv.Id];
            if(jv.Document_Date__c != null){
            	documentDate = jv.Document_Date__c.format();
            }
            date createdDate = date.valueOf(jv.createddate);
            	preparedByDate =createdDate.format();
            
            jvd = [SELECT id,Add_to_Interface__c,Add_to_PDF__c, Agency__c, Amount__c,Debit_Credit__c,Fund__c,General_Ledger_Account__c,JournalVoucher__r.Amount__c,Major_Group__c,Major_Source__c,Program_Index__c,Reference_Document_Suffix__c,Reversal__c,Subsidiary_Account_Credit__c,Subsidiary_Account_Debit__c,Sub_Source__c,Target_Accounting_System__c,Transaction_Code__c FROM Journal_Voucher_Detail__c WHERE JournalVoucher__c = :jv.id and Add_to_PDF__c = true];     
             Amt=0;
            for(Journal_Voucher_Detail__c jvdrec:jvd){
                if(jvdrec.Amount__c != null)
              	Amt= Amt+jvdrec.Amount__c.abs();
            }
            
        
    }
}