src/objects/License_Verification__c.object
<CustomObject>
    <description>This is used to store license verification records.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>This is the status of the license.</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>License Verification</label>
    <nameField>
        <displayFormat>LVF-{000000}</displayFormat>
        <label>License Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Hide_Upload_button_in_backend__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Submission List Hide Upload button in backend</description>
        <label>Hide Upload button in backend</label>
        <type>Checkbox</type>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated submission record(s).</description>
        <label>Submission</label>
        <referenceTo>MUSW__Submission__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Available_to_public__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox field to indicate available to public or not</description>
        <label>Available to public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Hardcopy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hardcopy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Backend_Submission__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate whether it is backend submission or not</description>
        <label>Is Backend Submission</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to License Renewal/Renewal Application</description>
        <label>License Renewal</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review</label>
        <referenceTo>MUSW__Review__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Submission_DateTime__c</fullName>
        <label>Submission Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_For_Credential_Reinstatement__c</fullName>
        <description>Returns true if a submission is to be displayed for Credential Reinstatement</description>
        <formula>IF((ISBLANK(Master_Submission_List__c) &amp;&amp; NOT(ISNULL(License_Renewal__c)) &amp;&amp; TEXT(License_Renewal__r.Renewal_Reinstatement_Type__c) == &apos;Reinstatement&apos; ) || 
(INCLUDES( Master_Submission_List__r.Show_For__c ,&apos;Credential Reinstatement&apos;)),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show For Credential Reinstatement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_For_Credential_Renewal__c</fullName>
        <description>Returns true if a submission is to be displayed for Credential Renewal</description>
        <formula>IF((ISBLANK(Master_Submission_List__c) &amp;&amp;  NOT(ISNULL(License_Renewal__c)) &amp;&amp;  TEXT(License_Renewal__r.Renewal_Reinstatement_Type__c) == &apos;Renewal&apos; ) || 
(INCLUDES( Master_Submission_List__r.Show_For__c,&apos;Credential Renewal&apos;)),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show For Credential Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_For_Credential__c</fullName>
        <description>Returns true if a submission is to be displayed for Credential</description>
        <formula>IF(((ISBLANK(Master_Submission_List__c) &amp;&amp;  MUSW__License2__c != null) || 
INCLUDES( Master_Submission_List__r.Show_For__c,&apos;Credential&apos;)),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show For Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_For_Permit_Renewal__c</fullName>
        <formula>IF((ISBLANK(Master_Submission_List__c) &amp;&amp; NOT(ISNULL(License_Renewal__c)) &amp;&amp; TEXT(License_Renewal__r.Renewal_Reinstatement_Type__c) == &apos;RenewalPTO&apos; ) || 
(INCLUDES( Master_Submission_List__r.Show_For__c,&apos;Permit Renewal&apos;)),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show For Permit Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_For_Permit__c</fullName>
        <formula>IF(((ISBLANK(Master_Submission_List__c) &amp;&amp; MUSW__Permit2__c != null) || 
INCLUDES( Master_Submission_List__r.Show_For__c,&apos;Permit&apos;)),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Show For Permit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status = Accepted when the document satisfies the submission requirement. Status = Additional Info. Required when the document does not satisfy the submission requirement and should be sent back to the Applicant.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Additional Info. Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/classes/BackendLicenseSubmission_CC.cls
/**
* User Story: 124- Submission List Triggers
* Name: BackendLicenseSubmission_CC
* Type: Custom Controller
* Description: Custom Controller for BackendLicenseSubmission component
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 06/28/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/
global class BackendLicenseSubmission_CC {

    public String pid{get;set;}
    public String permitpid{get;set;}
    public Boolean enableDoneButton{get;set;}
    private String retURL;
    public List<MUSW__Submission__c> submissionList;
    public Attachment file{ get;set;}
    public String subId{get;set;}
    public String hiddenSubId{get;set;}
    public MUSW__Submission__c newSubmission{get;set;}

    
    //Flags to decide which submissions need to be shown
    public Boolean isRenewal{get;set;}
    public Boolean isRenewalPTO{get;set;}
    public Boolean isSR{get;set;}
    public Boolean isReinstatement{get;set;}
    public Boolean isLicense{get;set; }  
    public Boolean isPermit{get;set; }  
    public Boolean isVerification{get;set;}
    public Boolean isReview{get;set;}
    public Boolean isComplaint{get;set;}
    public Boolean isExamCredit{get;set;}
    public Boolean isLicenseReinstatement{get;set;}
    
    /***************************************************************************************************
    * @Description : Method to redirect user back to the license record
    * @Param       : NA
    * @Return      : PageReference
    ****************************************************************************************************/
    public BackendLicenseSubmission_CC() {
        System.debug('in BackendLicenseSubmission_CC');
        newSubmission = new MUSW__Submission__c();
        file = new Attachment();
        submissionList = new List<MUSW__Submission__c >();
        enableDoneButton = getStatus(submissionList);
    }

    /***************************************************************************************************
    * @Description : Method to get submissions under a license
    * @Param       : NA
    * @Return      : NA
    ****************************************************************************************************/
    public List<MUSW__Submission__c> getsubmissionList() {
        System.debug('in getSubmissionList');
        submissionList = new List<MUSW__Submission__c>();
        System.debug('pid '+pid);
        System.debug('permitpid '+permitpid);
        System.debug('isRenewalPTO '+isRenewalPTO);
        System.debug('isRenewal '+isRenewal);
        System.debug('isReinstatement '+isReinstatement);
        System.debug('isLicense '+isLicense);
        System.debug('isPermit '+isPermit);
        if((pid != null && pid != '') || (permitpid != null && permitpid != '')){
            System.debug('isRenewal in back'+ isRenewal);
             if(isRenewal != null && isRenewal){
                 System.debug('isRenewal in if');
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE License_Renewal__c=:pid AND Show_For_Credential_Renewal__c=TRUE ORDER BY Name];
                 System.debug('isRenewal in if size of submissionList '+submissionList.size());
            }else if(isRenewalPTO != null && isRenewalPTO){
                 System.debug('isRenewalPTO in if');
                 submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE License_Renewal__c=:permitpid AND Show_For_Permit_Renewal__c=TRUE ORDER BY Name];
                 System.debug('isRenewalPTO in if size of submissionList '+submissionList.size());
            }else if(isReinstatement != null && isReinstatement){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE License_Renewal__c=:pid AND Show_for_Credential_Reinstatement__c=TRUE ORDER BY Name];
            }/*//Todo
             *else if(isSR != null && isSR){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE MUSW__Application2__c=:pid AND Show_For_Name_Change_SR__c=TRUE ORDER BY Name];
            }*/else if(isLicense != null && isLicense){
                System.debug('in license');
                
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE MUSW__License2__c=:pid AND Show_For_Credential__c=TRUE ORDER BY Name];
                System.debug('submissionList.size '+submissionList.size());
                System.debug('submissionList '+submissionList);
                
            }else if(isPermit != null && isPermit){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE MUSW__Permit2__c=:permitpid AND Show_For_Permit__c=TRUE ORDER BY Name];
            }/*else if(isLicenseReinstatement != null && isLicenseReinstatement){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE MUSW__License2__c=:pid AND Show_for_License__c=TRUE ORDER BY Name];
            }
            else if(isReview != null && isReview){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE MUSW__Review__c=:pid ORDER BY Name];
            }else if(isComplaint != null && isComplaint){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE Complaint__c=:pid ORDER BY Name];
            }
            else if(isExamCredit != null && isExamCredit){
                submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,is_Backend_Submission__c,Available_To_Public__c,MUSW__Link__c,MUSW__Submission_DateTime__c,Status__c,Master_Submission_List__r.Hide_Upload_button_in_backend__c,(Select Id,Name FROM Attachments ORDER BY Name) FROM MUSW__Submission__c WHERE CE_Exam_Credit__c=:pid ORDER BY Name];         
            }*/
        }
        enableDoneButton = getStatus(submissionList);
        return submissionList;
    }
    
    /***************************************************************************************************
    * @Description : Method to create attachment under submission
    * @Param       : NA
    * @Return      : PageReference
    ****************************************************************************************************/
    public PageReference uploadFile(){
        PageReference currentPage = Apexpages.CurrentPage();
        if(file.body != null){
            try{
                file.parentId = subId;
                if(file != null){
                    insert file;    
                }  
                MUSW__Submission__c submissionUpdate = new MUSW__Submission__c(Id=subId,MUSW__Submission_DateTime__c=System.now());
                if(submissionUpdate != null){
                    update submissionUpdate;    
                }
                //submissionList = [Select Id,Name,Hardcopy__c,Description_Long__c,Type__c,(Select Id,Name FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__License2__c=:pid];                     
            }catch(Exception ex){
                ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.ERROR,ex.getmessage()));
                return null;
            }finally{
                //Clearing file body to avoid serizling file body into view state
                file = new Attachment();
            }
        }
        return null;
    }

    /***************************************************************************************************
    * @Description : Method to create new submission
    * @Param       : NA
    * @Return      : PageReference
    ****************************************************************************************************/
    public PageReference createSubmission(){
        try{
            if(hiddenSubId != null && hiddenSubId !=''){
                newSubmission.Id = hiddenSubId;
            }
            if(isLicense!=null && isLicense)
            {
                newSubmission.MUSW__License2__c = pid;
            }else if(isPermit!=null && isPermit)
            {
                newSubmission.MUSW__Permit2__c = permitpid;
            }else if(isLicenseReinstatement!=null && isLicenseReinstatement)
            {
                newSubmission.MUSW__License2__c = pid;
            }            
            else if((isRenewal!=null && isRenewal))
            {
                newSubmission.License_Renewal__c = pid;
            }
            else if((isRenewalPTO!=null && isRenewalPTO))
            {
                System.debug('in createSubmission renewalPTO');
                newSubmission.License_Renewal__c = permitpid;
            }
            else if(isReinstatement!=null && isReinstatement)
            {
                newSubmission.License_Renewal__c = pid;
            }/*
            else if(isVerification!=null && isVerification)
            {
                newSubmission.License_Verification__c = pid;
            }
            else if(isReview!=null && isReview)
            {
                newSubmission.MUSW__Review__c = pid;
            }
            else if(isComplaint!=null && isComplaint)
            {
                newSubmission.Complaint__c = pid;
            }
            else if(isSR!=null && isSR)
            {
                newSubmission.MUSW__Application2__c = pid;
            }
            else if(isExamCredit!=null && isExamCredit)
            {
                newSubmission.CE_Exam_Credit__c = pid;
            }*/
            newSubmission.MUSW__Submission_DateTime__c=System.now();
            newSubmission.is_Backend_Submission__c = TRUE;
            if(newSubmission !=  null){
                upsert newSubmission;   
            }
            newSubmission = new MUSW__Submission__c();
            if(hiddenSubId != null && hiddenSubId !=''){
                ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.INFO,label.Str_Submission_is_updated_successfully));
            }else{
                ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.INFO,label.Str_New_submission_is_created_successfully));
            }
        }catch(Exception ex){
            ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.ERROR,ex.getmessage()));
            return null;
        }
        return null;
    }
    
    /***************************************************************************************************
    * @Description : Method to delete submission and refresh submissionList
    * @Param       : NA
    * @Return      : PageReference
    ****************************************************************************************************/
    public PageReference refreshSubmissions(){
        if(hiddenSubId != null){
            try{
                MUSW__Submission__c backendSubmission = new MUSW__Submission__c(Id=hiddenSubId);
                if(backendSubmission != null){
                    delete backendSubmission;   
                }
                
                ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.INFO,label.Str_Submission_is_deleted_successfully));
            }catch(Exception ex){
                ApexPages.Addmessage(new ApexPages.Message(Apexpages.SEVERITY.ERROR,label.Str_Error_in_deleting_submission));
            }
        }
        return null;
    }    
    
    /***************************************************************************************************
    * @Description : Method to get status of completion of necessary uploads
    * @Param       : List<MUSW__Submission__c>
    * @Return      : Boolean
    ****************************************************************************************************/
    public static Boolean getStatus(List<MUSW__Submission__c> subList){
        Boolean completionStatus = TRUE;
        for(MUSW__Submission__c submission: subList){
            if((submission.Attachments == NULL || submission.Attachments.isEmpty()) && submission.Hardcopy__c == FALSE){
                completionStatus = FALSE;
            }   
        }
        return completionStatus;
    }
    
    /***************************************************************************************************
    * @Description : JSRemoted method to get submission details for editing
    * @Param       : ID
    * @Return      : MUSW__Submission__c
    ****************************************************************************************************/
    @RemoteAction
    global static MUSW__Submission__c getSubmissionDetails(Id submissionId){
        try{
            MUSW__Submission__c submission = [select id,Description_Long__c,Name,MUSW__Link__c,Available_To_Public__c FROM MUSW__Submission__c WHERE ID=:submissionId];
            return submission;
        }catch(Exception ex){
            system.debug(ex.getMessage());
        }
        return null;
    }
    
    /***************************************************************************************************
    * @Description : JSRemoted method to update submission hard copy field as true
    * @Param       : ID
    * @Return      : String
    ****************************************************************************************************/
    @RemoteAction
    global static String updateHardCopy(Id submissionId){
        try{
            MUSW__Submission__c submission = [select id,Hardcopy__c FROM MUSW__Submission__c WHERE ID=:submissionId];
            submission.Hardcopy__c = TRUE;
            if(submission != null){
                update submission;  
            }
            
            return label.Str_success;
        }catch(Exception ex){
            return ex.getMessage();
        }
    }

    /***************************************************************************************************
    * @Description : JSRemoted method to update submission status
    * @Param       : ID
    * @Param       : String
    * @Return      : String
    ****************************************************************************************************/
    @RemoteAction
    global static String updateStatus(Id submissionId,String status){
        try{
            MUSW__Submission__c submissionUpdate = new MUSW__Submission__c(Id=submissionId,Status__c=status);
            if(submissionUpdate != null){
                update submissionUpdate;    
            }
            
            return label.Str_success;
        }catch(Exception ex){
            return ex.getMessage();
        }
    }
    
    /***************************************************************************************************
    * @Description : JSRemoted method to delete attachment
    * @Param       : ID
    * @Return      : String
    ****************************************************************************************************/
    @RemoteAction
    global static String deleteAttachment(Id attachmentId){
        try{
            Attachment attachment = New Attachment(Id=attachmentId);
            if(attachment != null){
                delete attachment;
            }
            
            return label.Str_success;
        }catch(Exception ex){
            return ex.getMessage();
        }
    }

    /***************************************************************************************************
    * @Description : JSRemoted method to get list of attachments under a submission
    * @Param       : ID
    * @Return      : List<Attachment>
    ****************************************************************************************************/
    @RemoteAction
    global static List<Attachment> getAttachmentList(Id submissionId){
        try{
            List<Attachment> attList = [Select Id,Name FROM Attachment where parentId=:submissionId];
            return attList;
        }catch(Exception ex){
            System.debug('Unexpected Error'+ex.getMessage());
        }
        return null;
    }
    
    /***************************************************************************************************
    * @Description : JSRemoted method to check if all submissions documents are uplaoded
    * @Param       : ID
    * @Return      : Boolean
    ****************************************************************************************************/
    @RemoteAction
    global static Boolean getCompletionStatus(Id submissionId,String isRenewal, String isRenewalPTO, String isExamCredit, String isSR,String isReinstatement,String isLicense, String isPermit, String isLicenseReinstatement,String isReview, String isEndorsement, String isComplaint){
        List<MUSW__Submission__c> subList;
         if(isRenewal!= null && isRenewal ==label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE License_Renewal__c=:submissionId AND Show_for_Credential_Renewal__c=TRUE AND is_Backend_Submission__c = FALSE];
        }/* Todo
         *else if(isSR!= null && isSR ==label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__Application2__c=:submissionId AND Show_For_Name_Change_SR__c=TRUE AND is_Backend_Submission__c = FALSE];
        }*/else if(isReinstatement !=null && isReinstatement ==label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE License_Renewal__c=:submissionId AND Show_for_Credential_Reinstatement__c=TRUE AND is_Backend_Submission__c = FALSE];
        } else if(isLicense !=null && isLicense == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__License2__c=:submissionId AND Show_For_Credential__c=TRUE AND is_Backend_Submission__c = FALSE];
            
        }else if(isPermit !=null && isPermit == label.Str_true){
            System.debug('in getCompletionStatus renewalPTO');
                subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__Permit2__c=:submissionId AND Show_For_Permit__c=TRUE AND is_Backend_Submission__c = FALSE];
            System.debug('in getCompletionStatus subList '+subList);
        }else if(isRenewalPTO != null && isRenewalPTO == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE License_Renewal__c=:submissionId AND Show_for_Permit_Renewal__c=TRUE AND is_Backend_Submission__c = FALSE];
        }/*else if(isLicenseReinstatement !=null && isLicenseReinstatement == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__License2__c=:submissionId AND Show_for_License__c=TRUE AND is_Backend_Submission__c = FALSE];
        }else if(isReview !=null && isReview == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE MUSW__Review__c=:submissionId AND is_Backend_Submission__c = FALSE];
        }else if(isComplaint !=null && isComplaint == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE Complaint__c=:submissionId AND is_Backend_Submission__c = FALSE];
        }
        else if(isExamCredit !=null && isExamCredit == label.Str_true){
            subList = [Select Id,Hardcopy__c,(Select Id FROM Attachments) FROM MUSW__Submission__c WHERE CE_Exam_Credit__c=:submissionId AND is_Backend_Submission__c = FALSE];
        }*/
        Boolean isComplete = getStatus(subList);
        return isComplete;
    }
}