src/objects/LnP_BackgroundSection__c.object
<CustomObject>
    <label>LnP_BackgroundSection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>LnP_BackgroundSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LnP_BackgroundSections</pluralLabel>
    <recordTypes>
        <fullName>Qualifying_Education</fullName>
        <active>true</active>
        <label>Qualifying Education</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>Review_and_Submit</fullName>
        <active>true</active>
        <label>Review and Submit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DOL_PDFDataDisplayControllerTest.cls
@isTest
public class DOL_PDFDataDisplayControllerTest{
    @isTest
    public static void setUpData(){
        //account record data
        Id AccRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account accountRecord = DOL_TestDataFactory.createAccount(AccRecTypeId);
        
        //license record data
        Id LicRecTypeId1 = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        MUSW__License2__c licenseRecord = DOL_TestDataFactory.createLicense(LicRecTypeId1, accountRecord.Id, 'Architects', 'Architect', 'General Application');
        
        //parcel record data
        Id parcelRecodTypeId = Schema.SObjectType.MUSW__Parcel__c.getRecordTypeInfosByDeveloperName().get('Address').getRecordTypeId() ;
        MUSW__Parcel__c parcelRecord = DOL_TestDataFactory.createParcel(parcelRecodTypeId);
        
        //license parcel record data
        MUSW__License_Parcel__c licenseParcelRecord = DOL_TestDataFactory.createLicenseParcel(licenseRecord.Id, parcelRecord.Id);
        
        //question record data
        Id questionRecordTypeId = Schema.SObjectType.Question__c.getRecordTypeInfosByDeveloperName().get('Review_and_Submit').getRecordTypeId() ;
        Question__c questionRecord = DOL_TestDataFactory.createQuestion(questionRecordTypeId);
        
        //qualifying education record
        Id qualifyingEducationRecordTypeId = Schema.SObjectType.LnP_BackgroundSection__c.getRecordTypeInfosByDeveloperName().get('Qualifying_Education').getRecordTypeId();
        LnP_BackgroundSection__c qualifyingEducationRecord = DOL_TestDataFactory.createBackgroundSection();
        qualifyingEducationRecord.RecordTypeId = qualifyingEducationRecordTypeId;
        update qualifyingEducationRecord;
        
        Test.StartTest(); 
        DOL_PDFDataDisplayController pdfControllerobj = new DOL_PDFDataDisplayController(new ApexPages.StandardController(licenseRecord));  
        Test.StopTest();
    }
}