src/objects/LnP_BackgroundSection__c.object
<CustomObject>
    <fields>
        <fullName>License_Bg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License Bg</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Qualifying Information</relationshipLabel>
        <relationshipName>LnP_BackgroundSections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LnP_BackgroundSection</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>LnP_BackgroundSection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LnP_BackgroundSections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LnP_DashboardApex_Test.cls
@isTest
public class LnP_DashboardApex_Test {
    //Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business Account').getRecordTypeId()
    public static testmethod void LnP_DashboardApexonstructor(){
        LnP_BackgroundSection__c testBgRec = DOL_TestDataFactory.createBackgroundSection();
        MUSW__License2__c liceId = DOL_TestDataFactory.createLicense('012r000000074ci', 
                                                                    DOL_TestDataFactory.createAccount('012r000000074cO').Id, 
                                                                    'Appraisal Management Companies', 
                                                                    'Appraisal Management Company', 
                                                                    'General Application');
        testBgRec.License_Bg__c = liceId.Id;
        Map<String, String> mapJSON = new Map<String, String>();
        Test.startTest();
         LnP_DashboardApexController_2.checkActiveCart();
        LnP_DashboardApexController_2.helptextFetch();
        LnP_DashboardApexController_2.getDashboardJSON();
        LnP_DashboardApexController_2.fetchRenewalRelatedEmploymentNEducationalHistoryRecords('test');
        LnP_DashboardApexController_2.fetchLicenseRelatedEmploymentNEducationalHistoryRecords(liceId.Id);
             Test.stopTest();
        
    }
}