src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>Sub-status is a dependent picklist driven off of Status.</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sub_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Name_Value_Pair__mdt.object
<CustomObject>
    <description>To store name value pairs - similar to key value pairs in a map</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value field for name value pair</description>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Name Value Pair</label>
    <pluralLabel>Name Value Pairs</pluralLabel>
</CustomObject>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

src/globalValueSets/Sub_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Additional Information Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <description>Sub-status is a dependent picklist driven off of Status.</description>
    <masterLabel>Sub Status</masterLabel>
</GlobalValueSet>

src/classes/AutoCloseAbandonedPTOTitlePRBatch_Test.cls
/**
* User Story:  285- Automatically abandoning applications
* Name: AutoCloseAbandonedPTOTitlePRBatch_Test
* Type: Test Class
* Description: Class to create Test Data and test the execution of AutoCloseAbandonedPTOTitlePRBatch
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 07/27/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/
@isTest
public class AutoCloseAbandonedPTOTitlePRBatch_Test {            
    @isTest
    public static void AutoCloseAbandonedCredentialBatchTest1() {
        
        Name_Value_Pair__mdt days = [select Value__c from Name_Value_Pair__mdt where Label = :Label.Str_AutoClosePermitsIn_nDays];
        String autoClosePermitDays = days.Value__c;
        String staticResourceName = 'permitTestData';
    	List<sObject> permitList = Test.loadData(MUSW__Permit2__c.sObjectType, staticResourceName);
        Test.startTest();    
        String autoClosePermitQuery = 'SELECT Id, Name, Application_Type__c, Program_Area__c, Permit_Type__c, MUSW__Status__c '+
                ' FROM MUSW__Permit2__c'+
                ' WHERE MUSW__Status__c = \''+Label.ST_In_Review+'\''+
                ' AND Sub_Status__c = \''+ Label.ST_Additional_Information_Required +'\''+
        		' AND LastModifiedDate < LAST_N_DAYS:'+autoClosePermitDays+'' +
            	' AND Application_Type__c IN (\'' + Label.Str_Permit_to_Operate + '\',' + '\'' + Label.Str_Manufactured_Homes_Communities +'\')';          
        //System.debug('autoClosePermitQuery '+autoClosePermitQuery);
        AutoCloseAbandonedPTOTitlePRBatch batchToExecute = new AutoCloseAbandonedPTOTitlePRBatch(autoClosePermitQuery);
        /*Execute batch- AutoCloseAbandonedCredentialBatch to auto close abandoned applications*/
        Database.executeBatch(batchToExecute, 1);    
        Test.stopTest();
        
        List<MUSW__Permit2__c> autoClosedPermitsList = new List<MUSW__Permit2__c>();          
        /*Fetching the updated Id, Status and SubStatus for the above created Licenses*/    
        //System.debug('permitList >> '+permitList);
        autoClosedPermitsList = [SELECT Id, MUSW__Status__c
                            FROM MUSW__Permit2__c
                            WHERE ID IN :permitList];
    
        if(autoClosedPermitsList.size() > 0)    {               
                
        //Status should be changed to Withdrawn and Substatus to Inactive
        System.AssertEquals(Label.ST_Withdrawn,autoClosedPermitsList[0].MUSW__Status__c);               
        //System.AssertEquals('Inactive', autoClosedCredentialsList[0].Sub_Status__c);
            }    
    
        }
    
}