src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_for_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected for Audit</label>
        <type>Checkbox</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the review.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved with Conditions</fullName>
                </value>
                <value>
                    <fullName>Corrections Required</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Exam Approved</fullName>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Audit Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Application</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
                <value>
                    <fullName>Maintenance Request</fullName>
                </value>
                <value>
                    <fullName>CE Audit</fullName>
                </value>
                <value>
                    <fullName>Comity</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
                <value>
                    <fullName>Exam Review</fullName>
                    <isActive>false</isActive>
                    <label>Exam Review</label>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <isActive>false</isActive>
                    <label>New Application</label>
                </value>
                <value>
                    <fullName>Renew</fullName>
                    <isActive>false</isActive>
                    <label>Renew</label>
                </value>
                <value>
                    <fullName>Sending Activation Code</fullName>
                    <isActive>false</isActive>
                    <label>Sending Activation Code</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Renewal_Application__c.object
    <fields>
        <fullName>Selected_for_Audit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected for Audit</label>
        <type>Checkbox</type>
    </fields>

src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type (To be Deleted)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Profession__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Service_Request_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Service_Request_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Request - Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Self-Service - Address</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request - Cancel License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact information to display on Catalogue</fullName>
    </customValue>
	<customValue>
        <fullName>Update Owners</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Name</fullName>
    </customValue>
    <customValue>
        <fullName>Provider Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Retire a course</fullName>
    </customValue>
    <customValue>
        <fullName>Project Size Change</fullName>
    </customValue>
    <customValue>
        <fullName>Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Contact Info Change</fullName>
    </customValue>
    <customValue>
        <fullName>Name Change</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Remove Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Supervisor Invite</fullName>
    </customValue>
    <customValue>
        <fullName>Qualifying Experience Log Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Management</fullName>
    </customValue>
    <customValue>
        <fullName>Course History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit Request</fullName>
    </customValue>
    <customValue>
        <fullName>Order Duplicate License</fullName>
    </customValue>
    <customValue>
        <fullName>Reactivate License from Expired Surety Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Change Designated CP / Owner</fullName>
    </customValue>
    <customValue>
        <fullName>License History Request</fullName>
    </customValue>
    <customValue>
        <fullName>License Affidavit</fullName>
    </customValue>
    <customValue>
        <fullName>Designated Controlling Person Closing Business Affidavit (APR-622-175)</fullName>
    </customValue>
    <customValue>
        <fullName>Closing Business Affidavit information update</fullName>
    </customValue>
    <customValue>
        <fullName>Ad Reviews</fullName>
    </customValue>
    <customValue>
        <fullName>AMC Controlling Person Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Add Associations</fullName>
    </customValue>
    <customValue>
        <fullName>Disassociation</fullName>
    </customValue>
    <customValue>
        <fullName>Add Affiliations</fullName>
    </customValue>
    <customValue>
        <fullName>CE Audit</fullName>
    </customValue>
    <masterLabel>Service Request Type</masterLabel>
</GlobalValueSet>

src/classes/LnP_CreateAuditClass.cls
/*@AUTHOR: Kojashree Kakariya
@Date:  25-June-2019      

Description: Class to select ten percent of renewal and license records for audit process.

MODIFICATION LOG:
DEVELOPER                          DATE                     DESCRIPTION
================================================================================
Kojashree Kakariya               25-June-2019             Initial Creation
================================================================================= */

public class LnP_CreateAuditClass {
    
    //Generic class to calculate ten percent of records of each License Type
    
    public static List<SObject> calculateTenPercentRecords(List<SObject> appList){
        system.debug('appList 123'+appList);
        Integer listSize = appList.size();
        system.debug('listSize---'+listSize);
        Integer tenPerRecList = (listSize < 10 ) ? 1 : (listSize*0.1).intValue();
        system.debug('tenPerRecList---'+tenPerRecList);
        List<SObject> selectedRenApp = new List<SObject>();  
        System.debug('tenPerRecList::'+tenPerRecList);
        
        for(Integer i= 0; i< tenPerRecList;i++){
            if(appList.size() !=0){
                selectedRenApp.add(appList[i]);
                system.debug('selectedRenApp---'+selectedRenApp); 
            }
            
        }
        system.debug('tenPerRecList---'+tenPerRecList);
        return selectedRenApp;
    } 
    
    // Create an updated map with ten percent records selected of each RE License type 
    public static Map<String,List<Renewal_Application__c>> getUpdatedRenewalAppMap(Map<String,List<Renewal_Application__c>> renApplicationMap){
        system.debug('renApplicationMap---'+renApplicationMap);
        Map<String,List<Renewal_Application__c>> updatedRenAppMap = new Map<String,List<Renewal_Application__c>>();
       
        for(String key : renApplicationMap.keySet()){
            system.debug('keySet--'+key);
            system.debug('value--'+renApplicationMap.get(key));
            
            List<Renewal_Application__c> updatedList = new List<Renewal_Application__c>();
            updatedList = calculateTenPercentRecords(renApplicationMap.get(key));
            system.debug('updatedList---'+updatedList);
            updatedRenAppMap.put(key,updatedList);
         }
        return updatedRenAppMap;
    }
    
    // Create an updated map with ten percent records selected of each RBS License type 
    public static Map<String,List<MUSW__License2__c>> getUpdatedLicenseMap(Map<String,List<MUSW__License2__c>> rbsAppMap ){
        system.debug('rbsAppMap---'+rbsAppMap);
        Map<String,List<MUSW__License2__c>> updatedLicenseMap = new Map<String,List<MUSW__License2__c>>();
        
        for(String key : rbsAppMap.keySet()){
            List<MUSW__License2__c> updatedRBSList = new List<MUSW__License2__c>();
            system.debug('keySet--'+key);
            system.debug('value--'+rbsAppMap.get(key));
            
           updatedRBSList = calculateTenPercentRecords(rbsAppMap.get(key));
           system.debug('updatedList---'+updatedRBSList);
           updatedLicenseMap.put(key,updatedRBSList);
            
        }
        return updatedLicenseMap;
    }
    
    
 public static void createAuditForRE(List<Renewal_Application__c> appList){
        List<MUSW__Review__c> auditList = new List<MUSW__Review__c>();
        List<Renewal_Application__c> updateFlagforAuditList = new List<Renewal_Application__c>();
        system.debug('appList---'+appList);
        Id recordTypeId = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get('CE Audit Review').getRecordTypeId();
        system.debug(' ce audit review record type '+recordTypeId);
        for(Renewal_Application__c renApp : appList){
            MUSW__Review__c newAuditReviewRec = new MUSW__Review__c(
                Renewal_Application__c = renApp.Id,
                recordTypeId = recordTypeId,
                Application_Type__c = renApp.Application_Type__c,
                License__c = renApp.License__c,
                MUSW__Status__c =  'Pending',
                Review_Type__c = 'CE Audit',
                License_Type__c = renApp.Credential_Type__c
            );
            renApp.Selected_for_Audit__c = true;
            updateFlagforAuditList.add(renApp);
            auditList.add(newAuditReviewRec);
            system.debug('auditList 1-------'+auditList);
        }
     if(!auditList.isEmpty()){
         insert auditList;
     } 
     if(!updateFlagforAuditList.isEmpty()){
         update updateFlagforAuditList;
     }
 }
    
    public static void createAuditForRBS(List<MUSW__License2__c> licenseList){
        List<MUSW__Review__c> auditList = new List<MUSW__Review__c>();
        List<Request__c> requestList = new List<Request__c>();
        List<MUSW__License2__c> updateFlagOnLicenseList = new List<MUSW__License2__c>();
        
        system.debug('licenseList---'+licenseList);
        Id recordTypeId = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get('CE Audit Review').getRecordTypeId();
        system.debug(' ce audit review record type '+recordTypeId);
        for(MUSW__License2__c licenseApp : licenseList){
            MUSW__Review__c newAuditReviewRec = new MUSW__Review__c(
                recordTypeId = recordTypeId,
                Application_Type__c = licenseApp.Application_Type__c,
                License__c = licenseApp.Id,
                MUSW__Status__c = 'Pending',
                Review_Type__c = 'CE Audit',
                License_Type__c = licenseApp.Credential_Type__c
            );
          
            auditList.add(newAuditReviewRec);
            system.debug('auditList-------'+auditList);
            
            Request__c newCEAuditRequest = new Request__c(
                Profession__c = licenseApp.Application_Type__c,
                License_Type__c = licenseApp.Credential_Type__c,
                Service_Request_Type__c = 'CE Audit',
                License__c = licenseApp.id,
                Status__c = 'Draft'
           );
           requestList.add(newCEAuditRequest); 
            
            licenseApp.Selected_for_Audit__c = true;
            updateFlagOnLicenseList.add(licenseApp);
           system.debug('newCEAuditRequest----'+newCEAuditRequest);
           
        }
        if(!auditList.isEmpty()){
            insert auditList;
        } 
        if(!requestList.isEmpty()){
            insert requestList;
        }
        if(!updateFlagOnLicenseList.isEmpty()){
            update updateFlagOnLicenseList;
        }
    }
    
}