src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>MUSW__BG_File_Location_Type__c</fullName>
        <description>Location of the document or file related to this submission record. Default is Salesforce</description>
        <inlineHelpText>Location of the document or file related to this submission record.</inlineHelpText>
        <label>File Location Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Bluebeam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAN_Image_URL__c</fullName>
        <description>URL of the image on SAN</description>
        <label>SAN Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dol_ViewTiffFile_Test.cls
@isTest
public class Dol_ViewTiffFile_Test {
    
    public static final String sUrl = DOL_AppConstants.NULL_EMPTY_STRING + 'http://seikichi.github.io/tiff.js/images/quad-tile.jpg.tiff';
    
    @isTest
    private static void testViewURL(){
        MUSW__Submission__c submission = new MUSW__Submission__c(MUSW__BG_File_Location_Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Salesforce',Name = DOL_AppConstants.NULL_EMPTY_STRING + 'Test Submission',
                                                                 SAN_Image_URL__c=sUrl);
        insert submission;
        test.startTest();
        pagereference testPage = page.Dol_ViewTiffFile;
        test.setcurrentpage(testPage);
        ApexPages.StandardController standCont = new ApexPages.StandardController(submission);
        Dol_ViewTiffFile contRoller1 = new Dol_ViewTiffFile(standCont); 
        test.stopTest();
        
    }

}