src/objects/MUSW__Inspection__c.object
<CustomObject>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Parcel (Address).</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <recordTypes>
        <fullName>Inspection</fullName>
        <active>true</active>
        <label>Inspection</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/mapDemoTest.cls
@isTest
public class mapDemoTest {
    public static testmethod void mapDemoConstructor(){
        MUSW__Parcel__c parcel = TestUtility.getParcel();
        insert parcel;
        MUSW__Inspection__c inspection = TestUtility.getInspection();
        inspection.MUSW__Parcel__c=parcel.id;
        Test.startTest();
        mapDemo.getMarkers();
        mapDemo.getRoute();
        
        Test.stopTest();
    }
    
}