src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ManufacturedHomesValidatorTest.cls
@istest
public class ManufacturedHomesValidatorTest extends BaseValidator {
    static testmethod void validate_homes_dealer_test()
    {
        BaseValidator.AllSections all=new AllSections();
        MUSW__License2__c newrc = new MUSW__License2__c(
        	credential__c='Manufactured Homes Dealer'            
        );
        //this is not being used in the class
        MUSW__License2__c oldrc = new MUSW__License2__c();
        ManufacturedHomesValidator obj=new ManufacturedHomesValidator();
        obj.validate(all, newrc, oldrc);
        System.assert(obj.e.hasErrors());
    }

    static testmethod void validate_homes_certificate_test()
    {
        BaseValidator.AllSections all=new AllSections();
        MUSW__License2__c newrc = new MUSW__License2__c(
        	credential__c='Manufactured Homes Certificate of Title'            
        );
        //this is not being used in the class
        MUSW__License2__c oldrc = new MUSW__License2__c();
        ManufacturedHomesValidator obj=new ManufacturedHomesValidator();
        obj.validate(all, newrc, oldrc);
        System.assert(obj.e.hasErrors());
    }

}