src/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeleteAbandonedApplications.cls
public without sharing class DeleteAbandonedApplications
{
    @InvocableMethod
    public static void ApplicationDelete(List<Id> ApplicationIds)
    {
        List<MUSW__Application2__c> Applications =[select id from MUSW__Application2__c
                          where (id in :ApplicationIds
                       AND LastModifiedDate >= LAST_N_DAYS:120) AND MUSW__Status__c = 'Abandoned'];
        delete Applications;
   }
}