src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated parcel or address of the permit.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Area__c</fullName>
        <description>This refers to the program area being applied for as defined by the application type</description>
        <label>Program Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Program_Area</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program_Area.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>POWTS</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Communities</fullName>
    </customValue>
    <customValue>
        <fullName>Delegated Municipality Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Notary Public Commission</fullName>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes Titling</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes Titling</label>
    </customValue>
    <customValue>
        <fullName>Manufactured Homes</fullName>
        <isActive>false</isActive>
        <label>Manufactured Homes</label>
    </customValue>
    <customValue>
        <fullName>Uniform Dwellings</fullName>
        <isActive>false</isActive>
        <label>Uniform Dwellings</label>
    </customValue>
    <description>This refers to the program area being applied for as defined by the application type</description>
    <masterLabel>Program Area</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/InspectionRequestControllerTest.cls
@isTest
public class InspectionRequestControllerTest {
	@isTest(SeeAllData=true)
    private static void testCon_withParent()
    {
        MUSW__Parcel__c par = new MUSW__Parcel__c(Name='zsdfsf');
        insert par;
        MUSW__Permit2__c p = new MUSW__Permit2__c(MUSW__Parcel__c=par.Id, Application_Type__c = 'Plan Review', Permit_Type__c = 'POWTS Petition for Variance', Program_Area__c = 'POWTS');
        insert p;
        
        pageReference pr = Page.InspectionRequest;
        pr.getParameters().put('pid', p.id );
        Test.setCurrentPage( pr );
        
        InspectionRequestController c = new InspectionRequestController();
        c.insSelectIndex = 0;
        c.save();
    }
}