src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Card_Type__c</fullName>
        <description>Deprecated.</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remittance_Process_Date_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Remittance Process Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>US_Bank_Payment_Status__c</fullName>
        <label>US Bank Payment Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Settled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LnP_PaymentReceiptStatusCtlr_Test.cls
@isTest
public class LnP_PaymentReceiptStatusCtlr_Test {
    @isTest
    public static void testMethod1() {
        Test.startTest();
        DateTime todayDateTime = DateTime.now();
        Date todayDate = Date.today();
        String parameter = 'true-true-true-true-true';
        MUSW__Receipt__c receipt1 = new MUSW__Receipt__c(MUSW__Card_Type__c='Amex',MUSW__Payment_Method__c='CreditCard',Remittance_Process_Date_Time__c=todayDateTime,US_Bank_Payment_Status__c='Processed',MUSW__Amount_Tendered__c=10.0);
        insert receipt1;
        MUSW__Receipt__c receipt2 = new MUSW__Receipt__c(MUSW__Card_Type__c='Visa',MUSW__Payment_Method__c='CreditCard',Remittance_Process_Date_Time__c=todayDateTime,US_Bank_Payment_Status__c='Processed',MUSW__Amount_Tendered__c=5.0);
        insert receipt2;
        MUSW__Receipt__c receipt3 = new MUSW__Receipt__c(MUSW__Card_Type__c='MasterCard',MUSW__Payment_Method__c='CreditCard',Remittance_Process_Date_Time__c=todayDateTime,US_Bank_Payment_Status__c='Processed',MUSW__Amount_Tendered__c=7.0);
        insert receipt3;
        MUSW__Receipt__c receipt4 = new MUSW__Receipt__c(MUSW__Card_Type__c='Discover',MUSW__Payment_Method__c='CreditCard',Remittance_Process_Date_Time__c=todayDateTime,US_Bank_Payment_Status__c='Processed',MUSW__Amount_Tendered__c=8.0);
        insert receipt4;
        MUSW__Receipt__c receipt5 = new MUSW__Receipt__c(MUSW__Card_Type__c='',MUSW__Payment_Method__c='ACH',Remittance_Process_Date_Time__c=todayDateTime,US_Bank_Payment_Status__c='Processed',MUSW__Amount_Tendered__c=5.0);
        insert receipt5;
        LnP_PaymentReceiptStatusCtlr.getPaymentTotals(parameter,todayDate);
        LnP_PaymentReceiptStatusCtlr.paymentReceiptRecordsUpdate(parameter,todayDate);
        LnP_PaymentReceiptStatusCtlr.getPmtInitialTotals();
        Test.stopTest();
    }
}