src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CE_Eligible__c</fullName>
        <description>To determine if a credential is CE eligible or not</description>
        <formula>OR(
ISPICKVAL(Credential__c, &quot;UDC HVAC Inspector&quot;), 
ISPICKVAL(Credential__c, &quot;UDC Plumbing Inspector&quot;),
ISPICKVAL(Credential__c, &quot;UDC Electrical Inspector&quot;),
ISPICKVAL(Credential__c, &quot;UDC Construction Inspector&quot;),
ISPICKVAL(Credential__c, &quot;Soil Tester&quot;),
ISPICKVAL(Credential__c, &quot;Manufactured Homes Installer&quot;),
ISPICKVAL(Credential__c, &quot;Dwelling Contractor Qualifier&quot;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CE Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CE_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll up summary field from class to show the total of hours</description>
        <label>CE Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CE_Hours_per_Cycle__c</fullName>
        <formula>CASE(Credential__c, &quot;UDC HVAC Inspector&quot;, 24, &quot;UDC Plumbing Inspector&quot;, 24, &quot;UDC Electrical Inspector&quot;, 24, &quot;UDC Construction Inspector&quot;, 24, &quot;Soil Tester&quot;, 12, &quot;Manufactured Homes Installer&quot;, 12, &quot;Dwelling Contractor Qualifier&quot;, 12,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CE Hours per Cycle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Late_Renewal_Eligible__c</fullName>
        <description>Formula to determine Late Renewal Eligibility</description>
        <formula>IF((TODAY()&gt;MUSW__Expiration_Date__c &amp;&amp; TODAY()&lt;= Late_Renewal_Eligible_End_Date__c &amp;&amp; (ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;) ||  ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Late Renewal&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Hold&apos;))), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Late Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Cycle_End_Date__c</fullName>
        <description>To calculate the renewal cycle duration- Multiplying the renewal window by 12 as it is in years</description>
        <formula>ADDMONTHS(MUSW__Expiration_Date__c,Renewal_Window__c*12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Cycle End Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/classes/HandleIncompleteRenewalsYearlyScheduler.cls
/**
* User Story: 285
* Name: HandleIncompleteRenewalsYearlyScheduler
* Type: Class
* Description: Scheduler class to run the batch class to handle incomplete renewals having CE requirements
* Date:        - Case#/Project:            - Developer/Company                         - Description
* ------------------------------------------------------------------------------------------------------------------------- *
* 09/10/2018   Sharad Maheshwari/Deloitte           Initial Creation 
*/
global with sharing class HandleIncompleteRenewalsYearlyScheduler implements Schedulable{
    
    /***************************************************************************************************
* @Description : Runs Batch to 
* @Param       : SchedulableContext
* @Return      : void
****************************************************************************************************/
    global void execute(SchedulableContext sc) {
        
        String licenseExpirationQuery='SELECT id, MUSW__Status__c, CE_Hours__c, Renewal_Cycle_End_Date__c, CE_Hours_Per_Cycle__c, MUSW__Expiration_Date__c, Application_Type__c, Is_Late_Renewal_Eligible__c  '+
                                        'FROM MUSW__License2__c  '+
                                        'WHERE (((Renewal_Cycle_End_Date__c >= TODAY) AND (MUSW__Expiration_Date__c < TODAY)) OR (Renewal_Cycle_End_Date__c < TODAY)) '+
             							'AND Credential__c NOT IN  ('+'\'' +Label.CR_Manufactured_Homes_Installer +'\''+', '+'\''+Label.CR_Dwelling_Contractor_Qualifier+'\'' +') '+
            							'AND CE_Eligible__c = TRUE';
          
        System.debug('query from final'+ licenseExpirationQuery);
          //call the next batch
        HandleIncompleteRenewalsExpirationBatch handleRenewalsExpirationBatch = new HandleIncompleteRenewalsExpirationBatch(licenseExpirationQuery); 
        try{
            database.executebatch(handleRenewalsExpirationBatch, Integer.valueOf(Label.Str_Batch_Execution_Limit));
        }
        /*
        HandleIncompleteRenewalsYearlyScheduler yearlyScheduler = new HandleIncompleteRenewalsYearlyScheduler();
        String sch = '0 0 23 30 6 ?';
        system.schedule('run yearly on june 30 11 pm', sch, yearlyScheduler);
        */
        catch(Exception e){
            System.debug('test exception');
            ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'HandleIncompleteRenewals', 'final', 'Schedulable', 'HandleIncompleteRenewals', label.Str_Low);            
        }
        
    }       
    
}