src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>The total Amount that needs to be collected.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Transfered_In_Amount__c</fullName>
        <description>Total amount that has been transferred in to this deposit.</description>
        <label>Transfered In Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MUSW__Deposit__c.object
    <fields>
        <fullName>Agency_Code__c</fullName>
        <description>1966</description>
        <label>Agency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agency_Code</valueSetName>
        </valueSet>
    </fields>

src/objects/MUSW__Payable_Receipt__c.object
<CustomObject>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>The amount of the transaction related to a deposit: deposit collection (positive value), transferred in (positive value), transferred out (negative value).</description>
        <label>Amount Collected</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Deposit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deposit</label>
        <referenceTo>MUSW__Deposit__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Payable_Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Receipt__c</fullName>
        <description>Lookup to the receipt record.</description>
        <label>Receipt</label>
        <referenceTo>MUSW__Receipt__c</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Payable_Receipts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payable Receipt</label>
    <nameField>
        <displayFormat>PYR-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>Agency_Code__c</fullName>
        <description>1966</description>
        <label>Agency Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Agency_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overshort_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Captures Overshort amount</description>
        <label>Overshort Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Agency_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>3000</fullName>
    </customValue>
    <customValue>
        <fullName>5400</fullName>
    </customValue>
    <description>1966 : Global value set for agency code</description>
    <masterLabel>Agency Code</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/DepositTriggerHandlerTest.cls
@isTest
public class DepositTriggerHandlerTest {

    public static testMethod void depositHandlerTest(){
        
        MUSW__Deposit__c depRec = new MUSW__Deposit__c();
        depRec.Agency_Code__c = '5400';
        depRec.Amount__c = 100;
        depRec.MUSW__Transfered_In_Amount__c = 100;
        insert depRec;
        
        MUSW__Receipt__c rptRec =  new MUSW__Receipt__c();
        rptRec.MUSW__Amount_Tendered__c = 100;
        insert rptRec;
        
        MUSW__Payable_Receipt__c payrec = new MUSW__Payable_Receipt__c();
        payrec.MUSW__Deposit__c = depRec.Id;
        payrec.MUSW__Receipt__c = rptRec.Id;
        payrec.MUSW__Amount__c = 100;
        insert payrec;
        
        test.startTest();
        depRec.Overshort_Amount__c = 1000;
        depRec.MUSW__Transfered_In_Amount__c = 10;
        depRec.Agency_Code__c = '3000';
        update depRec;
        test.stopTest();
        
    }
}