src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The applicant submitting the permit application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Permit Applications</relationshipLabel>
        <relationshipName>Applicant_Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the permit that the renewal is referring to.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RenewalCreatedByDelegate.cls
/**
* Name: RenewalCreatedByDelegate
* Type: Class
* Description: Trigger handler class to handle sharing for Renewal records with the 
*  			   the community plus user who also happens to be the applicant of a renewal
* Date:        Developer/Company                 	Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 08/22/2018   Srikanth Kottam/Deloitte           Initial Creation
**/
public class RenewalCreatedByDelegate {
	/**
	* @Method name   : shareRenewalRecords
	* @Description   : Share the Renewal records when the Delegated Admin is the applicant on the Renewal 
	* @Return Type   : None
	* @Parameter     : Trigger.new
	**/
    public void shareRenewalRecords(List<Renewal_Application__c> RenewalShareRecords) {
        
        set <Id> LicenseIds = new set<Id>();
        List<MUSW__License2__c> LicenseList = new List<MUSW__License2__c>();
        set <Id> PermitIds = new set <Id> ();
        List <MUSW__Permit2__c> PermitList = new List <MUSW__Permit2__c> ();
        List <Id> RenewalIds = new List <Id> ();
        Set <Id> ContactIdsSet = new Set <Id> ();
        
        SharingUtilityController utilityCOntroller = new SharingUtilityController();
        for(Renewal_Application__c renewal:RenewalShareRecords) {
            if(renewal.License__c!=null){
                LicenseIds.add(renewal.License__c);
            }else if(renewal.Permit__c != null){
                PermitIds.add(renewal.Permit__c);
            }
            RenewalIds.add(renewal.Id);
        }
        
        if(LicenseIds.size()>0) {
            try{
                LicenseList = [select Id, MUSW__Applicant__c from MUSW__License2__c where Id IN:LicenseIds];
            }
            catch(exception e){
                ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'LicenseRenewalCreatedByDelegate', 'Error Occured Processing Share Records in LicenseRenewalCreatedByDelegate', 'ShareRenewalRecords', 'LicenseRenewalCreatedByDelegate', 'HIGH');
            }
        }
        
        if (PermitIds.size() > 0){
            try{
                PermitList = [select Id, MUSW__Applicant__c from MUSW__Permit2__c where Id IN: PermitIds];
            } 
            catch (exception e){
                ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'LicenseRenewalCreatedByDelegate', 'Error Occured Processing Share Records in LicenseRenewalCreatedByDelegate', 'ShareRenewalRecords', 'LicenseRenewalCreatedByDelegate', 'HIGH');
            }
        }
        
        if(LicenseList.size()>0) {
            for (MUSW__License2__c license: LicenseList){
                if (license.MUSW__Applicant__c != null){
                    ContactIdsSet.add(license.MUSW__Applicant__c);
                }
            }
        }
        
        if(PermitList.size() > 0){
            for(MUSW__Permit2__c permit: PermitList){
                if (permit.MUSW__Applicant__c != null){
                    ContactIdsSet.add(permit.MUSW__Applicant__c);
                }
            }
        }
        
        if (RenewalIds.size() > 0 && ContactIdsSet.size() > 0){
            list <Id> contactids = new List <Id> ();
            contactids.addAll(ContactIdsSet);
            UtilityCOntroller.ShareRecords_CreatedByDelegate(ContactIds, RenewalIds, 'Renewal_Application__c', 'LicenseRenewalCreatedByDelegate');
        }
    }
}