src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>An obligation amount (fee) that needs to be paid.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated license record.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>The type of fee. Each type may have a different accounting code.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>DHP</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Staff Hours</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Mileage</fullName>
                </value>
                <value>
                    <fullName>Trust - Prearrangement Funeral Services Deposit</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance (AMR)</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Is the fee related to a  renewal application?</description>
        <label>Renewal Application</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CE_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll up summary field from class to show the total of hours</description>
        <label>CE Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CE_Hours_per_Cycle__c</fullName>
        <formula>CASE(Credential__c, &quot;UDC HVAC Inspector&quot;, 24, &quot;UDC Plumbing Inspector&quot;, 24, &quot;UDC Electrical Inspector&quot;, 24, &quot;UDC Construction Inspector&quot;, 24, &quot;Soil Tester&quot;, 12, &quot;Manufactured Homes Installer&quot;, 12, &quot;Dwelling Contractor Qualifier&quot;, 12,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CE Hours per Cycle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Late_Renewal_Eligible__c</fullName>
        <description>Formula to determine Late Renewal Eligibility</description>
        <formula>IF((TODAY()&gt;MUSW__Expiration_Date__c &amp;&amp; TODAY()&lt;= Late_Renewal_Eligible_End_Date__c &amp;&amp; (ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;) ||  ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Late Renewal&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Hold&apos;))), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Late Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Primary descriptor of the License.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Liquor</fullName>
                </value>
                <value>
                    <fullName>Animal</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Cycle_End_Date__c</fullName>
        <description>To calculate the renewal cycle duration- Multiplying the renewal window by 12 as it is in years</description>
        <formula>ADDMONTHS(MUSW__Expiration_Date__c,Renewal_Window__c*12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Cycle End Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CE_Hours__c</fullName>
        <description>CE hours</description>
        <label>CE Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Status__c</fullName>
        <description>This is the renewal status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Renewal_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Renewal_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Incomplete</fullName>
    </customValue>
    <customValue>
        <fullName>Generate Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Submitted</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Draft</fullName>
    </customValue>
    <customValue>
        <fullName>In-Review</fullName>
    </customValue>
    <customValue>
        <fullName>Submission Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Payment</fullName>
    </customValue>
    <customValue>
        <fullName>Waiting for Third Party Verification</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Applicant Action</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Additional Qualifications</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Denied</fullName>
    </customValue>
    <customValue>
        <fullName>Abandoned</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
        <isActive>false</isActive>
    </customValue>
    <masterLabel>Renewal Status</masterLabel>
</GlobalValueSet>

src/classes/HandleIncompleteRenewalsExpirationBatch.cls
global with sharing class HandleIncompleteRenewalsExpirationBatch implements Database.Batchable<sObject> {
		
    
    global final String query;  
    
    global HandleIncompleteRenewalsExpirationBatch(String q){        
        query=q;        
        System.debug('query from batch '+ query);
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
          return Database.getQueryLocator(query);
      }

      //Method to execute the batch
      global void execute(Database.BatchableContext BC, List<MUSW__License2__c> scope ){
          System.debug('in HandleIncompleteRenewalsExpirationBatch scope '+ scope);          
        	Date todaysDate = System.Date.today();
          Set<ID> licenseIdList = new Set<ID>();
          for(MUSW__License2__c licRecord :scope){
              licenseIdList.add(licRecord.ID);
          }
          System.debug('licenseIdList '+licenseIdList);
          Map<ID, ID> licenseRenewalMap = new Map<ID, ID>();
          //fetch all the renewals in submitted status for the given credentials
          List<Renewal_Application__c> correspondingRenewalList = [SELECT license__r.Id, Id
                                                                  FROM Renewal_Application__c
                                                                  WHERE license__r.id IN :licenseIdList
                                                                  AND Renewal_Status__c = :Label.ST_Submitted];
          System.debug('correspondingRenewalList '+correspondingRenewalList);
          //create a map to store license id and corresponding renewal id
          for(Renewal_Application__c renewalRecord: correspondingRenewalList){
              licenseRenewalMap.put(renewalRecord.license__r.Id, renewalRecord.Id);
              
          }
          System.debug('licenseRenewalMap '+licenseRenewalMap);
          List<MUSW__License2__c> licensesToUpdateList = new List<MUSW__License2__c>();
          List<MUSW__Fee__c> feesToCreate = new List<MUSW__Fee__c>();
          List<Renewal_Application__c> renewalsToUpdate = new List<Renewal_Application__c>();
          MUSW__License2__c licenseToUpdate; 
        for(MUSW__License2__c licenseRecord :scope){
            /*System.debug('licenseRecord '+licenseRecord);
            System.debug('licenseRecord.CE_Hours_per_Cycle__c '+licenseRecord.CE_Hours_per_Cycle__c);
            System.debug('licenseRecord.MUSW__Status__c '+licenseRecord.MUSW__Status__c);
            System.debug('licenseRecord.Renewal_Cycle_End_Date__c '+licenseRecord.Renewal_Cycle_End_Date__c);
            System.debug('todaysDate '+todaysDate);*/
            Decimal licenseCEHours = licenseRecord.CE_Hours__c;
            if(licenseCEHours == null){
                licenseCEHours = 0.0;
            }
            System.debug('licenseCEHours '+licenseCEHours);
            
            if(licenseCEHours < licenseRecord.CE_Hours_per_Cycle__c &&
               licenseRecord.Is_Late_Renewal_Eligible__c &&
              licenseRecord.MUSW__Status__c <> Label.ST_Late_Renewal &&
              todaysDate > licenseRecord.MUSW__Expiration_Date__c &&
              licenseRecord.Renewal_Cycle_End_Date__c > todaysDate){
                  System.debug('batch in if');
                  licenseToUpdate = new MUSW__license2__c(Id = licenseRecord.Id, 
                                                          MUSW__Status__c = Label.ST_Late_Renewal);
                   licensesToUpdateList.add(licenseToUpdate);
                  //if there is a submitted renewal for the given credential, then create a fee record for the same
                  if(licenseRenewalMap.containsKey(licenseRecord.Id)){
                      
                   MUSW__Fee__c lateCEFee = new MUSW__Fee__c(MUSW__Amount__c = 25, Application_Type__c = licenseRecord.Application_Type__c,
                                                            Renewal_Application__c = licenseRenewalMap.get(licenseRecord.Id), MUSW__Type__c = Label.ST_Late_Renewal);
                   //charge late renewal fee
                   feesToCreate.add(lateCEFee);
                   
                   Renewal_Application__c renewalToUpdate = new Renewal_Application__c(Id = licenseRenewalMap.get(licenseRecord.Id), Renewal_Status__c = Label.ST_Additional_Fee_Required);
                   renewalsToUpdate.add(renewalToUpdate);
                      
                  } else{
                   
                   MUSW__Fee__c lateCEFee = new MUSW__Fee__c(MUSW__Amount__c = 25, Application_Type__c = licenseRecord.Application_Type__c,
                                                            MUSW__License2__c = licenseRecord.Id, MUSW__Type__c = Label.ST_Late_Renewal);
                   //charge late renewal fee
                   feesToCreate.add(lateCEFee);
                   
                      
                  }
                  
                  
                
            }else if(licenseCEHours < licenseRecord.CE_Hours_per_Cycle__c &&
              licenseRecord.MUSW__Status__c == Label.ST_Late_Renewal &&
                    todaysDate > licenseRecord.Renewal_Cycle_End_Date__c){
					System.debug('batch in else');
                        licenseToUpdate = new MUSW__license2__c(Id = licenseRecord.Id, 
                                                          MUSW__Status__c = Label.ST_Expired);
                   licensesToUpdateList.add(licenseToUpdate);
                
            }   
                   
        }
          System.debug('licensesToUpdateList '+licensesToUpdateList);
          System.debug('feesToCreate '+feesToCreate);
          System.debug('renewalsToUpdate '+renewalsToUpdate);
          if(licensesToUpdateList.size()>0){
              update licensesToUpdateList;
          }
          if(feesToCreate.size()>0){
              insert feesToCreate;
          }  
          if(renewalsToUpdate.size() > 0){
              update renewalsToUpdate;
          }
       
      }

      // Method to be called after the excute
      global void finish(Database.BatchableContext BC) {
      }
}