src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>MUSW__Outstanding_Fee__c</fullName>
        <description>Amount outstanding based on the following formula: (Amount) - (Amended Amount) - (Waived Amount) - (Paid Amount).</description>
        <formula>If(MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c &lt; 0, 0, MUSW__Amount__c - MUSW__Amount_Waived__c - MUSW__Amount_Paid__c - MUSW__Amended_Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>The type of fee. Each type may have a different accounting code.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>DHP</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Staff Hours</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Mileage</fullName>
                </value>
                <value>
                    <fullName>Trust - Prearrangement Funeral Services Deposit</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance (AMR)</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_To_Name__c</fullName>
        <formula>IF(MUSW__Permit2__c != null, MUSW__Permit2__r.Name, 
IF(MUSW__Application2__c != null, MUSW__Application2__r.Name, 
IF(MUSW__License2__c != null, MUSW__License2__r.Name, 
IF(Renewal_Application__c!=null,Renewal_Application__r.Name, 
IF(Fine__c!=null,Fine__r.Name, 
null)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Related To Name</label>
        <type>Text</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LnP_SendToCollectionAgencyReminder.cls
global class LnP_SendToCollectionAgencyReminder implements Schedulable {
    global String [] email = new String[] {'nazbegum@deloitte.com'};
    global void execute(SchedulableContext ctx) {
       // Map<Id,Id> licenseToAttachmentIdMap = new Map<Id,Id>();
        List<MUSW__Fee__c> feeList = [SELECT Id,Name,Related_To_Name__c,MUSW__Outstanding_Fee__c,MUSW__Type__c FROM MUSW__Fee__c WHERE MUSW__Type__c =:'Fine' AND MUSW__Outstanding_Fee__c>0  AND CreatedDate < last_n_days:10];
        system.debug('feeList::'+feeList);
      
        // Send reminder emails
        List<Messaging.SingleEmailMessage> emailList = new list<Messaging.SingleEmailMessage>();
        for(MUSW__Fee__c fee : feeList){
            system.debug('teh fee is' +fee);
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setToAddresses(email);
                message.setSubject('Reminder Notification to Collection Agency For the fees');
                String messageBody = '<html><body>Hello,</body></html>';
                String messageBody1 = '<html><body>The fine is pending for the License:</body></html>'+fee.Related_To_Name__c;
                String messageBody2 = '<html><body>The Outstanidng amount for the fee is:</body></html>'+fee.MUSW__Outstanding_Fee__c;
                message.setHtmlBody(messageBody+''+messageBody1+''+messageBody2);
                //message.setPlainTextBody('The fine is pending for the fee:' +fee.Name);
                //message.setPlainTextBody('The Outstanidng amount for the fee is:' +fee.MUSW__Outstanding_Fee__c);
                emailList.add(message);
            
        }
        system.debug('emailList::'+emailList);
        if(emailList.size() > 0){
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailList);
        }
    }
}