src/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>Fee_amount_for_labor_charge__c</fullName>
        <formula>IF(ISPICKVAL(MUSW__Type__c, &apos;Trust Expense - Staff Hours&apos;), ( $Setup.Trust_Fund_Setting__c.Hour_Rate__c  *  Labor_Hours__c )  + ($Setup.Trust_Fund_Setting__c.Hour_Rate__c  *  (Labor_Minutes__c  / 60)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fee amount for labor charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_amount_for_mileage__c</fullName>
        <formula>IF(ISPICKVAL(MUSW__Type__c, &apos;Trust Expense - Mileage&apos;),Mileage__c  *  $Setup.Trust_Fund_Setting__c.Mileage_Rate__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fee amount for mileage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>An obligation amount (fee) that needs to be paid.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>The type of fee. Each type may have a different accounting code.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fine</fullName>
                </value>
                <value>
                    <fullName>DHP</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Staff Hours</fullName>
                </value>
                <value>
                    <fullName>Trust Expense - Mileage</fullName>
                </value>
                <value>
                    <fullName>Trust - Prearrangement Funeral Services Deposit</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance (AMR)</fullName>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeeTriggerHandler.cls
/**
* Name: FeeTriggerHandler
* Type: Class
* Description: Trigger Handler for MUSW__Fee__c object being called from FeeTrigger
* Date:        Developer/Company                   Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 08/22/2018   Srikanth Kottam/Deloitte          Initial Creation
* 07/10/2019   Chiranth                          Added the code before Insert and before update method (US1818)
**/
public class FeeTriggerHandler implements BGCM.ITriggerHandler{
    public static boolean isTrue  = true;
    public void onAfterDelete() {}
    public void onAfterInsert() {
        afterMethod();
    }
    public void onAfterUndelete() {}
    public void onAfterUpdate() {
        afterMethod();
    }
    public void onBeforeDelete() {}
    public void onBeforeInsert() {
        //Add for the US1812 on 7/11/2019 [Chiranth]
        for(SObject record: trigger.new) {
           MUSW__Fee__c fee = (MUSW__Fee__c)record;
            if(fee.MUSW__type__c == 'Trust Expense - Staff Hours'){
                fee.MUSW__Amount__c = fee.Fee_amount_for_labor_charge__c;
            }else if(fee.MUSW__type__c == 'Trust Expense - Mileage'){
                fee.MUSW__Amount__c = fee.Fee_amount_for_mileage__c; 
            }   
            
         }
         // End of code US1812
    }
    public void onBeforeUndelete() {}
    public void onBeforeUpdate() {
    
        //Add for the US1812 on 7/11/2019 [Chiranth]
         for(SObject record: trigger.new) {
            MUSW__Fee__c fee = (MUSW__Fee__c)record;
            SObject oldrecord = Trigger.oldMap.get(record.Id);
            MUSW__Fee__c oldfee = (MUSW__Fee__c)oldrecord;
            if(fee.MUSW__type__c == 'Trust Expense - Staff Hours' && fee.MUSW__type__c != oldfee.MUSW__type__c){
                fee.MUSW__Amount__c = fee.Fee_amount_for_labor_charge__c;
            }else if(fee.MUSW__type__c == 'Trust Expense - Mileage' && fee.MUSW__type__c != oldfee.MUSW__type__c){
                fee.MUSW__Amount__c = fee.Fee_amount_for_mileage__c; 
            }   
            
         }
         // End of code US1812
    }
    
    public void afterMethod() {
        //This Method is called when already an AccountContact Record exists on an Account and Fee records get Created. This Record will be shared with the community Plus User
        if(userinfo.getName()!='System Integration' && isTrue){
        //FeeUsersharing controller = new FeeUsersharing();
        //controller.FeeSharing_RecordInsert(Trigger.New);
        //End of FeeUsersharing
        isTrue =false;
        //Share the Fee records when the Delegated Admin is the applicant
        //FeeCreatedByDelegate DelegateController = new FeeCreatedByDelegate();
        System.debug('Entered fee trigger');
      //  DelegateController.shareFeeRecords(Trigger.New);
        System.debug('Entered fee trigger again');
        }
    } 
}