src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <description>Facility Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Facility Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DefaultPermitLicensing.cls
/**
* @see SObjectTriggerHandler
* @see BaseValidator
* @see ValidationError
* @author Akosa Okwudiafor*/

public class DefaultPermitLicensing extends BaseValidator {
    
    // constructor
    public DefaultPermitLicensing () {
         System.debug('===> in constructor DefaultPermitLicensing');
    }
    
         /***************************************************************************************************
* @Description :
* @Param       : NA
* @Return      : NA
***************************************************************************************************/
    public override void validate(AllSections sec, SObject newRec, SObject oldRec){
        Musw__Permit2__c l = (Musw__Permit2__c)newRec;
        //Declare three boolean variables. 
        Boolean powtsBusiness =false;
        if(l.Permit_Type__c == Label.PT_POWTS_Petition_for_Variance){
            powtsBusiness = true;
        }
        
        if(powtsBusiness&&l.Facility_Name__c==null)
        {
                  // e.addCompError('Facility_Name__c', 'Please complete all the required fields in the section');
        }
        
    }       
}