src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>for Business Type License</description>
        <label>Business</label>
    </recordTypes>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>for Individual Type License</description>
        <label>Individual22</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PortalAttachmentSection_Test.cls
/* 
*Class Name   : PortalAttachmentSection_Test
* Description  : Testclass for PortalAttachmentSection
* Created By   : Shreya Surabhi
* Created On   : 20/09/2019 
* Modification Log:  
*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
* Developer                    Date                        Description
*------------------------------------------------------------------------------------------------------------------------------------------------------------------------
*
*/
@isTest
public class PortalAttachmentSection_Test{
    
    private static testmethod void testMethod_PortalAttachmentSection(){
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        Account accObj = DOL_TestDataFactory.createAccount(accRecordTypeId);
        
        Id licRecordTypeId = Schema.SObjectType.MUSW__License2__c.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        MUSW__License2__c licenseObj = DOL_TestDataFactory.createLicense(licRecordTypeId,accObj.Id,'Funerals','Embalmer Intern','General Application');
        Document sampleDocument = new Document (Name ='Military Spouse Required Attachment',DeveloperName = 'Military_Spouse_Required_Attachment');
        sampleDocument.FolderId = [select id from folder where name = 'Shared Documents'].id;
        insert sampleDocument;
        
        MUSW__Submission__c subRec = DOL_TestDataFactory.createSubmission(licenseObj.Id);
        subRec.Name = 'Military Spouse Required Attachment';
        subRec.Document_API_Name__c = 'Military_Spouse_Required_Attachment';
        update subRec;
        
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        Attachment attachDoc = new Attachment(Name = 'Test Attachment', Description ='Test Class Data', ParentId=subRec.Id,Body=bodyBlob);
        insert attachDoc;
        PortalAttachmentSection portalObj = new PortalAttachmentSection('Funerals','Embalmer Intern',licenseObj.Id);
    }
}