src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__License_Parcel__c.object
<CustomObject>
    <description>Parcels associated to a License</description>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <description>Lookup to the License.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>License2_Parcels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <description>Lookup to the Parcel.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>License as Property</relationshipLabel>
        <relationshipName>Parcel_License2s</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mailing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To check if the address is Mailing address</description>
        <label>Mailing</label>
        <type>Checkbox</type>
    </fields>
    <label>License Parcel</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Polaris_LicenseParcelTriggerHandler.cls
public with sharing class Polaris_LicenseParcelTriggerHandler {
    private boolean m_isExecuting = false;
    private integer BatchSize = 0;
    public Polaris_LicenseParcelTriggerHandler(boolean isExecuting, integer size)
    {
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    public void OnAfterInsert(list<MUSW__License_Parcel__c> licenseParcelList)
    {
        
        //logic for updating the Parcel feild on license which is captured in LicenseParcel 
        system.debug('Trigger On After Insert ');
        
        Map<Id, MUSW__License2__c> licenseMap = new  Map<Id, MUSW__License2__c>([Select Id, MUSW__Parcel__c from MUSW__License2__c limit 200]) ;
        
        list<MUSW__License2__c> licensetoUpdate = new list<MUSW__License2__c>();
        for(MUSW__License_Parcel__c lp : licenseParcelList){
            if(lp.Mailing__c == true && lp.MUSW__Parcel__c != null && lp.MUSW__License2__c != null){                
                MUSW__License2__c licRec = licenseMap.get(lp.MUSW__License2__c) ;
                licRec.MUSW__Parcel__c = lp.MUSW__Parcel__c;
                licensetoUpdate.add(licRec);
            }
        }
        if(!licensetoUpdate.isEmpty() ){
            update licensetoUpdate;
        }
        
    }
    
    public void OnBeforeInsert(list<MUSW__License_Parcel__c> licenseParcelList)
    {
        system.debug('Trigger On Before Insert ');
    }    
    
    public void OnAfterUpdate( List<MUSW__License_Parcel__c> newlicenseParcelList, List<MUSW__License_Parcel__c> oldlicenseParcelList, 
                              Map<ID, MUSW__License_Parcel__c> newlicenseParcelMap , Map<ID, MUSW__License_Parcel__c> oldlicenseParcelMap ) 
    {
        //logic for updating the Parcel feild on license which is captured in LicenseParcel 
        system.debug('Trigger On After Update ');
        Map<Id, MUSW__License2__c> licenseMap = new  Map<Id, MUSW__License2__c>([Select Id, MUSW__Parcel__c from MUSW__License2__c]) ;
        
        list<MUSW__License2__c> licensetoUpdate = new list<MUSW__License2__c>();
        
        for(MUSW__License_Parcel__c lp : newlicenseParcelList){
            if(lp.Mailing__c == true && lp.MUSW__Parcel__c != null && lp.MUSW__License2__c != null){   
                if((oldlicenseParcelMap.get(lp.Id).MUSW__Parcel__c != lp.MUSW__Parcel__c) || (oldlicenseParcelMap.get(lp.Id).MUSW__License2__c != lp.MUSW__License2__c)){
                    MUSW__License2__c licRec = licenseMap.get(lp.MUSW__License2__c) ;
                    licRec.MUSW__Parcel__c = lp.MUSW__Parcel__c;
                    licensetoUpdate.add(licRec);
                }
                
            }
        }
        if(!licensetoUpdate.isEmpty() ){
            update licensetoUpdate;
        }
        
    }
    
    public void OnBeforeUpdate( List<MUSW__License_Parcel__c> newlicenseParcelList, List<MUSW__License_Parcel__c> oldlicenseParcelList, 
                               Map<ID, MUSW__License_Parcel__c> newlicenseParcelMap , Map<ID, MUSW__License_Parcel__c> oldlicenseParcelMap ) 
    {
        
        system.debug('Trigger On Before Update ');
        
    }
}