src/objects/MUSW__Review__c.object
<CustomObject>
    <description>Tracks the collaborative plan review process and associated documents</description>
    <fields>
        <fullName>MUSW__Completed_DateTime__c</fullName>
        <description>The date and time when review was completed.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>When Review was completed</inlineHelpText>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Review Start Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Review</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ReviewCompletionTimeComputation_test.cls
@isTest
public class ReviewCompletionTimeComputation_test {
    @isTest
    public static void testMethod1(){
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        system.runAs(thisUser){
            Holiday h = new Holiday();
            h.ActivityDate = system.today()+1;
            h.name = 'test holiday';
            insert h;
        }
        
        Id reviewRT = Schema.SObjectType.MUSW__Review__c.getRecordTypeInfosByName().get('License Review').getRecordTypeId();
        MUSW__Review__c rev = new MUSW__Review__c();
        rev.RecordTypeId = reviewRT;
        rev.Start_Date__c = system.now();
        rev.MUSW__Completed_DateTime__c = system.now()+10;
        insert rev;
        ReviewCompletionTimeComputation rc = new ReviewCompletionTimeComputation();
        
        
        Decimal dec = rc.ReviewCompletionTimeComputation(rev);
        
    }
    
}