src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Amount__c</fullName>
        <description>The total Amount that needs to be collected.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Validation_number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Validation number</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Deposits</relationshipLabel>
        <relationshipName>Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Effective_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Paid_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Paid By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Receipts (Paid By)</relationshipLabel>
        <relationshipName>Receipts_Paid_by</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Envelope</label>
        <referenceTo>Customer_Envelope__c</referenceTo>
        <relationshipLabel>Receipts</relationshipLabel>
        <relationshipName>Receipts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Polaris_voucherAsPayment.cls
global class Polaris_voucherAsPayment implements Database.batchable<SObject>, Database.Stateful {
    
    
    public Database.QueryLocator start(Database.BatchableContext objContext) {
        
        String query = DOL_AppConstants.NULL_EMPTY_STRING + 'SELECT Id, Name, MUSW__Amount_Tendered__c,MUSW__Paid_By__c,MUSW__Effective_Date__c, Validation_number__c FROM MUSW__Receipt__c where Validation_number__c !=null';
        return Database.getQueryLocator(query);
        
    }
    
    
    public void execute(Database.BatchableContext objContext, List<MUSW__Receipt__c> receipts) {
        
        
        // Map<List<MUSW__Receipt__c>, List<MUSW__Deposit__c>=new  Map<List<MUSW__Receipt__c>, List<MUSW__Deposit__c>(); 
     //   system.debug('hello');
     //   system.debug('the list of receipt records:' +receipts.size());
        List<MUSW__Deposit__c> dep=depositRecords();
      // system.debug('thre dep are' +dep.size());
        BGBK.Payable[] payables = new BGBK.Payable[]{};
            for (MUSW__Deposit__c deposit : dep){              
                payables.add(new BGBK.Payable(deposit, deposit.Amount__c));               
            }
        
        Map<MUSW__Receipt__c, Decimal> receiptMap = new Map<MUSW__Receipt__c, Decimal>();
        for(MUSW__Receipt__c rec : receipts){
            receiptMap.put(rec, rec.MUSW__Amount_Tendered__c);
        }
        
        DateTime myDateTime = DateTime.newInstance(2000, 7, 7, 7, 8, 12);
        BGBK.PaymentService paymentServiceObj = new BGBK.PaymentService();
        paymentServiceObj.processPayment(payables, receiptMap,null,myDateTime);
        
    }
    
    
    global void finish(Database.BatchableContext objBatchableContext) {
        
    }
    
    public static list<MUSW__Deposit__c> depositRecords(){
        List<MUSW__Deposit__c> deposits=[SELECT Id, Name, MUSW__Amount__c, Amount__c,Validation_number__c FROM MUSW__Deposit__c where Validation_number__c!=null];
        return deposits;
    }
    
}