src/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated project for permits that need to aggregated</description>
        <label>Project</label>
        <referenceTo>MUSW__Project2__c</referenceTo>
        <relationshipLabel>Permits</relationshipLabel>
        <relationshipName>Permit2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permit_Type__c</fullName>
        <description>This refers to the permit type being applied for as defined by the program area</description>
        <label>Permit Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Program_Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Permit_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Plan_Review__c</fullName>
        <label>Type of Plan Review</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Plan_Review</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Project2__c.object
<CustomObject>
    <description>Project container</description>
    <fields>
        <fullName>MUSW__Project2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MUSW__Project2__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Project2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Type_of_Plan_Review.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Public Health Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Priority</fullName>
    </customValue>
    <description>Type of Plan Review</description>
    <masterLabel>Type of Plan Review</masterLabel>
</GlobalValueSet>

src/classes/POWTSGeneralValidator.cls
/**
* @see POWTSGeneralValidator
* @see BaseValidator
* @see ValidationError
* @author Akosa Okwudiafor*/

public class POWTSGeneralValidator extends BaseValidator {
    
    // constructor
    public POWTSGeneralValidator () {
      //  System.debug('===> in constructor POWTSGeneralValidator');
    }
    
    /***************************************************************************************************
* @Description :
* @Param       : NA
* @Return      : NA
***************************************************************************************************/
    public override void validate(AllSections sec, SObject newRec, SObject oldRec){
        Musw__Permit2__c l = (Musw__Permit2__c)newRec;
        /*if(l.Type_of_Plan_Review__c==null&&l.Permit_Type__c==Label.PT_POWTS_Component_Manual_Review)
        {
            e.addCompError('Type_of_Plan_Review__c', 'Please enter the Type of Plan Review');
        }*/
        if(l.MUSW__Project2__c==null&&l.Permit_Type__c!=Label.PT_POWTS_Consultation&&l.Permit_Type__c!=Label.PT_POWTS_Sanitary_Permit&&L.Permit_Type__c!=Label.PT_POWTS_Component_Manual_Review)
        {
                 e.addCompError('ProjectInformationComponent', 'You must have one site.');
        }
    }       
}