src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>This is being used instead of MUSW__Type__c as MUSW__Type__c is a managed field and cannot be changed to be dependent on a global picklist. This refers to the credential type being applied for</description>
        <label>License Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Background_Question_Field_API_Name__c</fullName>
        <description>Field to store field API name for background question</description>
        <label>Background Question Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>List of license types</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates submission list entries that are always required and will be defaulted to the Portal.</description>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Expected_Answer__c</fullName>
        <description>Expected Answer for the question based on which submission list will be generated</description>
        <label>Expected Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Question based on which submission list record will be created</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Master Submission Lists</relationshipLabel>
        <relationshipName>Master_Submission_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <description>Submission list record show for</description>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Application_Method__c</fullName>
        <description>This refers to the application method being applied for- General Application, Examination, etc.</description>
        <label>Application Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Application_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Profession</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Various credential types available under a functional area and division</description>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique record identifier</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Show_For__c</fullName>
        <label>Show For</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Show_For</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Renewal_Application__c.object
<CustomObject>
    <description>This is the object where permits and licenses can be renewed.</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential_Type__c</fullName>
        <description>Credential Type</description>
        <label>Credential Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This field shows what credential type is being renewed/reinstatement</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id of the record</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the license that is being renewed.</description>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Renewal &amp; Reinstatement Applications</relationshipLabel>
        <relationshipName>Renewal_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Reinstatement_Type__c</fullName>
        <description>Type of reinstatement.</description>
        <label>Renewal Reinstatement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Reinstatement</fullName>
                </value>
                <value>
                    <fullName>Renewal PTO</fullName>
                </value>
                <value>
                    <fullName>Renewal Plan Review</fullName>
                </value>
                <value>
                    <fullName>ReinstatementPTO</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPTO</label>
                </value>
                <value>
                    <fullName>ReinstatementPlanReview</fullName>
                    <isActive>false</isActive>
                    <label>ReinstatementPlanReview</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Renewal &amp; Reinstatement Application</label>
    <nameField>
        <displayFormat>RNW-{0000}</displayFormat>
        <label>Renewal &amp; Reinstatement Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/Credential_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist In Training</fullName>
        <label>Geologist in Training</label>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Crematory</fullName>
    </customValue>
    <customValue>
        <fullName>Cremated Remains Disposition Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <description>This refers to the credential type being applied for</description>
    <masterLabel>Credential Type</masterLabel>
</GlobalValueSet>

src/globalValueSets/Show_For.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Answer</fullName>
    </customValue>
    <customValue>
        <fullName>Credential</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Credential Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Permit</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Renewal</fullName>
    </customValue>
    <customValue>
        <fullName>Permit Reinstatement</fullName>
    </customValue>
    <customValue>
        <fullName>Service Request</fullName>
    </customValue>
    <customValue>
        <fullName>License</fullName>
        <default>true</default>
        <label>License</label>
    </customValue>
    <customValue>
        <fullName>Renewal</fullName>
        <isActive>false</isActive>
        <label>Renewal</label>
    </customValue>
    <customValue>
        <fullName>Reinstatement</fullName>
        <isActive>false</isActive>
        <label>Reinstatement</label>
    </customValue>
    <description>Allows customizing what item to show for license, renewal, reinstatement, etc.</description>
    <masterLabel>Show For</masterLabel>
</GlobalValueSet>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

src/classes/RenewalSubmissionTriggerHandler.cls
/**
* Name: RenewalSubmissionTriggerHandler
* Type: Class
* Description: Trigger Handler for Renewals on MUSW__License2__c
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 08/06/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/
public with sharing class RenewalSubmissionTriggerHandler {
    public static void updateSubmissionRecords(Map<Id,Renewal_Application__c> newLicenseRenewalMap){
        //System.debug('in RenewalSubmissionTriggerHandler=>'+newLicenseRenewalMap);
        String renewalOrReinstatement = '';
        String showFor = '';
        String credential = '';
        String credentialType = '';
        String applicationMethod ='';
        Set<String> credentialList = new Set<String>();
       Set<String> applicationMethodSet = new Set<String>();
       for(Renewal_Application__c renewalApp: newLicenseRenewalMap.values())
        {
            renewalOrReinstatement = renewalApp.Renewal_Reinstatement_Type__c;
            if(renewalOrReinstatement == 'Renewal'){
                showFor = 'Credential Renewal';
            }else if(renewalOrReinstatement == 'Reinstatement'){
                showFor = 'Credential Reinstatement';
            }
            credential = renewalApp.Credential__c;
            credentialType = renewalApp.Credential_Type__c;
            //applicationMethod = renewalApp.Application_Method__c;
            List<Renewal_Application__C> tempcredList = [select id, license__c, license__r.credential__C, license__r.Application_Method__c from renewal_application__C where Id=:renewalApp.Id];   
           for(Renewal_Application__C a:tempcredList ){
               credentialList.add(a.license__r.credential__c);
               applicationMethodSet.add(a.license__r.Application_Method__c);
           }
            
        }
        ////System.debug('renewalOrReinstatement :'+renewalOrReinstatement);
        ////System.debug('showFor :'+showFor);
        ////System.debug('credential :'+credential);
        ////System.debug('credentialType :'+credential);
        
        
        /***************************************************************************************************
        * @Description : Method to update default sumission records for Renewals on the Renewal Application Object
        * @Param       : Map<Id,Renewal_Application__c> newLicenseRenewalMap
        * @Return      : NA
        ****************************************************************************************************/
        //Creating a map of license type and corresponding submission list.
        Map<String, List<MUSW__Master_Submission_List__c>> typeToSubmissionMap = new Map<String,List<MUSW__Master_Submission_List__c>>();
        ////System.debug('typeToSubmissionMap>>'+typeToSubmissionMap);
        
        for(MUSW__Master_Submission_List__c masterSubmission:[SELECT Id, External_id__c, Name, Background_Question_Field_API_Name__c, Question__c,Expected_Answer__c,
                                                                    Description_Long__c, Application_Type__c, Credential_Type__c, Credential__c, Show_For__c,
                                                                    Default__c, Submission_Type__c, Document_API_Name__c, BG_File_Location_Type__c
                                                              FROM MUSW__Master_Submission_List__c 
                                                              WHERE Active__c = TRUE 
                                                              AND Object__c='Renewal_Application__c' 
                                                              AND Show_For__c includes (:showFor)                                                              
                                                              AND Credential__c IN :credentialList
                                                              //AND Credential_Type__c = :credentialType
                                                              AND Application_Method__c IN :applicationMethodSet
                                                              ]){
            //System.debug('masterSubmission==>'+masterSubmission);
            List<MUSW__Master_Submission_List__c> tempSubmissionList = new List<MUSW__Master_Submission_List__c> ();
            if(typeToSubmissionMap.containsKey(masterSubmission.Credential__c)){
                tempSubmissionList = typeToSubmissionMap.get(masterSubmission.Credential__c);
            }
            
            tempSubmissionList.add(masterSubmission);
            ////System.debug('tempSubmissionList>>'+tempSubmissionList);
            typeToSubmissionMap.put(masterSubmission.Credential__c, tempSubmissionList);
            ////System.debug('typeToSubmissionMap>>'+typeToSubmissionMap);
                
        }
        Set<String> renewalFieldSet = Schema.SObjectType.Renewal_Application__c.fields.getMap().keyset();
        List<MUSW__Submission__c> submissionUpsertList = new List<MUSW__Submission__c>();
        List<MUSW__Submission__c> submissionDeleteList = new List<MUSW__Submission__c>();
        
        for(Renewal_Application__c licenseRenewal:[Select id,(Select Id,Name,LicenseQuestionKey__c FROM Submissions__r) FROM Renewal_Application__c WHERE Id=:newLicenseRenewalMap.keyset() and (Renewal_Reinstatement_Type__c = :renewalOrReinstatement)]){
            ////System.debug('licenseRenewal==>'+licenseRenewal);
            
            //Getting new license instance from Trigger.newMap
            Renewal_Application__c newLincenseRenewal = newLicenseRenewalMap.get(licenseRenewal.Id);
            
            //Creating a map of existing submission records
            Map<String,MUSW__Submission__c> keyToSumissionMap = new Map<String,MUSW__Submission__c>();
            for(MUSW__Submission__c submission: licenseRenewal.Submissions__r){
                if(submission.LicenseQuestionKey__c != null){
                    keyToSumissionMap.put(submission.LicenseQuestionKey__c,submission);
                }
            }
            //System.debug(typeToSubmissionMap.containsKey(newLincenseRenewal.Credential__c));
            //Creating submissions based on License Type
            if(typeToSubmissionMap.containsKey(newLincenseRenewal.Credential__c)){
                ////System.debug('Entering 66');
                for(MUSW__Master_Submission_List__c masterSubmission:typeToSubmissionMap.get(newLincenseRenewal.Credential__c)){
                    String licenseSubmissionComboKey = String.valueOf(newLincenseRenewal.Id)+String.valueOf(masterSubmission.Id);
                    
                    if(masterSubmission.Default__c){
                        ////System.debug('entering 71');
                        ////System.debug('key++'+keyToSumissionMap);
                        ////System.debug(licenseSubmissionComboKey);
                        if(!keyToSumissionMap.containsKey(licenseSubmissionComboKey)){
                            ////System.debug(masterSubmission.Show_For__c);
                            ////System.debug(masterSubmission.Show_For__c.contains(showFor));
                            if(masterSubmission.Show_For__c != null && (masterSubmission.Show_For__c.contains(showFor)))
                            {
                                ////System.debug('entering here!');
                                MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name=masterSubmission.Name,Description_Long__c=masterSubmission.Description_Long__c,
                                                                                        LicenseQuestionKey__c = licenseSubmissionComboKey,License_Renewal__c = newLincenseRenewal.Id,
                                                                                        Type__c =(masterSubmission.Submission_Type__c =='Hardcopy: To be Mailed'? 'Hardcopy: To be Mailed' : 'Softcopy: To be Uploaded'),
                                                                                        Document_API_Name__c = masterSubmission.Document_API_Name__c, 
                                                                                        Master_Submission_List__c=masterSubmission.Id,MUSW__Required__c=masterSubmission.Default__c,
                                                                                        MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
                                
                                if(newSubmission.MUSW__BG_File_Location_Type__c == null || newSubmission.MUSW__BG_File_Location_Type__c == '') newSubmission.MUSW__BG_File_Location_Type__c = 'Salesforce';
                                submissionUpsertList.add(newSubmission);
                            }
                        }
                    }
                    
                    else if(masterSubmission.Background_Question_Field_API_Name__c != null && renewalFieldSet.contains(masterSubmission.Background_Question_Field_API_Name__c.toLowerCase()))
                    {
                        ////System.debug('need to enter here>>');
                        String questionAnswer;
                        try{
                            questionAnswer= (String)newLincenseRenewal.get(masterSubmission.Background_Question_Field_API_Name__c);
                        }catch(Exception ex){
                            //System.debug('ERROR - Please update Question-Submission Mapping cusotm setting with correct field API names'+ex);
                        }
                        
                        //If answer is 'Yes' new submission is created
                        if(questionAnswer!= null && questionAnswer.equalsIgnoreCase('yes')){ 
                            if(!keyToSumissionMap.containsKey(licenseSubmissionComboKey)){
                                MUSW__Submission__c newSubmission = new MUSW__Submission__c(Name=masterSubmission.Name,Description_Long__c=masterSubmission.Description_Long__c,
                                                                                            LicenseQuestionKey__c = licenseSubmissionComboKey,MUSW__License2__c = newLincenseRenewal.Id,
                                                                                            Type__c =(masterSubmission.Submission_Type__c =='Hardcopy: To be Mailed'? 'Hardcopy: To be Mailed' : 'Softcopy: To be Uploaded'),
                                                                                            Master_Submission_List__c=masterSubmission.Id,MUSW__Required__c=masterSubmission.Default__c,
                                                                                            Document_API_Name__c = masterSubmission.Document_API_Name__c, License_Renewal__c = newLincenseRenewal.Id,
                                                                                            MUSW__BG_File_Location_Type__c = masterSubmission.BG_File_Location_Type__c);
                                
                                if(newSubmission.MUSW__BG_File_Location_Type__c == null || newSubmission.MUSW__BG_File_Location_Type__c == '') newSubmission.MUSW__BG_File_Location_Type__c = 'Salesforce';
                                submissionUpsertList.add(newSubmission);
                            }
                        }else if((questionAnswer == null || questionAnswer.equalsIgnoreCase('no')) && keyToSumissionMap.containsKey(licenseSubmissionComboKey)){
                            //If answer is 'No' and there is an existing submission, it is deleted
                            MUSW__Submission__c oldSubmission = keyToSumissionMap.get(licenseSubmissionComboKey);
                            submissionDeleteList.add(oldSubmission);
                        }
                    }
                }
            }
        }
        
       try{
            ////System.debug('submissionUpsertList>>'+submissionUpsertList);
            ////System.debug('submissionDeleteList>>'+submissionDeleteList);
            upsert submissionUpsertList LicenseQuestionKey__c;
            ////System.debug(LicenseQuestionKey__c);
            ////System.debug(submissionUpsertList );
            delete submissionDeleteList;
        }catch(Exception ex){
            //System.debug(ex);
        }
    }
}