src/objects/MUSW__Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>wadol_Program_Type__c</fullName>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Deposit</label>
    <nameField>
        <label>Deposit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Receipt__c.object
<CustomObject>
    <description>Payments Collected</description>
    <fields>
        <fullName>MUSW__Amount_Tendered__c</fullName>
        <description>Amount tendered during the payment transaction.</description>
        <label>Amount</label>
        <precision>13</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MUSW__Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Lockbox</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - Counter</fullName>
                </value>
                <value>
                    <fullName>Check/Cashier&apos;s Check</fullName>
                </value>
                <value>
                    <fullName>Money Order</fullName>
                </value>
                <value>
                    <fullName>Inter-agency Payment</fullName>
                </value>
                <value>
                    <fullName>Voucher</fullName>
                </value>
                <value>
                    <fullName>Misc - Unknown</fullName>
                </value>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>NCR - cash</fullName>
                </value>
                <value>
                    <fullName>NCR - check</fullName>
                </value>
                <value>
                    <fullName>Reapplied Payment</fullName>
                </value>
                <value>
                    <fullName>Overshort</fullName>
                </value>
                <value>
                    <fullName>Vitalcheck - DHP</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LnP_ProgramTypeTest.cls
@isTest
public class LnP_ProgramTypeTest {

     @testSetup
    public static void setupMethod(){
        //creating Deposit
        MUSW__Deposit__c deposit = new MUSW__Deposit__c(Name = DOL_AppConstants.NULL_EMPTY_STRING + 'System Number');
        deposit.Amount__c = 100.00;
        deposit.wadol_Program_Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Misc Payments';
        insert deposit;
        
        MUSW__Receipt__c receipt = new MUSW__Receipt__c();
        receipt.MUSW__Amount_Tendered__c = 100.00;
        receipt.MUSW__Payment_Method__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Cash';
        insert receipt;
        }
        
    public static void testMethod1(){
        
        list<MUSW__Deposit__c> depLst = [Select Id, Amount__c, wadol_Program_Type__c from MUSW__Deposit__c];
        list<MUSW__Receipt__c> recLst = [Select Id,MUSW__Amount_Tendered__c,MUSW__Payment_Method__c from MUSW__Receipt__c];
       // system.debug('depLst : '+depLst);
        //system.debug('recLst : '+recLst);
        
        Test.startTest();
     //   LnP_ProgramType.getDependency(objDetail, contrfieldApiName, depfieldApiName);
             LnP_ProgramType.getDefaultProgramType();
             LnP_ProgramType.getPayment();
             LnP_ProgramType.getProgramType();
             LnP_ProgramType.getFormNumber();
             LnP_ProgramType.getDepositInfo();
            // LnP_ProgramType.saveReciept(recList);
             LnP_ProgramType.getObjViews();
           LnP_ProgramType.saveReciptRecords(recLst[0]);
            LnP_ProgramType.updateRecieptRec(recLst[0]);
             LnP_ProgramType.saveDeposit_Receipt_Records(depLst[0]);
             LnP_ProgramType.updateDepositRec(depLst[0]);
           //  LnP_ProgramType.updateEnvelopRec(programType, recRecLstArr, depRecLstArr, customerEnvelopeRec, parRecordId);
             LnP_ProgramType.getValidationNumberInfo();
        Test.stopTest();
    }
}