src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Additional_Address__c</fullName>
        <description>Additional address field to store additional address associated with a credential, ex-branch office address, co-owner mailing address, etc.</description>
        <label>Additional Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Body_Length_with_hitch__c</fullName>
        <description>to store body length with hitch</description>
        <label>Body Length with Hitch (in feet)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Body_Width_with_hitch__c</fullName>
        <description>to store body width with hitch</description>
        <label>Body Width with Hitch (in feet)</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Facilities_will_be_ready__c</fullName>
        <description>To store date the facility will be ready</description>
        <label>Date Facilities will be ready</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Makes_of_Homes_to_be_Sold__c</fullName>
        <description>To store Makes of Homes to be Sold</description>
        <label>Makes of Homes to be Sold</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufactured_Homes_Serial_Number__c</fullName>
        <description>Manufactured Homes Serial Number</description>
        <label>Manufactured Homes Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <description>community model year</description>
        <label>Manufactured Home Model Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax_Seller_Permit_Number__c</fullName>
        <description>To store sales tax seller permit no</description>
        <label>Sales Tax Seller Permit Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Name__c</fullName>
        <description>to store trade name</description>
        <label>Trade Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/classes/ManufacturedHomesValidator.cls
/**
* User Story: 
* Class Name: ManufacturedHomesValidator
* Test Class Name: 
* Description: This class represents ManufacturedHomesValidator to be performed on the MUSW__License2__c object
*
* Date:        Developer/Company                    Description
* ---------------------------------------------------------------------------------------------------------------------------------------- *
* 09/14/2018   Sharad Maheshwari/Deloitte           Initial Creation
**/
public class ManufacturedHomesValidator extends BaseValidator {

    // constructor
    public ManufacturedHomesValidator() {
        System.debug('===> in constructor ManufacturedHomesValidator');
    }

    public override void validate(AllSections sec, SObject newRec, SObject oldRec ){ 
       MUSW__License2__c license = (MUSW__License2__c)newRec;
        
        if(license.credential__c == Label.CR_Manufactured_Homes_Dealer){
            if(license.Trade_Name__c == null || license.Trade_Name__c == ''){
                e.addError ('Trade_Name__c', 'You must specify the Trade Name');
            }
            if(license.Sales_Tax_Seller_Permit_Number__c == null || license.Sales_Tax_Seller_Permit_Number__c == ''){
                e.addError ('Sales_Tax_Seller_Permit_Number__c', 'You must specify Sales Tax Seller Permit Number');
            }
            if(license.Makes_of_Homes_to_be_Sold__c == null || license.Makes_of_Homes_to_be_Sold__c == ''){
                e.addError ('Makes_of_Homes_to_be_Sold__c', 'You must specify the Makes of Homes to be Sold');
            }
            if(license.Date_Facilities_will_be_ready__c == null){
                e.addError ('Date_Facilities_will_be_ready__c', 'You must specify the Date Facilities will be ready');
            }
            /*if(license.Additional_Address__c == null || license.Additional_Address__c == ''){
                e.addError ('Additional_Address__c', 'You must specify Branch Office Address');
            }
            if(license == null || license == ''){
                e.addError ('', 'You must specify ');
            }*/
        }else if(license.credential__c == Label.CR_Manufactured_Homes_Certificate_of_Title){
            if(license.Manufactured_Homes_Serial_Number__c == null || license.Manufactured_Homes_Serial_Number__c == ''){
                e.addError ('Manufactured_Homes_Serial_Number__c', 'You must specify Manufactured Home (Serial) Identification Number');
            }
            if(license.Model_Year__c == null){
                e.addError ('Model_Year__c', 'You must specify the Model Year');
            }
            /*if(license.Trade_Name__c == null || license.Trade_Name__c == ''){
                e.addError ('Trade_Name__c', 'You must specify the Trade Name');
            }*/
            if(license.Body_Length_with_hitch__c == null || license.Body_Length_with_hitch__c == 0.0){
                e.addError ('Body_Length_with_hitch__c', 'You must specify the Body Length (with hitch)');
            }
            if(license.Body_Width_with_hitch__c == null || license.Body_Width_with_hitch__c == 0.0){
                e.addError ('Body_Width_with_hitch__c', 'You must specify the Body Width (with hitch)');
            }
           /* if(license.Additional_Address__c == null || license.Additional_Address__c == ''){
                e.addError ('Additional_Address__c', 'You must specify the Address for Location of Manufactured Home');
            }
            if(license == null || license == ''){
                e.addError ('', 'You must specify the ');
            }*/
        }        
         
          
  }     
 }