src/objects/MUSW__Inspection__c.object
<CustomObject>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <fields>
        <fullName>Close_Inspection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Inspection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed_DateTime__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Inspection_Chain_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inspection Chain Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Letter_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Letter Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Closed_DateTime__c</fullName>
        <description>Optional. This can be used if inspection metrics are measured in hours rather than days.</description>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MUSW__Completed_Date__c</fullName>
        <description>Date the inspection was completed.</description>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__On_Itinerary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true on the itinerary page when an inspection is added to the itinerary and saved. This should be used in the creation of Views for the Itinerary page.</description>
        <label>On Itinerary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Previous_Inspection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is commonly used in configuration. If a reinspection is created via a DRE rule, it is a best practice to fill in the parent inspection lookup.</description>
        <label>Previous Inspection</label>
        <referenceTo>MUSW__Inspection__c</referenceTo>
        <relationshipLabel>Re-Inspections</relationshipLabel>
        <relationshipName>Next_Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Priority__c</fullName>
        <description>Can be used for sort order in views and reports.  Not used in any default configuration.</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3 High</fullName>
                </value>
                <value>
                    <fullName>2 Normal</fullName>
                    <default>true</default>
                    <label>2 Normal</label>
                </value>
                <value>
                    <fullName>1 Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Scheduled_Start_Date__c</fullName>
        <description>Date the inspection is scheduled for (usually before or by due date if not late). Used for views on the itinerary page.</description>
        <label>Scheduled Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status or outcome of the inspection.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>In Violation</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Scope of the inspection activity to be done.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Reinspection</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>High Risk</fullName>
                </value>
                <value>
                    <fullName>Follow-up Inspection</fullName>
                </value>
                <value>
                    <fullName>Check Rides</fullName>
                </value>
                <value>
                    <fullName>Exam Observation</fullName>
                </value>
                <value>
                    <fullName>Record</fullName>
                </value>
                <value>
                    <fullName>Skills Observation</fullName>
                </value>
                <value>
                    <fullName>Classroom Observation</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Examiner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pass_Fail__c</fullName>
        <formula>CASE( MUSW__Status__c, 

&quot;Failed&quot;,&quot;Failed&quot;, 
&quot;Passed&quot;,&quot;Passed&quot;, 
&quot;Stop Work&quot;,&quot;Failed&quot;, 
&quot;Closed&quot;,&quot;Passed&quot;, 

&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pass/Fail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_DateTime__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InspectionUpdateParentTriggerTest.cls
@isTest(SeeAllData = true)
public class InspectionUpdateParentTriggerTest{


    public static testMethod void testCreateReinspectionFromIV(){
    
        MUSW__Inspection__c preIns = new MUSW__Inspection__c();
                
        preIns.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'asfsdafsda';
        preIns.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Mechanical';
        preIns.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        preIns.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'failed';
        preIns.Close_Inspection__c = false;
        preIns.MUSW__On_Itinerary__c = false;
        preIns.Letter_Generated__c = false;
        preIns.MUSW__Scheduled_Start_Date__c = date.today();
        preIns.Requested_DateTime__c = date.today();
        preIns.Completed_DateTime__c = date.today();
        preIns.MUSW__Completed_Date__c = date.today();
        preIns.MUSW__Closed_DateTime__c = date.today();
        preIns.Inspection_Chain_Closed__c = false;
        preIns.MUSW__Previous_Inspection__c = null;
        insert preIns;   
        
             

        MUSW__Inspection__c ins = new MUSW__Inspection__c();
                
        ins.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'hot123';
        ins.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Mechanical';
        ins.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        ins.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'failed';
        ins.Close_Inspection__c = false;
        ins.MUSW__On_Itinerary__c = false;
        ins.Letter_Generated__c = false;
        ins.MUSW__Scheduled_Start_Date__c = null;
        ins.Requested_DateTime__c = date.today();
        ins.Completed_DateTime__c = date.today();
        ins.MUSW__Completed_Date__c = date.today();
        ins.MUSW__Closed_DateTime__c = date.today();
        ins.Inspection_Chain_Closed__c = false;
        ins.MUSW__Previous_Inspection__c = preIns.id;
        
        
        insert ins;


        MUSW__Inspection__c nextIns = new MUSW__Inspection__c();
                
        nextIns.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'tgrahgdsadfsdg';
        nextIns.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Mechanical';
        nextIns.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        nextIns.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Pending';
        nextIns.Close_Inspection__c = false;
        nextIns.MUSW__On_Itinerary__c = false;
        nextIns.Letter_Generated__c = false;
        nextIns.MUSW__Scheduled_Start_Date__c = null;
        nextIns.Requested_DateTime__c = null;
        nextIns.Completed_DateTime__c = null;
        nextIns.MUSW__Completed_Date__c = null;
        nextIns.MUSW__Closed_DateTime__c = null;
        nextIns.Inspection_Chain_Closed__c = false;
        nextIns.MUSW__Previous_Inspection__c = ins.id;
        //ins.Pass_Fail__c == 'Passed';
        
        insert nextIns;
        nextIns.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'passed';
        nextIns.Inspection_Chain_Closed__c = true;
        update nextIns;
        
        ins.Inspection_Chain_Closed__c = true;
        
        update ins;
        
        preIns.Inspection_Chain_Closed__c = true;
        
        update preIns;
        
        
        /*
        

        MUSW__Inspection__c updateIns = [select id, Name, MUSW__Type__c, MUSW__Priority__c, MUSW__Status__c, Close_Inspection__c, 
                                            MUSW__On_Itinerary__c, Letter_Generated__c, MUSW__Scheduled_Start_Date__c, Requested_DateTime__c , 
                                            Completed_DateTime__c, MUSW__Closed_DateTime__c,  Inspection_Chain_Closed__c, MUSW__Previous_Inspection__c  from MUSW__Inspection__c  where Name = DOL_AppConstants.NULL_EMPTY_STRING + 'hot123' limit 1 ];


        updateIns.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'abc';
        nextIns.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Passed';
        update updateIns ;
       
       MUSW__Inspection__c updatePreIns = [select id, Name, MUSW__Type__c, MUSW__Priority__c, MUSW__Status__c, Close_Inspection__c, 
                                            MUSW__On_Itinerary__c, Letter_Generated__c, MUSW__Scheduled_Start_Date__c, Requested_DateTime__c , 
                                            Completed_DateTime__c, MUSW__Closed_DateTime__c,  Inspection_Chain_Closed__c, MUSW__Previous_Inspection__c  from MUSW__Inspection__c  where Name = DOL_AppConstants.NULL_EMPTY_STRING + 'asfsdafsda' limit 1 ];

        
        
        update updatePreIns ;
        
    */
    }  


}