src/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>CE_Hours__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Roll up summary field from class to show the total of hours</description>
        <label>CE Hours</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CE_Hours_per_Cycle__c</fullName>
        <formula>CASE(Credential__c, &quot;UDC HVAC Inspector&quot;, 24, &quot;UDC Plumbing Inspector&quot;, 24, &quot;UDC Electrical Inspector&quot;, 24, &quot;UDC Construction Inspector&quot;, 24, &quot;Soil Tester&quot;, 12, &quot;Manufactured Homes Installer&quot;, 12, &quot;Dwelling Contractor Qualifier&quot;, 12,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CE Hours per Cycle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Late_Renewal_Eligible__c</fullName>
        <description>Formula to determine Late Renewal Eligibility</description>
        <formula>IF((TODAY()&gt;MUSW__Expiration_Date__c &amp;&amp; TODAY()&lt;= Late_Renewal_Eligible_End_Date__c &amp;&amp; (ISPICKVAL(MUSW__Status__c, &apos;Expired&apos;) ||  ISPICKVAL(MUSW__Status__c, &apos;Inactive&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Late Renewal&apos;) || ISPICKVAL(MUSW__Status__c, &apos;Hold&apos;))), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Late Renewal Eligible?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Late_Renewal_Eligible_End_Date__c</fullName>
        <description>Date until which a credential is eligible for late renewal - based on expiration date and logic from Renewal_Reinstatement_Eligibility__c</description>
        <inlineHelpText>Date until which a credential is eligible for late renewal - based on expiration date and logic from Renewal_Reinstatement_Eligibility__c</inlineHelpText>
        <label>Late Renewal Eligible End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Expiration_Date__c</fullName>
        <description>Date when the license is effective to</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Action</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Pending Additional Qualifications</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>In-Review</fullName>
                </value>
                <value>
                    <fullName>Unlicensed Activity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Cycle_End_Date__c</fullName>
        <description>To calculate the renewal cycle duration- Multiplying the renewal window by 12 as it is in years</description>
        <formula>ADDMONTHS(MUSW__Expiration_Date__c,Renewal_Window__c*12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Cycle End Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/HandleIncompleteRenewalsSchedulerTest.cls
@istest
public class HandleIncompleteRenewalsSchedulerTest {
    
	 public static testmethod void  testschedule() {
        Test.StartTest();
        List<sObject> ls = Test.loadData(MUSW__License2__c.sObjectType,'credentialsWithExpirationDate'); 
         System.assert(ls.size() == 4);
         musw__license2__c license2 = (musw__license2__c)ls[1];
         license2.MUSW__Status__c = 'Active';
         license2.musw__expiration_date__c = date.parse('11/28/2018');
         license2.CE_Hours__c = 5;         
		update license2;         
         System.debug('license2.Is_Late_Renewal_Eligible__c ' + license2.Is_Late_Renewal_Eligible__c);
         System.debug('license2.CE_Hours_per_Cycle__c ' + license2.CE_Hours_per_Cycle__c);
         System.debug('license2.MUSW__Expiration_Date__c ' + license2.MUSW__Expiration_Date__c);
         System.debug('license2.Renewal_Cycle_End_Date__c ' + license2.Renewal_Cycle_End_Date__c);
        HandleIncompleteRenewalsScheduler sh1 = new HandleIncompleteRenewalsScheduler();      
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, sh1);
        Test.stopTest();
    }
    
    public static testmethod void  testschedule2() {
        Test.StartTest();
        List<sObject> ls = Test.loadData(MUSW__License2__c.sObjectType,'credentialsWithExpirationDate'); 
         System.assert(ls.size() == 4);
         musw__license2__c license1 = (musw__license2__c)ls[2];
		 license1.musw__status__c = 'Expired';
         license1.musw__expiration_date__c = date.parse('11/25/2018');
         license1.Late_Renewal_Eligible_End_Date__c = date.parse('12/25/2018');
         license1.CE_Hours__c = 5;
        	
		update license1;   
        
        System.debug('license1.Is_Late_Renewal_Eligible__c ' + license1.Is_Late_Renewal_Eligible__c);
         System.debug('license1.CE_Hours_per_Cycle__c ' + license1.CE_Hours_per_Cycle__c);
         System.debug('license1.MUSW__Expiration_Date__c ' + license1.MUSW__Expiration_Date__c);
         System.debug('license1.Late_Renewal_Eligible_End_Date__c ' + license1.Late_Renewal_Eligible_End_Date__c);
         System.debug('license1.Renewal_Cycle_End_Date__c ' + license1.Renewal_Cycle_End_Date__c);
        
        HandleIncompleteRenewalsScheduler sh1 = new HandleIncompleteRenewalsScheduler();      
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, sh1);
        Test.stopTest();
    }
}