src/objects/MUSW__Complaint2__c.object
<CustomObject>
    <description>Cases to track violations</description>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to address record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Complaints</relationshipLabel>
        <relationshipName>Complaint2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Priority__c</fullName>
        <description>Can be configured to be reflected on an inspection to assist with inspection assignments.</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                    <default>true</default>
                    <label>Medium</label>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current disposition of the complaint visible to respondent (person who has requested the case).</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Intake</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Classification of the complaint to determine what department or role the case could be escalated to.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fire and Life Safety</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Property</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Complaint</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Inspection__c.object
<CustomObject>
    <description>Ensure work is done in compliance with rules and regulations</description>
    <fields>
        <fullName>Close_Inspection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Inspection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Completed_DateTime__c</fullName>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Letter_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Letter Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Closed_DateTime__c</fullName>
        <description>Optional. This can be used if inspection metrics are measured in hours rather than days.</description>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Complaint.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Completed_Date__c</fullName>
        <description>Date the inspection was completed.</description>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__On_Itinerary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set to true on the itinerary page when an inspection is added to the itinerary and saved. This should be used in the creation of Views for the Itinerary page.</description>
        <label>On Itinerary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Parcel (Address).</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Priority__c</fullName>
        <description>Can be used for sort order in views and reports.  Not used in any default configuration.</description>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>3 High</fullName>
                </value>
                <value>
                    <fullName>2 Normal</fullName>
                    <default>true</default>
                    <label>2 Normal</label>
                </value>
                <value>
                    <fullName>1 Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Scheduled_Start_Date__c</fullName>
        <description>Date the inspection is scheduled for (usually before or by due date if not late). Used for views on the itinerary page.</description>
        <label>Scheduled Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status or outcome of the inspection.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approval</fullName>
                </value>
                <value>
                    <fullName>In Violation</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Scope of the inspection activity to be done.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Reinspection</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>High Risk</fullName>
                </value>
                <value>
                    <fullName>Follow-up Inspection</fullName>
                </value>
                <value>
                    <fullName>Check Rides</fullName>
                </value>
                <value>
                    <fullName>Exam Observation</fullName>
                </value>
                <value>
                    <fullName>Record</fullName>
                </value>
                <value>
                    <fullName>Skills Observation</fullName>
                </value>
                <value>
                    <fullName>Classroom Observation</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Financial</fullName>
                </value>
                <value>
                    <fullName>Examiner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_DateTime__c</fullName>
        <label>Requested Date</label>
        <type>DateTime</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Inspection_Violation__c.object
<CustomObject>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Complaint.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Inspection Violations</relationshipLabel>
        <relationshipName>Inspection_Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Inspection__c</fullName>
        <description>Associated Inspection (required). This allows multiple violations to be recorded per inspection.</description>
        <label>Inspection</label>
        <referenceTo>MUSW__Inspection__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Inspection_Violations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associated Parcel (Address).</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Inspection Violations</relationshipLabel>
        <relationshipName>Inspection_Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Violation__c</fullName>
        <description>Associated Violation. This allows the same violation to be worked within the re-inspection.</description>
        <label>Violation</label>
        <referenceTo>MUSW__Violation__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Violation_Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Inspection Violation</label>
    <nameField>
        <displayFormat>IV-{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Violations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MUSW__Parcel__c.object
<CustomObject>
    <description>Property parcel information</description>
    <label>Parcel</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Violation__c.object
<CustomObject>
    <description>Violation cited on Complaints</description>
    <fields>
        <fullName>Days_to_correct_User_defined__c</fullName>
        <label>Days to correct - User defined</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MUSW__Complaint2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated complaint record.</description>
        <label>Complaint</label>
        <referenceTo>MUSW__Complaint2__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Parcel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated parcel record.</description>
        <label>Parcel</label>
        <referenceTo>MUSW__Parcel__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Allegation</fullName>
                    <default>true</default>
                    <label>Allegation</label>
                </value>
                <value>
                    <fullName>Finding</fullName>
                </value>
                <value>
                    <fullName>Charged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary descriptor of the violation. Unlike most type fields in the system, this is a lookup to the ordinance table rather than a picklist.</description>
        <label>Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MUSW__Violation_Type__c.MUSW__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>MUSW__Violation_Type__c</referenceTo>
        <relationshipLabel>Violations</relationshipLabel>
        <relationshipName>Violations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Violation</label>
    <nameField>
        <displayFormat>VI-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Violations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViolationAddEditBatchTest.cls
@isTest(SeeAllData = true)
public class ViolationAddEditBatchTest{


    @isTest(SeeAllData=true)
    private static void testBatch(){
    
        TriggerService.setLock();
        BGCM.TestMock tm = new BGCM.TestMock();
        MUSW__Parcel__c par = new MUSW__Parcel__c(Name= DOL_AppConstants.NULL_EMPTY_STRING + 'zsdfsf');
        insert par;
            
        MUSW__Complaint2__c c = new MUSW__Complaint2__c();
        c.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Other';
        c.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'New';
        c.MUSW__Parcel__c = par.id;
        insert c; system.debug('c======' + c);

        MUSW__Inspection__c ins = new MUSW__Inspection__c();
                
        ins.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'abcefg123456';
        ins.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'fieldObservations';
        ins.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        ins.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'New';
        ins.Close_Inspection__c = false;
        ins.MUSW__On_Itinerary__c = false;
        ins.Letter_Generated__c = false;
        ins.MUSW__Scheduled_Start_Date__c = Date.today();
        ins.Requested_DateTime__c = Date.today();
        ins.Completed_DateTime__c = Date.today();
        ins.MUSW__Completed_Date__c = Date.today();
        ins.MUSW__Closed_DateTime__c = Date.today();
        
        insert ins;
        
        MUSW__Violation__c v = new MUSW__Violation__c();
        v.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Open';
        v.MUSW__Complaint2__c = c.id;
        v.Days_to_correct_User_defined__c = 20.0;
        insert v;
        
        MUSW__Inspection_Violation__c  iv = new MUSW__Inspection_Violation__c();
        iv.MUSW__Inspection__c = ins.id;
        iv.MUSW__Violation__c = v.id;
        insert iv;

        MUSW__Inspection__c[] fos = new MUSW__Inspection__c[]{};

        MUSW__Inspection__c ins2 = new MUSW__Inspection__c();
                
        ins2.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'ethjnwhfb';
        ins2.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Mechanical';
        ins2.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        ins2.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'New';
        ins2.Close_inspection__c = false;
        ins2.MUSW__On_Itinerary__c = false;
        ins2.Letter_Generated__c = false;
        ins2.MUSW__Scheduled_Start_Date__c = Date.today();
        ins2.Requested_DateTime__c = Date.today();
        ins2.Completed_DateTime__c = Date.today();
        ins2.MUSW__Completed_Date__c = Date.today();
        ins2.MUSW__Closed_DateTime__c = Date.today();
        
        fos.add(ins2);        
        insert ins2;
/*               
        MUSW__Inspection__c ins3 = new MUSW__Inspection__c();
                
        ins3.Name = DOL_AppConstants.NULL_EMPTY_STRING + 'fg';
        ins3.MUSW__Type__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Mechanical';
        ins3.MUSW__Priority__c= DOL_AppConstants.NULL_EMPTY_STRING + '2 Normal';
        ins3.MUSW__Status__c = DOL_AppConstants.NULL_EMPTY_STRING + 'Pending';
        ins3.Close_inspection__c = true;
        ins3.MUSW__On_Itinerary__c = false;
        ins3.Letter_Generated__c = false;
        ins3.MUSW__Scheduled_Start_Date__c = null;
        ins3.Requested_DateTime__c = null;
        ins3.Completed_DateTime__c = Date.today();
        ins3.MUSW__Completed_Date__c = null;
        ins3.MUSW__Closed_DateTime__c = null;
        fos.add(ins3);        
        
        insert fos;
*/        
        
        MUSW__Inspection_Violation__c[] ivs = new MUSW__Inspection_Violation__c[]{};
        
        MUSW__Inspection_Violation__c  iv2 = new MUSW__Inspection_Violation__c();
        iv2.MUSW__Inspection__c = ins2.id;
        iv2.MUSW__Violation__c = v.id;
        ivs.add(iv2);
        insert iv2;
/*        
        MUSW__Inspection_Violation__c  iv3 = new MUSW__Inspection_Violation__c();
        iv3.MUSW__Inspection__c = ins3.id;
        iv3.MUSW__Violation__c = v.id;                
        ivs.add(iv3);
        insert iv3;
       // insert ivs;
        
        system.debug('iv2='+ iv2);
        system.debug('iv3='+ iv3);
*/        
        //update iv2;
        
       //   update iv3;
        
        Test.startTest();
        
        Id batchInstanceId = Database.executeBatch(new ViolationAddEditBatch(ins, fos, ivs), 2);
        
        Test.stopTest();
        
    }     


}