src/objects/Portal_Article__c.object
<CustomObject>
    <description>To store the content (instructions, links, help) that need to be displayed in portal in various pages.</description>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>Unique external id for migrating data b/w sandboxes.</description>
        <externalId>true</externalId>
        <inlineHelpText>&lt;Page&gt;-&lt;RecortType&gt;-&lt;Title&gt;
Eg: PUB-ART-SAW-1</inlineHelpText>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Portal Article</label>
    <nameField>
        <displayFormat>ART-{0000}</displayFormat>
        <label>Article Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Articles</pluralLabel>
    <recordTypes>
        <fullName>Main</fullName>
        <active>true</active>
        <description>Article Placeholder</description>
        <label>Main</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DOL_DynamicPortalArticlesRenderer_Test.cls
@isTest
public class DOL_DynamicPortalArticlesRenderer_Test {
	@isTest
    public static void getPortalArticlesByDisplayPageTest(){
        Id portalArticleRecType = Schema.SObjectType.Portal_Article__c.getRecordTypeInfosByName().get('Main').getRecordTypeId();
        Portal_Article__c portalArticle = DOL_TestDataFactory.createPortalArticle('Active','Public Home',portalArticleRecType);       
        DOL_DynamicPortalArticlesRenderer_Apex.getPortalArticlesByDisplayPage('Public Home');
    }
    
    @isTest
    public static void getPortalArticlesByArticleTitleTest(){
        Id portalArticleRecType = Schema.SObjectType.Portal_Article__c.getRecordTypeInfosByName().get('Main').getRecordTypeId();
        Portal_Article__c portalArticle = DOL_TestDataFactory.createPortalArticle('Active','Public Home',portalArticleRecType);       
        DOL_DynamicPortalArticlesRenderer_Apex.getPortalArticlesByArticleTitle('Test Article');
    }
    
    @isTest
    public static void getPortalArticlesByArticleExternalIdTest(){
        Id portalArticleRecType = Schema.SObjectType.Portal_Article__c.getRecordTypeInfosByName().get('Main').getRecordTypeId();
        Portal_Article__c portalArticle = DOL_TestDataFactory.createPortalArticle('Active','Public Home',portalArticleRecType);
        portalArticle.External_Id__c = 'abc123';
        update portalArticle;
        DOL_DynamicPortalArticlesRenderer_Apex.getPortalArticlesByArticleExternalId('abc123');
    }
}