src/objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type (To be Deleted)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start Time</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Deny</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                    <isActive>false</isActive>
                    <label>Approve</label>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                    <isActive>false</isActive>
                    <label>Canceled</label>
                </value>
                <value>
                    <fullName>Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This is the application type related to resource</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the resource.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Resource_Availability_Modifier__c.object
<CustomObject>
    <description>Resource Availability Modifier</description>
    <fields>
        <fullName>Activity__c</fullName>
        <description>Resource Availability Modifier Activity</description>
        <label>Activity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Resource_Availability_Modifier_Activity</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>More_Information__c</fullName>
        <description>More Information</description>
        <label>More Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Availability Modifiers</relationshipLabel>
        <relationshipName>Resource_Availability_Modifiers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Resource_Modifier_Availability_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Availability_per_Day__c</fullName>
        <description>Time Availability per Day</description>
        <label>Time Availability per Day</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Working_Hours</valueSetName>
        </valueSet>
    </fields>
    <label>Resource Availability Modifier</label>
    <nameField>
        <displayFormat>RMA-{0000}</displayFormat>
        <label>ResourceModifier Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availability Modifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Backend_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Backend User</description>
        <label>Backend User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End Time</description>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Time Slots</relationshipLabel>
        <relationshipName>Time_Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>DATEVALUE(Start_Time__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>This is the Start time</description>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Time_Slot_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Time Slot</label>
    <nameField>
        <displayFormat>TSN-{0000}</displayFormat>
        <label>Time Slots Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Resource_Availability_Modifier_Activity.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Make Unavailable</fullName>
    </customValue>
    <customValue>
        <fullName>Make Available</fullName>
    </customValue>
    <masterLabel>Resource Availability Modifier Activity</masterLabel>
</GlobalValueSet>

src/globalValueSets/Resource_Modifier_Availability_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Failed</fullName>
    </customValue>
    <customValue>
        <fullName>Eligible</fullName>
        <default>true</default>
        <label>Eligible</label>
    </customValue>
    <masterLabel>Resource Modifier Availability Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Time_Slot_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Free</fullName>
    </customValue>
    <customValue>
        <fullName>Available</fullName>
    </customValue>
    <customValue>
        <fullName>Busy</fullName>
    </customValue>
    <masterLabel>Time Slot Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Working_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8.00 to 8.30</fullName>
    </customValue>
    <customValue>
        <fullName>8.30 to 9.00</fullName>
    </customValue>
    <customValue>
        <fullName>9.00 to 9.30</fullName>
    </customValue>
    <customValue>
        <fullName>9.30 to 10.00</fullName>
    </customValue>
    <customValue>
        <fullName>10.00 to 10.30</fullName>
    </customValue>
    <customValue>
        <fullName>10.30 to 11.00</fullName>
    </customValue>
    <customValue>
        <fullName>11.00 to 11.30</fullName>
    </customValue>
    <customValue>
        <fullName>11.30 to 12.00</fullName>
    </customValue>
    <customValue>
        <fullName>12.00 to 12.30</fullName>
    </customValue>
    <customValue>
        <fullName>12.30 to 13.00</fullName>
    </customValue>
    <customValue>
        <fullName>13.00 to 13.30</fullName>
    </customValue>
    <customValue>
        <fullName>13.30 to 14.00</fullName>
    </customValue>
    <customValue>
        <fullName>14.00 to 14.30</fullName>
    </customValue>
    <customValue>
        <fullName>14.30 to 15.00</fullName>
    </customValue>
    <customValue>
        <fullName>15.00 to 15.30</fullName>
    </customValue>
    <customValue>
        <fullName>15.30 to 16.00</fullName>
    </customValue>
    <customValue>
        <fullName>Unavailable</fullName>
    </customValue>
    <description>Working Hours</description>
    <masterLabel>Working Hours</masterLabel>
</GlobalValueSet>

src/classes/ResourceAvailabilityModifierHandler.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Name                : ResourceAvailabilityModifierHandler
** Description         :  
** Version             : 1.0
** Built By            : 
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
**
**
**
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
************************************************************************************/
public class ResourceAvailabilityModifierHandler {
    
    public static  void ResourceAvailabilityModifierHandlerManager(List<Resource_Availability_Modifier__c> newSObj){
        ResourceAvailabilityModifierHandler.unavailableresource(newSobj);
        ResourceAvailabilityModifierHandler.availableresource(newSobj);
    }
    public static void unavailableresource(List<Resource_Availability_Modifier__c> newSObj){
        Boolean fbslotcomplete=false;
        List<Resource_Availability_Modifier__c> Sorteditems = new   List<Resource_Availability_Modifier__c>();
        Map<Id,Id> resMd = new  Map<Id,Id> ();
        for(Resource_Availability_Modifier__c resmod: newSObj){            
            if(resmod.Status__c==Label.ST_Eligible&&resmod.Date__c!=null&&resmod.Activity__c==Label.Str_Make_Unavailable){
                sorteditems.add(resmod);
                resMd.put(resmod.Id,resmod.resource__c);
            }
        }
        Map<String,List<Time_slot__c>> usertimeslots = new  Map<String,List<time_slot__c>>();
        for( time_slot__c timeslot :   [Select id,Resource__c,Start_Date__c from time_slot__c where Resource__c=:resmd.values() and Backend_User__c!='' and status__c=:Label.ST_Available])
        {
            if(usertimeslots.containsKey(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c)))
            {
                usertimeslots.get(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c)).add(timeslot);
            }
            else if(!usertimeslots.containsKey(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c))) {
                usertimeslots.put(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c),new List<time_slot__c> { timeslot} );
            }
        }
        
        List<Time_slot__c> fbslotsforupdate = new List<Time_slot__c>(); 
        for(Resource_Availability_Modifier__c resmod : sorteditems)
        {
            if(usertimeslots.containskey(resmod.Resource__c+String.valueof(resmod.Date__c)))
            {
                fbslotsforupdate.addall(usertimeslots.get(resmod.Resource__c+String.valueof(resmod.Date__c)));
                resmod.Status__c=Label.Str_success;
                resmod.More_Information__c='The time modification succeeded to make the day busy ';
            }
            else {
                resmod.Status__c=Label.St_Failed;
                resmod.More_Information__c='The resource is currently busy or there is no availability on the chosen date.';
            }
        }
        if(fbslotsforupdate.size()>0)
        {
            for(Time_slot__c timeslot:fbslotsforupdate )
            {
                timeslot.Status__c=Label.St_Busy;
            }
        }
        if(fbslotsforupdate.size()>0){
            List <Database.SaveResult > saveResults = Database.update(fbslotsforupdate, true);  
            fbslotcomplete =ErrorLogger.logDMLDatabaseResultErrorsWithResponse(UserInfo.getUserId(), null, saveResults, null, 'sObject',' Update records', null, 'ResourceAvailabilityModifierHandler', label.str_HIGH, 'ResourceAvailabilityModifierHandler');
        }
        
        if(!fbslotcomplete)
        {
            for(Resource_Availability_Modifier__c resmod : sorteditems)
            {
                resmod.Status__c=Label.St_Failed;
                resmod.More_Information__c='There was an unexpected error,please try again.';
            }
            
        }
    }
    
    public static void availableresource(List<Resource_Availability_Modifier__c> newSObj){
        Boolean fbslotcomplete=false;
        List<Resource_Availability_Modifier__c> Sorteditems = new   List<Resource_Availability_Modifier__c>();
        Map<Id,Id> resMd = new  Map<Id,Id> ();
        for(Resource_Availability_Modifier__c resmod: newSObj){            
            if(resmod.Status__c==Label.ST_Eligible&&resmod.Date__c!=null&&resmod.Activity__c==Label.Str_Make_Available){
                sorteditems.add(resmod);
                resMd.put(resmod.Id,resmod.resource__c);
            }
        }
        Map<Id,Resource__c> resmap =new Map<Id,Resource__c> ([Select id, User__r.Id,Application_Type__c from Resource__c where id=:resmd.values()]);
        Map<String,List<Time_slot__c>> usertimeslots = new  Map<String,List<time_slot__c>>();
        for( time_slot__c timeslot :   [Select id,Status__c,Request__c,Resource__c,Start_Date__c from time_slot__c where Resource__c=:resmd.values() and Backend_User__c!='' ])
        {
            if(usertimeslots.containsKey(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c)))
            {
                usertimeslots.get(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c)).add(timeslot);
            }
            else if(!usertimeslots.containsKey(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c))) {
                usertimeslots.put(timeslot.Resource__c+String.valueof(timeslot.Start_Date__c),new List<time_slot__c> { timeslot} );
            }
        }
        
        List<Time_slot__c> fbslotsforupdate = new List<Time_slot__c>(); 
        List<Time_slot__c> fbslotsforudelete = new List<Time_slot__c>(); 
        for(Resource_Availability_Modifier__c resmod : sorteditems)
        {
            if(usertimeslots.containskey(resmod.Resource__c+String.valueof(resmod.Date__c)))
            {
                List<Time_slot__c> testing = new List<Time_slot__c>();
                boolean status=true;
                for(Time_Slot__c timeslots : usertimeslots.get(resmod.Resource__c+String.valueof(resmod.Date__c))){
                    if(timeslots.status__c==Label.St_Available||(timeslots.Request__c==null&&timeslots.status__c==Label.St_Busy)){
                        resmod.Status__c=Label.Str_success;
                        resmod.More_Information__c='The time modification succeeded to make the time Available';
                    }
                    else{
                        resmod.Status__c=Label.St_Failed;
                        status=false; 
                        resmod.More_Information__c='The time modification failed as the resource is already booked on this day.';
                    }
                    
                }
                if(status)
                { 
                    boolean deleteall = deleteslots(usertimeslots.get(resmod.Resource__c+String.valueof(resmod.Date__c)));
                    if(deleteall)
                    {
                        List<Time_Slot__C> newslots=  createnewslots( resmod, resmap);
                        if(newslots!=null&&newslots.size()>0)
                        {
                            fbslotsforupdate.addall(newslots);
                        }
                        
                    }
                    else{
                        resmod.Status__c=Label.St_Failed;
                        resmod.More_Information__c='The time modification failed.';
                    }
                }
            }
            else {
                
                List<Time_Slot__C> newslots=  createnewslots( resmod, resmap);
                if(newslots!=null&&newslots.size()>0)
                {
                    fbslotsforupdate.addall(newslots);
                }
            }
        }

        if(fbslotsforupdate.size()>0){
            List <Database.SaveResult > saveResults = Database.insert(fbslotsforupdate, true);  
            fbslotcomplete =ErrorLogger.logDMLDatabaseResultErrorsWithResponse(UserInfo.getUserId(), null, saveResults, null, 'sObject',' Update records', null, 'ResourceAvailabilityModifierHandler', label.str_HIGH, 'ResourceAvailabilityModifierHandler');
        }
        
        if(!fbslotcomplete)
        {
            for(Resource_Availability_Modifier__c resmod : sorteditems)
            {
                resmod.Status__c=Label.St_Failed;
                resmod.More_Information__c='There was an unexpected error,please try again.';
            }
            
        }
    }
    
    /***************************************************************************************************
* @Description : Determining which fbslots should be created for the given configuration, either available
or slots are created for the next  day for the batch on the license.
* @Param       : List<Time_Slot__c>, ID ,Decimal, Boolean ,Date ,Date ,Map<String,Set<Time>> 
* @Return      : void
***************************************************************************************************/ 
    public static List<Time_Slot__c> applyAllocationToLocationdailybatch(resource__c selectedresource,List<Time_Slot__c> availableSlots,ID resourceID,Date EndTime,Map<String,Set<Time>> DayTimeMap){
        List<Time_Slot__c> availableSlottemplate=availableSlots;              
        Datetime endDateTime=EndTime;
        List<Time_Slot__c> locationBusy_final=new List<Time_Slot__c>(); 
        Set<Datetime> newitems = new Set<Datetime> ();
        Datetime dates=System.now().addDays(120);
        Set<Datetime> slots = new Set<Datetime>();
        
        for(Time_Slot__c slot: [Select id,Start_Time__c from Time_Slot__c where status__c=:Label.ST_Available and Resource__c =:resourceID and
                                Start_Time__c>=:dates])
        { 
            slots.add(slot.Start_Time__c);
        }
        for(Integer i=0;i<availableSlottemplate.size();i++){            
            Time_Slot__c temp=availableSlottemplate.get(i);
                locationBusy_final.add(ManageLocationAvailability.createNewAvailableSlot(selectedresource.Application_Type__c,temp,resourceID,selectedresource.User__r.Id));
                newitems.add(temp.Start_Time__c);                                                                               
        }
        return locationBusy_final;
    }
    
    static Time getTimeByString(String hh,String mm){
        return Time.newInstance(Integer.valueOf(hh.trim()), Integer.valueOf(mm.trim()), 0, 0);
    }
    
    /***************************************************************************************************
* @Description : This functions creates a set of time based on the dates given
on the license.
* @Param       : Date,Date
* @Return      : Set<time> Time
***************************************************************************************************/      
    static Set<Time> getTimeBetweenStartAndEndTime( DateTime EndDateTime,DateTime StartDateTime){
        BusinessHours bh =TimeSlotsHelper.getBusinessHours();
        Integer  slot=30;
        Set<Time> times=new Set<time>();
        while(true){
            if(StartDateTime>=EndDateTime)
                break;
            if(BusinessHours.isWithin(bh.id, StartDateTime)){
                Time temp=Time.newInstance(StartDateTime.hour(), StartDateTime.minute(),0,0);
                times.add(temp);               
            }            
            StartDateTime=StartDateTime.addMinutes(slot); 
        }
        return times;
    }
    
    static List<Time_Slot__c> createnewslots(Resource_Availability_Modifier__c resmod,  Map<Id,Resource__c> resmap){
        Datetime startDateTime=resmod.Date__c;
        Datetime endDateTime=resmod.Date__c.addDays(1);
        List<Time_Slot__c> freeSlots=[Select id,status__c,Resource__c,Start_Time__c,End_Time__c 
                                      from Time_Slot__c 
                                      where status__c=:Label.ST_Free and
                                      Start_Time__c>:startDateTime and Start_Time__c<=:endDateTime];
        if(resmod.Time_Availability_per_Day__c!=''&&!resmod.Time_Availability_per_Day__c.contains(Label.ST_Unavailable)){
            Resource__c res = new Resource__c();
            Set<Time> times=new Set<Time>();
            Map<String,Set<Time>> DayTimeMap=new Map<String,Set<Time>>();
            DayTimeMap.put(endDateTime.format('EEEE'), times);
            res=  resmap.get(resmod.Resource__c);
            for(String aTime:resmod.Time_Availability_per_Day__c.split(';')){                    
                String[] splitTimeRange=aTime.split('to');                   
                Time StartTime=getTimeByString(splitTimeRange[0].split('\\.')[0],splitTimeRange[0].split('\\.')[1]);
                Time EndTime=getTimeByString(splitTimeRange[1].split('\\.')[0],splitTimeRange[1].split('\\.')[1]);                    
                times.addAll(getTimeBetweenStartAndEndTime(DateTime.newInstance(resmod.Date__c,EndTime)
                                                           ,DateTime.newInstance(resmod.Date__c,StartTime))); 
            }
            return  applyAllocationToLocationdailybatch(res,freeSlots,res.Id,resmod.Date__c.adddays(1),DayTimeMap);
        }
        return null;
    }
    
    static Boolean deleteslots(List<Time_slot__c> fbslotsfordelete){
        boolean fbslotcomplete=false;
        if(fbslotsfordelete.size()>0)
        {
            List <Database.deleteresult > saveResults = Database.delete(fbslotsfordelete, true);  
            fbslotcomplete =ErrorLogger.logDMLDatabaseResultErrorsWithResponse(UserInfo.getUserId(), saveResults,null, null, 'sObject',' Update records', null, 'ResourceAvailabilityModifierHandler', label.str_HIGH, 'ResourceAvailabilityModifierHandler');        
        }
        return  fbslotcomplete;
    }
}