src/objects/Resource_Availability__c.object
<CustomObject>
    <fields>
        <fullName>New_Availability_Start_Date__c</fullName>
        <description>New Availability Start Date</description>
        <label>New Availability Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Time_Availability__c</fullName>
        <description>New Time Availability</description>
        <label>New Time Availability</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Working_Hours</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Availability__c</fullName>
        <description>Time Availability of the resource</description>
        <label>Time Availability</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Working_Hours</valueSetName>
        </valueSet>
    </fields>
    <label>Resource Availability</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>Resource Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Working_Hours.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>8.00 to 8.30</fullName>
    </customValue>
    <customValue>
        <fullName>8.30 to 9.00</fullName>
    </customValue>
    <customValue>
        <fullName>9.00 to 9.30</fullName>
    </customValue>
    <customValue>
        <fullName>9.30 to 10.00</fullName>
    </customValue>
    <customValue>
        <fullName>10.00 to 10.30</fullName>
    </customValue>
    <customValue>
        <fullName>10.30 to 11.00</fullName>
    </customValue>
    <customValue>
        <fullName>11.00 to 11.30</fullName>
    </customValue>
    <customValue>
        <fullName>11.30 to 12.00</fullName>
    </customValue>
    <customValue>
        <fullName>12.00 to 12.30</fullName>
    </customValue>
    <customValue>
        <fullName>12.30 to 13.00</fullName>
    </customValue>
    <customValue>
        <fullName>13.00 to 13.30</fullName>
    </customValue>
    <customValue>
        <fullName>13.30 to 14.00</fullName>
    </customValue>
    <customValue>
        <fullName>14.00 to 14.30</fullName>
    </customValue>
    <customValue>
        <fullName>14.30 to 15.00</fullName>
    </customValue>
    <customValue>
        <fullName>15.00 to 15.30</fullName>
    </customValue>
    <customValue>
        <fullName>15.30 to 16.00</fullName>
    </customValue>
    <customValue>
        <fullName>Unavailable</fullName>
    </customValue>
    <description>Working Hours</description>
    <masterLabel>Working Hours</masterLabel>
</GlobalValueSet>

src/classes/ModifyTimeResources.cls
/*Name: ModifyTimeResources
*This batch updates the time availability if the new availability start date is now past the start tme.
* Date:        - Case#/Project:            - Developer/Company                               - Description
* ------------------------------------------------------------------------------------------------------------------------- *
* 11/17.2017                           - Okwudiafor Akosa, Deloitte                  - Initial Implementation.
*/
global class ModifyTimeResources implements Database.Batchable < sObject > {
    public String Query;
    global ModifyTimeResources() {
        Query ='Select id,Time_Availability__c,New_Time_Availability__c from Resource_Availability__c where New_Availability_Start_Date__c=today and New_Time_Availability__c!=null limit 1000';
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        for (Resource_Availability__c res : (List<Resource_Availability__c>) scope) {
            if(res.New_Time_Availability__c.contains(Label.ST_Unavailable))
            {
                           res.Time_Availability__c =''; 
            }
            else{
                            res.Time_Availability__c = res.New_Time_Availability__c;
            }
            res.New_Time_Availability__c = '';
            res.New_Availability_Start_Date__c  = null;
        }
        if (scope != null) {
            update scope;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}