src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this an active resource?</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This is the application type related to resource</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Review_Types__c</fullName>
        <description>Plan Review types</description>
        <label>Permit / Plan Review Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POWTS Individual Site Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Design</fullName>
                </value>
                <value>
                    <fullName>POWTS Petition for Variance</fullName>
                </value>
                <value>
                    <fullName>POWTS Experimental System</fullName>
                </value>
                <value>
                    <fullName>POWTS Miscellaneous Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Sanitary Permit</fullName>
                </value>
                <value>
                    <fullName>POWTS State-Owned Privy Registration</fullName>
                </value>
                <value>
                    <fullName>POWTS Consultation</fullName>
                </value>
                <value>
                    <fullName>POWTS Component Manual Review</fullName>
                </value>
                <value>
                    <fullName>POWTS Soil Saturation Determination</fullName>
                </value>
                <value>
                    <fullName>Manufactured Homes Community Permit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the resource.</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <recordTypes>
        <fullName>POWTS</fullName>
        <active>true</active>
        <label>POWTS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Resource_Week_Availability__c.object
<CustomObject>
    <fields>
        <fullName>Autorenewal__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Autorenewal</description>
        <label>Autorenewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Backend_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Backend_User__c</description>
        <label>Backend User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Resource_Week_Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <description>Resource</description>
        <label>Resource</label>
        <referenceTo>Resource__c</referenceTo>
        <relationshipLabel>Resource Week Availability</relationshipLabel>
        <relationshipName>Resource_Group_Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Valid_From__c</fullName>
        <description>Schedule Valid From</description>
        <label>Schedule Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Schedule_Valid_till__c</fullName>
        <description>Schedule Valid till</description>
        <label>Schedule Valid till</label>
        <type>Date</type>
    </fields>
    <label>Resource Week Availability</label>
    <nameField>
        <displayFormat>RWA-{0000}</displayFormat>
        <label>Resource Week Availability Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Week Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchRecalculateScheduletest.cls
@isTest(SeeAllData=true)
private class BatchRecalculateScheduletest {
    static testmethod void test() {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            User a=CreateTestDataUtility.createBackendUser();
            insert a;
            Resource__c rsc = new Resource__c();
            rsc.Application_Type__c=label.Str_Plan_Review;
            rsc.Active__c=true;
            rsc.User__c=a.id;
            rsc.Plan_Review_Types__c='POWTS Petition for Variance';
        insert rsc;
        Resource_Week_Availability__c nwResLocAvai = new Resource_Week_Availability__c();
        nwResLocAvai.Schedule_Valid_till__c = Date.Today();        
        nwResLocAvai.Resource__c = rsc.ID;
        nwResLocAvai.Backend_User__c=a.id;
        nwResLocAvai.Autorenewal__c=true;
        if ( nwResLocAvai != null ) { insert nwResLocAvai;}
        
        BatchRecalculateSchedule batchExecution=new BatchRecalculateSchedule();
        Test.startTest();
        Database.executeBatch(batchExecution);
        Test.stopTest();
        System.Assert(nwResLocAvai!= null);
        }
        //system.assertEquals(Date.today(), nwResLocAvai.Schedule_Valid_From__c); 
    }
}