src/objects/SlipPrinterNameToUserMap__mdt.object
<CustomObject>
    <description>Every user would have a different slip printer linked to their machine. we would be maintaining the list here.</description>
    <fields>
        <fullName>IsDebugON__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDebugON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrinterName__c</fullName>
        <label>PrinterName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SlipPrinterNameToUserMap</label>
    <pluralLabel>SlipPrinterNameToUserMaps</pluralLabel>
</CustomObject>

src/classes/Dol_ConnectToSlipPrinter.cls
public class Dol_ConnectToSlipPrinter {
	public String printParameter {get;set;}
    public String printerName {get;set;}
    public Boolean isdebugOn {get;set;}
    public Boolean isPrinterConfigured {get;set;}
    
   	public Dol_ConnectToSlipPrinter() {
        printParameter = ApexPages.currentPage().getParameters().get('validationNo');
    	System.debug('printParameter'+printParameter);
        String userName = UserInfo.getUserName();
        List<SlipPrinterNameToUserMap__mdt> slipprinterDetail = [select IsDebugON__c, PrinterName__c, UserName__c from SlipPrinterNameToUserMap__mdt where UserName__c=:userName limit 1];
   		System.debug('slipprinterDetail'+slipprinterDetail);
        if(slipprinterDetail != null && Dol_IntegrationUtil.isNotEmpty(slipprinterDetail)){
            isPrinterConfigured = true;
            printerName = slipprinterDetail[0].PrinterName__c;
            Boolean debugOn = slipprinterDetail[0].IsDebugON__c;
            if(debugOn){
                isdebugOn = True;
            }
            else isdebugOn = False;
        }else  isPrinterConfigured= false;
        System.debug('isPrinterConfigured=='+isPrinterConfigured);
    }     
}