src/objects/SlipPrinterNameToUserMap__mdt.object
<CustomObject>
    <description>Every user would have a different slip printer linked to their machine. we would be maintaining the list here.</description>
    <fields>
        <fullName>IsDebugON__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDebugON</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrinterName__c</fullName>
        <label>PrinterName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SlipPrinterNameToUserMap</label>
    <pluralLabel>SlipPrinterNameToUserMaps</pluralLabel>
</CustomObject>

src/classes/Dol_ConnectToSlipPrinter_Test.cls
@isTest(SeeAllData=true)
public class Dol_ConnectToSlipPrinter_Test {
 @isTest
    public static void testSlipPrinter(){
        //String userName = 'TestClassSlipPrinter';
         //List<SlipPrinterNameToUserMap__mdt> slipprinterDetail = [select IsDebugON__c, PrinterName__c, UserName__c from SlipPrinterNameToUserMap__mdt where  UserName__c=:userName limit 1];
        User admin = [SELECT id from user where Username like '%integrationuser@deloitte.com.polaris%'];
        System.runAs(admin) {

            test.startTest();
                PageReference pageRef = Page.Dol_ConnectToSlipPrinter;
                Test.setCurrentPage(pageRef);
                Dol_ConnectToSlipPrinter slipprinter = new Dol_ConnectToSlipPrinter();
             test.stopTest();
        }
    }
        
}