retrieveUnpackaged/objects/Affiliation__c.object
<CustomObject>
    <description>Affiliation</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Application Type</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_s_City__c</fullName>
        <description>Contact&apos;s City</description>
        <label>Contact&apos;s City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Credential_Number__c</fullName>
        <description>Contact&apos;s Credential Number</description>
        <label>Contact&apos;s Credential Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Email__c</fullName>
        <description>Contact&apos;s Email</description>
        <label>Contact&apos;s Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_s_Last_Name__c</fullName>
        <description>Contact&apos;s Last Name</description>
        <label>Contact&apos;s Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Middle_Name__c</fullName>
        <description>Contact&apos;s Middle Name</description>
        <label>Contact&apos;s Middle Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Name__c</fullName>
        <description>Contact&apos;s Name</description>
        <label>Contact&apos;s First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Phone__c</fullName>
        <description>Contact&apos;s Phone</description>
        <label>Contact&apos;s Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact_s_Street_Address__c</fullName>
        <description>Contact&apos;s Street Address</description>
        <label>Contact&apos;s Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_Zip_code__c</fullName>
        <description>Zip code</description>
        <label>Contact&apos;s Zip code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_s_state__c</fullName>
        <description>Contact&apos;s State</description>
        <label>Contact&apos;s State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Provinces</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Credential</description>
        <label>Credential</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Affiliations</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_date__c</fullName>
        <description>End date of the Affiliation</description>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of affiliation</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Affiliation</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>General_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Affiliation</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Affiliation</valueSetName>
        </valueSet>
    </fields>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AFF- {0000}</displayFormat>
        <label>Affiliation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Affiliation which is used for the service request</description>
        <label>Affiliation</label>
        <referenceTo>Affiliation__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <label>Credential</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Contact applicant associated with the application.</description>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Planning Applications</relationshipLabel>
        <relationshipName>Application2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>The current status of the application. This picklist can be defined according to the client&apos;s business processes.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Closed due to Inactivity</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Variance</fullName>
                </value>
                <value>
                    <fullName>Development Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Purpose of the service request, used for affiliation</description>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Purpose</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <description>This is the date for submission of the service request.</description>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>This refers to the application type being applied for: Application Types- Trades Credential, Plan Review, Permit To Operate, etc.</description>
        <label>Program Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Application_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credential__c</fullName>
        <description>This refers to the credential being applied for</description>
        <label>Credential</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Credential_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Credential</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact applying for license.</description>
        <inlineHelpText>Person applying for License on behalf of Licensee</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Primary_Licensee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account lookup for licenses not held by individuals.</description>
        <label>Licensee</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>License2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Current status of the license record</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Generate Fee</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Exam Scheduled</fullName>
                </value>
                <value>
                    <fullName>Exam Result</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Rescinded</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Final Close</fullName>
                </value>
                <value>
                    <fullName>Late Renewal</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Payment</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
                <value>
                    <fullName>Pending Deficient Status</fullName>
                </value>
                <value>
                    <fullName>Pending Issuance - Sent to the Printer</fullName>
                </value>
                <value>
                    <fullName>Submission Failed</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Waiting for Third Party Verification</fullName>
                </value>
                <value>
                    <fullName>Pending Applicant Action</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Sunset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <description>Primary descriptor of the License.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Credential.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Notary Public</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist</fullName>
    </customValue>
	<customValue>
        <fullName>Registered Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Camping Resort Company</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Architect Firm</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Salesperson</fullName>
    </customValue>
    <customValue>
        <fullName>Timeshare Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraiser Course</fullName>
    </customValue>
    <customValue>
        <fullName>Certified General Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Geologist in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Removal Registration</fullName>
    </customValue>
    <customValue>
        <fullName>Academic Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Certified General</fullName>
    </customValue>
    <customValue>
        <fullName>Engineer in Training</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>State Licensed Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Management Company</fullName>
    </customValue>
    <customValue>
        <fullName>Appraisal Controlling Person</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Designer</fullName>
    </customValue>
    <customValue>
        <fullName>On-site Wastewater Inspector</fullName>
    </customValue>
    <customValue>
        <fullName>Certified Residential Appraiser</fullName>
    </customValue>
    <customValue>
        <fullName>Landscape Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Director Intern</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment</fullName>
    </customValue>
    <customValue>
        <fullName>Prearrangement Funeral Services</fullName>
    </customValue>
    <customValue>
        <fullName>Funeral Establishment Branch</fullName>
    </customValue>
    <customValue>
        <fullName>Embalmer Intern</fullName>
    </customValue>
    <description>This refers to the credential being applied for</description>
    <masterLabel>Credential</masterLabel>
</GlobalValueSet>

src/globalValueSets/General_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <description>Status values if active or inactive</description>
    <masterLabel>General Status</masterLabel>
</GlobalValueSet>

src/globalValueSets/Purpose.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Edit</fullName>
    </customValue>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Deactivate</fullName>
    </customValue>
    <masterLabel>Purpose</masterLabel>
</GlobalValueSet>

src/globalValueSets/State_Provinces.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alabama</fullName>
    </customValue>
    <customValue>
        <fullName>Alaska</fullName>
    </customValue>
    <customValue>
        <fullName>Arizona</fullName>
    </customValue>
    <customValue>
        <fullName>Arkansas</fullName>
    </customValue>
    <customValue>
        <fullName>California</fullName>
    </customValue>
    <customValue>
        <fullName>Colorado</fullName>
    </customValue>
    <customValue>
        <fullName>Connecticut</fullName>
    </customValue>
    <customValue>
        <fullName>Delaware</fullName>
    </customValue>
    <customValue>
        <fullName>Florida</fullName>
    </customValue>
    <customValue>
        <fullName>Georgia</fullName>
    </customValue>
    <customValue>
        <fullName>Guam</fullName>
    </customValue>
    <customValue>
        <fullName>Hawaii</fullName>
    </customValue>
    <customValue>
        <fullName>Idaho</fullName>
    </customValue>
    <customValue>
        <fullName>Illinois</fullName>
    </customValue>
    <customValue>
        <fullName>Indiana</fullName>
    </customValue>
    <customValue>
        <fullName>Iowa</fullName>
    </customValue>
    <customValue>
        <fullName>Kansas</fullName>
    </customValue>
    <customValue>
        <fullName>Kentucky</fullName>
    </customValue>
    <customValue>
        <fullName>Louisiana</fullName>
    </customValue>
    <customValue>
        <fullName>Maine</fullName>
    </customValue>
    <customValue>
        <fullName>Maryland</fullName>
    </customValue>
    <customValue>
        <fullName>Massachusetts</fullName>
    </customValue>
    <customValue>
        <fullName>Michigan</fullName>
    </customValue>
    <customValue>
        <fullName>Minnesota</fullName>
    </customValue>
    <customValue>
        <fullName>Mississippi</fullName>
    </customValue>
    <customValue>
        <fullName>Missouri</fullName>
    </customValue>
    <customValue>
        <fullName>Montana</fullName>
    </customValue>
    <customValue>
        <fullName>Nebraska</fullName>
    </customValue>
    <customValue>
        <fullName>Nevada</fullName>
    </customValue>
    <customValue>
        <fullName>New Hampshire</fullName>
    </customValue>
    <description>List of US States and Provinces</description>
    <masterLabel>State Provinces</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type_of_Affiliation.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Primary Enforcement Contact</fullName>
        <default>true</default>
        <label>Primary Enforcement Contact</label>
    </customValue>
    <customValue>
        <fullName>Enforcement Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Designer</fullName>
    </customValue>
    <customValue>
        <fullName>Co-Owner</fullName>
    </customValue>
    <customValue>
        <fullName>Secured Party</fullName>
    </customValue>
    <description>Type of Affiliation</description>
    <masterLabel>Type of Affiliation</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/AddAffiliation.cls
/** Controller for component - AddAffiliation page
* 
* @author      - Akosa Okwudiafor helps the user add or edit affilations to aparticular license.
* @Reference   - AddAffiliation.vfp
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                 Date              Version     Description
** Akosa Okwudiafor         8/21/2018           1.0         Initial Implementation
**------------------------------------------------------------------------------------------------------------
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
***************************************************************************************************************/

public class AddAffiliation {
    // class variables 
    public Boolean isError{get;set;}
    public String errorMessage{get;set;}    
    public Affiliation__c affiliation {get;set;}
    public Affiliation__c newAffiliation {get;set;}
    public MUSW__License2__c credential {get;set;}
    public String credentialId {get;set;}
    public boolean NewAgreement {get;set;}
    public String serviceRequestId {get;set;}
    public String message {get;set;}
    public Id contactId;
    public MUSW__Application2__c serviceRequest{get;set;}
    public String affiliationid {get;set;}
    
    
    /***************************************************************************************************
* @Description : method for adding the new affiliation
* @Param       : NA
* @Return      : void
****************************************************************************************************/
    public AddAffiliation(){       
        try{
            contactId= null;
            affiliationid = ApexPages.currentPage().getParameters().get('affiliationid'); 
            credentialId = ApexPages.currentPage().getParameters().get('credentialId');
            serviceRequestId = ApexPages.currentPage().getParameters().get('servReqId');
            if(affiliationid!=null){
                NewAgreement=false;
            }
            else{
                NewAgreement=true;
            }
            affiliation = new Affiliation__c();
            affiliation.RecordTypeId=Utilities.getRecordTypeForName(Label.API_Affiliation,Label.RT_Delegated_Agent_Affiliation); 
            affiliation.Type__c='Primary Enforcement Contact'; 
            if(String.isNotBlank(credentialId)){
                List<MUSW__license2__c> credentials = [SELECT Id,Credential__c,Name,Application_Type__c,MUSW__Type__c,MUSW__Primary_Licensee__c,MUSW__Applicant__c FROM MUSW__License2__c WHERE Id=:credentialId limit 1];
                if(credentials.size()>0){
                    User user = [SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId()];
                    contactId =  user.ContactId;     
                    credential= credentials[0];
                    if(affiliationid != NULL){
                        affiliation = [SELECT Contact_s_City__c, End_date__c,Contact_s_Last_Name__c, Contact_s_Middle_Name__c,Start_Date__c, Type__c, Status__c, Contact_s_Zip_code__c, Contact_s_state__c, Contact_s_Street_Address__c, Contact_s_Credential_Number__c, 
                                       Contact_s_Email__c, Contact_s_Phone__c, Contact_s_Name__c, Credential__c, Id FROM Affiliation__c
                                       WHERE Id=: affiliationid];
                        newAffiliation= affiliation.clone(false, true, false,false);                                
                    } 
                }
                else{  
                    isError = true;
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected error occurred while loading the application'));
                    errorMessage = 'Unexpected error occurred while loading the application';
                }
            }            
        }catch(Exception ex){
            isError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected error occurred '+ex.getMessage()));
            errorMessage = 'Unexpected error occurred '+ex.getMessage();
        }        
    }
    
    /***************************************************************************************************
* @Description : Method to save the affiliation
* @Param       : PageReference
* @Return      : NA
****************************************************************************************************/
    public PageReference SaveAffiliation(){
        PageReference returnPage = null;
        try{ 
            affiliationid = ApexPages.currentPage().getParameters().get('affiliationid');            
            serviceRequest = new MUSW__Application2__c();
            affiliation.application_type__c = credential.application_type__c;
            //serviceRequest.RecordTypeId= Schema.SObjectType.MUSW__Application2__c.getRecordTypeInfosByName().get('Manage Affiliations Service Request').getRecordTypeId();
            if(affiliationid== null||affiliationid== '')
            {               
                affiliation.Status__c=Label.St_Pending;
                affiliation.Credential__c=credential.Id;
                upsert affiliation;
                affiliationid = affiliation.id;
                servicerequest.Credential__c=credential.Credential__c;
                serviceRequest.License__c = credential.Id;
                serviceRequest.application_type__c = credential.application_type__c;
                serviceRequest.MUSW__Applicant__c=contactId;
                serviceRequest.MUSW__Status__c = label.ST_Submitted;
                serviceRequest.Submitted_Date__c = System.today();
                serviceRequest.Affiliation__c= affiliation.id;
                serviceRequest.RecordTypeId=Utilities.getRecordTypeForName(Label.API_Service_Request,'Manage Affiliations'); 
                serviceRequest.Purpose__c='Add';
                serviceRequest.MUSW__Type__c = 'Manage Affiliations';
                upsert serviceRequest;        
            }
            else{         
                serviceRequest.License__c = credential.Id;
                serviceRequest.MUSW__Type__c = 'Manage Affiliations';
                serviceRequest.application_type__c = credential.application_type__c;
                serviceRequest.MUSW__Applicant__c=contactId;
                serviceRequest.MUSW__Status__c = label.ST_Submitted;
                serviceRequest.RecordTypeId= Utilities.getRecordTypeForName(Label.API_Service_Request,'Manage Affiliations'); 
                serviceRequest.Submitted_Date__c = System.today();
                serviceRequest.Affiliation__c= affiliation.id;
                serviceRequest.Purpose__c='Edit';
                upsert serviceRequest;
                newAffiliation.application_type__c = credential.application_type__c;
                newAffiliation.Status__c= label.ST_Pending;        
                newAffiliation.Credential__c=null;
                if(newAffiliation.End_Date__c==affiliation.End_Date__c)
                {
                    newAffiliation.End_Date__c=null;
                }
                else{
                    newAffiliation.End_Date__c=affiliation.End_Date__c;
                }
                if(newAffiliation.Start_Date__c==affiliation.Start_Date__c)
                {
                    newAffiliation.Start_Date__c=null;
                }
                else{
                    newAffiliation.Start_Date__c=affiliation.Start_Date__c;
                }
                if(newAffiliation.Contact_s_Street_Address__c==affiliation.Contact_s_Street_Address__c)
                {
                    newAffiliation.Contact_s_Street_Address__c='';
                }
                else{
                    newAffiliation.Contact_s_Street_Address__c=affiliation.Contact_s_Street_Address__c;
                }
                if(newAffiliation.Contact_s_state__c==affiliation.Contact_s_state__c)
                {
                    newAffiliation.Contact_s_state__c='';
                }
                else{
                    newAffiliation.Contact_s_state__c=affiliation.Contact_s_state__c;
                }
                if(newAffiliation.Contact_s_City__c==affiliation.Contact_s_City__c)
                {
                    newAffiliation.Contact_s_City__c='';
                }
                else{
                    newAffiliation.Contact_s_City__c=affiliation.Contact_s_City__c;
                }
                if(newAffiliation.Contact_s_Zip_code__c==affiliation.Contact_s_Zip_code__c)
                {
                    newAffiliation.Contact_s_Zip_code__c='';
                }
                else{
                    newAffiliation.Contact_s_Zip_code__c=affiliation.Contact_s_Zip_code__c;
                }
                if(newAffiliation.Contact_s_Phone__c==affiliation.Contact_s_Phone__c)
                {
                    newAffiliation.Contact_s_Phone__c=null;
                }
                else{
                    newAffiliation.Contact_s_Phone__c=affiliation.Contact_s_Phone__c;
                }
                if(newAffiliation.Type__c==affiliation.Type__c)
                {
                    newAffiliation.Type__c='';
                }
                else{
                    newAffiliation.Type__c=affiliation.Type__c;
                }
                
                newAffiliation.Service_Request__c=serviceRequest.Id;
                upsert newAffiliation;
            }
            MUSW__Application2__c somesr= [SELECT Id, Application_type__c, Name FROM MUSW__Application2__c where Id=: serviceRequest.Id];    
            returnPage = new PageReference(label.PR_ServiceRequestConfirmation);
            returnPage.getParameters().put('Id',somesr.Name);
            return returnPage ;
        }
        catch(Exception queryEx){
            isError = true;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unexpected error occurred '+queryEx.getMessage()));
            errorMessage = 'Error in upserting affiliation ==> '+queryEx.getMessage();         
        }
        return returnPage;
    }
    
    
    
}