retrieveUnpackaged/objects/Application_Field__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Objects on portal</description>
        <inlineHelpText>Objects on portal</inlineHelpText>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Objects_on_portal</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>This is the subsection where the field is found.</description>
        <label>Parent</label>
        <referenceTo>Application_Subsection__c</referenceTo>
        <relationshipName>Fields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this required?</description>
        <inlineHelpText>Is this required?</inlineHelpText>
        <label>Required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Section__c.object
<CustomObject>
    <label>Application Section</label>
    <nameField>
        <label>Sections Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Subsection__c.object
<CustomObject>
    <description>This is part of the application design on the portal.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <description>This is the section that the subsection is found</description>
        <label>Parent</label>
        <referenceTo>Application_Section__c</referenceTo>
        <relationshipLabel>Application Subsections</relationshipLabel>
        <relationshipName>Application_Subsections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>to make subsection required</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Service Request</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Subsection</label>
    <nameField>
        <label>Subsection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Subsections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <fields>
        <fullName>MUSW__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Variance</fullName>
                </value>
                <value>
                    <fullName>Development Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Effective_Date__c</fullName>
        <label>Requested Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Objects_on_portal.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Main Object</fullName>
    </customValue>
    <customValue>
        <fullName>Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Parent of Main Object</fullName>
    </customValue>
    <description>Objects on portal</description>
    <masterLabel>Objects on portal</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/ServiceRequestValidator.cls
public class ServiceRequestValidator {
    
    public static ValidationError validate(ValidationError e, sObject newRec){
    	MUSW__Application2__c serviceReq = (MUSW__Application2__c) newRec;
    	
        String query ='';
        query = 'Select Name From Application_Field__c where Required__c = true and Object_Name__c = \'Main Object\' and ' + 
            ' Parent__r.Parent__r.Parent__r.Service_Request_Type__c = \'' + serviceReq.MUSW__Type__c + '\' and Service_Request__c = true';
        
        System.debug('query '+query);
        List<Application_Field__c> lstRequiredFields = Database.query(query);
        Set<String> setRequiredFields = new Set<String>();
        for(Application_Field__c reqField : lstRequiredFields){
            setRequiredFields.add(reqField.Name);
        }
        system.debug(setRequiredFields);
        
        for(String requiredField : setRequiredFields){
            if(serviceReq.get(requiredField) == null || serviceReq.get(requiredField) == ''){
                e.addError(requiredField, 'You must enter a value.');
            }
        }
        
        if(serviceReq.MUSW__Type__c == 'Relinquish Delegated Agent Status'){
        	if(serviceReq.Requested_Effective_Date__c != null && serviceReq.Requested_Effective_Date__c < (Date.today() + 30)){
        		e.addError('Requested_Effective_Date__c', 'The Requested Effective Date should be at least 30 days in the future.');
        	}
        }
        
        return e;
    }
}