retrieveUnpackaged/objects/MUSW__Application2__c.object
<CustomObject>
    <description>Planning Applications eg. Site Plan</description>
    <label>Application</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__License2__c.object
<CustomObject>
    <description>Authorization for a person or facility to perform a function for a period of time: business, profession or privilege</description>
    <label>License</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Master_Submission_List__c.object
<CustomObject>
    <description>Master control table to determine which Permit, License, etc values will set or create Submission outcomes via DRE rules. Can be used to allow non-admin users with appropriate permissions to edit their own criteria and outcome values.</description>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Master Submission List</label>
    <nameField>
        <label>Master Submission List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Submission Lists</pluralLabel>
    <recordTypes>
        <fullName>License</fullName>
        <active>true</active>
        <description>License Submissions</description>
        <label>License</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>All</fullName>
        <active>true</active>
        <label>All</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MUSW__Submission__c.object
<CustomObject>
    <description>Tracks online files</description>
    <fields>
        <fullName>Attest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description_Long__c</fullName>
        <label>Description Long</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Document_API_Name__c</fullName>
        <description>API name of the document record. This file will be provided as a hyperlink to the user to download from the submission.</description>
        <label>Document API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extid_from_Submission_List__c</fullName>
        <description>Extid from Submission List</description>
        <label>Extid from Submission List</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Renewal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to License Renewal/Renewal Application</description>
        <label>License Renewal</label>
        <referenceTo>Renewal_Application__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Application2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>MUSW__Application2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__BG_File_Location_Type__c</fullName>
        <description>Location of the document or file related to this submission record. Default is Salesforce</description>
        <inlineHelpText>Location of the document or file related to this submission record.</inlineHelpText>
        <label>File Location Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                    <default>true</default>
                    <label>Salesforce</label>
                </value>
                <value>
                    <fullName>Bluebeam</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MUSW__License2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>MUSW__License2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Submission_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Master Submission List</description>
        <label>Master Submission List</label>
        <referenceTo>MUSW__Master_Submission_List__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Submission_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Submission_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Board Action</fullName>
    </customValue>
    <customValue>
        <fullName>Hardcopy: To be Mailed</fullName>
    </customValue>
    <customValue>
        <fullName>Softcopy: To be Uploaded</fullName>
    </customValue>
    <description>This field indicates whether an applicant/licensee should upload a hardcopy or softcopy submission, or whether the document is Board Action and should appear in the license lookup.</description>
    <masterLabel>Submission Type</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/PortalAttachmentSection.cls
/*************************************************************************************************************
** User Story: 
**************************************************************************************************************
** Class Name    : PortalAttachmentSection
** Description   : Class for managing attachments
** Version       : 1.0
** Built By      : Vicrumnaug Vuppalapaty
**------------------------------------------------------------------------------------------------------------
** Modification Log:
**------------------
** Developer                         Date                    Version                      Description
**------------------------------------------------------------------------------------------------------------
** Srikanth Kottam                02/19/2018                   2.0           Added exception handling and Logging Errors
** Review Log:
**---------------
** Reviewer                  Date           Version               Description
**------------------------------------------------------------------------------------------------------------
**
**************************************************************************************/
public class PortalAttachmentSection {
    
    // List of all child attachments
    public List<MUSW__Submission__c> attachedFilesList {get; set;}
    
    // List of parent attachments
    public List<SubmissionRecord> attachmentList {get; set;}
    
    /**
* Constructor
* @param     License type, application type, current record Id
*/
    public PortalAttachmentSection(String licenseType, String applicationType, String recordId) {
        
        // Initialize parent questions list
        attachmentList = new List<SubmissionRecord>();
        
        // Get all child attachments
        System.debug('recordid '+recordid);
        String queryAttachedFiles = 'SELECT Id, Name, MUSW__License2__c,MUSW__Permit2__c,Extid_from_Submission_List__c, Description_Long__c, Master_Submission_List__c,Master_Submission_List__r.Required__c, Type__c, Attest__c, Document_API_Name__c, MUSW__BG_File_Location_Type__c FROM MUSW__Submission__c WHERE MUSW__License2__c = :recordId or License_Renewal__c  = :recordId or MUSW__Permit2__c =:recordId or MUSW__Application2__c = :recordId';
        
        attachedFilesList = Database.query(queryAttachedFiles);
        
        //Document API Name provides the name of the document that should be added as a hyperlink with the submission description.
        //Create a map to store corresponding document id for each document name provided.
        Map<String,String> mapDocNameAndId = new Map<String,String>();
        for(MUSW__Submission__c subObj : attachedFilesList) {
            if(subObj.Document_API_Name__c != null && subObj.Document_API_Name__c != ''){
                mapDocNameAndId.put(subObj.Document_API_Name__c, '');
            }
        }
        
        if(mapDocNameAndId.size() > 0){
            for(Document doc : [Select Id, Name, DeveloperName From Document where DeveloperName IN :mapDocNameAndId.keySet()]){
                mapDocNameAndId.put(doc.DeveloperName, doc.Id + ';' + doc.Name);
            }
        }
        
        // Build a list of submission records
        for(MUSW__Submission__c subObj : attachedFilesList) {
            
            // Call constructor and add fields
            attachmentList.add(new SubmissionRecord(subObj.Id, subObj.Name, 
                                                    subObj.Description_Long__c, subObj.Master_Submission_List__c,subObj.Master_Submission_List__c, subObj.Type__c,
                                                    subObj.MUSW__License2__c, subObj.Attest__c, mapDocNameAndId.get(subObj.Document_API_Name__c), subObj.MUSW__BG_File_Location_Type__c,subObj.Master_Submission_List__r.Required__c));
        }
        
        // Get all submission Ids
        Set<Id> submissionSet = new Set<Id>();
        
        for(MUSW__Submission__c subObj : attachedFilesList) {            
            submissionSet.add(subObj.Id);
        }
        
        // Declare attachment list
        List<Attachment> atts;

        // Query attachment objects
        if(submissionSet.size()>0)
            atts = [SELECT Id, Name, Description, ParentId FROM Attachment WHERE ParentId IN :submissionSet];
        
        
        // Add attachments to submission records
        if(atts!= null && atts.size()>0){  //SRN R5 - Added null check to avoid error from test class
            for(Attachment subAttObj : atts) {
                for(SubmissionRecord subObj : attachmentList) {
                    if(subAttObj != null) {
                        if(subAttObj.ParentId == subObj.Id) {
                            subObj.attachmentList.add(subAttObj);
                        }
                    }
                }
            }
        }
        System.debug('Entered Here' +attachmentList);
        // Clear lists
        if(atts!= null) atts.clear();
        attachedFilesList.clear();
        
    }
    
    /**
* Class for Submission and Attachment records
* @version     1.0
*/
    public class SubmissionRecord {
        
        public String id {get; set;}
        public String name {get; set;}
        public String description {get; set;}
        public String parent {get; set;}
        public String submissionType {get; set;}
        public String licenseObjId {get; set;}
        public String renewalReinstatementId {get; set;}
        public String externalIdSubList {get; set;}
        public String endorsementId {get; set;}
        public Boolean isAttested {get; set;}
        public String documentId {get; set;}
        public String fileLocationType {get; set;}
        public List<Attachment> attachmentList {get; set;}
        public Boolean requiredSubmission {get; set;}
        /**
* Constructor
* @param     Record Id, Name, Description, Parent Id, Submission type, License object Id, 
*            Renewal/Reinstatement Id, Endorsement Id, Attestation
*/
        public SubmissionRecord(String id, String name, String description, 
                                String parent,String extid, String submissionType, String licenseObjId,
                                Boolean isAttested, String documentId, String fileLocationType,Boolean requiredSubmission) {
                                    
                                    // Add values
                                    this.id = id;
                                    this.name = name;
                                    this.externalIdSubList=extid;
                                    this.description = description;
                                    this.parent = parent;
                                    this.submissionType = submissionType;
                                    this.licenseObjId = licenseObjId;
                                    this.renewalReinstatementId = renewalReinstatementId;
                                    this.endorsementId = endorsementId;
                                    this.isAttested = isAttested;
                                    this.documentId = documentId;
                                    this.fileLocationType = fileLocationType;
                                    this.attachmentList = new List<Attachment>();
                                    this.requiredSubmission = requiredSubmission;
                                }
    }
}