retrieveUnpackaged/objects/MUSW__Fee__c.object
<CustomObject>
    <description>Fees/Fines associated to Permits, Complaints, Planning Applications</description>
    <fields>
        <fullName>MUSW__Permit2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the associated permit record.</description>
        <label>Permit</label>
        <referenceTo>MUSW__Permit2__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/MUSW__Permit2__c.object
<CustomObject>
    <description>Permit application details</description>
    <fields>
        <fullName>MUSW__Status__c</fullName>
        <description>Status of the permit as it moves through the business workflow.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Issued</fullName>
                </value>
                <value>
                    <fullName>Finaled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marked_for_Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this field is checked then the record will be deleted using batch class</description>
        <label>Marked for Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>Sub-status is a dependent picklist driven off of Status.</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Sub_Status</valueSetName>
        </valueSet>
    </fields>
    <label>Permit</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Permits</pluralLabel>
    <recordTypes>
        <fullName>Permit</fullName>
        <active>true</active>
        <description>This is the record type for all permits.</description>
        <label>Permit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Sub_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Additional Information Required</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Fee Required</fullName>
    </customValue>
    <customValue>
        <fullName>Scheduled</fullName>
    </customValue>
    <description>Sub-status is a dependent picklist driven off of Status.</description>
    <masterLabel>Sub Status</masterLabel>
</GlobalValueSet>

retrieveUnpackaged/classes/AutoCloseAbandonedPTOTitlePRBatch.cls
/**
 * User Story: 285
 * Name: AutoCloseAbandonedPTOTitlePRBatch
 * Type: Class
 * Description: Batch to auto change Status and Sub Status field for abandoned Permit to operate ONLY-
 *  -DIS (PTO) switch to Closed after 30 days of being in a request for additional information status
 * Date:        - Case#/Project:            - Developer/Company                         - Description
 * ------------------------------------------------------------------------------------------------------------------------- *
 * 07/09/2018   Sharad Maheshwari/Deloitte           Initial Creation 
 */

global with sharing class AutoCloseAbandonedPTOTitlePRBatch implements Database.Batchable<sObject>{
    global final String query;  
    
    global AutoCloseAbandonedPTOTitlePRBatch(String q){  
        //System.debug('constructor query'+q);
        query=q;        
    }
    global Database.QueryLocator start(Database.BatchableContext BC){ 
        //System.debug('before calling');
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, 
                        List<MUSW__Permit2__c> scope){
                            //System.debug('scope +'+scope);
                            List<MUSW__Permit2__c>  permitListToUpdateStatus = new List<MUSW__Permit2__c>();       
                            
                            for(MUSW__Permit2__c permitList : scope){            
                                permitList.MUSW__Status__c = Label.ST_Withdrawn;
                                //licList.Sub_Status__c = 'Abandoned';//Label.ST_Abandoned;                                  
                                permitListToUpdateStatus.add(permitList); 
                            }      
                            //System.debug('permitListToUpdateStatus >>'+permitListToUpdateStatus);
                            try{
                                if(!permitListToUpdateStatus.isEmpty()){
                                    //System.debug('in is not empty');
                                update permitListToUpdateStatus;
                                //check how to delete fee??
                                
                                /*//previous approach
                                 * Once the status is updated, the fee will be deleted overnight through ENT batch 
                                which checks for Marked_for_Deletion__c field on MUSW__Fee__c object*/
                                }
                            }
                            catch(Exception e){
                                //System.debug('in exception');
                               ErrorLogger.logGeneralException(e, UserInfo.getUserId(), 'AutoCloseAbandonedPTOTitlePRBatch', 'Update record', 'execute', 'AutoCloseAbandonedPTOTitlePRBatch', label.Str_Low);
                            }                            
                        }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}